### ISSUE TITLE
Copy/Paste Highlighting being lost

### ISSUE THREAD

**Issue by robmburke** [jacobslusser/ScintillaNET#1]
I am new to ScintallaNET and maybe I'm just missing a setting that turns this on, but whenever I copy/paste syntax highlighted text, the clipboard doesn't also get the syntax highlighting with it.  I know that, essentially, none of that information is saved to the file and so it's just text and that only the presentation of it in the editor is actually where the coloring is being done.  But, is there some way to get the syntax highlighting to go with the copy so that it can be pasted into an email to a co-developer so they can read it more easily and not just see black text?

**Comment by jacobslusser** [comment]
This is not a bug. The native Scintilla component copies text to the clipboard, but doesn't natively copy RTF or HTML to the clipboard as well--which is necessary to copy syntax highlighting.

I'm pretty sure this is a feature that could be added to ScintillaNET (or at least document how to do it) even though it's not supported by the native component.

I'll put it on the backlog.

**Comment by robmburke** [comment]
That's what I figured. Thanks for putting it in as something to look at.
________________________________

**Comment by jacobslusser** [comment]
BTW, I'm making progress but it's time consuming to get it right. Not to mention what's involved in understanding and implementing the RTF format....

To get an early preview you can get latest and check out the `Scintilla.CopyAsHtml` method.

**Comment by robmburke** [comment]
Cool. I can be patient. Lol. I just got sidetracked on starting my first Windows Phone project yesterday, so my project using Scintilla will probably be put on the back burner for a couple weeks.  Thanks for the update :)

**Comment by robmburke** [comment]
And yeah, RTF is a pain.

**Comment by Petarian** [comment]
For some reason scintilla.Copy(CopyFormat.Html) is not doing anything. Copy(CopyFormat.Rtf) works fine. I am using version 3.5.1.0. Nothing is getting copied to the clipboard.

**Comment by theryan722** [comment]
@Petarian It is in fact getting copied to the clipboard, just in HTML format. I thought the same thing at first as well. An application has to be able to handle the format in order to view it. It is planned in the future to add the ability to export the contents of the control in HTML as a string.

**Comment by Petarian** [comment]
Ah, I see. I tried pasting in MS Word and that worked. I wonder if this logic can be modified and instead of setting the data type to CF_HTML the type should be plain text. This way, it should copy the raw HTML code as string. 

Obviously, a better option would be to have both.

BTW, I love ScintillaNet and wanted to thank Jacob for all the work he is doing.

**Comment by robmburke** [comment]
I know I requested this a long time ago, but I am just now getting into a place where I started using this feature.  I am reopening this because, while I wasn't super specific, I didn't expect this bug to happen.

As Petarian noted, because of whatever the object type is that is sent to the clipboard, a program that doesn't know what to do with HTML cannot handle this and will not display anything.

The normal behavior for most programs would to still allow the text itself to be pasted if it can't support the markup.  I used Copy(CopyStyle.HTML) and pasted it into Outlook just fine.  Notepad and Notepad++ had no clue that there was still text available.  I then copied what I pasted into Outlook and pasted that into both Notepad and Notepad++ and got just the text with no highlighting, as would be expected.

This is the ultimate behavior I was looking for: something that was dynamic based on where the target paste was going to occur.  Sorry I did not make this expectation clear, but since most programs work this way, I guess I assumed it was a given.

**Comment by jacobslusser** [comment]
I think what you're looking for is `Scintilla.Copy(CopyFormat.Text | CopyFormat.Rtf | CopyFormat.Html)`

**Comment by robmburke** [comment]
Oh. Is that how that works.  So i guess it's a similar process  with other applications to supply multiple formats at once so that the proper one can be chosen? Not too familiar with how the clipboard works.  Sorry to drudge this up again then.  Didn't realize you supported  multiple inputs or that that would even be possible.

Thanks

**Comment by jacobslusser** [comment]
No worries. BTW, you may find a "clipboard viewer" application interesting. Google it. It can show you everything that is currently on the clipboard.
