### ISSUE TITLE
OnPreviewKeyDown event inconsistency

### ISSUE THREAD

**Issue by HTD** [jacobslusser/ScintillaNET#101]
I have code like this:

        protected override void OnPreviewKeyDown(PreviewKeyDownEventArgs e) {
            if (e.Control && e.KeyCode == Keys.G) {
                Controls.Add(new GoToLineControl(this));
                e.IsInputKey = false;
            }
            base.OnPreviewKeyDown(e);
        }

I get [BEL] symbol inserted to edited text, despite of e.IsInputKey is set false. There is a workaround for this, assign any command to the same keyboard shortcut. I assign `Command.Cancel`, but it's not exactly `NoOperation` as I'd prefer.

**Comment by jacobslusser** [comment]
```cs
protected override bool ProcessCmdKey(ref Message msg, Keys keyData)
{
    if ((keyData & (Keys.Control | Keys.G)) > 0)
    {
        // Do stuff here
        return true;
    }

    return base.ProcessCmdKey(ref msg, keyData);
}
```

**Comment by HTD** [comment]
This, after changing condition from `((keyData & (Keys.Control | Keys.G)) > 0` to `keyData == (Keys.Control | Keys.G)` it actually works. It's probably because `Keys` `enum` is like `1, 2, 3, 4, 5...` and not like `1, 2, 4, 8, 16...`. And probably it's designed this way to make shortcut easily configurable, so you can just test equality to configured shortcut.

It still looks like inconsistency, but I just found similar "inconsistencies" with `KeyDown` and `PreviewKeyDown` events in original Microsoft .NET controls, like `ToolStrip`. It's impossible to intercept `Escape` key pressed inside `ToolStripTextBox` with those events, but `ProcessCmdKey` works as charm.

So it's probably safe to assume it's a feature not bug.

**Comment by robmburke** [comment]
Tou are doing an Or.  need to do an And

**Comment by jenokizm** [comment]
Hi, your solution works. However, I have a question, this can be done without creating your own class with inheritance and overriding?

**Comment by Fduch93** [comment]
InsertCheck event worked for me, this solution does not need overriding `ProcessCmdKey` in a derived class.
Composition over inheritance, guys.
```C#
private void sci_InsertCheck(object sender, InsertCheckEventArgs e)
{
    if (e.Text.Length == 1 && char.IsControl(e.Text[0]))
        e.Text = string.Empty;
}
```
