### ISSUE TITLE
How to update Scintilla styles on the fly without changing previously styled text?

### ISSUE THREAD

**Issue by rdarnold** [jacobslusser/ScintillaNET#102]
Hello,
I'm trying to write a MUD (telnet) client using ScintillaNET to control styles - but to use Scintilla as I understand it, this requires a ton of styles to be set (16 bits of color plus flashing, and other styles).  This is greater than the 256 max style limit of the Scintilla.  Is there a way I can update a style on the fly without also updating all the text that was previously styled in that same style?  For example, I would like to color some text dark green using a style, but then change that style to dark yellow to color a later piece of text without affecting the state of the earlier text (still display it as green).  Is this possible, and if so, how do I do it?
Thanks!

**Comment by jacobslusser** [comment]
Generally speaking, ScintillaNET isn't designed for this type of display. The assumption is that most people will use ScintillaNET for displaying source code and the language elements don't change their style once defined. For this reason, ScintillaNET defines styles separately from the application of styles. Define once, apply many.

What you're looking for is the ability to style text in a very unstructured way. To give something a color but not necessarily say what type of language construct it is. This is more akin to what a RichTextBox does. It doesn't attempt to attach meaning to the text, only set the appearance.

If you have less than 256 possible combinations of font, color, background color, etc... then you *could* do this with ScintillaNET, but it sounds like you intend to exceed that, in which case, there isn't a (good) workaround.

**Comment by rdarnold** [comment]
Thanks for the quick reply!  The problem with RichTextBox and the reason I went with Scintilla is due to the immutable strings in the C# RichTextBox.  My text buffer could potentially grow infinitely (or at least, very large) and the constant string reallocation is very slow.  It actually works extremely well with Scintilla, I just can't support all the colors.  Is there a way I can just increase the max number of styles, and if I do that, is that going to have any negative performance effects anywhere?

**Comment by jacobslusser** [comment]
ScintillaNET is a wrapper around Scintilla and it has a limit of 256 document styles. I know that's not the answer you were hoping for, but that is the reality of the situation. :(

I'm interested though in what you come up with so please report back when you decide on an approach.

**Comment by rdarnold** [comment]
Hmm, darn it.  Well one potential approach I might use is to set up styles dynamically for the colors as they're used.  That way unless all colors with backgrounds were used within a single buffer, which is unlikely, everything would be fine.  Might be a decent compromise.
