### ISSUE TITLE
Links as hotspots

### ISSUE THREAD

**Issue by jonandr** [jacobslusser/ScintillaNET#105]
Hello,

I am working on a text editor based on ScintillaNET: https://github.com/jonandr/Strindberg

I've been trying to figure out how to get ScintillaNET to highlight URLs and respond to double-clicks (so the links can be opened in a browser). I know Notepad++ does this by marking URLs as hotspots and then handling the "SCN_HOTSPOTDOUBLECLICK" message from Scintilla. Is this possible to do in ScintillaNET?

**Comment by jacobslusser** [comment]
In commit 966458804bf27cad7f581f6051585e3f69e222a7 I added the missing events: `HotspotClick`, `HotspotDoubleClick`, and `HotspotRelease`. Let me know if you need anything else.

**Comment by theryan722** [comment]
How do you mark something as a hotspot?

**Comment by jonandr** [comment]
@jacobslusser  Thanks.

@theryan722 I haven't tested it yet, but I think you should set the Hotspot property on the style to true and then style the text you want.

~~~
            if (_sci.Text.Length > 5)
            {
                _sci.Styles[1].Hotspot = true;
                _sci.StartStyling(0);
                _sci.SetStyling(5, 1);
            }
~~~
