### ISSUE TITLE
How can I modify the CPP lexer to have more then a keyword set ?

### ISSUE THREAD

**Issue by JohnyMac** [jacobslusser/ScintillaNET#106]
As the title says.
I use this to set the styles of the existing keywords: 
```
Editor.Styles(Style.Cpp.Word).ForeColor = Color.Blue
Editor.Styles(Style.Cpp.Word2).ForeColor = Color.CadetBlue
```

And then I do: 
```
Editor.SetKeywords(0, "bla Bla")
Editor.SetKeywords(1, "Bla Bla")
```

How can I add more like, Word3, Word4 and so on.

**Comment by jacobslusser** [comment]
Can't. :(

The lexers that ship with Scintilla are what they are. They can't be extended or modified.

**Comment by JohnyMac** [comment]
Is there any other lexers that are the similar to the CPP but can be modified ?

**Comment by jacobslusser** [comment]
Not to my knowledge. With the Scintilla lexers, you either accept them completely as-is, or write your own lexer from scratch. There are no extensible lexers in Scintilla. 

Perhaps we can solve your problem another way though. If you tell me a little more of what you're trying to do maybe there is an alternative approach.

**Comment by JohnyMac** [comment]
Its same as issue #102 honestly.

I was thinking to do like each time i parse the codes, I refresh the list of the keywords in Scintilla with the functions I have detected to color them.

However, Set 1 is already used for the language keywords, And I need 2 more sets.
One will be for the functions and one will be for defines.

**Comment by JohnyMac** [comment]
Ok.. Honestly its very annoying to have pretty much 75% of the keywords in the same color.
Greatly appreciated if you can provide a work around for this.

**Comment by jacobslusser** [comment]
I don't have a good answer for this. I was hopeful that there was some other trick we could employ to get you what you want, but in this case it seems what you want/need is more keyword lists than the C++ lexer offers.

**Comment by kphillisjr** [comment]
I believe it takes knowing how to set each keyword set. That said, here is the list of how keywords are set. Just as a note, where the identifier is found does make a huge difference.

Keyword Set | style |  description
------------ | ------------ | -------------
0 | Style.Cpp.Word | Primary keywords and identifiers
1 | Style.Cpp.Word2 | Secondary keywords and identifiers
2 | Style.Cpp.CommentDocKeyword | Documentation comment keywords
3 | Style.Cpp.GlobalClass | Global classes and typedefs
4 | Style.Cpp.Preprocessor | Preprocessor definitions
5 |  Style.Cpp.TaskMarker |Task marker and error marker keywords

**Comment by JohnyMac** [comment]
The problem is that I am using the CPP lexer for a non CPP language...
For example, I have the Style.Cpp.GlobalClass set to none.. As in the language I am doing its called "enum" and not "typedef" and plus that the lang is not OOP so no classes too....

So yeah.. thats the problem here.. 75% of the styles here are useless for me so I need custom ones..

However, Thanks for attempting to help :)

**Comment by kphillisjr** [comment]
I understand this, and you do have some global classes... there is just not a lot of these.
``` CS
/* Some Base Keywords */
Editor.SetKeywords(0, "new native const forward operator public "
         "stock static defined sizeof state tagof");

/* Basic Control statements */
Editor.SetKeywords(1, "assert break enum continue default do else "
         "exit for goto if return sleep state switch while case default");

/* Comment Doc goes here.*/
Editor.SetKeywords(2, "");

/* Global Classes. */
Editor.SetKeywords(3, "Rational Fixed bool");

/* These are Pre-Processor stuff. As a quick note, you can include duplicate stuff here. */
Editor.SetKeywords(4, "assert define else elseif endif  endinput  error  file "
         "include line pragma section tryinclude undef defined sizeof state tagof");

/* Marker keywords*/
Editor.SetKeywords(5, "FIXME TODO HACK UNDONE");
```

**Comment by JohnyMac** [comment]
Ooooooo..... If this is correct.. You sir saved my life :D
I never knew you can change the keywords of those stylesets...

If this works, Seriously.. Thanks a lot :)

**Comment by JohnyMac** [comment]
Sorry for taking long to reply but I was busy with other aspects of my program.

I have tested this right now and its working great :D
Thanks a lot :)

**Comment by SinghRajenM** [comment]
@Ahmad45123 As I can solution described by @kphillisjr worked for you. Now, I am in same situation. I need to utilize existing lexer. How can I clear the existing lexer completely and define my keywords, comment text, operator, folding etc.?

Example of file is as below - 

```
*% This is comment

*Feature: Locale
{
    *Name: "Locale"
    *ConcealFromUI?: TRUE
    *Option: Option 1
    {
        *Name: " My Option1 "
        *OptionID: 0x0000
    }
    *Option: Option 2
    {
        *Name: " My Option2 "
        *OptionID: 0x0001
    }
}
```
In above 

`*% `This is comment. it can start anywhere
`* Feature`, `*Name`, `*ConcealFromUI?` etc staring with * are keywords
`:` is kind of operator
`0x0001` is number. it can be in decimal
String can start with `"` or `'`

**Comment by Ahmad45123** [comment]
@SinghRajenM I ended up using StartStyling and SetStyling methods in the UpdateStyle event.
However, in my case, I only wanted to colorize different keywords so it was fairly easy to code.
I'm not sure how'd you do what you want.

https://github.com/Ahmad45123/ExtremeStudio/blob/master/ExtremeStudio/DockPanelForms/MainFormDocks/EditorDock/EditorDock.cs#L885-L1120

**Comment by SinghRajenM** [comment]
@Ahmad45123 Thank you for quick reply. I'm using C++ flavor of Scinitilla. I will check your solution and will try to utilize it. 😊
