### ISSUE TITLE
Context Menu on ScintillaNet 

### ISSUE THREAD

**Issue by METOUIA7** [jacobslusser/ScintillaNET#107]
Hi, How to change context menu copy cut past  into copie couper coller (french)

**Comment by jacobslusser** [comment]
I believe Scintilla uses the standard EDIT control context menu provided by Windows and assume that if you change the default language in Windows to French, this menu would be French also. If that is not the case and you wanted to provide your own context menu you can disable the default with the `UsePopup` property and then provide your own.

**Comment by METOUIA7** [comment]
thanks alot for help

**Comment by andy194** [comment]
Hi, is there a way to extend the context menu with new items yet?  After initialisation I've checked to see if it's accessible but it's null, yet appears when right clicking with the standard edit items in-place.

**Comment by roblarky** [comment]
It appears it does not use the Windows edit menu. I've had users confirm that the context menu in text boxes (within my app) receive their language in the context menu, but see English in the ScintillaNET editor window.
