### ISSUE TITLE
Find next/previous in selection

### ISSUE THREAD

**Issue by theryan722** [jacobslusser/ScintillaNET#108]
Here is the code I have for find next in selected text:

searchselect_start is the start position of the selection, and searchselect_end is the end position of the selection. I set these as variables because when iterating through the search, it selects the found word.

```c#
Scintilla1.SearchFlags = sf;
Scintilla1.TargetStart = Math.Max(Scintilla1.CurrentPosition, searchselect_start);
Scintilla1.TargetEnd = searchselect_end;
dynamic pos = Scintilla1.SearchInTarget(txt);
if (pos >= 0) {
	Scintilla1.SetSel(Scintilla1.TargetStart, Scintilla1.TargetEnd);
	return Scintilla1.TargetStart;
} else {
	Scintilla1.SearchFlags = sf;
	Scintilla1.TargetStart = searchselect_start;
	Scintilla1.TargetEnd = searchselect_end;
	dynamic pos1 = Scintilla1.SearchInTarget(txt);
	if (pos1 >= 0) {
		Scintilla1.SetSel(Scintilla1.TargetStart, Scintilla1.TargetEnd);
		return Scintilla1.TargetStart;
	} else {
		return -1;
	}
}
```

However I cannot get this to work for FindPrevious. Any ideas?

**Comment by sepich** [comment]
Looked and haven't found nice way to do it too. For now did it like that
```
scintilla.Text.LastIndexOf(text, Math.Max(0, scintilla.CurrentPosition-2), StringComparison.CurrentCultureIgnoreCase);
```
Or there is a way to [destroy the world](https://github.com/jacobslusser/ScintillaNET/wiki/Direct-Messages) by using `DirectMessage` and SCI_FINDTEXT

**Comment by jacobslusser** [comment]
```cs
public int FindNext(string text, SearchFlags flags)
{
    scintilla.SearchFlags = flags;
    scintilla.TargetStart = Math.Max(scintilla.CurrentPosition, scintilla.AnchorPosition);
    scintilla.TargetEnd = scintilla.TextLength;

    var pos = scintilla.SearchInTarget(text);
    if (pos >= 0)
        scintilla.SetSel(scintilla.TargetStart, scintilla.TargetEnd);

    return pos;
}

public int FindPrevious(string text, SearchFlags flags)
{
    scintilla.SearchFlags = flags;
    scintilla.TargetStart = Math.Min(scintilla.CurrentPosition, scintilla.AnchorPosition);
    scintilla.TargetEnd = 0;

    var pos = scintilla.SearchInTarget(text);
    if (pos >= 0)
        scintilla.SetSel(scintilla.TargetStart, scintilla.TargetEnd);

    return pos;
}
```

**Comment by theryan722** [comment]
Thanks, my code for the FindPrevious was quite similar but I sort of see the mistake now.

**Comment by KaosKidd** [comment]
Jacob; Thanks for the "spot on" code!  I've created a VB.Net equivalent code for non C programmers:
`    Private Sub btnNext_Click(sender As Object, e As EventArgs) Handles btnNext.Click
        If cbxFind.Text.ToString > "" Then Find(cbxFind.Text.ToString, GetFlags(), True)
    End Sub

    Private Sub btnPrevious_Click(sender As Object, e As EventArgs) Handles btnPrevious.Click
        If cbxFind.Text.ToString > "" Then Find(cbxFind.Text.ToString, GetFlags(), False)
    End Sub
    Private Sub Find(ByVal sTerm As String, ByVal SearchFlags As Integer, ByVal bForwardFlag As Boolean)
        Editor.searchFlags = SearchFlags
        Editor.TargetStart = Max(Editor.CurrentPosition, Editor.AnchorPosition)
        If bForwardFlag = True Then
            Editor.TargetEnd = Editor.TextLength
        Else
            Editor.TargetEnd = 0
        End If
        Dim iPos As Integer = Editor.SearchInTarget(sTerm)
        If iPos >= 0 Then
            Editor.SetSel(Editor.TargetStart, Editor.TargetEnd)
        End If
    End Sub
    Private Function GetFlags() As Integer
        'TODO Convert to actual search flags
        Return ScintillaNET.SearchFlags.None
    End Function
    Private Function Max(ByVal iNum1 As Integer, ByVal iNum2 As Integer)
        If IsNumeric(iNum1) And IsNumeric(iNum2) Then
            If iNum1 > iNum2 Then Return iNum1 Else Return iNum2
        Else
            Return 0
        End If
    End Function`
