### ISSUE TITLE
Disable Graying out of a Preprocessor block Programatically

### ISSUE THREAD

**Issue by ajithpadman** [jacobslusser/ScintillaNET#109]
I have seen Scintilla automatically Grays out (mostly dos not do syntax highlight) for a block of code inside the Preprocessor Directive.Such as 

#if defined(MACRO)
   someCodeBlock...
#endif 

How can I reenable the syntax highlighting of this "someCodeBlock" with out adding #define MACRO in the same file. In case the macro is enabled in some other files or as a compilation argument. 

Is there a way available ?

**Comment by jacobslusser** [comment]
The answer to this question is briefly described in the original Scintilla documentation about new lexer capabilities here: [http://www.scintilla.org/nulex.html](http://www.scintilla.org/nulex.html).

In summary it works like this in ScintillaNET:

1. Use keyword set `5` to specify the defines. They take the form `"name=value name=value"`. i.e. `"WIN32=1 NOGDI=0"`.
2. Enable the `"lexer.cpp.track.preprocessor"` and `"lexer.cpp.update.preprocessor"` lexer properties.
3. Use the `Style.Cpp.` constants plus `64` to define how styles should appear in the disabled preprocessor blocks.

```cs
scintilla.SetProperty("lexer.cpp.track.preprocessor", "1");
scintilla.SetProperty("lexer.cpp.update.preprocessor", "1");
scintilla.SetKeywords(5, "WIN32=1 WIN32_LEAN_AND_MEAN NOGDI=0");
scintilla.Styles[Style.Cpp.Default + 64].BackColor = Color.LightGray;
scintilla.Styles[Style.Cpp.Comment + 64].BackColor = Color.LightGray;
// etc...
``` 

I'll make a note to add new `+64` constants to ScintillaNET to make this a little easier going forward.
