### ISSUE TITLE
How to get column editing to work

### ISSUE THREAD

**Issue by theryan722** [jacobslusser/ScintillaNET#110]
I am able to use Alt+Mouse to select a column of text, but when I start typing it only starts typing on the bottom of the selection instead of all of the lines. Am I missing something?

**Comment by jacobslusser** [comment]
Could `Scintilla.AdditionalSelectionTyping` be what you're looking for? Some more information is available on the [wiki](https://github.com/jacobslusser/ScintillaNET/wiki/Rectangular-and-Multiple-Selections).

**Comment by theryan722** [comment]
Thanks alot!
