### ISSUE TITLE
Combining hotspots with syntax highlighting

### ISSUE THREAD

**Issue by jonandr** [jacobslusser/ScintillaNET#111]
Hello,

I am trying to figure out how to add hotspots (for URLs) in documents which have had syntax highlighting applied. My current method:

1) Define a new style for hotspots.
2) In UpdateUI, look for URLs (with a regex) and use SetStyle to change the style for the range to the hotspot style.

It works, but only if you place the cursor at the right place:

![good](https://cloud.githubusercontent.com/assets/1019727/9561512/63e39eaa-4e49-11e5-89b5-7fc49662750b.png)

Move it down and the hotspot style gets overwritten:

![bad](https://cloud.githubusercontent.com/assets/1019727/9561519/905df098-4e49-11e5-8180-7317b3156463.png)

My guess is that the syntax highlighter owns the styles. Is there some way to solve it? Maybe some way to mark text as "user styled"...

**Comment by jacobslusser** [comment]
Your assumption is correct. The built-in lexers assume they own the text and styles. Trying to do your own styles on top of that will likely get them overwritten.

Fortunately, what you're trying to do can be accomplished with indicators. Indicators are not used by lexers and so wont get overwritten. Assuming all you would like to do is underline some text that contains a URL, you could configure an indicator like this:

```cs
// Define an indicator for marking URLs and apply it to a range.
// How you determine a particular range is a URL and how often
// you want to scan the text for them is up to you.
scintilla.Indicators[0].Style = IndicatorStyle.Plain;
scintilla.Indicators[0].ForeColor = Color.Blue;
scintilla.IndicatorCurrent = 0;
scintilla.IndicatorFillRange(0, 21); // Use your own logic

// An indicator can only change the appearance of text in one way. So
// to get underlining AND a different foreground color we have to use two indicators.
scintilla.Indicators[1].Style = IndicatorStyle.TextFore;
scintilla.Indicators[1].ForeColor = Color.Blue;
scintilla.IndicatorCurrent = 1;
scintilla.IndicatorFillRange(0, 21); // Use your own logic
```

That--plus your own custom logic for identifying the URL text--is all you need to mark a range of text in blue/underlined and not interfere with the styling process. In commit 251fe96220b796a1c8d2eda9c215c03a0ea6c98f I added some events that will get raised when an indicator is clicked. If we take this example a step further, we can handle the `IndicatorClick` event to actually open the URL.

```cs
private void scintilla_IndicatorClick(object sender, IndicatorClickEventArgs e)
{
    var url = GetUrlAtPosition(e.Position);
    if (url != null)
    {
        // Open the URL in the default browser
        var psi = new ProcessStartInfo { FileName = url, UseShellExecute = true };
        Process.Start(psi);
    }
}

private string GetUrlAtPosition(int position)
{
    // Determine whether the specified position is on our 'URL indicator'
    // and if so whether it is a valid URL.

    var urlIndicator = scintilla.Indicators[0];
    var bitmapFlag = (1 << urlIndicator.Index);
    var bitmap = scintilla.IndicatorAllOnFor(position);
    var hasUrlIndicator = ((bitmapFlag & bitmap) == bitmapFlag);

    if (hasUrlIndicator)
    {
        var startPos = urlIndicator.Start(position);
        var endPos = urlIndicator.End(position);

        var text = scintilla.GetTextRange(startPos, endPos - startPos).Trim();
        if (Uri.IsWellFormedUriString(text, UriKind.Absolute))
            return text;
    }

    return null;
}
```

Cool. Now when a user clicks on some text using indicator `0` our code will find the start and end range of that indicator, determine if it is a valid URL, and then open it. For more information on indicators, see the [documentation](https://github.com/jacobslusser/ScintillaNET/blob/master/docs/sections/indicators.md).

We can take this example one step further though. One of the limitations of using indicators is that it won't change the cursor the way a hotspot style does. No matter. Visual Studio doesn't change the cursor style either. What it does is display a tool-tip indicating to the user that they can open the link when holding the `CTRL` key and clicking the text. We can do the same by displaying a call-tip in the `DwellStart` event and checking for the `CTRL` key when clicked.

Here's the complete sample:

```cs
private void form_Load(object sender, EventArgs e)
{
    scintilla.Text = "http://www.google.com";

    // Define an indicator for marking URLs and apply it to a range.
    // How you determine a particular range is a URL and how often
    // you want to scan the text for them is up to you.
    scintilla.Indicators[0].Style = IndicatorStyle.Plain;
    scintilla.Indicators[0].ForeColor = Color.Blue;
    scintilla.IndicatorCurrent = 0;
    scintilla.IndicatorFillRange(0, 21); // Use your own logic

    // An indicator can only change the appearance of text in one way. So
    // to get underlining AND a different foreground color we have to use two indicators.
    scintilla.Indicators[1].Style = IndicatorStyle.TextFore;
    scintilla.Indicators[1].ForeColor = Color.Blue;
    scintilla.IndicatorCurrent = 1;
    scintilla.IndicatorFillRange(0, 21); // Use your own logic

    // BONUS: Configure call tips for the Dwell events
    scintilla.MouseDwellTime = 400;
    scintilla.Styles[Style.CallTip].SizeF = 8.25f;
    scintilla.Styles[Style.CallTip].ForeColor = SystemColors.InfoText;
    scintilla.Styles[Style.CallTip].BackColor = SystemColors.Info;
}

private void scintilla_IndicatorClick(object sender, IndicatorClickEventArgs e)
{
    var url = GetUrlAtPosition(e.Position);
    if (url != null && (e.Modifiers & Keys.Control) == Keys.Control)
    {
        // Open the URL in the default browser
        var psi = new ProcessStartInfo { FileName = url, UseShellExecute = true };
        Process.Start(psi);
    }
}

private void scintilla_DwellStart(object sender, DwellEventArgs e)
{
    var url = GetUrlAtPosition(e.Position);
    if (url != null)
    {
        var callTip = string.Format("{0}\nCTRL + click to follow link", url);
        scintilla.CallTipShow(e.Position, callTip);
    }
}

private void scintilla_DwellEnd(object sender, DwellEventArgs e)
{
    scintilla.CallTipCancel();
}

private string GetUrlAtPosition(int position)
{
    // Determine whether the specified position is on our 'URL indicator'
    // and if so whether it is a valid URL.

    var urlIndicator = scintilla.Indicators[0];
    var bitmapFlag = (1 << urlIndicator.Index);
    var bitmap = scintilla.IndicatorAllOnFor(position);
    var hasUrlIndicator = ((bitmapFlag & bitmap) == bitmapFlag);

    if (hasUrlIndicator)
    {
        var startPos = urlIndicator.Start(position);
        var endPos = urlIndicator.End(position);

        var text = scintilla.GetTextRange(startPos, endPos - startPos).Trim();
        if (Uri.IsWellFormedUriString(text, UriKind.Absolute))
            return text;
    }

    return null;
}
```

**Comment by jonandr** [comment]
Thanks, seems to work well!

**Comment by jonandr** [comment]
For future reference, there is a slight issue when the indicator is placed at the absolute end of a document. Consider this example:

![click](https://cloud.githubusercontent.com/assets/1019727/9564155/13c561a2-4e9d-11e5-965a-cd81e27370ee.png)

Using @jacobslusser's code, then clicking anywhere in the red area will count as a click on the indicator.

Something like this is better, but not perfect because it doesn't allow you to click on the very last m:

```
private void scintilla_IndicatorClick(object sender, IndicatorClickEventArgs e)
{
    if(e.Position == scintilla.TextLength)
        return;

    var url = GetUrlAtPosition(e.Position);
    if (url != null && (e.Modifiers & Keys.Control) == Keys.Control)
    {
        // Open the URL in the default browser
        var psi = new ProcessStartInfo { FileName = url, UseShellExecute = true };
        Process.Start(psi);
    }
}
```
