### ISSUE TITLE
Markdown Lexer: what am I missing?

### ISSUE THREAD

**Issue by qujck** [jacobslusser/ScintillaNET#116]
I'm trying to highlight Markdown in the `Scintilla` control but can't get anything to work.

For example, I have the following code

```csharp
private void Form1_Load(object sender, EventArgs e)
{
    this.textBox1.Styles[Style.Markdown.Header1].Size = 20;
    this.textBox1.Lexer = Lexer.Markdown;
}
```

But nothing happens when I enter markdown such as:

```
# Heading

Heading
=======
```

What am I doing wrong?

**Comment by jacobslusser** [comment]
Not sure, let me take a look.

**Comment by theryan722** [comment]
It's working fine for me. Perhaps you didn't set the lexer styles? I.e.
```c#
Scintilla1.Styles(Style.Markdown.Header1).ForeColor == COLOR_HEADER
```

**Comment by qujck** [comment]
You're right that colour does work (although it only changes the colour of the `#` not the whole line and does nothing for `=======`).

Does size work for you?

**Comment by qujck** [comment]
Despite the very clear instructions in the wiki I missed the line `this.TextView.StyleClearAll();`

It's sort of working now, including the size

**Comment by theryan722** [comment]
Yeah the lexer for Markdown is a bit weird for me as well.
