### ISSUE TITLE
Construct git diff

### ISSUE THREAD

**Issue by Aghlara** [jacobslusser/ScintillaNET#118]
I have list of lines which I know their status based on time, (deleted, added) now I want to construct something like bellow:

![image](https://cloud.githubusercontent.com/assets/5187409/9951574/7464e7b2-5e0b-11e5-939e-fbf22adcafe6.png)

Any idea how to do this?

**Comment by Aghlara** [comment]
To be more specific I am asking about the line numbers.

**Comment by jonandr** [comment]
There are 4 margins in Scintilla and you can display whatever you want in them. Haven't tried it in ScintillaNET specifically, but try repurposing margins 0 and 1 (they display ordinary line numbers and some symbols by default) and fill them manually with your line numbers the diff algorithm. You will need to set the margin types to text (SCI_SETMARGINTYPEN/SC_MARGIN_TEXT) and then use SCI_MARGINSETTEXT to set the text. (Or rather, the ScintillaNET equivalents, hopefully these exist on the control's Margin member).

http://www.scintilla.org/ScintillaDoc.html#Margins

**Comment by jacobslusser** [comment]
What @jonandr is describing can be done in ScintillaNET by following the documentation on custom line numbers.

[https://github.com/jacobslusser/ScintillaNET/wiki/Displaying-Line-Numbers](https://github.com/jacobslusser/ScintillaNET/wiki/Displaying-Line-Numbers)

**Comment by Aghlara** [comment]
Thanks for the response.

I managed to do the custom numbering on the Margin.

How do I change the forecolor in margin? I do see MarginStyle in each line, but cannot understand how does that work.

Thanks,

**Comment by Aghlara** [comment]
I found the answer,

```
codeViewer.Styles[10].ForeColor = System.Drawing.Color.Red;
```

And then you set `MarginStyle = 10` for example.

Cheers,
