### ISSUE TITLE
Customize behavior of Home button for wrapped lines

### ISSUE THREAD

**Issue by jonandr** [jacobslusser/ScintillaNET#119]
Does Scintilla have a setting for customizing how Home (and End) work for wrapped lines? I'd like for it to go to the "virtual" beginning (or end) of a line, and not the "actual" beginning/end.

As an example, here is a wrapped line:

![x](https://cloud.githubusercontent.com/assets/1019727/9976163/5ef0a60c-5edb-11e5-83f2-9ecf34923450.png)

If I place the cursor at the last character (the Y) and then press Home, I want the cursor to end up at the X.

Notepad++ has this behavior but I can't figure out how it does it.

**Comment by jacobslusser** [comment]
By default I believe the Home key is bound to the `Command.Home` command. What you want is to bind it to either the `Command.HomeDisplay` or `Command.HomeWrap` command using `Scintilla.AssignCmdKey`.

Please refer to the [documentation](https://github.com/jacobslusser/ScintillaNET/wiki/Key-Bindings).

**Comment by jonandr** [comment]
Thanks.
