### ISSUE TITLE
How can I prevent ScintillaNET from destroying on Form.Close()

### ISSUE THREAD

**Issue by Petarian** [jacobslusser/ScintillaNET#123]
Hi,
I want to hide my form, not close. Here is my code for the FormClosing event:

private void HandleFormClosing(object sender, FormClosingEventArgs e) {            
            e.Cancel = true;
            Hide();
        }

However, the HandleDestroy event of Scintalla still gets called and the scintilla controls is no longer valid.

How can I make this to not destroy?

**Comment by JohnyMac** [comment]
I am pretty sure this is related to the issue #85

**Comment by jacobslusser** [comment]
Please try using commit d632e6ee64bd5ef647706fadd89edf58fc2eda55 and let me know if that solves your issue.
