### ISSUE TITLE
[Question] How to change the backcolor of a margin. (A folding one)

### ISSUE THREAD

**Issue by JohnyMac** [jacobslusser/ScintillaNET#125]
I am making a some sort of a themeing system.
However, I am unable to change the margin back-color because I don't know how.

Example: 
![You can see margin 2 white here](https://i.gyazo.com/3f39c055e957f82b4383edaa4016aeef.png)

I think you can clearly see margin 2 is white while the rest is black.

Also, Here is the function I use to change the back-color: 
Yes its vb.net, But it should be understandable to any C# developer :P
```vb.net
Private Sub SetBackColor(clr As Color)
        For Each stle As Style In Editor.Styles
            stle.BackColor = clr
        Next
End Sub
```

**Comment by jacobslusser** [comment]
I believe `Styles[Style.LineNumber]` will be the style used for any margin that is NOT a fold margin. For fold margins, the colors are determined by the markers used. i.e.

```cs
Markers[Marker.FolderEnd].SetBackColor(Color.Black);
// etc...
```

**Comment by JohnyMac** [comment]
So, I did: 
```vb.net
    Private Sub SetBackColor(clr As Color)
        For Each stle As Style In Editor.Styles
            stle.BackColor = clr
        Next

        Editor.Markers(Marker.Folder).SetBackColor(clr)
        Editor.Markers(Marker.FolderOpen).SetBackColor(clr)
        Editor.Markers(Marker.FolderEnd).SetBackColor(clr)
        Editor.Markers(Marker.FolderMidTail).SetBackColor(clr)
        Editor.Markers(Marker.FolderOpenMid).SetBackColor(clr)
        Editor.Markers(Marker.FolderSub).SetBackColor(clr)
        Editor.Markers(Marker.FolderTail).SetBackColor(clr)
    End Sub
```

But no difference..

**Comment by jacobslusser** [comment]
Sorry, bad advice. The `Marker.SetBackColor` and `Marker.SetForeColor` methods affect the color of the fold symbols, not the margin.

For the margin you'll want `Scintilla.SetFoldMarginColor` and `Scintilla.SetFoldMarginHighlightColor`. See pull #12.

**Comment by JohnyMac** [comment]
Yep, Worked.. 
Thanks.

**Comment by jacobslusser** [comment]
FYI [ScintillaNET v3.6.3](https://github.com/jacobslusser/ScintillaNET/releases) brings support for additional margins beyond the limit of 5 and support for more background color options.

**Comment by thehill383** [comment]
i was struggling to put together a themed JSON viewer with folding. After looking at this article i was able to get the background colour of the folding margin set correctly but the + - symbol did not have the correct colours.

what i realised was, that when you set the colours of the markers, you have to switch round fore and back colours, so you actually set the forecolor to your backcolor and vice versa

      ' Set colors for all folding markers
        For i As Integer = 25 To 31
            Scintilla1.Markers(i).SetForeColor(backcolor)
            Scintilla1.Markers(i).SetBackColor(forecolor)
        Next i

my full sample is here. I am actually getting my back and fore colors from a devexpress theme that i am trying to match, but you could modify to use your own colors. Hope this helps someone else


        Dim currentskin As DevExpress.Skins.Skin = DevExpress.Skins.CommonSkins.GetSkin(UserLookAndFeel.Default)
        Dim backcolor As Color = currentskin.Colors("Control")
        Dim forecolor As Color = currentskin.Colors("ControlText")

        Scintilla1.StyleResetDefault()
        Scintilla1.Styles(Style.Json.Default).Font = "Consolas"
        Scintilla1.Styles(Style.Default).Size = 10

        Scintilla1.Margins(0).Width = 35
        Scintilla1.Margins(0).BackColor = backcolor

        Scintilla1.Lexer = ScintillaNET.Lexer.Json
        Scintilla1.Zoom = 3

        Scintilla1.Styles(Style.Default).BackColor = backcolor

        Scintilla1.Styles(Style.Json.Default).ForeColor = forecolor
        Scintilla1.Styles(Style.Json.Default).BackColor = backcolor

        Scintilla1.Styles(Style.Json.BlockComment).ForeColor = Color.FromArgb(0, 128, 0)
        Scintilla1.Styles(Style.Json.BlockComment).BackColor = backcolor

        Scintilla1.Styles(Style.Json.LineComment).ForeColor = Color.FromArgb(0, 128, 0)
        Scintilla1.Styles(Style.Json.LineComment).BackColor = backcolor

        Scintilla1.Styles(Style.Json.Number).ForeColor = Color.FromArgb(183, 206, 166)
        Scintilla1.Styles(Style.Json.Number).BackColor = backcolor

        Scintilla1.Styles(Style.Json.PropertyName).ForeColor = Color.FromArgb(14, 221, 219)
        Scintilla1.Styles(Style.Json.PropertyName).BackColor = backcolor

        Scintilla1.Styles(Style.Json.String).ForeColor = Color.FromArgb(201, 144, 118)
        Scintilla1.Styles(Style.Json.String).BackColor = backcolor

        Scintilla1.Styles(Style.Json.StringEol).BackColor = Color.Pink

        Scintilla1.Styles(Style.Json.Operator).ForeColor = forecolor
        Scintilla1.Styles(Style.Json.Operator).BackColor = backcolor

        Scintilla1.Styles(Style.Json.Error).ForeColor = Color.FromArgb(97, 156, 216)
        Scintilla1.Styles(Style.Json.Error).BackColor = backcolor

        Scintilla1.Styles(Style.Json.Uri).ForeColor = Color.FromArgb(201, 144, 118)
        Scintilla1.Styles(Style.Json.Uri).BackColor = backcolor

        Scintilla1.Styles(Style.LineNumber).ForeColor = forecolor
        Scintilla1.Styles(Style.LineNumber).BackColor = backcolor

        ' Instruct the lexer to calculate folding
        Scintilla1.SetProperty("fold", "1")
        Scintilla1.SetProperty("fold.compact", "1")

        ' Configure a margin to display folding symbols
        Scintilla1.Margins(2).Type = MarginType.Symbol
        Scintilla1.Margins(2).Mask = Marker.MaskFolders
        Scintilla1.Margins(2).Sensitive = True
        Scintilla1.Margins(2).Width = 20

        ' Configure folding markers with respective symbols
        Scintilla1.Markers(Marker.Folder).Symbol = MarkerSymbol.BoxPlus
        Scintilla1.Markers(Marker.FolderOpen).Symbol = MarkerSymbol.BoxMinus
        Scintilla1.Markers(Marker.FolderEnd).Symbol = MarkerSymbol.BoxPlusConnected
        Scintilla1.Markers(Marker.FolderMidTail).Symbol = MarkerSymbol.TCorner
        Scintilla1.Markers(Marker.FolderOpenMid).Symbol = MarkerSymbol.BoxMinusConnected
        Scintilla1.Markers(Marker.FolderSub).Symbol = MarkerSymbol.VLine
        Scintilla1.Markers(Marker.FolderTail).Symbol = MarkerSymbol.LCorner

        ' Set colors for all folding markers
        For i As Integer = 25 To 31
            Scintilla1.Markers(i).SetForeColor(backcolor)
            Scintilla1.Markers(i).SetBackColor(forecolor)
        Next i

        ' Enable automatic folding
        Scintilla1.AutomaticFold = (AutomaticFold.Show Or AutomaticFold.Click Or AutomaticFold.Change)

        Scintilla1.SetFoldMarginColor(True, backcolor)
        Scintilla1.SetFoldMarginHighlightColor(True, backcolor)
