### ISSUE TITLE
UseTabs not working on the latest version?

### ISSUE THREAD

**Issue by ascii1457** [jacobslusser/ScintillaNET#127]
Hi!
For some reason after update my project from ScintillaNET 3.2 to the last version, the function UseTabs (SCI_SETUSETABS) is not working anymore. I checked creating a new Scintilla control on a blank project and the problem persist ( The ver 3.2 works fine ).

I hope someone can test if is a real problem or not... Maybe i'm missing something.

**Comment by jacobslusser** [comment]
Works for me. Setting `Scintilla.UseTabs = true` will cause the tab character to be inserted when the tab key is used. Setting `Scintilla.UseTabs = false` will cause space characters to be inserted when the tab key is used.

Is that not what you're seeing?

**Comment by ascii1457** [comment]
Weird... in my case is always using space characters regardless of the UseTabs setting.

**Comment by jacobslusser** [comment]
I would guess commit 194d81bb2d733dab9c0bfc14b23baddbeb4fdc85 is related then to your issue. In summary, I discovered at that time that the tab settings are stored with the document and that switching the current document would reset the current tab settings. That commit copies the tab settings from one document to the next. 

Are you doing anything interesting with documents? Would you mind stepping through the code a bit to see if you can find where the setting is getting lost? I would do it myself but as I said I cannot seem to reproduce it.

**Comment by ascii1457** [comment]
Yep, the setting is lost when the Document parameter is set ( I'm using the "Documents" to add a mini-map to my editor )... I tested configuring the tabs values after the document setup and everything works fine... It's a strange behavior anyway.

**Comment by jacobslusser** [comment]
I found a small mistake in the default settings of `UseTabs` which I corrected in commit 91a951af71adfc362af4d3edc8a17b1a7117c834. Can you see if this resolves the issue you were seeing when changing documents?
