### ISSUE TITLE
ScrollCaret doesn't seem to work?

### ISSUE THREAD

**Issue by roschler** [jacobslusser/ScintillaNET#128]
I use the following code to try and auto-scroll the ScintillaNet control to the end after setting the Text property:

scintillaCtl.Text = newText;
scintillaCtl.ScrollCaret();

However, the control's client area is still positioned at the start of the text and the text extends beyond the bottom of the viewable client area.  How do I get the control to auto-scroll when text larger than the client area is assigned to the Text property?  I tried next:

scintillaCtl.Text = newText;
scintillaCtl.ScrollCaret();
scintillaCtl.Refresh();

But that didn't work either.  Note, I am using the ScintillaNET control embedded in a WindowsFormsHost control in a WPF 4.51 C# application.

**Comment by roschler** [comment]
I've come up with a work-around that successfully scrolls a Scintilla editor control:

http://stackoverflow.com/questions/2898722/how-make-autoscroll-in-scintilla/33172398#33172398

Seems like this is a bug though.  Perhaps ScrollCaret() needs to be updated?

**Comment by jacobslusser** [comment]
Setting the `Scintilla.Text` property doesn't change the position of the caret. You're expecting it to be at the end of the document and thus calling `ScrollCaret` will scroll to the end of the document. But if you check your caret position I'm sure you'll find that `ScrollCaret` is indeed scrolling the caret into view and that your caret is probably still at the start of your document, not the end.

What you want is to either set the caret to the last position of the document before calling `ScrollCaret` or use the `ScrollRange` method instead which allows you to scroll the display independent of the caret position. i.e.

```cs
scintilla.SetSel(scintilla.TextLength, scintilla.TextLength);
scintilla.ScrollCaret();

// --- or---

scintilla.ScrollRange(scintilla.TextLength, scintilla.TextLength);
```

No bug; no updates needed. :)

**Comment by roschler** [comment]
Thanks Jacob.  That makes sense.  Just tested it and it works fine.
