### ISSUE TITLE
Is there an INI lexer and if not, Any tips on how to create one ?

### ISSUE THREAD

**Issue by JohnyMac** [jacobslusser/ScintillaNET#129]
Hello,

I need an INI lexer, If its available already please add it.

And if not, I am sure a lexer for a simple thing like INI should be pretty easy but how can it be done, Is there any interfaces to use or something ?

**Comment by jacobslusser** [comment]
The `Properties` lexer in commit efeddf626cad60f85c380b5ad78ddd82c6bb0c21.

BTW, back in the day I created an INI lexer for ScintillaNET v2 to demonstrate how to create a custom lexer. Even though it is not necessary anymore you might still find the lessons there applicable in future projects.

[https://scintillanet.codeplex.com/SourceControl/latest#Trunk/SCide/IniLexer.cs](https://scintillanet.codeplex.com/SourceControl/latest#Trunk/SCide/IniLexer.cs)
