### ISSUE TITLE
Create a ScintillaNET demonstration app

### ISSUE THREAD

**Issue by jokn53** [jacobslusser/ScintillaNET#13]
Because of an earlier issue where I have had problems with the custom lexer  in Scintilla.Net 2.6 [https://scintillanet.codeplex.com/discussions/633010]  I've tried to change my project which based on the SCide from Codeplex.net to ScintillaNET 3.3, but it looks like this library is not compatible with the one from codeplex. Is there any container project for the newer  ScintillaNET 3.3?

**Comment by jacobslusser** [comment]
You are correct. ScintillaNET v3.x is vastly different from v2.x. It is a *complete rewrite*. There has been no attempt to keep the API compatible and no plans to create any kind of "compatibility layer".

That being said, most of the time there should be an equivalent v3.x API for whatever you were doing in v2.x. 

Is there a particular API I can help you find? Or something missing in v3.x?

**Comment by jokn53** [comment]
OK i understand. I have to decide staying at v2.6 or changing to v3.x? 
- Do you know, if v2.6 still alive?
- Do's there exist a container project like SCide also for v3.x?

**Comment by jacobslusser** [comment]
ScintillaNET v2.x is effectively dead. AFAIK I was the only one still working on it and I've moved on to v3.x so there really isn't anyone left. Some of this is explained in the move announcement at the old CodePlex site: [https://scintillanet.codeplex.com/](https://scintillanet.codeplex.com/).

There isn't currently a sample project for v3.x like SCide was for v2.x but I'm starting to think that I should create one. You're not the first person to ask for more complete samples.

**Comment by jokn53** [comment]
Thanks very much for your help jacob. 
I will change to v3.x now. 
Josef

**Comment by jacobslusser** [comment]
Time permitting I'm going to try and create a sample application to highlight some of ScintillaNET's features.

**Comment by JohnyMac** [comment]
Would be great if you can create it in C# and VB.NET.

**Comment by xonyen** [comment]
I'm trying the new version of ScintillaNET, and I got a problem on xml code folding. Can you give me some advice? Thanks!

**Comment by jacobslusser** [comment]
Is it possible your question has been asked and answered in Issue #2?

**Comment by yes3nov** [comment]
I had used Scintilla 3.5.5 with Qt and now would be very good to look little example for ScintillaNET for VS13. I built and inserted ScintillaNET (first v3.4.0 then master) in my app, but it doesn't work. And how I can add my own lexer? Thanks.

**Comment by jacobslusser** [comment]
You'll have to be more specific about what isn't working when you use ScintillaNET. Did you receive an exception?

If you haven't yet, you should read the [Wiki](https://github.com/jacobslusser/ScintillaNET/wiki) to learn more about ScintillaNET. If you're interested in learning how to write a custom lexer you should read the guide [Custom Syntax Highlighting](https://github.com/jacobslusser/ScintillaNET/wiki/Custom-Syntax-Highlighting).

**Comment by jacobslusser** [comment]
BTW, for everyone hoping for a ScintillaNET demonstration project, you should know that you'll be waiting a long time. That isn't something that just comes together over night. My first priority is to maintain ScintillaNET and that takes enough of my time as it is.

The [Wiki](https://github.com/jacobslusser/ScintillaNET/wiki) is fairly comprehensive and my preference would be to continue enhancing that before I spend time on a demonstration app. Perhaps one day there will be a demonstration app but I wouldn't want to give any developers the impression that one is just around the corner. If any of you have questions now, we should answer them via the project Issue tracker or Wiki.

P.S. If anybody else is using ScintillaNET in an open-source project I'm interested in creating a list of "applications which use ScintillaNET" in the Wiki.

**Comment by yes3nov** [comment]
Thank you for your advice, i'll go to Wiki. 
I've built ScintillaNET  and added it to Studio 13 as scintilla tool ok (one library ScintillaNET.dll). I can see scintilla and it's properties in my editor. Then I added scintilla to my app and built it ok too. I changed default value of property "text" "scintilla 1" to "TEST Scintilla" successfully and so. I tried different value of property "lexer" (cpp, xml), but couldn't got highlighted text.
App is running ok, without exceptions (and without highlighted text too).
I added my own lexer as new cpp module with Qt and Scintilla 3.5.5 earlier, but I'm beginner in C#.
May be I'm mistaken, it seems to me I must configure lexer in xml file, isn't it?

**Comment by jacobslusser** [comment]
Setting the `Lexer` property is only one of several steps necessary to see syntax highlighting. You should read the [Automatic Syntax Highlighting](https://github.com/jacobslusser/ScintillaNET/wiki/Automatic-Syntax-Highlighting) wiki page.

**Comment by yes3nov** [comment]
Thank you very much! All the same as my Qt project: styles and their colors. I go further and look for references of making my own lexer.

**Comment by yes3nov** [comment]
Excuse me, once more question. 
I made my own lexer by "Custom Syntax Highlighting". 
Are there some tools to set folding marks of lines in ScintillaNET? It isn't enough configure folding by "Automatic Code Folding". 
May be I'm mistaken, it looking the same as "Bookmark Lines", isn't it? 
Thanks.

**Comment by jacobslusser** [comment]
"Automatic Code Folding" will not work for custom lexers. When you develop a custom lexer you also must implement your own folding. Sadly, I haven't gotten around to authoring a Wiki article on the subject so you're going to have to blaze your own trail if you don't want to wait for me.

The native scintilla documentation includes a brief example on how to use folding here: [http://sphere.sourceforge.net/flik/docs/scintilla-folding.html](http://sphere.sourceforge.net/flik/docs/scintilla-folding.html). It's written in C but should be fairly easy to map to ScintillaNET concepts.

**Comment by jacobslusser** [comment]
P.S. This link also has a guide on how to implement folding for a custom lexer:
[https://bitbucket.org/StarFire/scintilla-doc/downloads/Scintilla-var'aq-Tutorial.pdf](https://bitbucket.org/StarFire/scintilla-doc/downloads/Scintilla-var'aq-Tutorial.pdf).

**Comment by yes3nov** [comment]
Thank you for your advice, I'll try.

**Comment by yes3nov** [comment]
I've used "Using a Custom SciLexer.dll" topic and added my SciLexer.dll (with my own lexer from mingw project). 
There are differences between two editors (mingw-Qt cpp and VS13 C#). 
Most important, i couldn't got  folding in C# project. I couldn't get result from my "styler.SetLevel(...);", but in my Qt project (the same Scintilla 3.4.0 ) i'm seeing it.

**Comment by yes3nov** [comment]
sorry, mistaken, 3.4.0 - ScintillaNET, Scintilla - 3.5.6

**Comment by yes3nov** [comment]
Three weeks later (after my holidays) i turned to my project and resolved folding with my own lexer.  It may be more comfortable to have a folding tool for custom lexer in debugging. Great  thanks to Jacobslusser for his very usefull help in wiki!

**Comment by vinodvinu** [comment]
Hi, 
I am making a IDE for AutoIt Scripting language in vb.net. I have successfully add the tool in tool box and create an instance of Scintilla editor. I choose "Au3" as lexer from property window. But i can't change the font font size of this editor. I have set the font consolas in property window, but in runtime, it changes some other font. Then i experiment with some code which i got from wiki. One of them shows like this - "Scintilla.Lexer = Lexer.cpp". I am sadly saying that i can't find a ".Lexer" method or property in my scintilla editor. It has a ".Lexing.Lexer" method.  And in wiki, it says "scintilla.Styles[Style.Cpp.CommentLine].Font = "Consolas"; ". But when i write this code in my visual studio, it shows an error line. It doesn't have "Styles() or Styles[]" option. Is there anything wrong in my project ?

**Comment by yes3nov** [comment]
Hi. 
It was very short project. 
It was stopped by my chief engineer  one year ago. 
I'll try refresh it in mind and answer you this week.

Good luck.

**Comment by yes3nov** [comment]
Hi once more,
As far as I remember i used my own lexer. 
I made it on  the base of Paskal's lexer. 
All other functions were on the base on Wiki. My code for increase/decrease is:

private void mhInc(Object sender, EventArgs e) {
scintilla1.ZoomIn(); // Increase
}
private void mhDec(Object sender, EventArgs e) {
scintilla1.ZoomOut(); // Decrease
}
And I couldn't find any method like ".Lexer" in my code.

Excuse me my English, please.
Good luck.

**Comment by PawelTroka** [comment]
If you want to have a look at sample app using ScintillaNET there is always mine app:
https://github.com/PawelTroka/Computator.NET

**Comment by yes3nov** [comment]
For Pawel Troka

Thanks a lot, I've finished my little project year ago. It works ok thanks to Wiki.
Thanks a lot Jacob Slusser, thanks all.

**Comment by jacobslusser** [comment]
This has been addressed with issue #280.

[https://github.com/hgupta9/ScintillaNET.Demo](https://github.com/hgupta9/ScintillaNET.Demo).
