### ISSUE TITLE
Styling the Margins

### ISSUE THREAD

**Issue by robmburke** [jacobslusser/ScintillaNET#133]
I noticed there is a SetFoldMarginColor.
Is there a way to set the Fore/Back-Colors of the line number margin?

**Comment by jacobslusser** [comment]
Is `Scintilla.Styles[Style.LineNumber]` what you're looking for?

**Comment by robmburke** [comment]
I did this:

`scintilla.Styles[Style.LineNumber].ForeColor = Color.White;
            scintilla.Styles[Style.LineNumber].BackColor = Color.Black;`

But nothing has changed.

**Comment by robmburke** [comment]
Any other ideas?  Nothing on the margin seemed to change where the line numbers are.

**Comment by robmburke** [comment]
I figured it out.
I was setting them before a `scintilla.StyleClearAll();`

Set it after and it is working.
