### ISSUE TITLE
Syntax Highlighting for SQL problems

### ISSUE THREAD

**Issue by Beanfrog** [jacobslusser/ScintillaNET#134]
Hi, I'm trying to write a recipe to make SQL look like it does in SSMS, but I'm really struggling. I don't understand what each of the styles are describing - a lot of them seem to change nothing, and others don't changes as expected.

The bits I'm most struggling with are strings and keywords. 
scintilla1.Styles[Style.Sql.String].ForeColor = Color.Red; seems to set double quotes to red text, but I can't find anything to alter single quotes.

I've also set the keywords, but can't seem to find a style which will set them to different colours! 
scintilla1.SetKeywords(0, "keywords in here");

Here is the whole text - I've commented out any lines where I can't figure out what they are meant to do. Can you help me out?  :smiley:

```
        /// <summary>
        /// Setup the SQL style to look a bit like SSMS
        /// </summary>
        private void InitialiseScintilla()
        {
            //Set the line numbers 
            scintilla1.Margins[0].Width = 16;

            scintilla1.StyleResetDefault();
            scintilla1.Styles[Style.Default].Font = "Consolas";
            scintilla1.Styles[Style.Default].Size = 10;
            scintilla1.StyleClearAll();

            scintilla1.Styles[Style.Sql.Character].ForeColor = Color.Black;

            // surrounded by /* */
            scintilla1.Styles[Style.Sql.Comment].ForeColor = Color.Green;

            // begins with --
            scintilla1.Styles[Style.Sql.CommentLine].ForeColor = Color.Green;

            //scintilla1.Styles[Style.Sql.CommentDoc].ForeColor = Color.Black;
            //scintilla1.Styles[Style.Sql.CommentDocKeyword].ForeColor = Color.Black;
            //scintilla1.Styles[Style.Sql.CommentDocKeywordError].ForeColor = Color.Black;
            //scintilla1.Styles[Style.Sql.CommentLineDoc].ForeColor = Color.Black;

            // Any text?
            scintilla1.Styles[Style.Sql.Identifier].ForeColor = Color.Black;

            // just a number
            scintilla1.Styles[Style.Sql.Number].ForeColor = Color.Black;

            //+ = <> - etc
            scintilla1.Styles[Style.Sql.Operator].ForeColor = Color.Black;

            //scintilla1.Styles[Style.Sql.QOperator].ForeColor = Color.Black;
            //scintilla1.Styles[Style.Sql.QuotedIdentifier].ForeColor = Color.Black;
            //scintilla1.Styles[Style.Sql.SqlPlus].ForeColor = Color.Black;
            //scintilla1.Styles[Style.Sql.SqlPlusComment].ForeColor = Color.Black;
            //scintilla1.Styles[Style.Sql.SqlPlusPrompt].ForeColor = Color.Black;

            //think it's supposed to be the keywords, but doesn't change them!
            scintilla1.Styles[Style.Sql.Word].ForeColor = Color.Blue;
            scintilla1.Styles[Style.Sql.Word2].ForeColor = Color.Pink;

            // in double quotes
            scintilla1.Styles[Style.Sql.String].ForeColor = Color.Red;

            scintilla1.Lexer = Lexer.Sql;
            //scintilla1.Text = scintilla1.DescribeKeywordSets();

            //scintilla1.SetKeywords(0, "ADD ALTER AS ASC AUTHORIZATION BACKUP BEGIN BREAK BROWSE BULK BY CASCADE CASE CHECK CHECKPOINT CLOSE CLUSTERED COLUMN COMMIT COMPUTE CONSTRAINT CONTAINSTABLE CONTINUE CREATE CURRENT CURRENT_DATE CURSOR DATABASE DBCC DEALLOCATE DECLARE DEFAULT DELETE DENY DESC DISK DISTINCT DISTRIBUTED DOUBLE DROP DUMP ELSE END ERRLVL ESCAPE EXCEPT EXEC EXECUTE EXIT EXTERNAL FETCH FILE FILLFACTOR FOR FOREIGN FREETEXT FREETEXTTABLE FROM FULL FUNCTION GOTO GRANT GROUP HAVING HOLDLOCK IDENTITY IDENTITY_INSERT IDENTITYCOL IF INDEX INSERT INTERSECT INTO KEY KILL LINENO LOAD MERGE NATIONAL NOCHECK NONCLUSTERED OF OFF OFFSETS ON OPEN OPENDATASOURCE OPENQUERY OPENROWSET OPENXML OPTION ORDER OVER PERCENT PLAN PRECISION PRIMARY PRINT PROC PROCEDURE PUBLIC RAISERROR READ READTEXT RECONFIGURE REFERENCES REPLICATION RESTORE RESTRICT RETURN REVERT REVOKE ROLLBACK ROWCOUNT ROWGUIDCOL RULE SAVE SCHEMA SECURITYAUDIT SELECT SEMANTICKEYPHRASETABLE SEMANTICSIMILARITYDETAILSTABLE SEMANTICSIMILARITYTABLE SET SETUSER SHUTDOWN STATISTICS TABLE TABLESAMPLE TEXTSIZE THEN TO TOP TRAN TRANSACTION TRIGGER TRUNCATE UNION UNIQUE UPDATETEXT USE USER VALUES VARYING VIEW WAITFOR WHEN WHERE WHILE WITH WITHIN GROUP WRITETEXT");
            //scintilla1.SetKeywords(1, "COALESCE COLLATE CONTAINS CONVERT CURRENT_TIME CURRENT_TIMESTAMP CURRENT_USER NULLIF SESSION_USER SYSTEM_USER TRY_CONVERT TSEQUAL UPDATE");
            //scintilla1.SetKeywords(2, "ALL AND ANY BETWEEN CROSS EXISTS IN INNER IS JOIN LEFT LIKE NOT NULL OR OUTER PIVOT RIGHT SOME UNPIVOT");
            
        }
```

**Comment by jonandr** [comment]
Single quotes seems to be the "Character" style.
Keywords are the "Word" style.

To set the keywords, do:

~~~
s.SetKeywords(0, "select where from");
~~~

I.e. send them in as a space-separated list. Note that they must be lower-case (at least for the SQL lexer).

I don't have any reference for this, it's just something I figured out by experimenting (there are only a finite number of styles).

**Comment by Beanfrog** [comment]
Lowercase! Didn't even occur to me! I shall have a look on Monday, hopefully that will all sort it. Many thanks!

**Comment by robmburke** [comment]
This is all I did for my SQL highlighting:

            Scintilla scintilla = new Scintilla();
            scintilla.Dock = System.Windows.Forms.DockStyle.Fill;
            scintilla.CaretForeColor = Color.White;

            scintilla.Styles[Style.LineNumber].ForeColor = Color.White;
            scintilla.Styles[Style.LineNumber].BackColor = Color.Black;

            scintilla.Margins[0].Width = 16;

            scintilla.StyleResetDefault();
            scintilla.Styles[Style.Default].Font = "Consolas";
            scintilla.Styles[Style.Default].Size = 10;
            scintilla.Styles[Style.Default].BackColor = Color.FromArgb(41, 49, 52);
            scintilla.StyleClearAll();

            scintilla.Lexer = Lexer.Sql;

            scintilla.Styles[Style.Sql.Word].ForeColor = Color.FromArgb(147, 199, 99);
            scintilla.Styles[Style.Sql.Word].Bold = true;
            scintilla.Styles[Style.Sql.Identifier].ForeColor = Color.FromArgb(255, 255, 255);
            scintilla.Styles[Style.Sql.Character].ForeColor = Color.FromArgb(236, 118, 0);
            scintilla.Styles[Style.Sql.Number].ForeColor = Color.FromArgb(255, 205, 34);
            scintilla.Styles[Style.Sql.Operator].ForeColor = Color.FromArgb(232, 226, 183);
            scintilla.Styles[Style.Sql.Comment].ForeColor = Color.FromArgb(102, 116, 123);
            scintilla.Styles[Style.Sql.CommentLine].ForeColor = Color.FromArgb(102, 116, 123);

            scintilla.SetKeywords(0, keywords);


`keywords` is just a string I grabbed from Notepad++.  I use the AutoComplete feature so I just do a `.ToUpper()` on the string because, for some reason, the AutoComplete won't work with the lowercase characters.  I based my colors on one of the Notepad++ themes.  You notice, I only have several of the styles actually referenced.  So far, it appears this is all that is needed.  I tried it that way because Notepad++ only referenced those specific styles in their program, so I was only going to have colors for the matching types of styles.  Thankfully, so far, I haven't seen a problem with my styling only using those 7 styles.

**Comment by VictoriaD** [comment]
Thanks so much for your help! I have tried it out this morning, and setting my keyword strings to lower case did the trick!

**Comment by Beanfrog** [comment]
Thanks so much for your help! I have tried it out this morning, and setting my keyword strings to lower case did the trick!
