### ISSUE TITLE
Scintilla Demo App + Theme Kitchen Sink

### ISSUE THREAD

**Issue by uuf6429** [jacobslusser/ScintillaNET#136]
Hi,

Due to (as of yet) lack of user recipes, I created a very simple app for visually changing the style of a running scintilla control - so one can see how the final style will look like.
The app, in particular, generates the code for the desired style.

I still have to implement the following:
- a proper readme file
- editing of keyword sets
- editing style of scintilla control

Please give it a look and let me know what you think!

https://github.com/uuf6429/ScintillaNET-Kitchen

Chris.

**Comment by jacobslusser** [comment]
Love it! I think that's a great idea. I'll update the documentation to reference it.

I also have a couple ideas for you that I'll see about posting over on your project page.

**Comment by theryan722** [comment]
Nice, thank you for creating this, makes setting up a language so much easier.

**Comment by uuf6429** [comment]
Thanks all!

@jacobslusser How do I go about "promoting" this? Also I don't mind passing on ownership of the repository to you - I know you're pretty busy on the main project, but for me this one is mostly a means to an end and I can't see myself very active on this in the future.

**Comment by jacobslusser** [comment]
I did not do a good job promoting this tool. My bad.

It is now listed on the front page README.md.
