### ISSUE TITLE
Indent on Return

### ISSUE THREAD

**Issue by robmburke** [jacobslusser/ScintillaNET#137]
Is there a built-in way to get the next line to indent as much as the previous line upon pressing Return?

**Comment by JohnyMac** [comment]
Here is the code for doing it: 
https://github.com/JohnyMac/ExtremeStudio/blob/master/ExtremeStudio/ExtremeStudio/DockPanel%20Forms/MainForm%20Docks/EditorDock/EditorDock.vb#L379-L401

Its in VB though.. There is plenty of converters if you want.

**Comment by JohnyMac** [comment]
Its issue #35 btw.

**Comment by robmburke** [comment]
Cool.  Thanks.  The link you sent me worked great.
Though, just for the record, issue #35 is a bit of a different situation.

**Comment by Petarian** [comment]
Sorry to open a closed ticket. The link JohnyMac pasted is resulting in a 404 error. Could you please paste the code here.

**Comment by jacobslusser** [comment]
```vb
#Region "AutoIndent of new lines"
    Private Sub Editor_InsertCheck(sender As Object, e As InsertCheckEventArgs) Handles Editor.InsertCheck
        If (e.Text.EndsWith("" & vbCr) OrElse e.Text.EndsWith("" & vbLf)) Then
            Dim startPos As Integer = Editor.Lines(Editor.LineFromPosition(Editor.CurrentPosition)).Position
            Dim endPos As Integer = e.Position
            Dim curLineText As String = Editor.GetTextRange(startPos, (endPos - startPos)) 'Text until the caret.
            Dim indent As Match = Regex.Match(curLineText, "^[ \t]*")
            e.Text = (e.Text + indent.Value)
            If Regex.IsMatch(curLineText, "{\s*$") Then
                e.Text = (e.Text + vbTab)
            End If
        End If
    End Sub

    Private Sub Editor_CharAdded(sender As Object, e As CharAddedEventArgs) Handles Editor.CharAdded
        If e.Char = 125 Then  'The '}' char.
            Dim curLine As Integer = Editor.LineFromPosition(Editor.CurrentPosition)
            If Editor.Lines(curLine).Text.Trim() = "}" Then 'Check whether the bracket is the only thing on the line.. For cases like "if() { }".
                Editor.Lines(curLine).Indentation -= 4
            End If
        End If
    End Sub
#End Region
```

**Comment by JohnyMac** [comment]
Here is fixed link: https://github.com/JohnyMac/ExtremeStudio/blob/master/ExtremeStudio/DockPanel%20Forms/MainForm%20Docks/EditorDock/EditorDock.vb  (link went change again, don't worry)

The file contains loads of useful stuff so just wanted to paste that here.

**Comment by Naicos** [comment]
private void scintilla1_InsertCheck(object sender, InsertCheckEventArgs e)
    {
      if ((e.Text.EndsWith(("" + "\r")) || e.Text.EndsWith(("" + "\n"))))
      {
        int startPos = scintilla1.Lines(scintilla1.LineFromPosition(scintilla1.CurrentPosition)).Position;
        int endPos = e.Position;
        string curLineText = scintilla1.GetTextRange(startPos, (endPos - startPos));
        // Text until the caret.
        Match indent = Regex.Match(curLineText, "^[ \\t]*");
        e.Text = (e.Text + indent.Value);
        if (Regex.IsMatch(curLineText, "{\\s*$"))
        {
          e.Text = (e.Text + '\t');
        }

      }
    }

    private void scintilla1_CharAdded(object sender, CharAddedEventArgs e)
    {
      if ((e.Char == 125))
      {
        // The '}' char.
        int curLine = scintilla1.LineFromPosition(scintilla1.CurrentPosition);
        if ((scintilla1.Lines(curLine).Text.Trim() == "}"))
        {
          // Check whether the bracket is the only thing on the line.. For cases like "if() { }".
          scintilla1.Lines(curLine).Indentation -= 4;
        }

      }
    }

It looks this way in C# but i get following error at "Scintilla1.Lines"

The unrecognizable Scintilla.Lines member can not be used as a method.
(Translated by google translator from german)

**Comment by xv** [comment]
@Naicos In C#, use square brackets `[ ]`. So it's `scintilla1.Lines[curLine]`

**Comment by DragonSkills99** [comment]
@Naicos code was a bit lacking, it had some issues like the `()` instead of `[]` brackets, recreated Regex objects often ( it's what `Regex.IsMatch` and `Regex.Match` internally does ), forgot some chars while copying the expressions from the VB code and so on. So here is an improved code, but please be aware, that it is not perfect ( I only did, what won't consume too much time ), the automatic indenting and outdenting on characters like `{` and `}` are not working. Also my code will work with other indent levels than only 4 spaces / 1 tab. I'm using the `scintilla1.IndentWith` field, so it will dynamically decide how much spaces should be taken for indenting. So long enough, here is my code:

```csharp

        private Regex indentLevel = new Regex( "^[\\s]*" );
        private Regex indenter = new Regex( "{\\s$" );
        private void scintilla1_InsertCheck( object sender, InsertCheckEventArgs e )
        {
            if ( e.Text.EndsWith( "\r" ) || e.Text.EndsWith( "\n" ) )
            {
                int startPos = scintilla1.Lines[ scintilla1.LineFromPosition( scintilla1.CurrentPosition ) ].Position;
                int endPos = e.Position;
                string curLineText = scintilla1.GetTextRange( startPos, endPos - startPos );
                // Text until the caret.
                Match indent = indentLevel.Match( curLineText );
                e.Text = e.Text + indent.Value;
                if ( indenter.IsMatch( curLineText ) )
                {
                    e.Text = e.Text + new string( ' ', scintilla1.IndentWidth );
                }

            }
        }

        private string[] outdentWords = new string[]
        {
            "end",
            "when",
            "else",
            "}"
        };

        private void scintilla1_CharAdded( object sender, CharAddedEventArgs e )
        {
            if ( ( e.Char == 125 ) )
            {
                // The '}' char.
                int curLine = scintilla1.LineFromPosition( scintilla1.CurrentPosition );
                if ( outdentWords.Contains( scintilla1.Lines[ curLine ].Text.Trim() ) )
                {
                    // Check whether the bracket is the only thing on the line.. For cases like "if() { }".
                    scintilla1.Lines[ curLine ].Indentation -= scintilla1.IndentWidth;
                }

            }
        }
```
PS: I personally prefer spaces between parentheses, but don't worry to much, if you havn't changed the VS Auto-Formatter it will remove those for you, as soon, as you paste the code ^^
