### ISSUE TITLE
ReplaceSelection and blank strings

### ISSUE THREAD

**Issue by robmburke** [jacobslusser/ScintillaNET#138]
I am using .ReplaceSelection() to replace the specified text for the Find/Replace window I'm coding.
Why is a blank string not a valid replacement?  I can put in a space, but if I have no text, it won't do the replace.  Is there a way around this behavior?

**Comment by jacobslusser** [comment]
This was a bug.

**Comment by robmburke** [comment]
Cool.  So how often do you update the nuget package?
Or is there a way to handle this with the DLL but not messing with Nuget versions?
Or, is the best way to get the latest changes is to d/l the source code whenever there are new changes and compile the dll myself?
