### ISSUE TITLE
Print and PrintPreview

### ISSUE THREAD

**Issue by apachexampp** [jacobslusser/ScintillaNET#139]
Is in new library metod to Print file, and Print preview?

**Comment by jacobslusser** [comment]
Printing has not been implemented yet.

**Comment by BrisingrAerowing** [comment]
I looked at the old ScintillaNET code for printing, and I don't think it would be all that hard to port over. I will take a look at it later today (going to bed now) and see what I can do.

I will submit a pull request if I can get it working.

**Comment by theryan722** [comment]
@BrisingrAerowing I think the reason it hasn't been ported over yet is because the project is trying to be kept as cross platform as possible, or something related to that matter.

**Comment by jacobslusser** [comment]
@BrisingrAerowing, a pull request would be great. I'm busy with life at the moment and so won't get a chance to look at this for a while. I originally had not intended to implement printing. Who prints code anymore?

**Comment by KarlMicroRobotics** [comment]
I don't print code, but I often use whatever text editor is available to print out other plain text files, when sometimes a paper record is required.  Printing would be very useful to include for that reason.

If printing is not going to be implemented, I guess it would be possible to implement it in my application - are there any suggestions for how best to do that?

Thanks.

**Comment by jacobslusser** [comment]
The Scintilla documenation on printing is at [http://www.scintilla.org/ScintillaDoc.html#Printing](http://www.scintilla.org/ScintillaDoc.html#Printing). Combine that with `DirectMessage`.

**Comment by KarlMicroRobotics** [comment]
Thanks :-)
    Karl
    
    Karl Lam
Technical Director
Micro-Robotics Ltd
Registered Office: 135 Ditton Walk, Cambridge CB5 8QB.
Tel: 01223 523100. Fax: 01223 524242.

Registered in England No. 03983610
VAT No. GB 393 2883 17
www.microrobotics.co.uk
    On 10/02/2016 15:48, jacobslusser
      wrote:
    
    
      The Scintilla documenation on printing is at http://www.scintilla.org/ScintillaDoc.html#Printing.
        Combine that with DirectMessage.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by KarlMicroRobotics** [comment]
I got printing working by copying the printing code out of the source of 
ScintillaNet 2.x, into my application project, and modifying parts of it 
so that it worked as part of the application.
Not the neatest solution, but it works.

Karl Lam

**Comment by jacobslusser** [comment]
Happy to hear that.

**Comment by sheldog17** [comment]
Hi, can someone share code on how to print using scintillaNET using c# or vb.net

I cant find anything obvious on google..

thanks

**Comment by jacobslusser** [comment]
Issue #277 has some user suggested code for printing.
