### ISSUE TITLE
VB.Net Syles

### ISSUE THREAD

**Issue by KaosKidd** [jacobslusser/ScintillaNET#140]
Hi Jacob;  Love the control, thank you very much for all the work you've put into it.
I'm using VB.Net to create a "hybrid" editor, centered around the most current version of Scintilla.  I've followed all of your posts, and I can't seem to get the lexer to highlight VBScript,  Here is a bit of the code that I have in place:
        With Scintilla1
            .Lexer = ScintillaNET.Lexer.VbScript
            .LexerLanguage = "vbscript"
            .StyleResetDefault()
            Call Me.SetFontSize(CInt(sLastFontSize))
            Call Me.SetFontName(sLastFontUsed)
            .StyleClearAll()

            .Styles(Style.VbScript.Comment).ForeColor = Color.Green
            .Styles(Style.VbScript.Keyword).ForeColor = Color.Blue
            .Styles(Style.VbScript.Keyword).ForeColor = Color.Blue
            .Styles(Style.VbScript.Keyword2).ForeColor = Color.Blue
            .Styles(Style.VbScript.Keyword3).ForeColor = Color.Blue
            .Styles(Style.VbScript.Keyword4).ForeColor = Color.Blue
            .Styles(Style.VbScript.Operator).ForeColor = Color.Red
            .Styles(Style.VbScript.Number).ForeColor = Color.Gray
            .Styles(Style.VbScript.String).ForeColor = Color.Gray
             sVBWordList = Trim(Join(Split(My.Resources.VBWordList, vbCrLf), " "))
             sM3WordList = Trim(Join(Split(My.Resources.M3WordList, vbCrLf), " "))
            .SetKeywords(0, sVBWordList)
            .SetKeywords(1, sVBWordList)
            .SetKeywords(2, sM3WordList)
            .SetKeywords(3, sVBWordList)
            .SetKeywords(4, sM3WordList)
        End With
So the code that sets the font size works (loops through all of the indexes and sets the size), and the code to set the font name works (again, loops through all of the indexes and sets the font.).  From what I understand, the code above should work, but the only parts that are working are the comments, numbers,strings and operators.  Not one of the key words lists in sVBWordList or sM3WordList get highlighted.  I've checked the word lists to make sure they are a space delimited list, with no other characters then text and space.
  I'm at a loss here because I can't seem to find what I'm doing wrong.  Could you please poke, push or prod me int the correct direction?
Thanks for the awesome control and any help you can toss my way!
Fred Kerber

**Comment by jacobslusser** [comment]
Remind me, is VB script case-insensitive? If so, you may need to supply a keyword list that is all uppercase or all lowercase to Scintilla.

**Comment by JohnyMac** [comment]
Yes it is.

**Comment by KaosKidd** [comment]
Hi Jacob;
  Yes it is, and you were spot on!  Two commands fixed the issue.
            sVBWordList = LCase(Trim(Join(Split(My.Resources.VBWordList, vbCrLf), " ")))
            sM3WordList = LCase(Trim(Join(Split(My.Resources.M3WordList, vbCrLf), " ")))
  NOTE: I added the LCase function to the front of each list.
  Thank you very much for the fast reply, and it being spot on!

  I believe I'll author a "Visual Basic.NET how to" for some of the functionality that really isn't spelled out.

  Again, thank you!

**Comment by JohnyMac** [comment]
I am using VB.NET too, so just writing as it might help you.
Creating an IDE for the PAWN scripting language to be used in the popular mod SAMP.

The project is a bit big, so here's where scintilla code lies: 
https://github.com/JohnyMac/ExtremeStudio/blob/master/ExtremeStudio/ExtremeStudio/DockPanel%20Forms/MainForm%20Docks/EditorDock/EditorDock.vb

**Comment by KaosKidd** [comment]
Hi JonnyMac;
  WOW.  Awesome code.  Thank you for sharing, it will save me a lot of time working on my project!
Fred Lerber
