### ISSUE TITLE
CurrentRegion support ?

### ISSUE THREAD

**Issue by JohnyMac** [jacobslusser/ScintillaNET#141]
In ScintillaNET 2.0, I remember there was something called or similar to *CurrentRegion*, It'd basically return the first visible line number and the last visible line number which enables getting the visible text only.

How to do this here ?

**Comment by jacobslusser** [comment]
A combination of `Scintilla.FirstVisibleLine` and `Scintilla.LinesOnScreen` should be what you're looking for.

**Comment by JohnyMac** [comment]
Yes it is.
Thanks mate.
