### ISSUE TITLE
ScintillaNET show autocomplete while typing

### ISSUE THREAD

**Issue by METOUIA7** [jacobslusser/ScintillaNET#142]
Hi, How ScintillaNET show autocomplete while typing

**Comment by jacobslusser** [comment]
Our [documentation](https://github.com/jacobslusser/ScintillaNET/wiki) has a fairly [good explanation](https://github.com/jacobslusser/ScintillaNET/wiki/Basic-Autocompletion).

**Comment by METOUIA7** [comment]
Thank you it work good with AutoCompleteMenu
