### ISSUE TITLE
AutoCompletion Doesn't Appear for word containing "-"

### ISSUE THREAD

**Issue by chapoonkz** [jacobslusser/ScintillaNET#143]
Hi, Sorry for my bad english. I've been using scintillanet version 3.3.5 to create html editor, but there is a problem when using autocompletion. autocompletion does not appear when I type the character "-", it seems scintillanet not assume the character "-" as a word, but some list contained in autocompletion there are words that contain the character "-" like the word "data-clearing”. I hope you can give solution

![haha](https://cloud.githubusercontent.com/assets/15965407/11323237/4f4be55e-90c2-11e5-91a8-84451eae73a4.png)
AutoCompletion appear when I typed “data”
![hide](https://cloud.githubusercontent.com/assets/15965407/11323244/8e0494c6-90c2-11e5-8b14-25131528ceae.png)
AutoCompletion doesn’t appear when I typed “data-m”

**Comment by jacobslusser** [comment]
I believe you need to add the dash '-' character to the list of characters considered "word characters" in Scintilla. For some reason I have the code to do this commented out. See here: [https://github.com/jacobslusser/ScintillaNET/blob/v3.5.4/src/ScintillaNET/Scintilla.cs#L5071-L5103](https://github.com/jacobslusser/ScintillaNET/blob/v3.5.4/src/ScintillaNET/Scintilla.cs#L5071-L5103).

I'm not sure why that code was disabled, but you are welcome to try and uncomment it and use it like this:

```cs
scintilla.WordChars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-"
```

When I have time I'll try to get this put back into the official builds. Let me know what you find.

**Comment by chapoonkz** [comment]
Thanks, it works...
