### ISSUE TITLE
indentation in ScintillaNet

### ISSUE THREAD

**Issue by METOUIA7** [jacobslusser/ScintillaNET#144]
Hi, indentation work in ScintillaNet in file opned from hard disk

**Comment by jacobslusser** [comment]
Can you please clarify? I don't understand the question.

**Comment by JohnyMac** [comment]
I think issue #35 is what you are looking for.
And here is the final code cause the issue is pretty long: https://gist.github.com/JohnyMac/f2910192987a73a52ab4

The indentation property has been added, So you can remove that region called *CodeIndent Handlers*

**Comment by METOUIA7** [comment]
Thank's alot for help
