### ISSUE TITLE
copy html error

### ISSUE THREAD

**Issue by METOUIA7** [jacobslusser/ScintillaNET#147]
I use this code for copy in html format 
Scintilla.Copy(CopyFormat.Html)
and i have this
![sans titre](https://cloud.githubusercontent.com/assets/13167974/11409285/226591ac-93bf-11e5-9cb4-2150c9b7bab7.jpg)

**Comment by jacobslusser** [comment]
So, ya, that's definitely odd. It looks like an encoding issue. A few questions:

- Is the clipboard viewer you're using working correctly? Showing the correct encoding?
- Does your text have any Unicode characters?
- Have you done anything to change the ScintillaNET encoding?

**Comment by METOUIA7** [comment]
thank's for help it's work well

**Comment by jacobslusser** [comment]
What was the issue?
