### ISSUE TITLE
Hide default margin

### ISSUE THREAD

**Issue by logiarun** [jacobslusser/ScintillaNET#148]
How to hide default margin (line number) ?

**Comment by jacobslusser** [comment]
Scintilla has 5 margins. When a new control is created, most of those margins have a starting `Width` of `0`, but some do not. To hide all the margins, give them all a `Width` of `0`:

```cs
foreach (var margin in scintilla.Margins)
    margin.Width = 0;
```

**Comment by logiarun** [comment]
Hi Jacobslusser,

Thank you very much.
