### ISSUE TITLE
Scintilla Event for SelectedText

### ISSUE THREAD

**Issue by tttmack** [jacobslusser/ScintillaNET#149]
I have a tool strip with some buttons like cut, copy, paste among others.

I have some code, that sets the various buttons Enabled property depending on certain conditions. For example cut and copy should be disabled when no text is selected and enabled when text is selected.

I am however having trouble finding which Scintilla event to call my code in. I have tried ContextMenuStripChanged, ContextMenuChanged, TextChanged, CursorChanged but none of them seem to get fired when text is selected.

Is there an Scintilla event that I can use that meets this requirement?

**Comment by robmburke** [comment]
I use KeyUp to check if someone is SHIFT-Arrow higlighting text and use MouseUp to test for drag highlighting with the pointer.

**Comment by jacobslusser** [comment]
The event designed to notify you of user changes is `UpdateUI`. It will fire when the user enters text, changes the selection, scrolls, etc... It will not, however, fire when you programmatically do those things. So if you are going to manually insert text, change the selection, etc... you'll need to also manually update your button state.

You can read a little more about `UpdateUI` in the documentation.
[https://github.com/jacobslusser/ScintillaNET/wiki/Updating-Dependent-Controls](https://github.com/jacobslusser/ScintillaNET/wiki/Updating-Dependent-Controls)

**Comment by tttmack** [comment]
thank you very much for your help. closing the issue.
