### ISSUE TITLE
Support for standard Click, DoubleClick events

### ISSUE THREAD

**Issue by BrisingrAerowing** [jacobslusser/ScintillaNET#15]
Would it be possible to hook into the native Scintilla events and raise the default WinForms events from those?

e.g. SCN_DOUBLECLICK -> DoubleClick event.

Overriding/Adding events to the control would be necessary, as Scintilla has, e.g. SCN_*CLICK events for different items.

**Comment by jacobslusser** [comment]
I added support for DoubleClick (but not MouseDoubleClick because I need to figure out a way to determine the mouse buttons used). Take a look and let me know if this is what you had in mind.

**Comment by jacobslusser** [comment]
Looking at `System.Windows.Forms.TextBoxBase` gave me an angle on how to get `MouseDoubleClick` working as well. All the click events should now be there:

- `Click`
- `MouseClick`
- `DoubleClick` (standard)
- `MouseDoubleClick`
- `DoubleClick` (Scintilla)

**Comment by BrisingrAerowing** [comment]
Looks good to me.
