### ISSUE TITLE
xml as the hitch in the new version?

### ISSUE THREAD

**Issue by jenokizm** [jacobslusser/ScintillaNET#150]
I used to do so http://stackoverflow.com/questions/14432106/change-syntax-color-in-scintilla-net
but it no longer works. how to be? documentation not found ...

**Comment by jacobslusser** [comment]
This question has been asked and answered multiple times. See #14 and #5 and others... A detailed explanation of how to configure syntax highlighting can be found in the documentation. [https://github.com/jacobslusser/ScintillaNET/wiki/Automatic-Syntax-Highlighting](https://github.com/jacobslusser/ScintillaNET/wiki/Automatic-Syntax-Highlighting)

**Comment by jenokizm** [comment]
ok good!
ps scintilla1.Styles[ScintillaNET.Style.Asm.CpuInstruction].ForeColor not work(

**Comment by jenokizm** [comment]
not only (at the assembly a lot of things not working (please check all

**Comment by jacobslusser** [comment]
You're likely not setting the keywords correctly. Please review the documentation.

**Comment by jenokizm** [comment]
ok thanks! its work!
