### ISSUE TITLE
Editor's wrap mode.

### ISSUE THREAD

**Issue by VisitorQ** [jacobslusser/ScintillaNET#151]
Hello,

first of all, thank you for your tool: ScintillaNET.

I am on my way to evaluate it and I found out that when one uses the "WrapMode.Word" or the "WrapMode.Whitespace", the words are properly wrapped but the indicator's marks are cut on the screen. As a consequence, when, by example, the "HoverForeColor" property of an indicator is different from its "ForeColor" property, the foreColor of all wrapped indicator's markers is partially rendered.
For example, if the expression "welcome home" is highlight in red using an indicator having a "ForeColor" set to red and a "HoverForeColor" set to yellow and the expression is wrapped in the editor, then on hovering over the word "home" its turns yellow (as expected) but the word "welcome" stays in red. The same effect is observed when hovering on the word "welcome": the forecolor of the 
second word of the expression, "home", stays red.

Hope my explanations are clear.

Best regards.

**Comment by VisitorQ** [comment]
Here is a screenshot :

![wrapmode](https://cloud.githubusercontent.com/assets/15521119/11531845/210ff662-9900-11e5-9346-bbc1732aad83.jpg)

NB: when the mouse is on the "x" character the whole mark appears in yellow but at the positions after the "x" only the word "exemple" appears in yellow.

**Comment by jacobslusser** [comment]
This looks to me like a bug in the native Scintilla component -- not something we have control over in the managed ScintillaNET wrapper. I've opened a bug report for the native Scintilla team to look into this issue. You can track the response with me at this link:

[https://sourceforge.net/p/scintilla/bugs/1784/](https://sourceforge.net/p/scintilla/bugs/1784/)

**Comment by VisitorQ** [comment]
Thank you very much for your quick answer and action.
I suspected a Scintilla bug as well. It is not a big bug, anyway...

**Comment by jacobslusser** [comment]
Neil has updated the bug tracker with information about the issue and a fix for the Native Scintilla component. It will likely be included in the next SciLexer.dll release. When it is, I will update ScintillaNET.
