### ISSUE TITLE
Select using alt + shift

### ISSUE THREAD

**Issue by Aghlara** [jacobslusser/ScintillaNET#153]
Hi,

Why selecting vertically works like this:

![image](https://cloud.githubusercontent.com/assets/5187409/11569054/b0018f9a-9a43-11e5-9cd4-b532766dcf8b.png)

It is supposed to select a rectangle area (bellow is notepad++):

![image](https://cloud.githubusercontent.com/assets/5187409/11569102/1d429fae-9a44-11e5-839e-1bebd3f6a054.png)

What should I do to get it working?

Regards,

**Comment by JohnyMac** [comment]
This wiki page should be what you want: https://github.com/jacobslusser/ScintillaNET/wiki/Rectangular-and-Multiple-Selections
