### ISSUE TITLE
Line Highlighting

### ISSUE THREAD

**Issue by ASIbrahim** [jacobslusser/ScintillaNET#154]
I was wondering if there was a way to highlight a particular line such that the highlight extends to the end of the display area on the line and not just the end of text on the line. Notepad++ seems to achieve this but I'm not sure if they are doing this with a feature available in the C++ dll, which maybe is not available in the .NET

I'm currently calling IndicatorFillRange which highlights to the end of the text on the line but not to the end of the display area on the line.

Any help would be appreciated.

Thanks

**Comment by jacobslusser** [comment]
What you are describing sounds to me like the `Style.FillLine` property. When this property is set and this style is used on the last character of the line, it will fill the remainder of the line with the style background color.

More information about syntax highlighting can be found in the documentation:
[https://github.com/jacobslusser/ScintillaNET/wiki/Automatic-Syntax-Highlighting](https://github.com/jacobslusser/ScintillaNET/wiki/Automatic-Syntax-Highlighting)
[https://github.com/jacobslusser/ScintillaNET/wiki/Custom-Syntax-Highlighting](https://github.com/jacobslusser/ScintillaNET/wiki/Custom-Syntax-Highlighting)

**Comment by ASIbrahim** [comment]
jacobslusser - Great, that's exactly what I was looking for. Many thanks
