### ISSUE TITLE
SearchFlags and CheckBoxes

### ISSUE THREAD

**Issue by mroshaw** [jacobslusser/ScintillaNET#155]
I've written a custom Find / Replace dialog for my Scintilla project. I have checkbox controls for the various SearchFlag options and am trying to find a 'nice' way to maintain the SearchFlags value when combinations of checkboxes are checked and unchecked.

I think I understand the concept of bitwise enums in C#, in terms of turning things on and off - I just can't get my head around the "best" way to combine combinations of the options the user selects via the UI.

I'm guessing that to turn something on, I simply OR it with anything else I want on:

    SearchFlags _searchFlags = new SearchFlags();

    if (checkBoxMatchCase.Checked && checkBoxRegEx.Checked)
        _searchFlags = SearchFlags.MatchCase || SearchFlags.Regex;

Is that right? How do I add or remove to the options from the _searchFlags, without building logic that covers every combination of check / unchecked of every checkbox control?

Apologies - I know this isn't explicitly related to Scintilla (best control ever, BTW - thank you!)

**Comment by jacobslusser** [comment]
My personal style would be to build the search flags *each time* the user clicks the 'Find' button by doing something like this:

```cs
var searchFlags = SearchFlags.None;
if(checkBoxMatchCase.Checked)
    searchFlags |= SearchFlags.MatchCase;
if(checkBoxRegEx.Checked)
    searchFlags |= SearchFlags.Regex;
// etc...
```

Since you are building the `searchFlags` each time the user clicks 'Find' you never need to remove an option from the search flags.

To answer your actual question though, a bitwise flag is removed by AND'ing the flag's complement (that's a mouthful). Using the example above, the way to remove options from the `searchFlags` would look like this:

```cs
if(!checkBoxMatchCase.Checked)
    searchFlags &= ~SearchFlags.MatchCase;
if(!checkBoxRegEx.Checked)
    searchFlags &= ~SearchFlags.Regex;
// etc...
```

**Comment by mroshaw** [comment]
Thank you ever so much for the detailed response. This is perfect!

That's the last piece of the puzzle for my Scintilla Find / Replace control. Would I be able to donate the code in some way, in case it helps someone else trying to achieve the same functionality?

I also have the full config for the XML lexer that replicates the behavior in the old 2.x control. Would that be on interest?

**Comment by jacobslusser** [comment]
The XML lexer config sounds like something that would be perfect for the "User Submitted Recipes" section of the Wiki. There are instruction on that page for submitting the information. [https://github.com/jacobslusser/ScintillaNET/wiki/User-Submitted-Recipes](https://github.com/jacobslusser/ScintillaNET/wiki/User-Submitted-Recipes)

As for the Find / Replace dialog, that is something that would probably best be shared through a repository / project of your own. As a general rule I've tried to keep any UI stuff out of the core ScintillaNET project that isn't the editor itself.

Thanks for wanting to give back.

**Comment by mroshaw** [comment]
Hi Jacob,

Thanks again for your work on this amazing control. It's absolutely
brilliant.

I have never been involved in open source development, so I'm a bit
clueless as to it all. I'm also a self taught C# hobbiest programmer, so my
coding style probably leaves a LOT to be desired!

Anyway, I'm always keen to get involed so I've signed up for Github and
created *something* that resembles some sort of reusable Find / Replace
thing, maybe / possibly! It's located here:

https://github.com/mroshaw/ScintillaFindReplace

I'm open to devastating, soul crushing criticism and comment from seasoned
developers and community contributors such as yourself! :)

I'll add the XML lexer stuff to the Wiki tomorrow, when I get a break from
work.

All the best,

Oli

**Comment by Stumpii** [comment]
For anyone interested, I tweaked the Find/Replace dialog, Go To dialog and Incremental Search control from ScintillaNET v2.5 to work with v3. The result is the project [ScintillaNET-FindReplaceDialog](https://github.com/Stumpii/ScintillaNET-FindReplaceDialog). Someone might find it useful if they find this thread.

**Comment by JohnyMac** [comment]
And also here is another example in VB for VB.NET users from my project: 
https://github.com/JohnyMac/ExtremeStudio/tree/master/ExtremeStudio/DockPanel%20Forms/MainForm%20Docks/EditorDock/EditorFunctions

GotoDialog and Search/ReplaceDialog.

**Comment by jacobslusser** [comment]
@Stumpii & @JohnyMac,

Thanks guys. I've added both your projects to list of [User Submitted Recipes](https://github.com/jacobslusser/ScintillaNET/wiki/User-Submitted-Recipes) as well.
