### ISSUE TITLE
Some Unicode Characters do not render correctly

### ISSUE THREAD

**Issue by tttmack** [jacobslusser/ScintillaNET#156]
I have a sample text file (attached) that has some unicode characters in it.

The characters in this file all render properly in Notepad++ (which is based on Scintilla), but some of the words do not render properly in ScintillaNET. They will appear as either blank (whitespace) or as square boxes.

[unicode-example-utf8.txt](https://github.com/jacobslusser/ScintillaNET/files/55957/unicode-example-utf8.txt)

**Comment by jacobslusser** [comment]
ScintillaNET is fully Unicode enabled. In fact, one of the main reasons for the v3 rewrite was for Unicode support.

My guess is that you are using a font which doesn't have the Unicode characters that your sample document includes. When I use the default Scintilla(NET) font -- which is "Verdana" -- I see the same results you do, however, when I change to "Courier New" -- which is the default for Notepad++ -- I see all the Unicode characters just fine.

```cs
scintilla.Styles[Style.Default].Font = "Courier New";
scintilla.StyleClearAll();

var text = File.ReadAllText(@"C:\Users\jslusser\Desktop\unicode-example-utf8.txt");
scintilla.Text = text;
```
![sample](https://cloud.githubusercontent.com/assets/345183/11675002/dae83f5c-9dda-11e5-9e1f-68e8cdcd5c20.png)

**Comment by tttmack** [comment]
thank you very much for your help and explanation. Closing the issue
