### ISSUE TITLE
Basic Intellisense problem link

### ISSUE THREAD

**Issue by MOURADD** [jacobslusser/ScintillaNET#159]
Hi,
the link in this wiki don't work 

https://github.com/jacobslusser/ScintillaNET/wiki/Basic-Intellisense
the link 
https://github.com/DanWBR/dwsim3/blob/master/DWSIM/Objects/Classes/Shared/ScintillaExtender.vb

can you upload it again and thank you

**Comment by JohnyMac** [comment]
I don't understand you at all.

Plus your first link is wrong... You posted your email verification link...

**Comment by theryan722** [comment]
The second link isn't even from this project haha. Are you sure this is the right repo?

**Comment by Orvid** [comment]
Random guess, but you probably wanted:
https://github.com/DanWBR/dwsim3/blob/7abe08d4dfcb094cb6f1f954699d1448fa289c85/DWSIM/Objects/Classes/Extenders/ScintillaExtender.vb

**Comment by MOURADD** [comment]
Thank's Orvid for help
