### ISSUE TITLE
Migrate the read me to wiki.

### ISSUE THREAD

**Issue by JohnyMac** [jacobslusser/ScintillaNET#16]
Hey,

I am creating an IDE and I want to underline wrong variables that don't exit with a red line.

So is there a way I can access the coloring list and modify it ?

I hope you understand me, If not tell me.

**Comment by JohnyMac** [comment]
Ok.. Just noticed that my question is answered in the readme... Thanks anyways :P
I suggest you better move that explanations to the wiki tab... Because the wiki is the first thing I checked and never noticed the explanation in the read me.

**Comment by jacobslusser** [comment]
Yes, the README.md has grow so large that it's starting to lose effectiveness. I have plans to migrate it to the Wiki.
