### ISSUE TITLE
How to open find/replace dialog in ScintillaNET?

### ISSUE THREAD

**Issue by adpgithub** [jacobslusser/ScintillaNET#161]
Hi
I recently started using ScintillaNET in my WPF application ( I have to use it inside WindowFormHost though). I was trying to use find/replace but I have no clue to to get this working. Where is find/replace dialog and how to show it and use it.
Please help me to achieve this.

Thanks,
adpgithub

**Comment by robmburke** [comment]
There isn't one.  You have to make your own.

Here is a good issue about it: https://github.com/jacobslusser/ScintillaNET/issues/155

**Comment by adpgithub** [comment]
Thanks robmburke. I will check that issue. #155 

Regards,
adpgithub

**Comment by mroshaw** [comment]
I've created a small GitHub project for a Windows Forms "Scintilla Find Replace" solution: https://github.com/mroshaw/ScintillaFindReplace

I'm very much a hobbiest, self taught C# coder - as such, please be gentle if you do decide to look at the code! I'd appreciate any input and assistance in improving it, too.

**Comment by adpgithub** [comment]
Hi mroshaw,
I am new to ScintillaNET. Your sample code looks good and helpful to me. Thanks for sharing.
If I tested it the right way, I found one minor issue while executing "Find". It searches from current cursor position to the end of the text and that's it. 
I think you should reset your cursor by placing it back  to the beginning once its reaches the end of the text. So that you can process the whole text.
Once its back to its starting location(which can be in the middle of the document) you can show a message saying something like "No more occurrences".

Regards,
adpgithub

**Comment by mroshaw** [comment]
Awesome, thanks for that! Can you raise an issue to that effect in my
Github project?

I'll fix it next week, if my kids allow me a minute to myself! :)

Oli

**Comment by Stumpii** [comment]
For anyone interested, I tweaked the Find/Replace dialog, Go To dialog and Incremental Search control from ScintillaNET v2.5 to work with v3. The result is the project ScintillaNET-FindReplaceDialog. Someone might find it useful if they find this thread.

**Comment by mroshaw** [comment]
This is fantastic, thank you!
