### ISSUE TITLE
Why are parenthesis considered operators?

### ISSUE THREAD

**Issue by robmburke** [jacobslusser/ScintillaNET#164]
I set the operator color and the parenthesis are getting the .Operator styling.  I also noticed commas and semicolons as well.  None of these are ever used as operators (at least not in SQL), so why are they in that list?

Is there a way to change the operator list?  I really would prefer these not be considered operators since they are not.

**Comment by jacobslusser** [comment]
Doesn't look like there is a way to change it. I went through the native Scintilla SQL lexer code and it calls this method to determine if a character is an operator:

```c
inline bool isoperator(int ch) {
	if (IsAlphaNumeric(ch))
		return false;
	if (ch == '%' || ch == '^' || ch == '&' || ch == '*' ||
	        ch == '(' || ch == ')' || ch == '-' || ch == '+' ||
	        ch == '=' || ch == '|' || ch == '{' || ch == '}' ||
	        ch == '[' || ch == ']' || ch == ':' || ch == ';' ||
	        ch == '<' || ch == '>' || ch == ',' || ch == '/' ||
	        ch == '?' || ch == '!' || ch == '.' || ch == '~')
		return true;
	return false;
}
```

**Comment by robmburke** [comment]
Should I open a ticket with them? I'm not well-versed in every SQL flavor but the ones I use do not have them as operators (SAL Server and Teradata) and it seems a bit limiting to hardcode them like that for every flavor of SQL when they are clearly not.

**Comment by robmburke** [comment]
I've got this in question at the scintilla bug report site.  Talking about it with Neil: https://sourceforge.net/p/scintilla/bugs/1795/

**Comment by robmburke** [comment]
So Neil's conclusion is that this is a feature request and not a bug (though I would beg to differ).
He says that there needs to be code written to allow the user to define the list of operators but that he will not be the one to do it.
That is a bit annoying. The nature of the control should be so that there is flexibility with what gets highlighted since no two language are the same. Should have already been in there from the start.

I digress.

Do you have any suggestions? Doesn't seem like it would be efficient to do regex on them and override them with indicators just to get them to look the way I want; especially something like parens which are used all over the place.

**Comment by jacobslusser** [comment]
I wish I had an easy answer...

As for whether you can augment the built-in lexer and override the behavior for just the parentheses, I've never had much success with that. You spend a lot of time fighting the lexer.

Also, I hate when others ask me questions like this -- that try to change the nature of the conversation -- but I'll shoot anyway: are you sure that highlighting semicolons and commas are an issue? I would argue that if they are not operators, then they should probably not be used in the code and hence you would never see them. If they are operators (and I'm under the understanding that some SQL variants do use commas and semicolons), shouldn't they then highlighted?

**Comment by robmburke** [comment]
Maybe some variants do; I wouldn't personally know.  I've used Teradata, MySQL, and SQL Server, and none of them do.

Sorry. I mean, at the end of the day, I want parenthesis not highlighted as operators, so I would say it's not necessarily off topic to figure out how to do so; that's mainly what this topic is about. Not really about overriding the system; that's just what needs to be done to give a developer the widest range of possibilities. But, since there doesn't seem to be a solution...
Just sucks that he programmed in one list of operators and that's it, without giving an override ability.
Also sucks there is no way around it.

I guess this can be closed then. I don't feel like delving into the guts of Scintilla, so it's not going to be that can create this "feature"...lol.
