### ISSUE TITLE
How to create a fold in a lexer.

### ISSUE THREAD

**Issue by JohnyMac** [jacobslusser/ScintillaNET#169]
I am creating a simple regex \colorizer\ using the StyleNeeded event and I want to add support for folding, To add folds for {'s and }'s.
In the C++ lexer, It was possible by doing so: 
```c#
        Editor.SetProperty("fold", "1");
        Editor.SetProperty("fold.compact", "0");
```

More like, How to create custom folds programmaticly ?

**Comment by jacobslusser** [comment]
I don't have a guide written specifically for ScintillaNET, but you should be able to follow this guide based on the native Scintilla component -- starting at the section titled "Special case: Folding":

[http://www.scintilla.org/Lexer.txt](http://www.scintilla.org/Lexer.txt)

**Comment by JohnyMac** [comment]
Thanks.
