### ISSUE TITLE
Font size settings do not work randomly while using IME

### ISSUE THREAD

**Issue by YangFan789** [jacobslusser/ScintillaNET#171]
Startup and enter text without IME:
![image](https://cloud.githubusercontent.com/assets/14011681/12222148/91a27096-b7ee-11e5-8168-6545a4ea7cc2.png)

Restart the application and enter text with Sougou IME([Sogou pinyin input method](http://pinyin.sogou.com/index.php)):
![image](https://cloud.githubusercontent.com/assets/14011681/12222156/e807c2c4-b7ee-11e5-92da-2b6acd9a657b.png)

This would occur randomly. When this happens, only to restart the application can return to normal.

Sets the font size of the code is as follows:
``` c#
        private void FormMain_Load(object sender, EventArgs e) {
            scintilla.Lexer = Lexer.Cpp;
            scintilla.Styles[Style.Cpp.Default].Font = "Microsoft Yahei Mono";
            scintilla.Styles[Style.Cpp.Default].Size = 14;
        }
```

**Comment by jacobslusser** [comment]
To be upfront, Scintilla is not very good at non-English support. We may not get to the bottom of this...

That being said, have you tried making sure that you've set the font for ALL the styles, and not just the Default?

```cs
scintilla.StyleResetDefault();
scintilla.Styles[Style.Default].Font = "Microsoft Yahei Mono";
scintilla.Styles[Style.Default].Size = 14;
scintilla.StyleClearAll(); // Will copy the Default style to all other styles
```
