### ISSUE TITLE
Strange behavior with marker

### ISSUE THREAD

**Issue by 4-k** [jacobslusser/ScintillaNET#172]
Refer the below code

       List<string> lines = ....
       ...
       for(int i = 0; i< lines.Count; i++)
       {
           if(lines.StartsWith("[NEW]"))
           {
                rightScintilla.AppendText(Environment.NewLine);
                rightScintilla.AppendText(lines[i]);
                ScintillaNET.Marker marker;
                marker = rightScintilla.Markers[0];
                marker.Symbol = ScintillaNET.MarkerSymbol.Background;
                marker.SetBackColor(Color.Yellow);
                rightScintilla.Lines[i].MarkerAdd(0);
           }
      }

Using the above code I am trying to add marker to all the lines which start with "[NEW]", however after a few iteration none of the markers are applied.
Please not that few string in the list 'lines' have zero length.
What could possibly be the reason?

**Comment by jacobslusser** [comment]
> after a few iteration none of the markers are applied.

Are you saying that the markers work some of the time and then stop working? Or are you saying that they never work?

The ["Bookmark Lines"](https://github.com/jacobslusser/ScintillaNET/wiki/Bookmark-Lines) recipe in our documentation has an explanation of how to use markers that you may find helpful.
