### ISSUE TITLE
Designer Incompatible with Extensions that reference SciLexer.dll

### ISSUE THREAD

**Issue by StevenBonePgh** [jacobslusser/ScintillaNET#173]
I don't believe there is anything that can be done with this other than a note in the Wiki, but the designer will fail to add the Scintilla control in design mode with a dll initialization failure if you happen to be running an extension that uses SciLexer.dll.  I found two extensions that use it: ActiveAssistX by WholeTomato and Object Exporter.  Disabling 'Object Exporter' seems to allow it to work (I didn't test ActiveAssistX intensively to see if something breaks there).  Hopefully this can assist others that experienced the same issue.

To locate potentially problematic extensions, check in your local AppData\Local\Microsoft\VisualStudio\14.0\Extensions folder.  A simple dir command "dir scilexer.dll /s" will help you find these problematic extensions.

**Comment by jacobslusser** [comment]
Interesting. Good to know that.

**Comment by lvj** [comment]
Is there any workaround to run multiple extensions using SciLexer.dll?
