### ISSUE TITLE
SCI_CALLTIPACTIVE supported?

### ISSUE THREAD

**Issue by KarlMicroRobotics** [jacobslusser/ScintillaNET#176]
Is there an API for the SCI_CALLTIPACTIVE function in Scintilla?
Is there a recommended work-around if not?
Thanks,
Karl

**Comment by jacobslusser** [comment]
The `Scintilla.CallTipActive` property.
[https://github.com/jacobslusser/ScintillaNET/blob/master/src/ScintillaNET/Scintilla.cs#L3348-L3360](https://github.com/jacobslusser/ScintillaNET/blob/master/src/ScintillaNET/Scintilla.cs#L3348-L3360)

For some reason it looks like this property is incorrectly flagged as `[EditorBrowsable(EditorBrowsableState.Never)]` which means Visual Studio may not give you IntelliSense, but it's there.

**Comment by KarlMicroRobotics** [comment]
OK, thanks :-)
    Karl
    
    Karl Lam
Technical Director
Micro-Robotics Ltd
Registered Office: 135 Ditton Walk, Cambridge CB5 8QB.
Tel: 01223 523100. Fax: 01223 524242.

Registered in England No. 03983610
VAT No. GB 393 2883 17
www.microrobotics.co.uk
    On 14/01/2016 15:46, jacobslusser
      wrote:
    
    
      The Scintilla.CallTipActive property.
        https://github.com/jacobslusser/ScintillaNET/blob/master/src/ScintillaNET/Scintilla.cs#L3348-L3360
      For some reason it looks like this property is incorrectly
        flagged as [EditorBrowsable(EditorBrowsableState.Never)]
        which means Visual Studio may not give you IntelliSense, but
        it's there.
      —
        Reply to this email directly or view
          it on GitHub.
