### ISSUE TITLE
SetSel, negative anchor position doesn't result in no selection

### ISSUE THREAD

**Issue by KarlMicroRobotics** [jacobslusser/ScintillaNET#179]
Using the SetSel method, supplying a  negative anchor position (-1) doesn't result in no selection, but in the selection extending back to the start of the document.

**Comment by jacobslusser** [comment]
So the documentation says that a negative value for the anchor position should move the anchor and caret to the same position -- effectively removing any selection. Is the documentation wrong? Is that the issue?

**Comment by KarlMicroRobotics** [comment]
Yes, that's the issue,
    Karl
    
    On 20/01/2016 16:02, jacobslusser
      wrote:
    
    
      So the documentation says that a negative value for the anchor
        position should move the anchor and caret to the same position
        -- effectively removing any selection. Is the documentation
        wrong? Is that the issue?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by jacobslusser** [comment]
I finally got  around to testing this and I cannot replicate the behavior you describe. When I call `scintilla.SetSel(-1, 5)` it moves the caret to position 5 with no selection, just as I would expect and as the documentation states.

Can you please retest?

**Comment by KarlMicroRobotics** [comment]
I can't reproduce the problem, so I agree it works as documented.
    Sorry for the extra work!
    

    On 06/03/2016 15:46, jacobslusser
      wrote:
    
    
      I finally got around to testing this and I cannot replicate the
        behavior you describe. When I call scintilla.SetSel(-1,
          5) it moves the caret to position 5 with no selection,
        just as I would expect and as the documentation states.
      Can you please retest?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by jacobslusser** [comment]
No worries.
