### ISSUE TITLE
Cursor issues with dark backColor

### ISSUE THREAD

**Issue by TN-1** [jacobslusser/ScintillaNET#183]
Hi.  
My application has got both dark and light themes.  
When I set my Scintilla.BackColor to gray which is what I want for the background, the text select cursor disappears(Because it is gray and you obviously can't see gray on gray)  
Is there a way to create a custom cursor over the Scintilla control so that I can add in a white text select cursor(As scintilla doesnt have a Cursor property)?  
  
Thanks

**Comment by robmburke** [comment]
scintilla.CaretLineBackColor = Color.White;

**Comment by TN-1** [comment]
That didnt do anything

**Comment by robmburke** [comment]
Oops, that was the wrong line.

scintilla.CaretForeColor

**Comment by TN-1** [comment]
That changed the little blinky thing which is something else I wanted to do, But to clarify I mean the actual mouse cursor itself

**Comment by jacobslusser** [comment]
No, the mouse pointer color cannot be changed. This is managed by Windows, not Scintilla.

**Comment by TN-1** [comment]
Controls like the textbox and richtextbox have got cursor properties though, Would something similar be possible to add to scintilla?

**Comment by jacobslusser** [comment]
Correct me if I'm mistaken, but the `Cursor` property does not change the color. It allows you to change the cursor type, but not whether it is black or purple. Right?

As for whether ScintillaNET has or should have a `Cursor` property, you should look at issue #22, commit d8b0e800f79a4aaff3de2cec0d0fb179e3588a63. When we let Windows Forms handle cursors for us it created problems, so the property was disabled. You're welcome to try and enable it again and see if you can get some of your ideas working.

**Comment by robmburke** [comment]
Yeah. The cursor property just lets you choose the cursor type that is seen when you mouse over the control, but it just uses the ones defined in the current cursors set in Windows.  Cursors are images, so you can't just change colors. You could look into custom cursors for the app as a whole but I bet you would have to hook into some Windows API stuff for that or something.

**Comment by TN-1** [comment]
I was under the impression one could define a custom .cur file with the cursor property.  
  
Ill have a look at that, Thanks for the help guys :)
