### ISSUE TITLE
Clear Brace highlighting

### ISSUE THREAD

**Issue by robmburke** [jacobslusser/ScintillaNET#184]
So I'm using the built-in brace matching stuff when I know I am near an open/closed paren.
When the cursor moves, I need to remove that highlight when I am no longer near a paren.

What's the best way to go about that?

**Comment by jonandr** [comment]
https://github.com/jacobslusser/ScintillaNET/wiki/Brace-Matching

See code after comment "Turn off brace matching".

**Comment by robmburke** [comment]
My bad, should have caught that.  Thanks.
Didn't realize there was some static properties on Scintilla.
Cool to know.
