### ISSUE TITLE
GoTo.ShowGoToDialog() - will this be implemented?

### ISSUE THREAD

**Issue by KarlMicroRobotics** [jacobslusser/ScintillaNET#187]
Will you implement something like the GoTo.ShowGoToDialog()?

Thanks,
Karl

**Comment by theryan722** [comment]
In Issue #4 Jacob said he was not planning on implementing the dialogs that were in version 2.x, I do not believe this has changed but maybe he will say otherwise.

**Comment by jacobslusser** [comment]
@theryan722 is correct. While we often think of those dialogs as being universal, in practice they actually tend to be application specific and impossible for us to cater to everybody's needs.

Feel free though to make a sister project to ScintillaNET which contains those kind of enhancements/extensions.

**Comment by KarlMicroRobotics** [comment]
No problem - I was going to implement the dialog in my application, but didn't want to do that if ScintillaNet dialogs were going to be implemented.
