### ISSUE TITLE
FindNextMarker

### ISSUE THREAD

**Issue by maxmont** [jacobslusser/ScintillaNET#189]
Hi all,

I'm migrating to new scintillanet version. I was using function "FindNextMarker" to find markers without searching in all lines.

Which function or how can I do now with the new version?

Thanks

**Comment by jacobslusser** [comment]
The wiki article [Bookmark Lines](https://github.com/jacobslusser/ScintillaNET/wiki/Bookmark-Lines) has a good example of using `MarkerNext`.

**Comment by maxmont** [comment]
Thanks for your answer.
I had seen this example. But anyway, I have to check all lines one by one. True?

**Comment by jacobslusser** [comment]
When you call `Scintilla.Lines[0].MarkerNext(...)` it will start a search from line 0, looking for the next line with that marker. Suppose it finds one at line 55. The return value from that call would then be `55`. From there you could search for the next marker after that by calling `Scintila.Lines[55].MarkerNext(...)`. Etc... You don't need to check all lines one-by-one. You're skipping from marker line to marker line. That's exactly how it works in the old ScintillaNET v2.

One other thing the old ScintillaNET v2 did was give you a `FindNextMarker` method which didn't require a starting line to being your search. What it's actually doing under the hood is starting from the "current line". i.e. `Scintilla.Lines[Scintilla.CurrentLine].MarkerNext(...)`

**Comment by maxmont** [comment]
Thanks for your help

**Comment by ericoporto** [comment]
The linked wiki article is now [Markers-and-Bookmarking-Lines](https://github.com/jacobslusser/ScintillaNET/wiki/Markers-and-Bookmarking-Lines) if someone is looking for it
