### ISSUE TITLE
Documents and custom syntax highlighting

### ISSUE THREAD

**Issue by iamtabo** [jacobslusser/ScintillaNET#19]
Hello, 

I'm using Scintilla to do some custom syntax highlighting for HLASM (that's IBM mainframe assembler), by hosting it in WPF. I can read in my data, display it and highlight, so all is well there.  However, I would like to be able to open another data file, read it, display it and highlight it as well.

The doc wasn't exactly very clear on this, so I created a new document, set it to as the new document and release the old one, like so:

    var oldDoc = scintilla.Document;
    scintilla.Document = new Document();
    scintilla.ReleaseDocument(oldDoc);

Once the document is created, I start appending text to the control.  However, it seems like either the styleposition or textLength field is not being reset properly, so my syntax highlight blows up in `SetStyling()` with 
`ArgumentOutOfRangeException("length", "Position and length must refer to a range within the document.");`

Any idea what I am doing wrong here?

Thanks

**Comment by jacobslusser** [comment]
Are you calling `StartStyling` before you call `SetStyling`? Each time you call `SetStyling` it advances an internal position so that subsequent calls will style subsequent ranges. To reset the internal position you should call `StartStyling` first, then `SetStyling`.

**Comment by iamtabo** [comment]
Ah, that was it.  Looks like I screwed up when I copied the code from the readme.  Thanks very much.
