### ISSUE TITLE
Possibility of cross-platform support?

### ISSUE THREAD

**Issue by theryan722** [jacobslusser/ScintillaNET#191]
Are there any plans in the future for ScintillaNET to be compatible with linux on Mono?

**Comment by jacobslusser** [comment]
Not from this guy. It's hard enough keeping up support for one platform. :)

I actually don't ever use Linux/Mono and so am not the right guy to do that kind of port, but my understanding is that Scintilla is GTK+ compatible so it is possible if someone else wants to take up the project.

**Comment by theryan722** [comment]
Haha yeah, I mean I guess I should have expected that. Thanks!

**Comment by DanWBR** [comment]
I do use Linux and macOS and I'm currently working on a scintilla control which will work on Linux and macOS through the [Eto library (C#)](https://github.com/picoe/Eto/). It will run native controls on these OSes (cocoa in macOS and GTK+ on Linux). ScintillaNET should be easily adapted to Linux but will be limited to Windows Forms, which doesn't run so well. I'll work on it after I finish the first job.

**Comment by DanWBR** [comment]
Got it working on Linux and macOS with C# through the Eto library. See the [ScintillaEto](https://github.com/DanWBR/ScintillaEto) project:

![](https://snag.gy/xnoMjk.jpg)

![](https://snag.gy/IYWMku.jpg)

**Comment by pablocar80** [comment]
@DanWBR amazing job Daniel. I'm the first person to star your project!
