### ISSUE TITLE
How to perform editing code, this is a headache problem?

### ISSUE THREAD

**Issue by 1290726334** [jacobslusser/ScintillaNET#192]
I have written the code, but I do not know how to use ScintillaNET
Compile, need to get help.

**Comment by jacobslusser** [comment]
Please review the [Wiki](https://github.com/jacobslusser/ScintillaNET/wiki).

**Comment by 1290726334** [comment]
can do with Demo?
Just a few lines of code

**Comment by jacobslusser** [comment]
The wiki contains numerous code samples. Is there a specific issue I can help you with? An error message you don't understand?

It would be impossible to provide a demo or code sample for you because I don't understand what your issue is.

**Comment by theryan722** [comment]
If you are referring to compiling code, this project does not serve that purpose. You will have to handle the compiling of code on your own or by using a compiler.
