### ISSUE TITLE
How to turn it on breakpoints

### ISSUE THREAD

**Issue by jenokizm** [jacobslusser/ScintillaNET#194]
The component provides breakpoints to debug?

**Comment by jacobslusser** [comment]
ScintillaNET is a text editor, not an IDE. So to be clear, there are no facilities within ScintillaNET for "breakpoints". That being said, I assume you want to know how to show a breakpoint *icon* in the margin. That can be done using markers.

The [Bookmark Lines](https://github.com/jacobslusser/ScintillaNET/wiki/Bookmark-Lines) recipe explains a little bit about margins and markers (which are margin icons). Hopefully you should be able to follow this guide and substitute `Marker.Circle` for `Marker.Bookmark` where necessary.

**Comment by jenokizm** [comment]
OK, great! Thank you!
one question, you can make that point were placed on the left of the line numbers like in the studio?

**Comment by jacobslusser** [comment]
Yes. Margins and markers appear to the left of the text just like Visual Studio. Give it a try.
