### ISSUE TITLE
 Add a lexer to Scintilla

### ISSUE THREAD

**Issue by Serg7845** [jacobslusser/ScintillaNET#197]
Hello,
How to change lexers in Scintilla ? 
Thanks

**Comment by jacobslusser** [comment]
The wiki articles for [Automatic Syntax Highlighting](https://github.com/jacobslusser/ScintillaNET/wiki/Automatic-Syntax-Highlighting) and [Custom Syntax Highlighting](https://github.com/jacobslusser/ScintillaNET/wiki/Custom-Syntax-Highlighting) are probably what you're looking for.
