### ISSUE TITLE
Find & Replace dialog 

### ISSUE THREAD

**Issue by igiona** [jacobslusser/ScintillaNET#198]
In the all website location (http://scintillanet.codeplex.com/) is clearly stated that ScintillaNET does provide S&R dialogs built in.

I donwloaded the code V3.5.6, but I'm not able to find them anywhere...

What I'm missing?

Kind regards

**Comment by robmburke** [comment]
Probably missing the fact that the last supported version on Codeplex is version 2.6 and version 3 is a total rewrite that does not provide any dialogs for the developer.

The documentation on codeplex will only be relevant if you download the version from codeplex. That project is no longer supported as Jacob has moved everything to github.

**Comment by igiona** [comment]
Yep, I definitely missed that point :).
It would be a nice feature which many people may want to/need to have.
