### ISSUE TITLE
XML Lexer?

### ISSUE THREAD

**Issue by twfurst** [jacobslusser/ScintillaNET#2]
I've used the previous version of ScintillaNET that was on CodePlex for displaying XML in C# WinForms. I downloaded this new version today and am having issues with setting up an XML lexer. Is there a new way to accomplish this? 

Thank you

**Comment by jacobslusser** [comment]
I've been implementing lexers on an "as needed basis" and haven't had any
requests yet for XML. I'll put in the code and drop you a line when it's
done.

Jacob

**Comment by jacobslusser** [comment]
I've checked-in the XML lexer enum value and style constants. You can find
direction on how to configure a lexer in the project README.md.

Please get latest and let me know if you have any other questions.


Jacob

**Comment by twfurst** [comment]
Thank you for making this available, the only question I have is about folding. Is it functional for the XML lexer? I used the example in the README.md file but it is not showing up in my form.
![form](https://cloud.githubusercontent.com/assets/12141046/7397103/35bbb66e-ee74-11e4-88d1-af03108559b8.jpg)
Screenshot of code:
![code](https://cloud.githubusercontent.com/assets/12141046/7397128/593cb0d4-ee74-11e4-96c0-f26a276b1c2c.jpg)

Thanks

**Comment by jacobslusser** [comment]
Looking at the native Scintilla code I think you also need to have the "fold.html" property set to "1" (in addition to the "fold" and "fold.compact" properties you already have).

If that doesn't work, let me know.

**Comment by twfurst** [comment]
That did it. Thank you

**Comment by xonyen** [comment]
I'm sorry that I hadn't seen this before. I have tried the solution and it works well. Thanks a lot!

**Comment by fut33v** [comment]
Is it possible to get current lexeme/token of XML code and get the info about is it a XML tag/attribute?
