### ISSUE TITLE
Documentation of changeset since previous releases

### ISSUE THREAD

**Issue by caiohamamura** [jacobslusser/ScintillaNET#20]
I was using a previous release, but suddenly a bunch of functions/properties which I was used to disappeared (ex: GetWordFromPosition, Lexing, AutoComplete), or had its name changed (CurrentPos -> CurrentPosition) and I'm having trouble to figure out whether I will have to code the function or only change the name I was used to.
So it would be great to have a documentation on the changeset, and in the first place why these functions/properties were deprecated?

**Comment by jacobslusser** [comment]
ScintillaNET v3 shares a name with previous versions, but none of the code. As explained in the project README, the new version is a complete rewrite and there was good reasons for doing this.

A different design philosophy drives this new version and where that is incompatible with a former feature it will not be ported over, but those instances are rare. Generally speaking you should find all the functionality you were using before but as you discovered it may be in a different place.

To document all the changes would be time consuming and may not answer your exact questions. Instead, I would rather just help you find what you're looking for.

Is there a particular API/functionality I can help you find?
