### ISSUE TITLE
Change color to Margin field

### ISSUE THREAD

**Issue by Serg7845** [jacobslusser/ScintillaNET#204]
Hello,
how to change the color of the field of Margin ?
Thanks

**Comment by jacobslusser** [comment]
The `Scintilla.SetFoldMarginColor` and `Scintilla.SetFoldMarginHighlightColor` methods can set the color of a fold margin.

Non-fold margins can style their text using the `Scintilla.Lines[n].MarginStyle` property on a per-line basis.

To set a solid color in the margin on a per-line basis you can also set a marker using `MarkerSymbol.FullRect`.

**Comment by PUSRISTEK** [comment]
this is my code on form load event, codeeditor is scintillaNET control.
CodeEditor.SetFoldMarginColor(true,Color.Blue);
CodeEditor.SetFoldMarginHighlightColor(true, Color.Blue);

but the margin won't change. why?

**Comment by jacobslusser** [comment]
See issue #220.

**Comment by jacobslusser** [comment]
FYI [ScintillaNET v3.6.3](https://github.com/jacobslusser/ScintillaNET/releases) brings support for additional margins beyond the limit of 5 and support for more background color options.
