### ISSUE TITLE
How to add other lexer supported by (not NET) Scintilla 

### ISSUE THREAD

**Issue by Hypernut** [jacobslusser/ScintillaNET#206]
How can i add/use the lexer for **PowerShell** which is seemingly supported by the base Scintilla, but does not show up as a valid value for "scintillaNET.lexer"?

**Comment by JohnyMac** [comment]
@jacobslusser adds lexers by request.. He will most likely add it soon now.

**Comment by Hypernut** [comment]
That is a pity.

**Comment by JohnyMac** [comment]
You can try adding it yourself.. Its not that hard.. Try following this commit: 
https://github.com/jacobslusser/ScintillaNET/commit/7accb08360b9af0e6af59eac3a5417c8990d3384

**Comment by Hypernut** [comment]
I'm a Powershell Guy, I have really not the slightest idea on how to do this.
