### ISSUE TITLE
CallTipShow with non-ASCII characters

### ISSUE THREAD

**Issue by RaeuberHotzenplotz** [jacobslusser/ScintillaNET#207]
I need to show tool-tips that include German "Umlaute" like "äÄöÖüÜ". If i understand the API correctly, only pure ASCII-strings are supported. That's quite a limitation since ScintillaNET claims to supports Unicode completely. Is there a workaround to make Unicode tool-tips possible?

**Comment by jacobslusser** [comment]
Somewhere along the line Scintilla must have added support for Unicode call tips and I didn't notice. I've updated ScintillaNET in commit b25ac72e0703b1c1ebcab62bf9eb513469a018a0 and my testing looks good. Give it a try.

**Comment by RaeuberHotzenplotz** [comment]
Works perfectly, thanks.
