### ISSUE TITLE
BraceMatch not woking properly.

### ISSUE THREAD

**Issue by Aghlara** [jacobslusser/ScintillaNET#210]
Hi,

I am following https://github.com/jacobslusser/ScintillaNET/wiki/Brace-Matching to find the brace match. Scintilla.BraceMatch is all good in normal characters:

![screen shot 2016-04-14 at 9 06 38 am](https://cloud.githubusercontent.com/assets/5187409/14512209/68be32c4-0220-11e6-871f-6f02a6c2227d.png)

but as soon as special characters are found inside braces, Scintilla.BraceMatch does not find the valid brace and returns -1:

![screen shot 2016-04-14 at 9 08 25 am](https://cloud.githubusercontent.com/assets/5187409/14512223/952efcf8-0220-11e6-9bb6-b1a8fbec7a6f.png)

Is it because != has a styling applied? As soon as I change != to something that does not have styling it works fine again.

How do I fix this?

Regards,

**Comment by jacobslusser** [comment]
I think the original Scintilla documentation for the `SCI_BRACEMATCH` function (which `Scintilla.BraceMatch` wraps) gives a possible explanation. It states:

> A match only occurs if the style of the matching brace is the same as the starting brace or the matching brace is beyond the end of styling. [http://www.scintilla.org/ScintillaDoc.html#SCI_BRACEMATCH](http://www.scintilla.org/ScintillaDoc.html#SCI_BRACEMATCH)

Is it possible that the style of the `'('` character does not match the style of the `')'` character?

**Comment by Aghlara** [comment]
Not really as you can see in the above example parentheses are matching if you count them you see they are balanced in that position.

**Comment by jacobslusser** [comment]
I'm not talking about the braces being unbalanced. I'm asking whether they have different styles. Visually, I know they look the same (black), but is is possible that one bracket has style index `0` and the other has style index `1`, or `2`, or `32`, or whatever? If both braces don't have the exact same style index then the brace matching logic will not work.

You can check what the styles are for each character by using `Scintilla.GetStyleAt`.

**Comment by jacobslusser** [comment]
I'm considering this question answered because I believe my last response explains the behavior. Let me know if this needs to be reopened.
