### ISSUE TITLE
Preserve Tabs on a new line

### ISSUE THREAD

**Issue by pstuart** [jacobslusser/ScintillaNET#211]
Trying to figure out a way to preserve the tab spacing in the editor when creating a new line so the column goes to the last line's tabs from the starting line.  Instead of writing something from scratch, is there something built into the scintilla syntax that does this?

**Comment by jacobslusser** [comment]
This has been discussed a bit in our forums and a few solutions presented in issue #35.

**Comment by pstuart** [comment]
Thanks, I did eventually find an example I could modify.  Thanks for your hard work on this project!
