### ISSUE TITLE
The Name Style Does Not Exist in The Current Context

### ISSUE THREAD

**Issue by PUSRISTEK** [jacobslusser/ScintillaNET#214]
Hello jacob i can't change the font..

scintilla1.Styles[**Style**.Default].Font = "Courier New";

error : 
The Name Style Does Not Exist in The Current Context

**Comment by jacobslusser** [comment]
That would imply you haven't imported the ScintillaNET namespace. Add this to the top of your class file...

```cs
using ScintillaNET;
```

... or change the code to this:

```cs
scintilla1.Styles[ScintillaNET.Style.Default].Font = "Courier New";
```

... and make sure you have a reference to the ScintillaNET library and that you can build your solution if you comment out that line of code.

**Comment by PUSRISTEK** [comment]
thank you so much :)

**Comment by PUSRISTEK** [comment]
thank you so much :)
