### ISSUE TITLE
Pixsys PLC

### ISSUE THREAD

**Issue by yoshadow** [jacobslusser/ScintillaNET#215]
Hi everyone.

Have you programmed a PLC using Scintilla? This kind of PLC I have is from Italy, Pixsys brand.
I'm using the PLProg software using ladder code to program this PLC, this software has the Scintilla editor integrated and you can use C to program the PLC.
So I'm looking the syntax to program this PLC using Scintilla. I already looked into the documentation on Pixsys web page and Scintilla web page, but I didn't find anything.
I'll be thankful If anyone has a tutorial or some info that can share with me.

**Comment by jacobslusser** [comment]
It sounds to me like you're looking for an IDE which would allow you to write code, compile it, and debug it on the PLC. That's beyond what Scintilla can do out of the box. Scintilla[NET] is a text editor, not a full-blown IDE. With Scintilla you could build an IDE using it as your text editor, but you would still need to implement your own logic for compilation and debugging of code.

If you're only interest is writing code for your PLC then this project is not what you're looking for. ScintillaNET is for people who want to write their own IDE as described above. You should be looking for an existing IDE or an extensible text editor that is already built.

**Comment by yoshadow** [comment]
Hi jacobslusser, thanks for your answer.

The PLProg software already has the Scintilla IDE
I Attached 2 screenshots, first for the PLProg software and second for the Scintilla IDE.

![screenshot_2](https://cloud.githubusercontent.com/assets/11691371/14329329/85d5e81e-fc00-11e5-934b-4ed9cc9850c5.png)

![screenshot_3](https://cloud.githubusercontent.com/assets/11691371/14329333/8b9a8eee-fc00-11e5-9158-affbceda4548.png)

I have a few comands that someone wrote, but I dont what are the syntax.

![screenshot_4](https://cloud.githubusercontent.com/assets/11691371/14329464/11e9c168-fc01-11e5-82c3-ae1e9e9de7a3.png)
