### ISSUE TITLE
Scintilla control Undo will remove all user text regardless of dwell time

### ISSUE THREAD

**Issue by glopesdev** [jacobslusser/ScintillaNET#218]
Calling Undo on Scintilla control seems to remove all user text rather than the most recently typed text.
Is there some kind of feature we need to tweak?

I did notice that sometimes (rarely) the control works ok and I can undo only the most recent chunks. Also if I copy and paste or do other programmatic modifications, the undo/redo works as expected.

For reference, I am using ScintillaNET 3.5.4 and was trying to avoid updating, but please let me know if the issue is fixed on later versions.

Thanks!

**Comment by glopesdev** [comment]
Weird, it looks like launching message boxes somehow changes the timing of this. I removed a message box that was launching simultaneously with the loading of the control and it seems to have solved it.

Would be nice to be able to configure the dwell time for undo though.

**Comment by jacobslusser** [comment]
When should undo points be set? The answer will differ greatly if you ask different developers. Obviously you wouldn't want an undo point after every. single. letter. typed... but you also wouldn't want it after you've typed too much and would loose all your work when you only wanted to undo the last keystroke.

When to set undo points is a bit of a heuristic.. an educated guess that Scintilla makes. The same is true of any undo system in any text editor.

The seemingly different behavior you observed with launching of a message box probably has more to do with Scintilla losing or gaining focus and how that might play into the heuristic it uses to set undo points.

The option(s) Scintilla provides to tune that logic is the `Scintilla.BeginUndoAction` and `Scintilla.EndUndoAction` APIs. With these you can effectively control how much should be grouped into a single undo, whether that be every character change, every "find and replace all", every 5 minutes... it's up to you, but you may find it can be a tricky problem. :)
