### ISSUE TITLE
caret on margins

### ISSUE THREAD

**Issue by xonyen** [jacobslusser/ScintillaNET#22]
I'm not sure why I can see caret on margins when moving mouse. See the picture below.
![image](https://cloud.githubusercontent.com/assets/9267574/8020653/35f56384-0cb3-11e5-9b03-6aa8c57f7c10.png)
When I stop moving, the cursor displays as arrow. But when I'm moving the mouse, it displays as caret. Do you have any opinions about this?
Thanks.

**Comment by jacobslusser** [comment]
Good catch. Commit d8b0e800f79a4aaff3de2cec0d0fb179e3588a63 should fix that for you.

**Comment by xonyen** [comment]
I've tried the new version(v3.4.1) and it real fixed this issue. Thank you very much!
