### ISSUE TITLE
Searching From Down To Up.

### ISSUE THREAD

**Issue by JohnyMac** [jacobslusser/ScintillaNET#222]
Hello,

Is it possible to search from down to top ?.. To get the first above the caret and keep going till up.

**Comment by jacobslusser** [comment]
Yes. When you specify your search range with `TargetStart` and `TargetEnd`, make your `TargetStart` greater/past than `TargetEnd` and it will search in the opposite direction.

**Comment by JohnyMac** [comment]
Yeah I tried that already and it worked.. Thanks a lot.
