### ISSUE TITLE
.TextLength and .Text.Length can differ when setting text.

### ISSUE THREAD

**Issue by nigelhawkins** [jacobslusser/ScintillaNET#223]
When you set the text on a scintillaNET control using the `.Text` property, one of the events that can fire is `Resize`. Inside a handler for this event, `.TextLength` seems to still hold the value for the old text in the control, while the `.Text` property seems to hold the new text.

This is with the 3.5.6 version of ScintillaNET grabbed from NuGet.

**Comment by jacobslusser** [comment]
Thanks for pointing this out so that other developers don't also get tripped up on this.

The reason is because the resize event fires before the document change event which ScintillaNET uses internally to update the line length cache and ultimately the `TextLength` property.
