### ISSUE TITLE
Embed CSS in HTML

### ISSUE THREAD

**Issue by F-H-I** [jacobslusser/ScintillaNET#225]
Hello once more,
I have found the according style numbers for Javascript(40-52) and PHP(118-127) embed in HTML, but i dont see any for CSS, do u maybe know more about this.
I looked through the following source code: [Sci lexer](https://github.com/H-uru/PlasmaShop/blob/master/QScintilla/include/SciLexer.h)(i've also downloaded the scintilla source code and didnt find anything in the Scilexer.h file aswell)

thanks in advance ;)

**Comment by jacobslusser** [comment]
Ya, I don't see it either. My conclusion is that Scintilla only supports styling of CSS as a whole, but not as a nested `style` block in an HTML document. Poking around Notepad++ seems to confirm this.
