### ISSUE TITLE
Speeding up custom lexer

### ISSUE THREAD

**Issue by gersonkurz** [jacobslusser/ScintillaNET#226]
Just a small comment: The "Custom Syntax Highlighting" contains the following code:
```
while (startPos < endPos)
{
      var c = (char)scintilla.GetCharAt(startPos);
```
I am working on large documents (typical size >10mb) and find that the following code speeds up syntax highlighting **tremendously**:
```
string copyOfText = scintilla.Text;
while (startPos < endPos)
{
      var c =copyOfText[startPos];
```
basically because you don't have to do thousands of function calls.

**Comment by jacobslusser** [comment]
Indeed, limiting the number of function calls -- especially those that go in and out of Scintilla -- will increase performance. In that same wiki article you mentioned is also this advice:

> On each loop iteration we advance the `starPos` and get the next character by calling `GetCharAt`. For performance or practical reasons you may prefer to get an entire line of text a time. It's entirely up to you how you go about writing your lexer.

Be careful going too far in the other direction though. Getting the entire document `Text` on every call to `StyleNeeded` could also be expensive.

Thanks for sharing.
