### ISSUE TITLE
I have some suggestions for development.

### ISSUE THREAD

**Issue by zbooa** [jacobslusser/ScintillaNET#228]
ScintillaNET is a great project, I also used other controls.This,Great.
There are a few points, hoping someone can improve it.
A . Document Map.      When the code is very long, display the whole
B.  Ruler. Like the line-number , each line has a length
C.  Custom slider. The default slider is too ugly.
If you have to improve these, this is the perfect control of the.

**Comment by JohnyMac** [comment]
I'd say you gotta suggest this stuff to Scintilla itself and not here, This is just a wrapper to get Scintilla to .NET.

**Comment by jacobslusser** [comment]
What @JohnyMac said is the short answer. ScintillaNET is a wrapper around Scintilla and most/all of these features are likely best implemented in the native control itself.

The longer answer is that I don't see anything in your wishlist that is impossible to implement if you wanted to create a document map, ruler, or slider control which sits next to Scintilla and works with it. It wouldn't be built in, but I believe it should be possible to have separate controls which work in conjunction with ScintillaNET and leverage the `UpdateUI` event for example to make it look like it is one cohesive control -- albeit, it would be no small effort to make such controls.

Finally, a question of my own... what is a "slider"? Are you speaking of the scrollbar?

**Comment by zbooa** [comment]
@JohnyMac Yes , scrollbar.
