### ISSUE TITLE
Some help creating a CTRL+Click thing.

### ISSUE THREAD

**Issue by JohnyMac** [jacobslusser/ScintillaNET#229]
I am trying to make something like CTRL+Click to navigate to functions declaration just like VS.

I have done this: 
```vb.net
 Private Sub Editor_KeyDown(sender As Object, e As KeyEventArgs) Handles Editor.KeyDown
        If e.KeyCode = Keys.ControlKey Then
            'The pos.
            Dim pos = Editor.CharPositionFromPointClose(Editor.PointToClient(MousePosition).X, Editor.PointToClient(MousePosition).Y)

            'Get what is there.
            Dim item As String = Editor.GetWordFromPosition(pos)
            
            'Loop in defines for it.
            If CodeParts.Defines.FindAll(Function(x) x.DefineName = item).Count > 0 Then
                Editor.StartStyling(Editor.WordStartPosition(pos, true))
                Editor.SetStyling(Editor.WordEndPosition(pos, true) - Editor.WordStartPosition(pos, true), Styles.Hotspot)
            End If
        End If
    End Sub
```

However, The hotspot styling doesn't appear.. I think its just because that place is already styled.. So, if thats correct, How to clear the style from only a specific region of code ?

After that, I want to clear the hotspot styling when the mouse go away from it.. Sooo, Any idea how I can do this ? :/

**Comment by jacobslusser** [comment]
I'm a little unclear on what you mean by "clear the style from only a specific region of code"... but take a look at the `HotspotClick` and `HotspotReleaseClick` events to see if that helps.

**Comment by JohnyMac** [comment]
Ik that, I want to remove the hotspot styling when the mouse moves away.. but I can't find something like `RemoveStyling` or ``

**Comment by JohnyMac** [comment]
Oops

**Comment by jacobslusser** [comment]
Could you be looking for `Scintilla.Colorize`?

**Comment by JohnyMac** [comment]
No lol, Is it really that complex ? xD

Look, How do I make hotspots ?

**Comment by jacobslusser** [comment]
Sorry dude... I guess I didn't understand the question...

You would use hotspots like this. Assume I'm using the VB lexer and I want all comments to be clickable hotspots, I would set up my styles like this (in addition to what is normally needed to [set up lexers and styles](https://github.com/jacobslusser/ScintillaNET/wiki/Automatic-Syntax-Highlighting)):
```cs
scintilla.Styles[Style.Vb.Comment].Hotspot = true;
```

Then handle one of the hotspot click events such as this:
```cs
private void scintilla_HotspotReleaseClick(object sender, HotspotClickEventArgs e)
{
    var startPos = scintilla.WordStartPosition(e.Position, true);
    var endPos = scintilla.WordEndPosition(e.Position, true);
    var text = scintilla.GetTextRange(startPos, endPos - startPos);
    if (!string.IsNullOrEmpty(text))
    {
        MessageBox.Show(text);
    }
}
```

**Comment by JohnyMac** [comment]
Okay, that worked.. Thanks.
However, I don't think hotspots is the best way to do what I want PLUS I am not keen to rewrite what I did right now xD, So I'll just close this issue now and reopen if and when I need it.
