### ISSUE TITLE
Lua lexer?

### ISSUE THREAD

**Issue by nagblock** [jacobslusser/ScintillaNET#23]
Hi,

As you said you've been implementing lexers on an "as needed basis" I wonder if you would consider adding lua (http://www.lua.org/) to the list? Is this only possible by extending the library itself? I see that there is a custom recipe for python but it uses the Lexer.Python enum for setting everything up. How would one add support for lua without a dedicated lua enum value? Is there a viable option apart from handling StyleNeeded and doing all the lexing manually?

best regards, nagblock

**Comment by jacobslusser** [comment]
I added Lua for you in commit 202759cd3f79a869f08b880db38ba58fa3f30a5f.

Lexers and styles in ScintillaNET are just integer constants. I get them from the `SciLexer.h` header file in the native Scintilla project. I include them in ScintillaNET to make it easier for developers, but strictly speaking there is nothing special about it. You could do the same for any lexer not officially in the project like this:

```cs
// Obtained from SciLexer.h
const int SCLEX_LUA = 15;
const int SCE_LUA_DEFAULT = 0;
const int SCE_LUA_COMMENT = 1;
const int SCE_LUA_COMMENTLINE = 2;
const int SCE_LUA_COMMENTDOC = 3;
const int SCE_LUA_NUMBER = 4;
const int SCE_LUA_WORD = 5;
const int SCE_LUA_STRING = 6;
const int SCE_LUA_CHARACTER = 7;
const int SCE_LUA_LITERALSTRING = 8;
const int SCE_LUA_PREPROCESSOR = 9;
const int SCE_LUA_OPERATOR = 10;
const int SCE_LUA_IDENTIFIER = 11;
const int SCE_LUA_STRINGEOL = 12;
const int SCE_LUA_WORD2 = 13;
const int SCE_LUA_WORD3 = 14;
const int SCE_LUA_WORD4 = 15;
const int SCE_LUA_WORD5 = 16;
const int SCE_LUA_WORD6 = 17;
const int SCE_LUA_WORD7 = 18;
const int SCE_LUA_WORD8 = 19;
const int SCE_LUA_LABEL = 20;

scintilla.Lexer = (Lexer)SCLEX_LUA;
scintilla.Styles[SCE_LUA_DEFAULT].ForeColor = Color.Black;
scintilla.Styles[SCE_LUA_COMMENT].ForeColor = Color.Green;
// etc..
```

**Comment by nagblock** [comment]
thanks, that's just what I needed! :)
