### ISSUE TITLE
Unable to load SciLexer from TEMP

### ISSUE THREAD

**Issue by Petarian** [jacobslusser/ScintillaNET#230]
Hi,
It appears ScintiallaNET.DLL copies SclLexer.dll to the %TEMP% folder and tries to load it. On certain machines, administrators can set GPO policies that can prevent loading binaries from certain folders, including TEMP. As a result, ScintiallaNET cannot load SciLexer.dll.

My question: Is there any option to prevent this behavior by either changing the PATH where it looks for this file or somehow make it look in the Current Directory before going to TEMP?

**Comment by jacobslusser** [comment]
See the [Using a Custom SciLexer.dll](https://github.com/jacobslusser/ScintillaNET/wiki/Using-a-Custom-SciLexer.dll) wiki article.

When you set the module path you basically tell ScintillaNET not to copy the embedded DLLs to the temp folder and instead just load it from the path you specify. How you get the SciLexer.dll file(s) there is up to you. You can either get the binaries from our project source and include them in your project build output or you can (probably) extract the embedded DLLs from the ScintillaNET binary at runtime and write them to your path. Either way, once you get the SciLexer.dll(s) where you want them you just need to call `Scintilla.SetModulePath` prior to using Scintilla for the first time.

**Comment by Petarian** [comment]
Awesome. This is exactly what I needed. Thank you very much.
