### ISSUE TITLE
Cannot Scroll Scintilla Programmatically

### ISSUE THREAD

**Issue by AlanBurkhart** [jacobslusser/ScintillaNET#235]
Odd problem:
In a spell checker, I'm using ScintillaNet to display the line containing a spelling error and highlighting the error with an indicator. All works well except that the Scintilla control won't scroll to the error. I've tried GotoPosition followed by ScrollCaret and ScrollRange (the range highlighted by the indicator). Neither works. With ScrollCaret, the caret is exactly where it should be, but Scintilla won't scroll to it. Here's the code I'm using at present. "main.sci" is the control in the editor that's being checked, and "sciErr" is the control in the spell checker. And "m" is the Regex match containing the word being checked.

                Dim lNum As Integer = main.sci.LineFromPosition(m.Index)
                sciErr.Text = main.sci.Lines(lNum).Text
                sciErr.IndicatorFillRange(m.Index - main.sci.Lines(lNum).Position, m.Length)
                sciErr.ScrollRange(m.Length, m.Index - main.sci.Lines(lNum).Position)

I'm hoping I'm missing something obvious so I can finish this thing.

**Comment by jacobslusser** [comment]
`ScrollCaret` should scroll the caret into view and display your highlighted word... assuming that is where the caret is. See issues #128, #160, and #162 and see if that helps.
