### ISSUE TITLE
The getter for FirstVisibleLine treats wrapped line as multiple lines

### ISSUE THREAD

**Issue by toehead2001** [jacobslusser/ScintillaNET#236]
Let's say, for example, Line 0 is very long, and gets wrapped two times. 
I scroll down so that Line 5 is at the top of the control. If I then call FirstVisibleLine, it will claim the first visible line is Line 7. (due to Line 0 being wrapped twice)

The setter for FirstVisibleLine is not affected by wrapped lines (as far as I can tell), and works as expected.

It [looks like](https://github.com/jacobslusser/ScintillaNET/blob/b12bf57e7b900edfa4fd29fc7a81e4dbce9af3b0/src/ScintillaNET/Scintilla.cs#L3952) this might be a upstream bug in Scintilla's function, but I don't know for sure.

**Comment by jacobslusser** [comment]
The remarks for `FirstVisibleLine` indicate that it will return the "visible line, not a document line" -- which means the wrapped line index. To get the actual document line, you need to pass the value returned from `FirstVisibleLine` to `DocLineFromVisible`.

**Comment by toehead2001** [comment]
Oh, that explains it. That certainly works. Thank you.
