### ISSUE TITLE
MarginClick is not fired when AutomaticFold is set

### ISSUE THREAD

**Issue by yoursen** [jacobslusser/ScintillaNET#237]
Hi, I have three margins in editor. The first one is line numbers, second is breakpoins and the third is automatic folding. And I have two issues with this configuration
1. When automatic folding is enabled by setting the AutomaticFold property, the scintilla does not fires the event MarginClick, when I click on the second margin (for breakpoints.)
2. Also breakpoint margins has symbols like folding. See attached image.
![capture](https://cloud.githubusercontent.com/assets/18039730/15574551/b2c21212-2356-11e6-87a0-7ccb55a3e76c.PNG)

**Comment by jacobslusser** [comment]
Your breakpoint margin needs to be marked as sensitive to mouse clicks and use a marker mask which excludes fold markers, i.e.
```cs
scintilla.Margins[1].Sensitive = true;
scintilla.Margins[1].Mask = ~Marker.MaskFolders;
```

**Comment by yoursen** [comment]
thank you! it works as expected!
