### ISSUE TITLE
How to change the font of Scintilla editor - Question

### ISSUE THREAD

**Issue by vinodvinu** [jacobslusser/ScintillaNET#239]
Hi, 
I am making an IDE for AutoIt Scripting language in vb.net. I have successfully add the tool in tool box and create an instance of Scintilla editor. I choose "Au3" as lexer from property window. But i can't change the font or font size of this editor. I have set the font consolas in property window, but in runtime, it changes some other font. Then i experiment with some code which i got from wiki. One of them shows like this - "Scintilla.Lexer = Lexer.cpp". I am sadly saying that i can't find a ".Lexer" method or property in my scintilla editor. It has a ".Lexing.Lexer" method.  And in wiki, it says "scintilla.Styles[Style.Cpp.CommentLine].Font = "Consolas"; ". But when i write this code in my visual studio, it shows an error line. It doesn't have "Styles() or Styles[]" option. Is there anything wrong in my project ?

**Comment by jacobslusser** [comment]
It sounds as if you may be using an older version of ScintillaNET... possibly v2.x. If you want to continue to use that version you should follow the instructions for that version [https://scintillanet.codeplex.com/](https://scintillanet.codeplex.com/).

This project supports v3.x and you can find releases here [https://github.com/jacobslusser/ScintillaNET/releases](https://github.com/jacobslusser/ScintillaNET/releases).

**Comment by vinodvinu** [comment]
@jacobslusser , 
Thank you for your quick reply.  Yes, unfortunately i downloaded the old version. Let me try with new version. Thanks.

**Comment by vinodvinu** [comment]
@jacobslusser ,
How can i add AutoIt lexer to ScintillaNet. The version 3.5.6 doesn't carry autoit.

**Comment by jacobslusser** [comment]
Please see my answer to your question in issue #242 and avoid opening several tickets for the same question.
