### ISSUE TITLE
How to make a new language lexer for ScintillaNet - Question

### ISSUE THREAD

**Issue by vinodvinu** [jacobslusser/ScintillaNET#240]
Hi,
Old version of ScintillaNet contains AutoIt lexer, but version 3.x doesn't contains Au3. So how can i use au3 lexer available for my project.

**Comment by JohnyMac** [comment]
@jacobslusser have been adding lexers in a as-requested basis.. If it really was in 2.x then he will most likely move it to the new version as of your request.

**Comment by vinodvinu** [comment]
@JohnyMac , Oh ,that's nice.
