### ISSUE TITLE
Highlighting lines

### ISSUE THREAD

**Issue by jenokizm** [jacobslusser/ScintillaNET#244]
Hey. that does not work (do I need to highlight the lines in two cases
1. those lines where breakpoints do background with red text, so that when you change the line and it covers the new text (VS example)
2. those lines where the cursor is to make the entire string barely gray (Notepad++ example)

I will be very grateful for help!

![vsh](https://cloud.githubusercontent.com/assets/11296510/15682708/a9480f60-2767-11e6-82ec-bdd7f1e4e87d.PNG)

![noteh2](https://cloud.githubusercontent.com/assets/11296510/15682993/dd249794-2768-11e6-9692-7843f4c96414.PNG)

**Comment by Stumpii** [comment]
For number 2, set the ScintillaNET properties. Took me a while to figure it out!

![2016-05-31_14-24-38](https://cloud.githubusercontent.com/assets/13594973/15687668/8721984c-273b-11e6-9be8-a6a1f2490d2e.png)

**Comment by jacobslusser** [comment]
For number 1, use markers: one for the breakpoint circle and another for the background color.

```cs
// Create a symbol margin
scintilla.Margins[1].Type = MarginType.Symbol;

// Define a "breakpoint" marker (0) and background color marker (1)
scintilla.Markers[0].Symbol = MarkerSymbol.Circle;
scintilla.Markers[0].SetForeColor(Color.Red);
scintilla.Markers[0].SetBackColor(Color.Red);
scintilla.Markers[1].Symbol = MarkerSymbol.Background;
scintilla.Markers[1].SetBackColor(Color.Red);

// Add to line 1
scintilla.Lines[1].MarkerAdd(0);
scintilla.Lines[1].MarkerAdd(1);
```

**Comment by jenokizm** [comment]
thanks for answers! love you!
ps although allocated the entire string rather than just text, well, nothing for the first time will go.

**Comment by davidbuckleyni** [comment]
> ```cs
> // Create a symbol margin
> scintilla.Margins[1].Type = MarginType.Symbol;
> 
> // Define a "breakpoint" marker (0) and background color marker (1)
> scintilla.Markers[0].Symbol = MarkerSymbol.Circle;
> scintilla.Markers[0].SetForeColor(Color.Red);
> scintilla.Markers[0].SetBackColor(Color.Red);
> scintilla.Markers[1].Symbol = MarkerSymbol.Background;
> scintilla.Markers[1].SetBackColor(Color.Red);
> 
> // Add to line 1
> scintilla.Lines[1].MarkerAdd(0);
> scintilla.Lines[1].MarkerAdd(1);
> ```

How do u actually cause it to click in the margin when u have line numbers activated as well?
