### ISSUE TITLE
BackColor around text

### ISSUE THREAD

**Issue by tttmack** [jacobslusser/ScintillaNET#245]
I can set the back color of the scintilla control like this: 
scintillaNet1.Styles[Style.Default].BackColor = Color.FromArgb(234, 242, 251);

this looks fine when there is no text in the control, but once I start typing text, the back color around the text is gray. 

How can I have the back color remain consistent, even when text is typed?

**Comment by jacobslusser** [comment]
Make sure the style you're typing in also has the same background color. Chances are you're typing in style `0` (the default). Try:

```cs
scintillaNet1.Styles[Style.Default].BackColor = Color.FromArgb(234, 242, 251);
scintillaNet1.Styles[0].BackColor = Color.FromArgb(234, 242, 251);
```

**Comment by tttmack** [comment]
thank you very much Jacob!
