### ISSUE TITLE
Tooltip

### ISSUE THREAD

**Issue by jenokizm** [jacobslusser/ScintillaNET#246]
How to make that hovering the mouse over some key words show a hint with the description of the word?
for example VS scren

![ashampoo_snap_2016 06 01_19h30m19s_003_](https://cloud.githubusercontent.com/assets/11296510/15850742/5188ee30-2ca2-11e6-8c18-2e4447cf2a45.png)

**Comment by jacobslusser** [comment]
A combination of the dwell event, get word at position, and then user/call tips is the approach I would suggest. You can learn about all of those topics by going through the wiki or past forum posts.

**Comment by jenokizm** [comment]
Thank you. After only a year I returned to this issue) Your approach works, but I get a word incorrectly. Even when the cursor is outside the word far below then take the final word. Also if the cursor is on the right side of the screen, then take the word from this line. I need to get a clear word on the cursor. Look at my code part:
`System.Drawing.Point point = System.Windows.Forms.Control.MousePosition;
        var cor = target.PointToClient(point);
        var pos = target.CharPositionFromPoint(cor.X, cor.Y);
        var word = target.GetWordFromPosition(pos);`

**Comment by jacobslusser** [comment]
I believe if you switch to the `CharPositionFromPointClose` method, it will return `-1` when it is not actually on a valid char (i.e. word) position. Check for `-1` and adjust your logic accordingly.
