### ISSUE TITLE
Why are keywords not highlighting if they have no whitespace after them (and another question)?

### ISSUE THREAD

**Issue by bryanedds** [jacobslusser/ScintillaNET#249]
In my Lisp-Lexer-based text box, keywords don't get highlighted unless they're followed by some form of whitespace, such as a space or newline.

Additionally, I'm finding that negative numbers aren't being highlighted as numbers.

Can I fix either of these issues with some C# code?

Here's the entirety of my control's code -

https://github.com/bryanedds/Nu/blob/master/Nu/Nu/Nu.Gaia.Design/SymbolicTextBox.cs

I don't think I've done anything special that would warrant either of these two issues.

Thanks!

**Comment by jacobslusser** [comment]
I saw that you created a workaround.. which I think is necessary in this case. The lexers that come built-in to Scintilla[NET] are mostly "all or nothing" functionality. If the behavior of the lexer isn't what you expected there is little you can do to influence the behavior.

**Comment by bryanedds** [comment]
Hmm, okay. Not much we can do then!

**Comment by jacobslusser** [comment]
Not unless you want to submit code fixes for the native Scintilla component. :)
