### ISSUE TITLE
Autocompletion and calltips

### ISSUE THREAD

**Issue by KakCAT** [jacobslusser/ScintillaNET#250]
Hi,

I'm trying to display autocompletion at the same time I'm showing calltips. Unless I misunderstood the issue, it seems that Scintilla does not support both at the same time, so I'm trying to lay my own ToolTips to combine them with autocompletion.

Everything is fine but I'm having a problem positioning the tooltip. How can I know in which position (in pixels) a word of the scintilla text is?  I'd like to locate the tooltip above the cursor, but I'm unable to know at which position the cursor is, in pixels

Thanks!

**Comment by jacobslusser** [comment]
`CharPositionFromPoint[Close]`, `PointXFromPosition`, `PointYFromPosition`.

**Comment by KakCAT** [comment]
Everything solved, thanks a lot! :)
