### ISSUE TITLE
[question] Is there a way to make a certain style not selectable/read-only ?

### ISSUE THREAD

**Issue by zhaDeth** [jacobslusser/ScintillaNET#251]
First, I really love this wrapper, thanks a whole lot for this !
Im using it in VB and I found the infos here to do everything I wanted except for this read-only thing.
I don't know if scintilla itself has this kind of feature, I could probably split the selection into multiple ones that goes around the text which is in the style I want to be read-only, but I thought there could be something I missed or a common way to deal with this.

**Comment by jacobslusser** [comment]
No, there is nothing quite like that built-in.
