### ISSUE TITLE
Style margin per line [question]

### ISSUE THREAD

**Issue by larsvoigt** [jacobslusser/ScintillaNET#252]
Hi @jacobslusser, 

the [margins](https://github.com/jacobslusser/ScintillaNET/issues/220)-stuff confuse me a little bit.
Can you help me:
 How can I create a "customized" margin and how can I set a background-style only for e.g. 3 lines.

![margin](https://cloud.githubusercontent.com/assets/8373218/16117712/b48292ce-33d3-11e6-9eb0-304a920715be.PNG)

Thanks Lars

**Comment by jacobslusser** [comment]
After having followed the recipes for [Displaying Line Numbers](https://github.com/jacobslusser/ScintillaNET/wiki/Displaying-Line-Numbers), [Automatic Syntax Highlighting](https://github.com/jacobslusser/ScintillaNET/wiki/Automatic-Syntax-Highlighting), and [Automatic Code Folding](https://github.com/jacobslusser/ScintillaNET/wiki/Automatic-Code-Folding), I then added the following code:

```cs
scintilla.Margins[1].Width = 4;
scintilla.Margins[1].Type = MarginType.Symbol;

scintilla.Markers[0].Symbol = MarkerSymbol.FullRect;
scintilla.Markers[0].SetBackColor(Color.FromArgb(108, 226, 108)); // Green

scintilla.Markers[1].Symbol = MarkerSymbol.FullRect;
scintilla.Markers[1].SetBackColor(Color.FromArgb(255, 238, 98)); // Yellow

for (int i = 80; i < 90; i++)
{
    // Green
    scintilla.Lines[i].MarkerAdd(0);
}

for (int i = 90; i < 95; i++)
{
    // Yellow
    scintilla.Lines[i].MarkerAdd(1);
}
```

This sets up Margin `1` for use as my 'change tracking' margin and I've configured two markers (`0` and `1`) for displaying the green and yellow change indicators. Each marker is set to use a symbol that fills the entire margin area with a solid color.

The result is this:

![image](https://cloud.githubusercontent.com/assets/345183/16174264/5b5d80f8-356f-11e6-84d6-ecdbb7fc00df.png)

**Comment by larsvoigt** [comment]
Thanks @jacobslusser. Excellent.  It does exactly what it is supposed to do.

**Comment by larsvoigt** [comment]
Sorry I need to reopen this issue. Now the real question ;-).

How can I set the marker to a specifc margin?
The result should follow this margin config: 

```c#
// linenumber I know it will sets per default 
scintilla.Margins[0]
// my "change tracking" margin
scintilla.Margins[1]
// my bookmark margin 
scintilla.Margins[2]
```
``` MarkerAdd() ``` adds always my  "change tracking" -marker and the bookmarker-marker
to same ``` margin[1]```.

What's  wrong?

Thanks Lars

**Comment by jacobslusser** [comment]
Ya, Scintilla didn't make this easy...

What you have to do is set the margin mask so that it will only show the markers you want it to. So using your existing example, you might have something like this:

```cs
scintilla.Margins[1].Mask = (0 | 1); // Because we want to see only markers 0 and 1
scintilla.Margins[2].Mask = 2; // Because we want to see only marker 2
// etc...
```

Margin `0` in your example doesn't need a mask because it is not a symbol margin, it is a line number margin based on the `Margin.Type` property.

**Comment by larsvoigt** [comment]
Ahh it is a scintilla legacy. 
Now  based your instruction I could relasise my intention.
I hope that I can really close the issue now :+1:  
Thanks @jacobslusser!

**Comment by Mudr0x** [comment]
I'm coming late but is there a way to override MarginSetStyle() even for margin number?
