### ISSUE TITLE
Event ZoomChanged

### ISSUE THREAD

**Issue by AndreySakun** [jacobslusser/ScintillaNET#253]
In my application I show line numbers. But ScintillaNet allows to change zoom  with Ctrl+scroll. After this a part of line number could be hidden. With ScintillaNet 2.x I can receive ZoomFactorChanged event, calculate new margin width and update it. With ScintillaNet 3.x I do not have this possibility.

Is it possible to add additional event ZoomChanged like in previous version 2.x?

**Comment by AndreySakun** [comment]
This is no longer necessary. I found a solution:

```
private void init()
{
	...
	scintilla.MouseWheel += new MouseEventHandler(scintilla_MouseWheel);
	...
}
private void scintilla_MouseWheel(object sender, MouseEventArgs e)
{
	if (_ctrlPushed)
		 updateMarginForNumbers();
}
private void scintilla_KeyDown(object sender, KeyEventArgs e)
{
	if (e.Control == true)
		_ctrlPushed = true;
}
private void scintilla_KeyUp(object sender, KeyEventArgs e)
{
	if (e.KeyCode == Keys.Control)
		_ctrlPushed = false;
}
```

**Comment by jacobslusser** [comment]
Glad you got something worked out. For good measure I also added the `ZoomChanged` event.
