### ISSUE TITLE
Is it possible to drag and drop selected text within the control?

### ISSUE THREAD

**Issue by lexkazakov** [jacobslusser/ScintillaNET#256]
I'm trying to enable dragging the selected text within the control using the following code (inspired by issue #6 ):
```
private void Editor_DragEnter(object sender, DragEventArgs e) {
	e.Effect = DragDropEffects.Move;
}
private void Editor_DragDrop(object sender, DragEventArgs e) {
	editor.InsertText(editor.CharPositionFromPoint(e.X, e.Y), editor.SelectedText);
}
```

But no results. Can you please help me with this stuff?

**Comment by lexkazakov** [comment]
I've resolved the issue by building ScintillaNET with the commented [NativeMethods.RevokeDragDrop(Handle)](https://github.com/jacobslusser/ScintillaNET/blob/master/src/ScintillaNET/Scintilla.cs#L1605) line of code. 

What kind of problems should I expect after such a workaround?

**Comment by jacobslusser** [comment]
My recollection of the issues is that we could get either the "in-control" drag/drop or "control-control" drag/drop to work, but not both at the same time. I believe commenting out that line will restore the native Scintilla control's built-in handling of drag and drop which will allow selected text to be moved around, but you may break drag/drop (events) between controls.

**Comment by jenokizm** [comment]
Hi, I have the same problem. Rebuild the library I do not want without commented line(
Are there any other solutions?

**Comment by jenokizm** [comment]
I understood what was happening. The library does not correctly determine the coordinates, we need not global but local. That's how works:
`var cor = sci1.PointToClient(new Point(e.X, e.Y));
            var pos = sci1.CharPositionFromPoint(cor.X, cor.Y);
            var char1 = sci1.GetCharAt(pos);
            sci1.InsertText(pos, name);`
There is a new question, how do you move to when the carriage is moved and showed a specific place inserts? (For example, see a video netepad++)
