### ISSUE TITLE
[Question] How do I get Scintilla on to a form?

### ISSUE THREAD

**Issue by SteveBarnettTF** [jacobslusser/ScintillaNET#257]
I've installed Scintilla in to a project using NuGet and it appears to be installed correctly. I see the ScintillaNet.dll in the packages folder and I have a reference to it in my project. I then added Scintilla to my toolbox by right clicking on the toolbox, selecting choose items and browsing to the ScintillaNet dll. 

The icon appears in the toolbox.

When I drag it on to a form, I get this error:

**Failed to create component 'Scintilla'.  The error message follows:
 'System.ComponentModel.Win32Exception (0x80004005): Could not load the Scintilla module at the path 'C:\Users\--uername--\AppData\Local\Temp\ScintillaNET\3.5.6\x86\SciLexer.dll'. ---> System.ComponentModel.Win32Exception (0x80004005): A dynamic link library (DLL) initialization routine failed

   at ScintillaNET.Scintilla.get_CreateParams()
   at System.Windows.Forms.Control..ctor(Boolean autoInstallSyncContext)
   at ScintillaNET.Scintilla..ctor()'**

Any suggestions as to what might be wrong? I've compiled the solution for "Any CPU", "x86" and "x64" and get the same error. I wondering whether its a permission issue with the dll being unpacked to a temp folder when I try to add the control.

I'm using VS2015 and Scintilla 3.5.6

**Comment by jacobslusser** [comment]
Ya, so the nuget packages don't automatically put controls in the toolbox for you... and I think your problem may be from doing that manually. Try removing the toolbox item you created and any references to Scintilla VS added to your designer file and close VS. Then reopen VS and make sure your project compiles without Scintilla.

Now here is the silly part that I do when I don't have an item in the toolbox. I just add a standard control like a Panel to the designer then modify the designer file and replace the System.Windows.Forms.Panel with ScintillaNET.Scintilla wherever "panel1" is used. When the designer refreshes you should now have a Scintilla control instead of a Panel control.

For all other times you need it going forward after that, just copy and paste the control in the designer.

**Comment by SteveBarnettTF** [comment]
Thanks for that. My solution compiles fine without Scintilla and I’ve tried adding a panel to the form and changing it to ScintillaNet.Scintilla. Syntactically, it’s fine. When I try to pen the form, I get:


A dynamic link library (DLL) initialization routine failed


And the form won’t open. I’m guessing this is the same error I was getting dragging from the toolbox.

Steve

**Comment by SteveBarnettTF** [comment]
If it helps, I can see the Scintilla folder created in my temp folder and it contains a single dll called SciLexer.dll. The path it's creating is 

C:\Users\--username--\AppData\Local\Temp\ScintillaNET\3.5.6\x86

Not sure why it's creating an x86 folder.

**Comment by jacobslusser** [comment]
The SciLexer.dll is copied out of the ScintillaNET.dll and placed in your temp folder and then loaded. The reason it is using x86 is because Visual Studio is a 32-bit process and thus would need the x86 version.

I'm not certain what is causing your problem. Clearly the file is there, it's just not being loaded.

It's possible there is a permissions issue and VS can't access the temp folder although I think that might be unlikely...

It's also possible issue #173 could be your problem.

**Comment by SteveBarnettTF** [comment]
Yep, that's my problem. I found the offending reference in a Telerik extension, renamed the files and can now add ScintillaNET to the project and a form. Sadly, my Visual Studio environment also requires Telerik components for other projects, so I can't just get rid of it. 

Shame, I've always liked ScintillaNET, it's just so easy to use.

Thanks for the assistance.

**Comment by jacobslusser** [comment]
Maybe with time we could find a way to make ScintillaNET play nice with other components that also use SciLexer.dll...

It's worth pointing out though that it doesn't mean you can't use ScintillaNET with your project. It just means your VS designer will have issues, but runtime should be unaffected.

Which Telerik component was it so other users will know what to look for?

**Comment by SteveBarnettTF** [comment]
The extension is a tool we use for debugging. We have some complex object structures and viewing them in Visual Studio is a bit of a pain. So we use an extension by Omar Elabd called Object Exporter. It allows you to export an object graph to an XML file for inspection:

https://github.com/OmarElabd/ObjectExporter

It’s a very useful tool – I’d struggle to prise it out of the hands of some of our developers. I suppose it might be possible to approach Omar and ask him to use a newer version of Scintilla (he’s using version 2.6.0.0) but it doesn’t fix the fundamental incompatibility and we may hit it again with another extension.

Maybe, if I can get the time, I’ll get the Scintilla source out and see if I can do anything to handle it. Though I doubt getting my head round Scintilla is going to be a 5 minute job!

Steve

**Comment by SteveBarnettTF** [comment]
FWIW I've got it on to a form in design mode. Its not perfect, but it's there and I can set the properties I need in code.

I updated the constructor in Scintilla.cs to 

`
                 if (moduleHandle == IntPtr.Zero)
                {
                    var path = GetModulePath();

                    // Load the native Scintilla library
                    moduleHandle = NativeMethods.LoadLibrary(path);

                    if (moduleHandle == IntPtr.Zero)
                    {
                        var winError = NativeMethods.GetLastError();

                        // We will get error 1114 if we're in design mode and the 
                        // library is lready loaded. We can relatively safely ignore it.
                        if (winError != 1114)
                        {
                            var message = string.Format(CultureInfo.InvariantCulture,
                                "Could not load the Scintilla module at the path '{0}'.",
                                path);
                            throw new Win32Exception(message, new Win32Exception()); // Calls GetLastError
                        }
                    }
                    else
                    {
                        // Get the native Scintilla direct function -- the only function the library exports
                        var directFunctionPointer = NativeMethods.GetProcAddress(new HandleRef(this, moduleHandle), "Scintilla_DirectFunction");
                        if (directFunctionPointer == IntPtr.Zero)
                        {
                            var message = "The Scintilla module has no export for the 'Scintilla_DirectFunction' procedure.";
                            throw new Win32Exception(message, new Win32Exception()); // Calls GetLastError
                        }

                        // Create a managed callback
                        directFunction = (NativeMethods.Scintilla_DirectFunction)Marshal.GetDelegateForFunctionPointer(
                            directFunctionPointer,
                            typeof(NativeMethods.Scintilla_DirectFunction));
                    }
                }
`

This just detects the library load error, which is 1114. To support that, I needed a new definition in NativeMethods:

`        [DllImport("kernel32.dll")]

        public static extern uint GetLastError();`

That mostly works, except that directFunction is now null. I changed the DirectMessage method to cope with that:

`        private static IntPtr DirectMessage(IntPtr sciPtr, int msg, IntPtr wParam, IntPtr lParam)
        {
            // Like Win32 SendMessage but directly to Scintilla
            if (directFunction == null) return (IntPtr)0;

            var result = directFunction(sciPtr, msg, wParam, lParam);
            return result;
        }`

And lo, the control appears on a form. It's not perfect, but it gives me a design time component without the crash if there are extensions that use the Scilexer dll.

Now all I have to do is work out how to get highlighting working! I load an XML file but it doesn't highlight unless I define  bunch of styles - I thought those were built in...

Hope this helps someone.
