### ISSUE TITLE
MouseDown event not triggered on ScintillaNet scrollbars

### ISSUE THREAD

**Issue by tttmack** [jacobslusser/ScintillaNET#258]
I need to handle the MouseDown event of a ScintillaNet control. It works fine in the text editing portion of the control, but is not triggered when the scrollbars are clicked.

There are also no child scrollbar controls that I can access via the ScintillaNet properties so I can't do something like:
scintilla1.HScrollBar.MouseDown += Scintilla_MouseDown;

Any suggestions how I can achieve this or can this functionality be added?
Thanks so much!

**Comment by zhaDeth** [comment]
In VB.NET (tho I guess its the same in C#), the mouse_move event still fires when the mouse is over the scrollbar and using its arguments it is possible to which mouse buttons are pressed. If you need to know if it is over the erm.. "moving part of the scrollbar", I guess you could calculate its rectangle from the number of lines in the documents, the control size and the first shown line.. altho I bet jacobslusser has a better less-hack idea in mind.

**Comment by jacobslusser** [comment]
Scintilla[NET] doesn't make use of the ScrollBar control. In Windows, it's possible to add scrollbars to any control simply by setting the right options when the control is created. Controls with that type of scrollbar, like Scintilla[NET], are completely handled by Windows and not as independent controls. When done this way, the scrollbars exist outside the normal control bounds in what's called the non-client area. Regular mouse events don't get raised for content outside of the client area. That's a bit of gross oversimplification, but that's the gist of it.

But all hope is not lost. If you are feeling adventurous, you should Google and learn everything that you can about the `WM_NCHITTEST` window message. This is a low-level message that you can listen for which could/should tell you about mouse clicks in the "NC", i.e. "non-client" area.

**Comment by tttmack** [comment]
thanks for the explanation. In the end, handling the scroll events was good enough for what I needed to do and I found that I could do them in the UpdateUI event.

private void ScintillaControl_UpdateUI(object sender, UpdateUIEventArgs e)
{
	if (e.Change == UpdateChange.VScroll || e.Change == UpdateChange.HScroll)
	{
		...
	}
}
