### ISSUE TITLE
Add BASIC auth helper page

### ISSUE THREAD

**Issue by jeremyh3** [jacobslusser/ScintillaNET#259]
Thanks for the great product, it is proving useful.  It would be nice though to be able to put in username + password when doing basic authorization header and have it handle the base64 encoding automatically.

**Comment by jacobslusser** [comment]
That's a very specific application need that can't/wont be handled by ScintillaNET. It should be pretty easy though for you to implement. Just monitor the `CharAdded` or some other event and continually parse the line looking for a Authorization header and if found, transpose the entered text for the Base64 version.
