### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by theryan722** [jacobslusser/ScintillaNET#260]
Hey I know I went quiet for quite a while, but I recently decided to publish one of my longtime projects to Github, a text editor powered by ScintillaNET. If you're interested at all, you can view it [here.](https://github.com/theryan722/XDev-Studio) I'm also planning on making a few more contributions to ScintillaNET in the future sometime.

**Comment by jacobslusser** [comment]
Looks good. Thanks for sharing.
