### ISSUE TITLE
Iterate through indicators in a specific range

### ISSUE THREAD

**Issue by Rafeethu** [jacobslusser/ScintillaNET#261]
Hi,

i need to iterate through indicators in a specific **range only**. not the whole document. i tried setting indicator.Start and indicator.End but it's returning related to whole document.

is there any other property to set? Please advice.

Regards,
Rifky

**Comment by OrkhanAlikhanov** [comment]
you mean like this?
```
var myRange = new[] { 1, 4, 6, 2, 3 };

foreach (var index in myRange)
{
    this.Indicators[index]
}
```

**Comment by Rafeethu** [comment]
No. I want to to check whether an indicator is available in a specific text range. 

eg: the whole text length in 500 characters. i want to check the indicator[8] is add in text index from 100 to 200.

**Comment by OrkhanAlikhanov** [comment]
Maybe [this](https://github.com/jacobslusser/ScintillaNET/blob/master/src/ScintillaNET/Indicator.cs#L80)?
`int ValueAt(int position)`

**Comment by Rafeethu** [comment]
I think the better way to do is using [Indicators iteration mentioned in the doc](https://github.com/jacobslusser/ScintillaNET/blob/master/docs/sections/indicators.md#navigating-indicators). but here that's iterated as indicator blocks for whole doc. any way to iterate for a text range.

is my question clear enough?

**Comment by jacobslusser** [comment]
Using the techniques described in the guide [you linked](https://github.com/jacobslusser/ScintillaNET/blob/master/docs/sections/indicators.md#navigating-indicators), it should be very easy to adjust the start and end positions to a specific range of text. Just change the `startPos` and `endPos` initial values from `0` to your start position and change `textLength` to your end position.
