### ISSUE TITLE
Adding new language to ScintillaNET

### ISSUE THREAD

**Issue by AleksandraTosic** [jacobslusser/ScintillaNET#262]
Is there any way to add a custom language to ScintillaNET? I'm trying to add a assembly looking language, but I'm not sure if I'm doing it the right way, so I want to check...

**Comment by markomiljkovic** [comment]
It is very easy just go ask your collegue Marko . He knows everything

**Comment by jacobslusser** [comment]
The Wiki is your friend.

**Comment by AleksandraTosic** [comment]
That's where I had a problem, I read the whole wiki several times, but I'm still not able to add a new language...I tried adding the language to Lexer.cs, NativeMethods.cs and Style.cs, but when I try to use it - nothing gets colored... 

            scintilla.StyleResetDefault();
            scintilla.Styles[Style.Default].Font = "Consolas";
            scintilla.Styles[Style.Default].Size = 10;
            scintilla.StyleClearAll();

            scintilla.Lexer = Lexer.Macro;

            scintilla.Styles[Style.Macro.Keywords].ForeColor = Color.Blue;
            scintilla.Styles[Style.Macro.Preprocessor].ForeColor = Color.BlueViolet;
            scintilla.Styles[Style.Macro.Operators].ForeColor = Color.Red;
            scintilla.Styles[Style.Macro.Number].ForeColor = Color.Plum;
            scintilla.Styles[Style.Macro.Comment].ForeColor = Color.Green;
            scintilla.Styles[Style.Macro.Stings].ForeColor = Color.Honeydew;
            scintilla.Styles[Style.Macro.Char].ForeColor = Color.GreenYellow;
            
            scintilla.SetKeywords(0, "some keywords");
            scintilla.SetKeywords(1, "some more keywords");

This is how the language looks like and how I'm using it...and I don't where I'm wrong... Do I need to change something else , or add something else somewhere in the library? Thank you in advance!

**Comment by markomiljkovic** [comment]
http://www.scintilla.org/Lexer.txt

**Comment by markomiljkovic** [comment]
https://www.youtube.com/watch?v=y8EEQrZBKoc

**Comment by jacobslusser** [comment]
Okay, sorry, I should explain more. The setup you have here would work for a lexer that is already built into Scintilla. Those lexers can be configured with the `Style.*` constants and `Lexer.*` enumeration, etc...

If you are looking to do syntax highlighting for a custom language, not already built into Scintilla, then you need to write a lexer. That process is explained [Custom Syntax Highlighting](https://github.com/jacobslusser/ScintillaNET/wiki/Custom-Syntax-Highlighting) recipe.

**Comment by AleksandraTosic** [comment]
I see now, thank you for help and keep up with the amazing work. ^^
