### ISSUE TITLE
Saving from `Document` class

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [jacobslusser/ScintillaNET#263]
How can I save `Document` into file without _assigning_ it to `Scintilla` component and reading from `Scintilla.Text` property?

I looked into `Document` class and it turned out that the class stores data in `IntPtr Value` which is _unmanaged_ `Document` class data. 
However I dived into Scintilla itself and found out that the _unmanaged_ `Document` class has BufferPointer() method which returns pointer to char array.
`Document -> CellBuffer -> SplitVector<char> -> char*`

**Comment by jacobslusser** [comment]
The document class is not meant to be handled outside of a Scintilla control. Trust me, I'm just as disappointed as you are. The benefits a document brings are that you can load data into it prior to assigning it to a control, you can use them to easily switch the contents of a control, but that's about it. For example, there is no function for modifying a document, saving a document, or doing things like formatting and highlighting of a document outside of a Scintilla control.

**Comment by OrkhanAlikhanov** [comment]
Then how people save all open documents without switching current open document? Do they just create an invisible `new Scintilla` and do all stuff on it?

Unfortunately, SciTE does not provide SaveAllBuffers, just opened one and uses SCI_GETCHARACTERPOINTER to read data.

**Comment by jacobslusser** [comment]
That's a good point actually. I've never thought about it but you're right. A hidden control might be the way to go.

From the Scintilla documentation you can see that there is no other form of background saving. The document has to be attached to a control (which I would argue isn't background saving at all...).

[http://www.scintilla.org/ScintillaDoc.html#BackgroundLoadSave](http://www.scintilla.org/ScintillaDoc.html#BackgroundLoadSave)

**Comment by OrkhanAlikhanov** [comment]
What about coding an extension(static) class which is fundamentally based on native `Scintilla` but implements **only** document related features such as content of document, whether document is dirty and so on. I mean should ignore unnecessary messages,  no need to store redundant data on memory only those for document.

**Comment by OrkhanAlikhanov** [comment]
Or something like this?
```
    public class CustomDocument
    {
        private static Scintilla HiddenScintilla = new Scintilla()
        {
            Visible = false
        };

        private Document doc;
        private void setDoc()
        {
            if (HiddenScintilla.Document == doc) return;
            HiddenScintilla.Document = doc;
            HiddenScintilla.ReleaseDocument(doc);
        }

        public CustomDocument(Document doc)
        {
            this.doc = doc;
        }
        public static explicit operator Document(CustomDocument custom)
        {
            return custom.doc;
        }

        public bool Modified
        {
            get
            {
                setDoc();
                return HiddenScintilla.Modified;
            }
        }
        public string Text
        {
            get
            {
                setDoc();
                return HiddenScintilla.Text;
            }
        }
        public void SaveToFile(string path, Encoding encoding, bool setSavePoint)
        {
            setDoc();
            File.WriteAllText(path, HiddenScintilla.Text, encoding);
            if (setSavePoint) HiddenScintilla.SetSavePoint();
        }
    }
```

**Comment by jacobslusser** [comment]
The thought has actually crossed my mind, but the goal of ScintillaNET v3.x is to be as close to the original Scintilla API as possible. Feel free though to implement such a feature and provide it as a ScintillaNET extension.

**Comment by jacobslusser** [comment]
P.S. Just a reminder that the general rule of working with any control is that it should always be done on the UI thread. So while this may give the appearance of document separation from the control, it would be of limited usefulness if it couldn't be run safely on a background thread. Just a thought...
