### ISSUE TITLE
Release Query

### ISSUE THREAD

**Issue by wesleywerner** [jacobslusser/ScintillaNET#264]
Hi, may I ask when can we can expect the next release? I'm asking mainly out of selfish reasons, three months ago I moved from building from source, to using the Nuget package, and I am pretty keen to use some of the new features, like #143 (Exposed the WordChars property).

I could use a `DirectMessage` call for the meantime, but thought it prudent to ask anyway.

Many thanks for a great project!

**Comment by jacobslusser** [comment]
Working on it...

**Comment by jacobslusser** [comment]
Done.
[https://github.com/jacobslusser/ScintillaNET/releases/tag/v3.5.10](https://github.com/jacobslusser/ScintillaNET/releases/tag/v3.5.10)

Thanks for being patient. It's easy to lose track of time between releases...

**Comment by wesleywerner** [comment]
Awesome, Thanks for the work, we really appreciate it :+1:
