### ISSUE TITLE
Styles defintion issue

### ISSUE THREAD

**Issue by ClarkLaneman** [jacobslusser/ScintillaNET#265]
I have a problem with the styles defintion.
I thought it is possible to define a style for every lexer, just like this:

```c#
private void configLexerStyles()  {
     //XML-Style
     textBox_SCI.Styles[Style.Xml.Tag].ForeColor = ColorTranslator.FromHtml("#881280");
     textBox_SCI.Styles[Style.Xml.Attribute].ForeColor = ColorTranslator.FromHtml("#994500");
     textBox_SCI.Styles[Style.Xml.Value].ForeColor = ColorTranslator.FromHtml("#1A1AA6");

     //LUA - Style
     textBox_SCI.Styles[Style.Lua.Comment].ForeColor = ColorTranslator.FromHtml("#008000");
     textBox_SCI.Styles[Style.Lua.CommentLine].ForeColor = ColorTranslator.FromHtml("#008000");
     textBox_SCI.Styles[Style.Lua.CommentDoc].ForeColor = ColorTranslator.FromHtml("#008000");
}
```

When i start my app and define the "textBox_SCI.Styles[Style.Xml.Tag].ForeColor" it gets later overriden by the "textBox_SCI.Styles[Style.Lua.Comment].ForeColor".

Is this a bug or is it working as intended?

**Comment by jacobslusser** [comment]
This is working as intended. Style definitions are not per-lexer.

**Comment by OrkhanAlikhanov** [comment]
That's because both constants, `Style.Xml.Tag` and `Style.Lua.Comment`, have exact same value `1`.
You have to set styles when you need and then specify lexer.
