### ISSUE TITLE
Text BackColor don't change

### ISSUE THREAD

**Issue by denoide** [jacobslusser/ScintillaNET#266]
i've set the default style back color on Color.Grey but the color behind the text remains white
there is a method for change it?

**Comment by OrkhanAlikhanov** [comment]
You have to iterate through all needed styles and set the back color for each one of them. 

Alternatively, let scintilla itself do this:
```CSharp
scintilla.Styles[Style.Default].BackColor = Color.Gray;
scintilla.StyleClearAll();
```
