### ISSUE TITLE
AppendText method doesnt work inside InsertCheck event

### ISSUE THREAD

**Issue by timopomer** [jacobslusser/ScintillaNET#268]
Its completely ignored. 

I figured there is a way to circumvent it using Queues and timers but it should at least throw an exception

**Comment by jacobslusser** [comment]
`AppendText` is not the only one... Virtually all text modification methods will not work within the `InsertCheck` event handler. To throw exceptions on all of them is not only impractical it would also break with our [conventions for exception handling](https://github.com/jacobslusser/ScintillaNET#conventions).

The only operation supported in the `InsertCheck` event is through the `InsertCheckEventArgs`. [https://github.com/jacobslusser/ScintillaNET/wiki/Intercepting-Inserted-Text](https://github.com/jacobslusser/ScintillaNET/wiki/Intercepting-Inserted-Text)
