### ISSUE TITLE
Enumerate key bindings Question

### ISSUE THREAD

**Issue by graceware** [jacobslusser/ScintillaNET#269]
Is there a way of populating a list or enumerating all of the known Scintilla key bindings? I'd like to generate a dialog where the user can scroll through them all and change at will. I would of course take care of key conflicts...

**Comment by jacobslusser** [comment]
Unfortunately no. I've wondered the same thing myself.

The next best thing is the list found in the Scintilla source:
[https://sourceforge.net/p/scintilla/code/ci/default/tree/src/KeyMap.cxx](https://sourceforge.net/p/scintilla/code/ci/default/tree/src/KeyMap.cxx)
