### ISSUE TITLE
[Question] Caret when the control is not focused

### ISSUE THREAD

**Issue by zhaDeth** [jacobslusser/ScintillaNET#271]
Is there a way to have the caret still visible when the control is not in focus ? I want have a list control that the user can double-click to paste the selected list item text into the scintilla control at the current position, it works alright, but with the caret beign invisible there is nothing that shows where it will be pasted.

**Comment by jenokizm** [comment]
hello, I subscribe to the issue. But most of all I would like to caret was visible while dragging.

**Comment by jacobslusser** [comment]
A similar question and possible workaround has been asked in issue #256. See if the proposed fix works for you.

[https://github.com/jacobslusser/ScintillaNET/issues/256#issuecomment-229441670](https://github.com/jacobslusser/ScintillaNET/issues/256#issuecomment-229441670)
