### ISSUE TITLE
Incorrect release notes

### ISSUE THREAD

**Issue by dail8859** [jacobslusser/ScintillaNET#272]
The release notes for [v3.5.10](https://github.com/jacobslusser/ScintillaNET/releases/tag/v3.5.10) states:

> Updated native SciLexer DLLs to version 3.3.6 (latest).

I'm assuming this should be:

> Updated native SciLexer DLLs to version **3.6.6** (latest).

**Comment by jacobslusser** [comment]
You are correct. Good catch. I've updated the release notes.

Thanks.
