### ISSUE TITLE
FoldAll() only folds top level

### ISSUE THREAD

**Issue by lafrank** [jacobslusser/ScintillaNET#273]
Am I doing soemthin wrong or is it intentional that FoldAll() only folds top level foldings ? 
I found that the below code effectively folds all levels :
```c#
foreach (Line thisLine in tbPyScriptCode.Lines) thisLine.FoldLine(FoldAction.Contract);
```
At the same time, FoldAll(FoldAction.Expand) does unfold all levels. So why does it not fold all levels ?

**Comment by jacobslusser** [comment]
You can read about `FoldAll` in the original Scintilla documentation here: [http://www.scintilla.org/ScintillaDoc.html#SCI_FOLDALL](http://www.scintilla.org/ScintillaDoc.html#SCI_FOLDALL).

As I understand it, your observations match the documentation. `FoldAll` will not affect child folds. 

You might be able to enhance your workaround above by switching to `thisLine.FoldChildren(FoldAction.Contract);`

**Comment by lafrank** [comment]
Thank you for the quick answer.
