### ISSUE TITLE
CurrentPosition Changed

### ISSUE THREAD

**Issue by jenokizm** [jacobslusser/ScintillaNET#274]
Hello, it would be superfluous to add to the next version of the event changes the cursor position in the text)

**Comment by OrkhanAlikhanov** [comment]
I reckon we can get it from `UpdateUI` event.
See [Updating Dependent Controls](https://github.com/jacobslusser/ScintillaNET/wiki/Updating-Dependent-Controls)

**Comment by jenokizm** [comment]
if i using https://github.com/jacobslusser/ScintillaNET/wiki/Updating-Dependent-Controls snippet
my mouse cursor glitch(

**Comment by OrkhanAlikhanov** [comment]
I didn't get what you said.
You want an event fire when mouse pointer changes position or caret?

**Comment by jenokizm** [comment]
OrkhanAlikhanov, русский знаешь наверное?
нет, я хочу сказать что UpdateUI event глючный и его использование приводит к тому что поток окна подтрормаживает, но самое главное визуальный курсор мыши беспорядочно меняется)
а так нужную мне задачу этот сниппет решает.

**Comment by jacobslusser** [comment]
Closing this item for lack of useful information...

**Comment by egkareem** [comment]
I  want an event  to fire when mouse pointer changes position or caret. I am usiing the Demo project. When I code:

	private void OnMouseMove(object sender, EventArgs e)
		{
		}
It does not fire.
Also this event does not fire:

```
private void TextPanel_MouseMove(object sender, MouseEventArgs e)
        {

        }
```

Thanks.
