### ISSUE TITLE
Setter for Scintilla.SelectedText is missing!

### ISSUE THREAD

**Issue by StavrosDimou** [jacobslusser/ScintillaNET#276]
Hello and thank you for Scintilla.
I found out that the .SelectedText's 'set' property is missing from the Scintilla control.
![scintillanoset](https://cloud.githubusercontent.com/assets/21987972/18717176/d00703f4-8027-11e6-8f51-94776431f25b.PNG)
It can be usefull in a number of situations.

**Comment by JohnyMac** [comment]
IDK why he didn't add it but see issue #53 . he told a workaround.

**Comment by StavrosDimou** [comment]
Thanks!
