### ISSUE TITLE
Automatically Highlight all occurrences of selected word

### ISSUE THREAD

**Issue by poloab** [jacobslusser/ScintillaNET#277]
Hi, I'd like to highlight all ocurrences os selected word automatically, it is implemented in scintillanet?
If not, any sugestion how can I implment it?

I am migrating from 2.6 version.
so in 2.6 when we have to save the file, we have to change `scintilla.Modified = false`, in version 3.x it is not necesary?

And how can I replace this 2.6 function in 3.x?

`public static void StyleNeeded(Scintilla scintilla, Range range)
{
       IniLexer lexer = new IniLexer(scintilla, range.Start, range.StartingLine.Length);
       lexer.Style();
}`

Thank you for your work.

**Comment by jacobslusser** [comment]
[https://github.com/jacobslusser/ScintillaNET/wiki/Find-and-Highlight-Words](https://github.com/jacobslusser/ScintillaNET/wiki/Find-and-Highlight-Words)

**Comment by jacobslusser** [comment]
[https://github.com/jacobslusser/ScintillaNET/wiki/Custom-Syntax-Highlighting](https://github.com/jacobslusser/ScintillaNET/wiki/Custom-Syntax-Highlighting)

**Comment by jacobslusser** [comment]
[https://github.com/jacobslusser/ScintillaNET/blob/master/src/ScintillaNET/Scintilla.cs#L4361-L4374](https://github.com/jacobslusser/ScintillaNET/blob/master/src/ScintillaNET/Scintilla.cs#L4361-L4374)
[https://github.com/jacobslusser/ScintillaNET/blob/master/src/ScintillaNET/Scintilla.cs#L2320-L2327](https://github.com/jacobslusser/ScintillaNET/blob/master/src/ScintillaNET/Scintilla.cs#L2320-L2327)
[https://github.com/jacobslusser/ScintillaNET/blob/master/src/ScintillaNET/Scintilla.cs#L5920-L5938](https://github.com/jacobslusser/ScintillaNET/blob/master/src/ScintillaNET/Scintilla.cs#L5920-L5938)
[https://github.com/jacobslusser/ScintillaNET/blob/master/src/ScintillaNET/Scintilla.cs#L5940-L5958](https://github.com/jacobslusser/ScintillaNET/blob/master/src/ScintillaNET/Scintilla.cs#L5940-L5958)

**Comment by poloab** [comment]
Thank you for your help, I finished migrating to 3.x, and implemented highlight of selected string with your sugestions.

Thank you.

**Comment by poloab** [comment]
I like the 3.x version, I added printing function by copying functions, some structures ans directMessages from 2.6 and it works well.

tahk you one more time for your time and work.

**Comment by jacobslusser** [comment]
Glad to hear it.

P.S. Some others were asking about printing functions and I haven't had time to implement them. See issues #232, #139 and #68. If you have any code to share I'm sure it would be appreciated.

**Comment by poloab** [comment]
b
