### ISSUE TITLE
Set CallTip Border Color

### ISSUE THREAD

**Issue by h3tch** [jacobslusser/ScintillaNET#278]
I know it is possible to set ForeColor and BackColor of a CallTip via
`((Scintilla)this).Styles[Style.CallTip].ForeColor = Color.Gray; // text color`
`((Scintilla)this).Styles[Style.CallTip].BackColor = Color.Black; // background color`

However, this does not change the color of the CallTip border.
Is there a way to do that?

Thanks!

**Comment by jacobslusser** [comment]
Short answer, no.
