### ISSUE TITLE
Changing the margin back color

### ISSUE THREAD

**Issue by hgupta9** [jacobslusser/ScintillaNET#279]
How do I change the background color of the number margin? I figured how to set the selection color (back/fore) and how to configure a lexer to get syntax coloring for various keywords, etc. But for the life of me there is no setting for margin color. The previous ScintillaNET had a simple property but this has none. 

My default style is configured with White as ForeColor and Black and BackColor. The font is still consolas and other stuff given in the recipe.

Things I tried: (none of these work)

- `scintilla.*`
- `scintilla.Styles[Style.Cpp.*]`
- `scintilla.Styles[Style.Cpp.TaskMarker].BackColor`
- `scintilla.Margins[0].*`
- `scintilla.Markers[0].*`
- `scintilla.Markers[0].SetBackColor(x)`

![scintilla](https://cloud.githubusercontent.com/assets/6797866/18881431/df1f8188-84f8-11e6-9548-c226320ed225.png)

**Comment by jacobslusser** [comment]
See issue #220.

And please remember to search the issues list and wiki before asking questions.

**Comment by hgupta9** [comment]
So Sorry. Will run search the next time.

**Comment by hgupta9** [comment]
Ok I figured it out. You have to set the styling AFTER you call StyleClearAll();`

**Comment by jacobslusser** [comment]
FYI [ScintillaNET v3.6.3](https://github.com/jacobslusser/ScintillaNET/releases) brings support for additional margins beyond the limit of 5 and support for more background color options.

**Comment by hgupta9** [comment]
Cool! Thanks for the info.
