### ISSUE TITLE
Identify if text is multi line

### ISSUE THREAD

**Issue by pjlasl** [jacobslusser/ScintillaNET#28]
Hi, 

Thank you for continuing the development of this great control! I am in the process of updating the control from 2 to 3 and have encountered numerous changes (most of which I have corrected). 

I do have a bit of code that I cannot find a solution for. I would like to know if the selected text is multiline.

Here is my old code:
```vb
Dim rng As ScintillaNET.Range = ActiveDocument.txtQuery.Selection.Range

        If rng.IsMultiLine Then
            rng.Text = "/*" & rng.Text & "*/"
        Else
            rng.Text = "--" & rng.Text
        End If
```

Unfortunately, version 3 does not have a Range object or a isMultiLine property.

Is there a solution for this in version 3?

**Comment by jacobslusser** [comment]
No, there isn't an equivalent property (yet) in ScintillaNET v3. I'll see about adding one. Until then you can use this helper method:

```cs
private static bool IsMultiline(Scintilla scintilla, int startPos, int endPos)
{
    var startLine = scintilla.LineFromPosition(startPos);
    var endLine = scintilla.LineFromPosition(endPos);
    return (startLine != endLine);
}
```

**Comment by pjlasl** [comment]
Thank you for the prompt reply. I am sure I may have a few more as I start digging into my code.
