### ISSUE TITLE
ScintillaNET demo app or wrapper

### ISSUE THREAD

**Issue by hgupta9** [jacobslusser/ScintillaNET#280]
I'm interested in building a ScintillaNET demo app or wrapper. What features would I have to include? I already have in mind:
- syntax coloring / keywords
- font/styling
- number margin
- bookmark icon on margin
- highlighting lines
- suggestion lists / intellisense
- code folding / regions
- rectangular selection

**Comment by jacobslusser** [comment]
All that sounds awesome. Keep us updated on the progress.

**Comment by hgupta9** [comment]
@jacobslusser - First version uploaded. Check it out!

https://github.com/hgupta9/ScintillaNET.Demo

I need some help with the bookmarks:

- Currently the bookmark circle is appearing on the number margin too. How to supress that?
- How to set the backcolor of the entire line when a bookmark is added?

**Comment by jacobslusser** [comment]
Looking good. Sorry I haven't had time to answer your questions, but they are easy changes. To make sure symbols appear on one margin but not another you need to set a mask. To highlight an entire line I believe you can add another symbol/marker (call background maybe?) in addition to the bookmark symbol that will cause the line to be highlighted. I can provide code samples when I have more time.

**Comment by TheGrovesy** [comment]
@hgupta9 Nice work on the Demo so far... I was struggling to work out how to get the styling to appear but your Demo was very helpful. I look forward to seeing the other features in it.

**Comment by jacobslusser** [comment]
Excellent work on this. Thanks again.

**Comment by hgupta9** [comment]
Sure, no problem. I'll try to improve the margins and add other features in.

**Comment by hgupta9** [comment]
@jacobslusser - Demo updated! Check it out at https://github.com/hgupta9/ScintillaNET.Demo

New features:
- code folding (with margin)
- quick search bar (Ctrl+F)
- main menu with viewing and editing commands
- zooming hotkeys (Ctrl+ and Ctrl-)

I had a small issue with indenting. It seems TAB and Shift+TAB are implemented in Scintilla, but API to access it is missing from ScintillaNET. Right now I used a workaround (`SendKeys()`!)

**Comment by hgupta9** [comment]
And I need some help with the bookmarks margin:
- If I set the mask to `1`, then the entire line gets colored (good)
- If I set the mask to `(1 << BOOKMARK_MARKER)` then the bookmark icon (red dot) is visible
- However I cannot get BOTH of these to be visible together!
- I tried `1 | (1 << BOOKMARK_MARKER)` but it doesn't work either

Can you help me get both a bookmark icon and the line coloring at once?

**Comment by jacobslusser** [comment]
```cs
private const int BOOKMARK_MARGIN = 1;
private const int BOOKMARK_MARKER = 2;
private const int BOOKMARK_MARKER_LINE = 3;
```

```cs
var margin = scintilla.Margins[BOOKMARK_MARGIN];
margin.Width = 20;
margin.Sensitive = true;
margin.Type = MarginType.Symbol;
margin.Mask = (1 << BOOKMARK_MARKER) + (1 << BOOKMARK_MARKER_LINE);
//margin.Cursor = MarginCursor.Arrow;

var marker = scintilla.Markers[BOOKMARK_MARKER];
marker.Symbol = MarkerSymbol.Circle;
marker.SetBackColor(ColorTranslator.FromHtml("#FF003B"));
marker.SetForeColor(ColorTranslator.FromHtml("#000000"));
marker.SetAlpha(100);

marker = scintilla.Markers[BOOKMARK_MARKER_LINE];
marker.Symbol = MarkerSymbol.Background;
marker.SetBackColor(ColorTranslator.FromHtml("#FF003B"));

scintilla.Lines[1].MarkerAdd(BOOKMARK_MARKER);
scintilla.Lines[1].MarkerAdd(BOOKMARK_MARKER_LINE);
```

**Comment by hgupta9** [comment]
Thanks! This solved my problem. Demo app updated.
