### ISSUE TITLE
Unhighlight search words

### ISSUE THREAD

**Issue by KakCAT** [jacobslusser/ScintillaNET#285]
Hello,

I'm using this document to highlight words: 
https://github.com/jacobslusser/ScintillaNET/wiki/Find-and-Highlight-Words

It'd be great if the same document would contain code (or at least a hint) to unhighlight those searched words.

Thanks!

**Comment by jacobslusser** [comment]
That's a good point. Perhaps we can clarify it a bit, but to be fair it does technically container the answer you're looking for. I'll direct you to this portion of the code snippet:

```cs
// Remove all uses of our indicator
scintilla.IndicatorCurrent = NUM;
scintilla.IndicatorClearRange(0, scintilla.TextLength);
```

**Comment by jacobslusser** [comment]
#169

**Comment by KakCAT** [comment]
thanks!
