### ISSUE TITLE
Search and replace [Question]

### ISSUE THREAD

**Issue by autovaton** [jacobslusser/ScintillaNET#287]
Is there still a search and replace dialogue in Scintilla?  Can't seem to find it if there is.  CTRL-F and CTRL-H paste control characters into the text now instead of pulling up the dialogue.

**Comment by Stumpii** [comment]
There isn't, but there is: [ScintillaNET-FindReplaceDialog](https://github.com/Stumpii/ScintillaNET-FindReplaceDialog)
