### ISSUE TITLE
[Question] Add space between Top and first line?

### ISSUE THREAD

**Issue by Zerowalker** [jacobslusser/ScintillaNET#288]
Hi,

is it possible to make a bit of space between the first line and the top of the textbox?

Currently it looks a bit bad cause it almost melts with the border in my case.

Also i would like some help with Markers and Hiding/Foldering text,
i got it working, but it's a big mess as it resets all markers everytime something changes basically.

Thanks:)!

**Comment by jacobslusser** [comment]
Not exactly. The best thing I could suggest is using the `ExtraAscent` and `ExtraDescent` properties which will add padding to the top and bottom of each line. But other than that, I don't think we have a way to add space to just the top of the control. 

Another option would be of course to fake it by putting the Scintilla control in a `Panel` or some other control that also has a white `Window` color background and then hide Scintilla's border with the `BorderStyle` property. If done correctly it will look like they are all the same control even though Scintilla is technically nested in another control that provides the padding at the top you want.

**Comment by Zerowalker** [comment]
Ah, thanks for the suggestion:)
