### ISSUE TITLE
In C#, how can I set the background colour of the document from white to another colour?

### ISSUE THREAD

**Issue by dspwhite** [jacobslusser/ScintillaNET#29]
Do I need to use interop for this? If so, why doesn't ScintillaNET have this basic functionality built in? 

Implementation of how to go about this would be appreciated.

I found this, but it's only C based:
http://stackoverflow.com/questions/12310144/how-to-change-the-editors-background-color-with-scintilla

**Comment by jacobslusser** [comment]
The `Default` style `BackColor` determines the control background color. The equivalent ScintillaNET code for the C-code you linked would be:

```cs
scintilla.Styles[Style.Default].BackColor = Color.Pink;
```

**Comment by dspwhite** [comment]
Since I have a multitude of foreground colour styles, unfortunately, changing the Background colour like this doesn't affect the small block of colour behind each character. I know I can create a whole new set of styles with and without the new background colour, but it would be quicker to code (and to run) if one were able to change the background colour independently. Any way through interop per chance?

**Comment by jacobslusser** [comment]
The quickest way to do what you want would be:

```cs
scintilla.Styles[Style.Default].BackColor = Color.Pink;
scintilla.StyleClearAll();
```

The `StyleClearAll` method applies the current `Default` style properties to *all* styles. Call this *before* you set your other styles and they will all start with a `BackColor` of pink.

There is no other, faster option--interop or otherwise.
