### ISSUE TITLE
[Question] How can we stop delete event?

### ISSUE THREAD

**Issue by wewake4** [jacobslusser/ScintillaNET#291]
Hi,

I want to stop the delete functionality triggered by contextmenu. We have a event (Before Delete) but how can we handle it.

Regards,
wewake4

**Comment by jacobslusser** [comment]
I'm not aware of any way to do that. The `BeforeDelete` event is not cancellable.

Instead, tell me what you're trying to do and there may be another way to accomplish what you want.

**Comment by wewake4** [comment]
Hi,

My requirement is that, when user edits the script, i have to prompt him with the login window. If user enters his credentials then he can continue his edit, otherwise reverting the changes.

For adding, I am checking with Insert Check event and handling it.
But if user clicks on Delete via context menu, i am not able to handle it.

Regard,
wewake4

**Comment by jacobslusser** [comment]
What you're trying to do is specifically what the `SetSavePoint`, `SavePointLeft`, `SavePointReached`, `Modified`, `ModifyAttempt`, and `ReadOnly` members are for.

It would work like this: you set `ReadOnly` to `true`. When a user attempts to modify the text, you'll get a `ModifyAttempt` notification and display your check-out / credentials dialog. If the credentials are correct, you can then set `ReadOnly` to `false`.  At that point the user can modify the document.

When the user makes a change to the document, the `Modified` property will change to `true` and the `SavePointLeft` notification will fire. That will allow you to update your display showing the document is unsaved. When they save it, you call `SetSavePoint` which will remove the dirty (`Modified`) flag and the `SavePointReached` event will be sent letting you update your display. That process continues until the user closes the document.
