### ISSUE TITLE
[Question] Multiple Text Margins

### ISSUE THREAD

**Issue by PlotinusRedux** [jacobslusser/ScintillaNET#292]
First, I just found this project, I didn't know about Scintilla or ScintillaNET.  This is an awesome control that I'm going to get a lot of use out of--in just the first 15 minutes I've got working as a great file difference viewer.

Thank you to Jacob and everyone else who has contributed to the project.

Quick question, though--a Scintilla control exposes a Margins array I see can be used to set various properties for up to 5 margins, and I see setting Type to MarginType.Text allows one to set the Style and Text via Lines[].MarginStyle and Lines[].MarginText.

However, I don't see a way to set separate text for individual Margins.  For instance, if I set both Margins[0] and Margins[1] to Type MarginType.Text, then set Lines[1].MarginText = "SomeText", both margins show "SomeText" side by side.

What I'm trying to accomplish is a file difference view that displays the line number from file 1 in one margin and the line number from file 2 in another margin.  I've got a work-around by only using one Margin and setting Lines[i].MarginText = string.Format("{0,5} {1,5}", file1linenum[i], file2linenum[i]), but I'd like to be able to do things I'd really need 2 margins to do, like displaying them in separate colors, displaying a plus symbol in the first margin rather than a number if the line doesn't exist in the first file, a minus symbol in the 2nd margin if the line doesn't exist in the 2nd file, etc.

Is there any way to set the MarginText separately for separate margins that I'm missing?  I was really expecting MarginText itself to be a string array of the same length as the Margins array.  If there isn't a way, is this a limitation of the underlying Scintilla DLL I won't be able to work around by digging into the ScintillaNet code?

Even with that limitation, this is pretty sweet for 15 minutes of work:

![image](https://cloud.githubusercontent.com/assets/24490283/21079074/5d8a3c2a-bf4b-11e6-934a-b2c39ba370e3.png)

**Comment by jacobslusser** [comment]
You're right, this is a limitation of the native Scintilla component. I guess the creators assumed you would never have more than one text margin. I think your workaround of using a single text margin with `string.Format` is pretty clever and probably the easiest way to go.

Your only option beyond that is "painting" in the margin, which is to say literally handle the WM_PAINT messages and do the text rendering yourself. We don't support custom painting and so you would have a massive challenge getting that approach to work.

Better stick with what you've got. :)
