### ISSUE TITLE
Caret.LineNumbers (CaretInfo)

### ISSUE THREAD

**Issue by cristo1985** [jacobslusser/ScintillaNET#293]
Hi,
i have rebuilt the project compile in year 2011 and i noticed that this not work now!

 Dim TheControl As ScintillaNET.Scintilla

TheControl.Caret.LineNumber

Caret is not Scintilla member.

How can i resolve it?

Thanks!!

**Comment by JohnyMac** [comment]
This version of ScintillaNET has been completely rewritten so the functions change a bit.
Assuming you want to get the current line, You just get it like this: 
```
Dim TheControl As ScintillaNET.Scintilla
TheControl.CurrentLine
```

**Comment by cristo1985** [comment]
Ok. I have this function:

`Public Sub IntelliSense(ByRef TheControl As ScintillaNet.Scintilla)
        Dim Starters() As String = {"if", "while", "for", "with"}
        Dim Enders() As String = {"end if", "end while", "next", "end with"}
        Dim CapsEnders() As String = {"End If", "End While", "Next", "End With"}
        Dim P As String = TheControl.Lines(TheControl.Caret.LineNumber - 1).Text
        P = P.Substring(0, P.Length - 2)
        If P.Length = 0 Then Exit Sub
        Dim SpaceCount As SByte = 0
        For i As Byte = 0 To P.Length - 1
            If Not P.Substring(i).StartsWith(" ") Then Exit For
            SpaceCount += 1
        Next
        Dim F As String = P.Substring(SpaceCount).ToLower
        Dim Amount As Byte = 1
        If SpaceCount Mod 2 = 0 Then Amount = 2
        Dim FID As Byte = 100
        For DOn As Byte = 0 To Starters.Count - 1
            If F.StartsWith(Starters(DOn) + " ") Then FID = DOn : Exit For
        Next
        If Not FID = 100 Then
            TheControl.InsertText(MakeSpaces(SpaceCount + Amount))
            Dim DoAdd As Boolean = True
            For i As Byte = TheControl.Caret.LineNumber To TheControl.Lines.Count - 1
                Dim L As String = TheControl.Lines(i).Text
                L = L.Substring(0, L.Length - 2).ToLower
                If L.Length = 0 Or L.Length <= SpaceCount Then Continue For
                L = L.Substring(SpaceCount)
                If L = Enders(FID).ToLower Then DoAdd = False
            Next
            If DoAdd Then
                Dim BackupPos As Int16 = TheControl.Caret.Position
                TheControl.InsertText(vbcrlf + MakeSpaces(SpaceCount) + CapsEnders(FID))
                TheControl.Caret.Position = BackupPos
                TheControl.Selection.Length = 0
            End If
            Exit Sub
        End If
        Dim IsOne As Boolean = False
        For Each D As String In Enders
            If F = D Then IsOne = True
        Next
        If F.StartsWith("next ") Then IsOne = True
        If IsOne And SpaceCount = TempSpaces Then
            SpaceCount -= Amount
            Dim FX As String = P
            If FX.StartsWith(MakeSpaces(Amount)) Then
                FX = FX.Substring(Amount)
                TheControl.Lines(TheControl.Caret.LineNumber - 1).Text = FX
            End If
        End If
        If SpaceCount < 0 Then SpaceCount = 0
        TempSpaces = SpaceCount
        TheControl.InsertText(MakeSpaces(SpaceCount))
    End Sub`

Many property of the control are missing or changed ... :(
Can you help me please?
Thanks!

**Comment by jacobslusser** [comment]
As @JohnyMac said, v3 is a complete rewrite and it not API compatible with v2 (hence the major version change).

Please review the extensive documentation we have available, starting with the [wiki](https://github.com/jacobslusser/ScintillaNET/wiki) and feel free to ask any questions you have beyond that.
