### ISSUE TITLE
Activate ESC Ansi Color parsing in .NET project

### ISSUE THREAD

**Issue by YvesR** [jacobslusser/ScintillaNET#295]
Hello,
maybe (probably) I am blind but I wasn't able to find out (neither code try and error or documentation) to activate ANSI Color parsing.

I load log files which contains ESC sequences for color codes.
I saw some posts about `lexer.cpp.escape.sequence` and reading version history I read something about `Errorlist` that parse color codes, but can not find a way how to use this.

`TextArea.Lexer = Lexer.cpp` e.g. do not has more properties to set.

Any help would be nice.
Thanks you.

**Comment by jacobslusser** [comment]
What you're looking for is the `SetProperty` method. You can see it demonstrated (although not explained) in the article on [Automatic Code Folding](https://github.com/jacobslusser/ScintillaNET/wiki/Automatic-Code-Folding).

Unfortunately the string constants which identify the names of the properties are not documented. For the C++ lexer you would need to scan the original Scintilla source code looking for instances of `DefineProperty` here: [https://sourceforge.net/p/scintilla/code/ci/default/tree/lexers/LexCPP.cxx](https://sourceforge.net/p/scintilla/code/ci/default/tree/lexers/LexCPP.cxx)

**Comment by YvesR** [comment]
Hello,
thank you for your answer, so you suggest add

```
// escape code
TextArea.Lexer = Lexer.Cpp;
TextArea.SetProperty("lexer.cpp.escape.sequence", "1");
```

I opened some rails logs that contains ESC sequences for bold and color codes. They still are not parsed. Do I still miss something?

**Comment by jacobslusser** [comment]
Have you set your [style definitions](https://github.com/jacobslusser/ScintillaNET/wiki/Automatic-Syntax-Highlighting)? i.e. 

```cs
scintilla.Styles[Style.Cpp.EscapeSequence].ForeColor = Color.Green;
```

It's very likely that your document is being parsed, you just can't see it if you don't define the appearance.

**Comment by YvesR** [comment]
I did set some styles, but I thought ESC sequences are parsed of their values to show the color codes?

Here is a current example. the ESC is still in the editor, my thought was it gets removed and the color code or bold/italic/underline used!?

<img width="501" alt="bildschirmfoto 2016-12-17 um 21 00 14" src="https://cloud.githubusercontent.com/assets/4928882/21289364/fd532398-c49b-11e6-834e-fde0d2c9f397.png">
