### ISSUE TITLE
SciLexer.dll. This file is within the project directory tree

### ISSUE THREAD

**Issue by monajalal** [jacobslusser/ScintillaNET#297]
How can I fix these in Visual Studio 2015?
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning		The file '3rdparty\ScintillaNET\SciLexer.dll' could not be added to the project.  Cannot add a link to the file C:\Users\mona\playing-for-data\renderdoc\renderdocui\3rdparty\ScintillaNET\SciLexer.dll. This file is within the project directory tree.	renderdocui			
Severity	Code	Description	Project	File	Line	Suppression State
Warning		The file '3rdparty\ScintillaNET\SciLexer64.dll' could not be added to the project.  Cannot add a link to the file C:\Users\mona\playing-for-data\renderdoc\renderdocui\3rdparty\ScintillaNET\SciLexer64.dll. This file is within the project directory tree.	renderdocui			

```

**Comment by jacobslusser** [comment]
Are you possibly using an old v2 of ScintillaNET?

Try our [nuget](https://www.nuget.org/packages/jacobslusser.ScintillaNET/3.5.10) [packages](https://www.nuget.org/packages/jacobslusser.ScintillaNET.Signed/3.5.10) or GitHub [releases](https://github.com/jacobslusser/ScintillaNET/releases).

Once you have the correct DLL, you can use the documentation found in the [wiki](https://github.com/jacobslusser/ScintillaNET/wiki) to get started.
