### ISSUE TITLE
SetSelBack settings

### ISSUE THREAD

**Issue by YvesR** [jacobslusser/ScintillaNET#299]
Hello,

not an issue but I searched an hour and couldn't find information about settings the selection background color.

I know this: http://www.scintilla.org/ScintillaDoc.html#SCI_SETSELBACK
But how to set this in the .NET wrapper implementation?

**Comment by Stumpii** [comment]
I find that searching the repos (at the top of this web page) for the Scintilla keyword is easiest and usually finds me where it is used. Especially if you use the dll and don't download the whole source.

A search for SETSELBACK reveals (in scintilla.cs):

`/// <summary>
        /// Sets a global override to the selection background color.
        /// </summary>
        /// <param name="use">true to override the selection background color; otherwise, false.</param>
        /// <param name="color">The global selection background color.</param>
        /// <seealso cref="SetSelectionForeColor" />
        public void SetSelectionBackColor(bool use, Color color)
        {
            var colour = ColorTranslator.ToWin32(color);
            var useSelectionForeColour = (use ? new IntPtr(1) : IntPtr.Zero);

            DirectMessage(NativeMethods.SCI_SETSELBACK, useSelectionForeColour, new IntPtr(colour));
}`

Hope this helps.

**Comment by YvesR** [comment]
Hello,
had the same idea, but from some reason I do not know I failed. Found it now, used it, works. Thanks!
