### ISSUE TITLE
Font assign encoding problem (base Scintilla library update)

### ISSUE THREAD

**Issue by lightfinder** [jacobslusser/ScintillaNET#3]
From scintilla 3.5.3 all multibyte support(win98 legacy) has been removed. Now styling functions in scintilla receives fontname in UTF-8 encoding, not windows default.

Current ScintillaNET still uses Encoding.Default to assign font names, but it fails when non-ascii named fonts applied. (e.g. CJK language fonts)

Encodings should be changed to UTF-8.

**Comment by jacobslusser** [comment]
Done. Thanks for the heads-up.

Fixed in commit 113b517. Please get latest and report any issues.
