### ISSUE TITLE
SQL Lexer Bug?

### ISSUE THREAD

**Issue by pjlasl** [jacobslusser/ScintillaNET#30]
I am incorporating the SQL lexer and i came across what I believe is a bug in the styling.

I set the Style.String for SQL and noticed that for it to work the string has to be surrounded by double quotes. This is incorrect.

```vb
Me.txtQuery.Styles(ScintillaNET.Style.Sql.String).ForeColor = Color.Red
```

The proper SQL syntax for strings is a single quote or apostrophe.

Can this be changed on your end or not?

**Comment by jacobslusser** [comment]
Try `Style.Sql.Character`.

**Comment by pjlasl** [comment]
worked great! I did not notice that one. Thanks!
