### ISSUE TITLE
Getting words around caret

### ISSUE THREAD

**Issue by Aztectrev** [jacobslusser/ScintillaNET#300]
Is there any way to get words around cursor? 
if currentWord is where my caret is, then I need a way to get prevWord, and nextWord, but also regardless of whitespace. I use GetWordFromPosition to get current word.
So it could be like a single space like below
prevWord currentWord nextWord 
or 
prevWord 
--------currentWord 
 ----------------nextWord

dashes being spaces as the editor is stripping them
and still be able to retrieve in both cases. any suggestions?
Thanks

**Comment by jacobslusser** [comment]
What I think you're looking for are the `WordStartPosition` and `WordEndPosition` methods. Depending on what you want to do (which I'm not entirely clear on) you can use those methods to essentially iterate the words ahead of or behind the current word. For example:

```cs
var pos = scintilla1.CurrentPosition;

var wordStart = scintilla1.WordStartPosition(pos, true);
var wordEnd = scintilla1.WordEndPosition(pos, true);
var word = scintilla1.GetTextRange(wordStart, wordEnd - wordStart);

var prevWordStart = scintilla1.WordStartPosition(wordStart - 1, true);
var prevWordEnd = scintilla1.WordEndPosition(prevWordStart, true);
var prevWord = scintilla1.GetTextRange(prevWordStart, prevWordEnd - prevWordStart);

var nextWordStart = scintilla1.WordStartPosition(wordEnd + 1, true);
var nextWordEnd = scintilla1.WordEndPosition(nextWordStart, true);
var nextWord = scintilla1.GetTextRange(nextWordStart, nextWordEnd - nextWordStart);

Console.WriteLine(string.Join(" ", prevWord, word, nextWord));
```

**Comment by Aztectrev** [comment]
Thanks for reply.

Basically I'm trying to make a Custom SQL editor with a autocomplete, and as spaces are the only things separating keywords, I need to get next and previous words to decide what items to place in autocomplete.
