### ISSUE TITLE
Question: Printing emojis

### ISSUE THREAD

**Issue by KakCAT** [jacobslusser/ScintillaNET#301]
Hi,

I'm writing an editor which now needs to be able to print color emojis. In theory this should be as easy as supplying a font to the editor which has emoji characters but this is proving to be very difficult, not only with ScintillaNET but with other Win32 programs (i.e. Visual Studio). 

Supposedly some windows 8 fonts should provide color emojis, in example, Segoe UI Symbol, but using them in ScintillaNET only shows a fairly ugly monochrome emoji. 

So, the question is: is it normal that I'm unable to print color emojis in Scintilla or amb I doing something wrong?

Thanks!

**Comment by jacobslusser** [comment]
I think you're trying to do something that isn't possible. I'm not aware of any font that has "color". A font is a series of glyphs/vectors, not bitmaps or pretty color emojis. 

Sorry, but what I think you're hoping for is an editor which can compose text and images together, inline the way HTML can (e.g. `<span>Some text and <img src="emoji.gif" />.</span>`. Scintilla cannot do that.

In fact, most messaging software usually uses an embedded web control/view to render those pretty things. You might want to look into the standard `WebBrowser` control instead.

**Comment by KakCAT** [comment]
Hi @jacobslusser ! Thanks for your answer.

I've been reading more about the fonts I mentioned and they seem to be usable (with color output) only in UWP applications via XAML. So no win32 apps can use them.

I'll try to get a mixed solution, like editing with Scintilla but popping a window rendered by me when I detect I'm writing a string (emojis should only appear inside my language's strings). Scintilla is too good to be replaced by a WebBrowser ;)

**Comment by zufuliu** [comment]
@KakCAT  Scintilla support colored font since 4.1.5 or 3.10.4 (2019-04-17) if you use Direct2D.
https://sourceforge.net/p/scintilla/feature-requests/1277/
https://www.scintilla.org/ScintillaHistory.html
https://scintilla.sourceforge.io/ScintillaHistory.html
