### ISSUE TITLE
Support for JS template strings?

### ISSUE THREAD

**Issue by fatcerberus** [jacobslusser/ScintillaNET#302]
JavaScript template strings are not currently recognized by the Cpp parser, leading to sometimes odd highlighting behavior:

![Imgur](http://i.imgur.com/zwJGmn5.png)

Any plans to support this syntax in the future?

**Comment by jacobslusser** [comment]
So it would seem.

This is a feature request that you should submit to the native Scintilla team. You can find the feature request tracker here: [https://sourceforge.net/p/scintilla/feature-requests/](https://sourceforge.net/p/scintilla/feature-requests/).

ScintillaNET is just a wrapper around that component and the the parser support we provide in ScintillaNET comes from the native Scintilla component.

**Comment by fatcerberus** [comment]
Thanks, I assumed this would be something Scintilla would have already supported by now and ScintillaNET would just have to enable it, but I guess not.  I'll send a feature request their way.

**Comment by fatcerberus** [comment]
It seems that Scintilla already has support for highlighting backquoted strings since 2014:
https://sourceforge.net/p/scintilla/code/ci/6e84f55dceeef188a6f79e7052c0d8299c860480/

It requires enabling the option "lexer.cpp.backquoted.strings".  That doesn't enable highlighting for the inner expressions in the template, but it's better than nothing.  However, I can't figure out how to enable that option through ScintillaNET... is it even possible?

**Comment by jacobslusser** [comment]
It would be:

```cs
scintilla.SetProperty("lexer.cpp.backquoted.strings", "1");
```

**Comment by fatcerberus** [comment]
Thanks, that worked.  Since there's nothing for Scintilla.NET to fix I'll close the issue.
