### ISSUE TITLE
Exception thrown when adding ScintillaNET to a form

### ISSUE THREAD

**Issue by theshinyknight** [jacobslusser/ScintillaNET#303]
Hi, I am trying to integrate Scintilla since I need a very basic text editor with the nice features that modern IDE give nowadays.

I did download the source code, built it in VS, so I have the ScintillaNET dll. So far so good.

I did start with a form; which open another form when I press the button. This will hide the main form, and create the new form, which is the editor using ScintillaNET.
I did add in the cs file the import statement for ScintillaNET; which does not give me an error so I assume the DLL is accessible.

The problem start when I open the new form; this is the call that I have in the form initialization, right after InitializeComponent(). If I do not call `TextArea = new Scintilla();` the form load and show; with all the other controls on it; but if I try to create a new Scintilla object, then I get the following exception in VS:

```
Exception thrown: 'System.BadImageFormatException' in testapp.exe
Additional information: Could not load file or assembly 'ScintillaNET, Version=3.5.10.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.
```

I did find old documentation that show how to run Scintilla, but they mention SciLexer.dll, which from my understanding, is now included inside ScintillaNET, so I do not need to add it in my DLL references area (I did even try to add it and nothing change). I am not sure exactly what is missing; I can't even see the Scintilla control in the toolbox; even after trying to add the DLL via "browse" in the WPF Components area of the toolbox Items window.

Is there an updated sequence of actions that has to be performed, to add ScintillaNET to an existing form in a project? I am using Visual Studio Community 2015, C# as language and I did download the latest code few hours ago. Thanks in advance

**Comment by jacobslusser** [comment]
A 'BadImageFormatException' occurs when you try to load a 32-bit file into a 64-bit process or vice versa. Something about what you're doing is getting the incorrect version of ScintillaNET or the native Scintilla component.

Rather than build yourself to start with, I would recommend the official NuGet packages or precompiled DLLs you can find from the [Releases](https://github.com/jacobslusser/ScintillaNET/releases) page. There might be an issue with the way you are building.

You might also be interested in issues #122 and #257.

**Comment by theshinyknight** [comment]
I see; I did built it as 64 bit, since everything is configured for 64 bit in my project, but probably I made a mistake somewhere. I did download the DLL from the link you posted and it did work this time. Thanks!!
