### ISSUE TITLE
Line number margin line selection doesn't work

### ISSUE THREAD

**Issue by ei** [jacobslusser/ScintillaNET#305]
I've been sitting for hours trying to figure that out how to get it to work, but without success. I'm using the latest ScintillaNET. Is there a way to achieve this, or am I missing something here? I found _MarginOptions.SublineSelect_, but I'm not sure how to use that.

![](http://i.imgur.com/dypUXGc.gif)

**Comment by jacobslusser** [comment]
When a margin is marked as `Sensitive` it will send a click notification that you can handle. When not, the default behavior is to select the line. 

What you're trying to accomplish should be the default behavior for a new margin.

**Comment by ei** [comment]
Wow, this is embarrassing...
Yup, I had the margin set to `sensitive`. Thank you!
