### ISSUE TITLE
Control Chars (Question)

### ISSUE THREAD

**Issue by Speed7811** [jacobslusser/ScintillaNET#308]
Dear all,

I have added the Scintilla.NET control on my WinForm and created a custom lexer successfully. 

If I press Ctrl+F, Ctrl+S, Ctrl+W or Ctrl+Q some control chars are entered. How can I deactivate it?

Kind regards

Rainer
![1](https://cloud.githubusercontent.com/assets/25704388/22862086/2257a80e-f128-11e6-97e2-9880c330073f.jpg)

**Comment by jacobslusser** [comment]
Issue #221, #101, #175.

**Comment by jacobslusser** [comment]
And #135, #121.

**Comment by Speed7811** [comment]
Hi,

thanks... that helps!

Rainer
