### ISSUE TITLE
Disable styling for certain lines

### ISSUE THREAD

**Issue by weswitt** [jacobslusser/ScintillaNET#309]
I have a marker defined:

textArea.Markers[SOURCE_MARKER].Symbol = MarkerSymbol.Background;
textArea.Markers[SOURCE_MARKER].SetBackColor(IntToColor(0xab616b));
textArea.Markers[SOURCE_MARKER].SetForeColor(Color.White);

This works great, but depending on the text and the colors that I use in my marker it can be difficult to read the text because the syntax highlighting conflicts.

I'd like to know how to disable styling for the lines that have a marker active.

**Comment by jacobslusser** [comment]
Never been asked that before... I'm not aware of a built-in way to disable styling only for a specific line.

I seem to recall that someone on this forum had some success with handling an event that occurs after styling occurs (such as `UpdateUI`) and then from that event *restyling or styling over* some of the already styled text. You could try something like that using the `StartStyling` and `SetStyling` APIs from that event or another one, but I'm not certain it would work or that the result would be desireable.
