### ISSUE TITLE
SQL Lexer Style Question

### ISSUE THREAD

**Issue by pjlasl** [jacobslusser/ScintillaNET#31]
Continuing the SQL Style conversation...I notice that the default style isn't working (or maybe i'm doing something wrong)...

```vb
Me.txtQuery.StyleResetDefault()
Me.txtQuery.Styles(ScintillaNET.Style.Default).Font = "Consolas"
Me.txtQuery.Styles(ScintillaNET.Style.Default).Size = "10"
Me.txtQuery.StyleClearAll()

Me.txtQuery.Styles(ScintillaNET.Style.Sql.Default).ForeColor = Color.Blue
Me.txtQuery.Styles(ScintillaNET.Style.Sql.Number).ForeColor = Color.Black
Me.txtQuery.Styles(ScintillaNET.Style.Sql.Operator).ForeColor = Color.Gray
Me.txtQuery.Styles(ScintillaNET.Style.Sql.String).ForeColor = Color.Red
```

I would expect the default text color to be BLUE...is my thinking incorrect?

Thanks!

**Comment by pjlasl** [comment]
OK...I figured out that I should be using ```Style.SQL.Identifier```. Setting that to blue worked.

**Comment by jacobslusser** [comment]
The default style would be anything that doesn't get styled/classified in some other way. Most lexers are pretty comprehensive and will style nearly everything in the document in some way, leaving very little text in the default style. Most often this means the only unstyled/default text left by the lexer is whitespace.

Try making whitespace visible and see if that is where your default style is going:

```cs
scintilla.ViewWhitespace = WhitespaceMode.VisibleAlways;
```

**Comment by pjlasl** [comment]
I used the ```style.sql.identifier``` and it worked properly. I did have a question about ```style.sql.user1...```. How do I get custom words like (COUNT, MAX) into that list so that I can use a different color on those?

**Comment by jacobslusser** [comment]
See the wiki article [Automatic Syntax Highlighting](https://github.com/jacobslusser/ScintillaNET/wiki/Automatic-Syntax-Highlighting). It contains a section on setting keywords. Following those instructions you would arrive at the possible keyword lists supported by the SQL lexer:

```cs
"Keywords",
"Database Objects",
"PLDoc",
"SQL*Plus",
"User Keywords 1",
"User Keywords 2",
"User Keywords 3",
"User Keywords 4"
```

i.e. keywords in list index `4` (`"User Keywords 1"`) would be styled by `Style.Sql.User1`, etc...

**Comment by pjlasl** [comment]
Thank you.  I saw the article and it worked great!
