### ISSUE TITLE
Strange background on a symbol margin

### ISSUE THREAD

**Issue by Klocman** [jacobslusser/ScintillaNET#311]
When trying to style Scintrilla I ran into a weird issue with background color of symbol margins. Here is the code (I dropped a new control into a fresh window in an empty project):
```
scintilla1.Margins[1].Width = 30;
scintilla1.Margins[1].Mask = Marker.MaskFolders;
scintilla1.Margins[1].Type = MarginType.Color;
scintilla1.Margins[1].BackColor = Color.Black;
scintilla1.SetFoldMarginColor(true, Color.Black);
```
The code produces this as a result: 
![capture](https://cloud.githubusercontent.com/assets/14913904/23270184/50363956-f9f3-11e6-940f-0ed1a2f5364d.PNG)
Obviously I expected a solid color, not a checkerboard. 
Removing `scintilla1.Margins[1].Mask = Marker.MaskFolders` fixes the problem - the background is solid black as expected.
All back colors bahave the same.
MarginType doesn't matter as long as it can display symbols.
It doesn't matter what margin I try this with.
Calling SetAlpha, SetForeColor and SetBackColor on markers doesn't make any difference.

**Comment by jacobslusser** [comment]
`MarginType.Color` is new in the latest release. I haven't had a chance to use it much yet.

From your description I believe I understand what you are saying, but I'm not sure what you are trying to do.

What are you trying to do?

**Comment by Klocman** [comment]
This issue is not specific to `MarginType.Color`. All margin types that can display symbols look like this. 

> What are you trying to do?
I want to make the margin's background black to match the rest of my theme.

**Comment by Klocman** [comment]
I managed to solve the problem. As it turns out, you HAVE to set both SetFoldMarginColor AND SetFoldMarginHighlightColor to the exact same color, or you will have this weird checkerboard. Even the official documentation doesn't seem to mention this.

**Comment by fatcerberus** [comment]
I still get the checkerboard even with the following code in place:
```csharp
_codeBox.SetFoldMarginColor(true, Color.FromArgb(24, 24, 24));
_codeBox.SetFoldMarginHighlightColor(true, Color.FromArgb(24, 24, 24));
```

My symbol margin (for showing breakpoints) is fine.  The fold margin I can't seem to get rid of the checkerboard.

**Comment by Klocman** [comment]
I'm not sure what else could be the problem. Here's the code I ended up with, can't remember what's important for this issue and what's not.
```
        private static void SetupFoldingMargin(Scintilla scintilla)
        {
            scintilla.AutomaticFold = AutomaticFold.Show | AutomaticFold.Click | AutomaticFold.Change;
            // Use margin 2 for fold markers
            scintilla.Margins[2].Type = MarginType.BackColor;
            scintilla.Margins[2].Mask = Marker.MaskFolders;
            scintilla.Margins[2].Sensitive = true;
            scintilla.Margins[2].Width = 12;
            scintilla.Margins[2].BackColor = ThemeManager.EditorBackColor;
            // Reset folder markers
            for (var i = Marker.FolderEnd; i <= Marker.FolderOpen; i++)
            {
                scintilla.Markers[i].SetAlpha(255);
                scintilla.Markers[i].SetForeColor(ThemeManager.EditorBackColor);
                scintilla.Markers[i].SetBackColor(ThemeManager.MarginForeColor);
            }

            scintilla.SetFoldMarginColor(true, ThemeManager.EditorBackColor);
            scintilla.SetFoldMarginHighlightColor(true, ThemeManager.EditorBackColor);
        }`
```

**Comment by fatcerberus** [comment]
I found the bug, it turns out I was calling `SetFoldMarginColor(true, Color.White)` somewhere else in my control.  😅

The checkerboard thing seems to be by design in Scintilla, so setting the two fold colors to the same value is the proper solution.
