### ISSUE TITLE
Grab, delete, or modify text with a certain style

### ISSUE THREAD

**Issue by tryashtar** [jacobslusser/ScintillaNET#316]
Hello, how's it going?
I was wondering if there was an easy or built-in way to reference text with a certain style. For example, converting all keywords to be lowercase, or deleting all comments, or giving the user a rundown of every function name they've typed, based on what the lexer sees.
If not, I suppose I can try to re-implement the lexer code in a separate function to do those things for me, but if there is a built-in way, I would love to be informed. My poking around hasn't lead to anything promising yet, haha. Anyway, thanks!

**Comment by jacobslusser** [comment]
`GetStyleAt` will get you the style at a position and from there you can determine if it is one of the keywords you want to lowercase, etc. That would happen post-styling.

If you want to make the change at the time the text is inserted, you want the `InsertCheck` event. See [https://github.com/jacobslusser/ScintillaNET/wiki/Intercepting-Inserted-Text](https://github.com/jacobslusser/ScintillaNET/wiki/Intercepting-Inserted-Text).

**Comment by tryashtar** [comment]
Perfect, thank you so much!
