### ISSUE TITLE
How to custom code folding?

### ISSUE THREAD

**Issue by gaby1989** [jacobslusser/ScintillaNET#317]
Dear, jacobslusser, how are you! I really appreciate your excellent work. 

I wanna custom code folding by my own key word, such as:

#statrt

#end

**Comment by jacobslusser** [comment]
Issue #307 has a brief explanation for using the folding API. You'll have to detect the words `#statrt` and `#end` yourself, but once found you can use the example code in that issue to set the fold points.

If you are using one of the built-in lexers you may be fighting it a bit try to implement your own folding scheme on top of its folding scheme. If you've done your own lexer you should have no problems.
