### ISSUE TITLE
ANSI encoding text display incorrect!

### ISSUE THREAD

**Issue by gaby1989** [jacobslusser/ScintillaNET#319]
dear all:
    There is something wrong with my displaying ANSI-Encoding text on ScintillaNet. Because the Chinese char is garbled.
wrong in ScintillaNet
![qq 20170323003655](https://cloud.githubusercontent.com/assets/20633550/24209428/3130abf8-0f61-11e7-8fc9-e2e62ff43de9.jpg)
correct in NotePad++
![qq 20170323003845](https://cloud.githubusercontent.com/assets/20633550/24209413/2228737a-0f61-11e7-8b31-b7fabad61304.jpg)

 I have try to set ANSI-Encoding Mode.
`DirectMessage(NativeMethods.SCI_SETCODEPAGE, new IntPtr(0));`
But it do not work. Thank you for your reading.

**Comment by jacobslusser** [comment]
How are you loading the text into ScintillaNET? Please share some code.

**Comment by gaby1989** [comment]
Thank you very much! I found my answer.
The bug is `mainEditor.scintilla.Text = File.ReadAllText(path_);`
I fix it as `mainEditor.scintilla.Text = File.ReadAllText(path_, Encoding.Default);`
It works well, thanks!
