### ISSUE TITLE
Optimizing GetStyleAt() ?

### ISSUE THREAD

**Issue by dspwhite** [jacobslusser/ScintillaNET#32]
After experiencing the various horrors of the RichTextBox when developing my OpalCalc software, I though I'd give ScintillaNET a whirl for my latest project. So far, so good. There aren't any of the flickering issues, and highlighting is a LOT faster. Thank you to the original programmers and of course those who ported this to .NET.

Anyway, even though it's generally fast, I was hoping there may be a way to get GetStyleAt() faster. In theory, it should be able to access the memory as if it were an array, though I suspect there's a reason why things aren't so simple (hmmm... accessing scintilla1.Text[x] is also relatively slow, so perhaps it's not just a simple linear array for the characters?).

My purpose is for my own custom highlighting scheme. I'm aware of the StyleNeeded event, though I need to highlight the (currently visible) page of text arbitrarily, and not simply nearby the text that's currently being typed out by the user. Looking at just the current visual page of text seems to be the simplest way of going about this.

**Comment by jacobslusser** [comment]
As you suspected, internally Scintilla doesn't store a simple linear array of characters. It uses a gap-buffer structure and includes style data along with character data (in UTF-8 format) in the same buffer.

But I don't think that's your issue. Using `scintilla.Text[x]` would indeed be very slow because accessing the `Text` property will copy the entire contents of the document to a `String` and then throw it all away so you can get character `x`. If you would like to iterate character-by-character you'll likely get a performance boost by trying:

```cs
var c = scintilla.GetCharAt(x);
var s = scintilla.GetStyleAt(x);
```
*NOTE: some of this is explained in the wiki article [Basic Text Retrieval and Modification](https://github.com/jacobslusser/ScintillaNET/wiki/Basic-Text-Retrieval-and-Modification).*

No doubt this approach has performance implications also because each call to `GetCharAt` and `GetStyleAt` have to traverse quite a bit of code and interop. Instead, you might consider eliminating the call to `GetCharAt` by getting a block of text at a time -- a line for example. You should see dramatic improvements in speed if you try this:

```cs
var line = scintilla.Lines[x];
var text = line.Text;
for (int i = 0; i < text.Length; i++)
{
    var c = text[i];
    var s = scintilla.GetStyleAt(line.Position + i);
}
```

Scintilla also provides a way to copy characters AND styles for a specified range into a single array with `SCI_GETSTYLEDTEXT` but I haven't implemented it yet. Beware that if you choose to use a raw Scintilla message you'll get back UTF-8 characters, which may bite you if you are not familiar with Unicode. I'll see about getting this on my to-do list.

Finally, I still think you can use the `StyleNeeded` event. I'm uncertain why you think it wouldn't work for you. The text currently displayed on screen will surely be run through the `StyleNeeded` event so that it doesn't appear to the user as unstyled. If for some reason you REALLY wanted to make sure you style a specific range (i.e. page) rather than let Scintilla make range suggestions for you, you can call `Colorize` at any time to trigger the `StyleNeeded` event for an arbitrary range:

```cs
scintilla.Colorize(x, y);
```

**Comment by dspwhite** [comment]
> It uses a gap-buffer structure

Ah, yes I've been reading up on that, and it seems like an elegant solution. I am curious though since although moving the cursor is O(n) time, simply accessing a character should in theory still be O(1).

> Using scintilla.Text[x] would indeed be very slow because accessing the Text property will copy the entire contents of the document to a String

Ah, I see. Interestingly, the latency of GetCharAt is slow enough that the characters in the document have to exceed around 5000 to see the benefit of using GetCharAt(x) over Text[x]. At say a million though, GetCharAt(x) is obviously much faster.

>  Instead, you might consider eliminating the call to GetCharAt by getting a block of text at a time -- a line for example.

Hmm, I might look into that. Is there a simple way of getting the visible page of text into a LineCollection?

> Scintilla also provides a way to copy characters AND styles for a specified range into a single array with SCI_GETSTYLEDTEXT but I haven't implemented it yet.

That sounds fantastic if you could. In the meantime, could I use interop to get at this, and if so, I'd be grateful if you or someone else could give the code for that, as my knowledge on interop is minimal.

> Finally, I still think you can use the StyleNeeded event. I'm uncertain why you think it wouldn't work for you.

I've tried again (along with trying Colorize), and I may try again in the future. Things don't seem to work out, though I don't want to bore you with the gory details really. It might be my fault anyway.

Thanks for the considered reply!

**Comment by jacobslusser** [comment]
Some of the latency in calling `GetCharAt` could be my fault. In ScintillaNET v3 that is not a direct interop call. It goes through our translation layer that maps byte-to-character offset and vice versa to support Unicode. This lookup is very fast, but is overhead none the less.

The `FirstVisibleLine` and `LinesOnScreen` properties can be used to calculate the range of lines displayed on screen.

For a guide on how to make a native Scintilla call you can read the [Direct Messages](https://github.com/jacobslusser/ScintillaNET/wiki/Direct-Messages) wiki article. But if you're not very experienced with interop it may make your head spin. As I also said you need to account for the internal encoding used by Scintilla which is configured as UTF-8 in ScintillaNET.

Finally, don't give up on the `StyleNeeded` event, I still think it's your best option. :)

**Comment by dspwhite** [comment]
It just hit me this morning that random character access is going to be O(n) lookup with UTF8 and that's what's causing the slower speed. I'm pretty sure a fixed char width encoding for a gap-buffer structure random lookup is O(1). Is that correct? I understand that C# (and I think Windows generally) uses pseudo UTF16 behind the scenes where the char is always fixed at two bytes.

What I'm going to say next is with full understanding of the great accomplishment you've just done in supporting UTF8 in the first place with this new version of Scintilla. But.... are there any plans for you to support UTF16 as the underlying mechanism as an option in preference over UTF8?

I say this as someone who loves (or at least used to love) UTF8 as the primary text format for use everywhere. My love for it has tarnished slightly since this discovery, though I guess for files, it is still appropriate due to filesize.

I understand that UTF16 doesn't offer the full universe of characters, though I can't help but think that would only be a problem in 0.0001% of use-cases, whilst the speed gain and simplicity would be most useful. I also understand that memory is not unlimited, and UTF16 would (usually) consume 2x the memory of UTF8 (except for some languages, where it's 2x less of course!). That would be a shame to lose, so would it be inconceivable to add UTF16 as an option instead of replacing UTF8?

**Comment by jacobslusser** [comment]
What Scintilla uses internally isn't up to me. The only form of Unicode supported by the native Scintilla component is UTF-8. The work I've done in ScintillaNET is to convert that to UTF-16 -- the format used by Windows and .NET -- seamlessly for the user.

I think you're going down the rabbit hole though. Scintilla (and ScintillaNET) is used in many, many high-performance applications. It is *very* fast. Was it not, it would not be the success that it is.

If you aren't getting the performance you're looking for I would advise you to take a different approach in how your application interacts with ScintillaNET. Utilize caching. Minimize memory movements and garbage collections. Give the user wait indicators for long operations to help with perceived performance. Use a different ScintillaNET API to accomplish your task (as I suggested in our other thread about using Indicators). Etc...

BTW, UTF-16 supports the full range of Unicode characters, same as UTF-8... and don't let this experience cause you to stop loving UTF-8. :)

**Comment by dspwhite** [comment]
Oh that changes things a bit.

I might have to go hassle the Scintilla team... ;) Those optimizations you recommended are certainly doable, though one just can't beat O(1) access for simplicity generally.

In the meantime, I'll try indicators again - thanks for your help!

Regarding "pseudo UTF-16", I think I meant UCS-2 as that forces 2 bytes per char and thus loses some characters but gains a fixed-width.

**Comment by dspwhite** [comment]
By the way, instead of `FirstVisibleLine`, `LineFromPosition( scintilla.CharPositionFromPoint(0, 0) )` may be more useful, as that's based on the non-wrapped line number which is then more compatible with `scintilla.Lines[x]`.

For reference and to potentially help others, here's a method to obtain the first and last visible character index in the display. I found `CharPositionFromPoint(input.ClientRectangle.Right, input.ClientRectangle.Bottom)` to crash sometimes (copy/pasting when the client section height is too small - around < 50-100 pixels), so getCharPosAtEndOfDisplay() is fairly involved:

	public void obtainVisibleRange() {
		int startCharIndex = input.CharPositionFromPoint(0, 0);	// get char pos at start of display	
		int endCharIndex = getCharPosAtEndOfDisplay(startCharIndex);
		......
	}
	public int getCharPosAtEndOfDisplay(int a)
	{
		int c = 0;
		int line = 0;
		int len = 0;
		int firstLine = input.LineFromPosition(a);
		while (true)
		{
			Line l = input.Lines[line + firstLine];
			c += input.Lines[line + firstLine].WrapCount;
			len += input.Lines[line + firstLine].Text.Length;
			line++;
			if (c > input.LinesOnScreen) break;
		}
		return len + a;
	}
