### ISSUE TITLE
Scroll to line number

### ISSUE THREAD

**Issue by weswitt** [jacobslusser/ScintillaNET#320]
I need to scroll the editor to a specific line and have that line be in the middle of the control. I've read thru the various issues and tried a number of things but I still don't have something that works right.

This is what I have right now:

Line line = this.textEditor.Lines[lineNumber - 1];
this.textEditor.ScrollRange(line.Position, line.Position);

This scrolls the line into view as expected -- great.

What I want is to have the line in the middle of the control.  So I tried this, which seems reasonable.

int linesVisible = this.textEditor.LinesOnScreen;
lineNumber = lineNumber - (linesVisible / 2);
Line line = this.textEditor.Lines[lineNumber - 1];
this.textEditor.ScrollRange(line.Position, line.Position);

Problem is that LinesOnScreen does not return the number of visible lines. The returned value is must less that what I expect.

What am I doing wrong???

**Comment by jacobslusser** [comment]
I think you're on the right track. `LinesOnScreen` returns the number of *possible* lines displayed based on the size of the window and the line height (i.e. how many lines *could* fit in that space). If you actually want the number of lines on screen it would be something like:

```cs
var firstVisible = scintilla.FirstVisibleLine;
var lastVisible = firstVisible + scintilla.LinesOnScreen;
if (lastVisible > scintilla.Lines.Count)
    lastVisible = scintilla.Lines.Count;
```
(please forgive any errors I haven't actually checked that code)

Regardless, that's likely not necessary based on what you're looking to do. If your ultimate goal is to make sure that line X is in the middle of the screen, you only need to make sure you call `ScrollRange` with values that will ensure that (i.e. the `start` and `end` arguments put line X in the middle).

For example, you could:

```cs
var linesOnScreen = scintilla.LinesOnScreen - 2; // Fudge factor

var line = 100;
var start = scintilla.Lines[line - (linesOnScreen / 2)].Position;
var end = scintilla.Lines[line + (linesOnScreen / 2)].Position;
scintilla.ScrollRange(start, end);
```

(again, I haven't checked this extensively so it might not work in positions at the beginning of end of the document).

The basic idea here is that you want to specify a `start` and `end` range that takes up as much of the screen as possible and has your target line equal distance between them. To do that we calculate the approximate first visible line from line `100` and the last visible line beyond `100`.  Scintilla will try to keep both `start` and `end` in view and by doing, will also put your target line near the middle.

**Comment by weswitt** [comment]
Thanks a lot for the explanation. That actually works pretty well.
