### ISSUE TITLE
When Lexer changed past style remains

### ISSUE THREAD

**Issue by bonalybob** [jacobslusser/ScintillaNET#321]
I have created a menu to change language, but when the lexer changes styles from the past lexer remains

This is what python code looks like after changing from HTML:
![image](https://cloud.githubusercontent.com/assets/9870007/24321854/ba5ff548-114e-11e7-85b6-152c567fa8b2.png)
This is what it should look like ( done after restarting the program):
![image](https://cloud.githubusercontent.com/assets/9870007/24321871/089f8994-114f-11e7-8c19-e8f6ae43be96.png)

Is there a way to wipe all lexer styles?

Thanks in advance

**Comment by jacobslusser** [comment]
You're looking for the `Colorize` method.

**Comment by bonalybob** [comment]
Thanks, it is working now.
