### ISSUE TITLE
Problem Using Scintilla With Cmd.exe

### ISSUE THREAD

**Issue by AlanBurkhart** [jacobslusser/ScintillaNET#322]
I'm redirecting the input / output from cmd.exe to ScintillaNet. Works fine except a command like TREE which includes graphics characters. I've been playing with the encodings but still get gibberish for graphics chrs. Encodings are a weak spot for me so I'm probably missing something obvious. Any suggestions?

**Comment by jacobslusser** [comment]
You'll have to provide some sample code and sample of what your problem is...

Without seeing your issue, it may be that you need to use the System font to display system characters. I question whether it is an encoding issue at all...

**Comment by AlanBurkhart** [comment]
Here is the code relevant to the issue and a few screen shots to illustrate what I am seeing. I saved a copy of the output and opened it in NotePad++ and screen capped it. Another is from cmd.exe in which the text appears correctly. And one from my own project.
Here's the code:
`    Dim input As StreamWriter
    Dim out, err As StreamReader
	Dim WithEvents cmdProc As Process 'cmd.exe
	
	'this is in the form's Load event...
	cmdProc = New Process
	            With cmdProc
                .StartInfo.FileName = "cmd.exe"
                .StartInfo.UseShellExecute = False
                .StartInfo.RedirectStandardOutput = True
                .StartInfo.RedirectStandardInput = True
                .StartInfo.RedirectStandardError = True
                .StartInfo.CreateNoWindow = True
            End With
			
			
	'this sub sets the font and colors for both Scintilla controls
    Private Sub SetScintillaStyles(scin As Scintilla)
        Try
            scin.Dock = DockStyle.Fill
            scin.StyleResetDefault()
            scin.CaretForeColor = Color.Gainsboro
            scin.Styles(Style.Default).Font = My.Settings.EditorFont.Name

            scin.Styles(Style.Default).Size = My.Settings.EditorFont.Size
            scin.Styles(Style.Default).ForeColor = Color.Gainsboro

            If scin.Equals(txt_Output) Then
                scin.Styles(Style.Default).BackColor = Color.Black
            Else
                scin.Styles(Style.Default).BackColor = Color.FromArgb(24, 45, 53)
            End If

            scin.StyleClearAll()

            With scin
                .CaretForeColor = Color.White
                .SetSelectionBackColor(True, Color.Orange)
                .SetSelectionForeColor(True, Color.White)
                .WrapMode = ScintillaNET.WrapMode.Word
                .BorderStyle = BorderStyle.None
                .Margins(0).Width = 0
                .Margins(1).Width = 0
                .TabIndex = 0
                .ContextMenuStrip = cntxInput
            End With
        Catch ex As Exception
            MsgBox(ex.ToString, MsgBoxStyle.Exclamation, title)
        End Try
    End Sub	
			
	'The rest is in the "input" Scintilla ("sci") KeyUp event handler
	'I only included code relevant to the issue to make it easier to read
	
	Dim comStr As String = ""
    'if the Enter key was pressed, get the text of the line containing a command
     If e.KeyCode.Equals(Keys.Enter) Then
        comStr = sci.Lines(sci.CurrentLine - 1).Text
    End If
			
	cmdProc.Start()

    input = cmdProc.StandardInput
    out = cmdProc.StandardOutput
    err = cmdProc.StandardError
	
	If comStr.Trim <> "" Then
        input.WriteLine("chdir " & ChrW(34) & cmb_WrkDir.Text & ChrW(34))
        input.WriteLine(comStr)
        input.Close()

	'txt_OutPut is also a Scintilla control
	'and it's where I'm seeing the gibberish
        txt_Output.Text &= ChrW(10) & out.ReadToEnd

        Dim errStr As String = err.ReadToEnd
        err.Close()
        If errStr.Trim.Length > 0 Then

            txt_Output.Text &= errStr
        End If
        cmdProc.Close()
		
		
		`

![cmdexe](https://cloud.githubusercontent.com/assets/13427011/24385426/af35ae00-132f-11e7-9b85-5519e6a13af1.jpg)
![myapp](https://cloud.githubusercontent.com/assets/13427011/24385425/af35c020-132f-11e7-864c-32fae99f6e47.gif)
![notepadpp](https://cloud.githubusercontent.com/assets/13427011/24385427/af368b2c-132f-11e7-968e-69eb0949abdb.gif)

**Comment by AlanBurkhart** [comment]
Oh crap. Didn't mean to close the thread. My bad.

**Comment by jacobslusser** [comment]
This is really not a Scintilla problem. What encoding the `tree` command uses when it prints is anyone's guess. You might find these SO links helpful:

[http://stackoverflow.com/questions/138576/saving-tree-f-a-results-to-a-textfile-with-unicode-support](http://stackoverflow.com/questions/138576/saving-tree-f-a-results-to-a-textfile-with-unicode-support)
[http://stackoverflow.com/questions/1259084/what-encoding-code-page-is-cmd-exe-using](http://stackoverflow.com/questions/1259084/what-encoding-code-page-is-cmd-exe-using)

The short story is that there is no consistency in the output encoding of `cmd.exe` programs. Thus you are never going to know what encoding to translate your captured `cmd.exe` output to. Scintilla will work with any .NET string. Your encoding problem occurs before your captured output is passed to Scintilla. You might look into whether you can change the encoding of `StandardOutput` but I'm not sure that is possible. That is where your conversion error is.

**Comment by jacobslusser** [comment]
Closing since this is not a Scintilla problem. We can reopen if necessary.

**Comment by AlanBurkhart** [comment]
If I find a practical solution I'll pass it along. Thanks.
