### ISSUE TITLE
How to catch caret-position-changed event?

### ISSUE THREAD

**Issue by gaby1989** [jacobslusser/ScintillaNET#323]
hi, dear jacobslusser!
I wanna do something when user move the caret in scintilla. How can I catch the event? 
Look forward to your guidance. Thank you!

**Comment by jacobslusser** [comment]
The `UpdateUI` even is what you want.

**Comment by gaby1989** [comment]
Thanks for your help. I am designing a text editor based on ScintillaNet. The  editor is very like editor in Visual Studio. I'd like to share my code when finnishing.

**Comment by padmadevd** [comment]
UPDATEUI handlers are called after the document is painted, so the style changing methods called inside the handler will get effect in the next paint phase.
