### ISSUE TITLE
How to move selections?

### ISSUE THREAD

**Issue by gaby1989** [jacobslusser/ScintillaNET#324]
Like many other editor, if I drag the selected text to another position, it's move the selected text to the new position. How can I realise this feature?
If I try to drag the selection, the cursor transfer to "forbidden" style.
Could you help me please?

**Comment by jacobslusser** [comment]
[https://github.com/jacobslusser/ScintillaNET/issues?utf8=%E2%9C%93&q=drag%20drop](https://github.com/jacobslusser/ScintillaNET/issues?utf8=%E2%9C%93&q=drag%20drop)

**Comment by jacobslusser** [comment]
Since this has already been discussed before I'm going to close this and track any issue under #203. We can reopen if necessary.
