### ISSUE TITLE
GetCharAt as Int?

### ISSUE THREAD

**Issue by kathorus** [jacobslusser/ScintillaNET#325]
I'm working through the Custom Syntax Highlighting wiki, translating it into vb.net, which is my preferred language. There is the line - var c = (char)scintilla.GetCharAt(startPos); which should translate, I think, to vb.net as Dim c = CChar(scintilla.GetCharAt(startPos)). However, the signature of the method is int, not char, which is what vb expects. Is there something I'm missing in how C# handles this?

**Comment by jacobslusser** [comment]
I'm the last guy you want to ask about VB.NET, however, some quick Googling confirms your issue and the `CChar` function only accepts string and char input, not integer. A similar question on SO suggests using the `Chr` or `ChrW` functions. [http://stackoverflow.com/a/4857882/2073621](http://stackoverflow.com/a/4857882/2073621)

**Comment by zhaDeth** [comment]
Using this lib in VB.NET too, I can confirm that ChrW should indeed give you what you need: `Dim chrAt As Char = ChrW(GetCharAt(i))`
It surprises me that C# can just use plain char actually

**Comment by kathorus** [comment]
Thanks, it didn't even click with me that what was being returned was the character code.

**Comment by theryan722** [comment]
Wow, when I had this issue a long time ago, I simply created a C# library to interface between the two. Guess I can remove one dependency!
