### ISSUE TITLE
Enhance Indicators : Set Text and Background from one color

### ISSUE THREAD

**Issue by MscrmTools** [jacobslusser/ScintillaNET#326]
Hi

First, thank you very much for this wonderful project! I'm in the process of migrating from AvalonEdit which is cool too but the WPF based code is a problem for me.

I'm trying to apply some highlights for Liquid language included in HTML document. I succeeded to do this but it would be awesome if it was possible to add the possibility to colorize Text AND Background color, based on the `ForeColor`. I think this wouldn't require too much effort to get the same result as below

![image](https://cloud.githubusercontent.com/assets/10774317/24850740/7da57e90-1dd1-11e7-825d-12a9cc8f4123.png)

It would require a new `IndicatorStyle` so that the `ForeColor` specified would be used by text and the `Alpha` to create the background color

**Comment by jacobslusser** [comment]
I understand what you're trying to do, but I don't understand why you think Scintilla isn't capable of it or why indicators would be necessary. A style can have a `ForeColor` and a `BackColor` (among other things). Why not just use the `BackColor` to achieve what you want?

**Comment by MscrmTools** [comment]
I'm already using HTML lexer (and Cpp for JavaScript) and I read it was not possible to change the behavior of an existing lexer.
I found that using indicators allowed me to "add" additional behavior (the one for Liquid syntax).
Is there a better way to handle this scenario?

**Comment by jacobslusser** [comment]
Ah, I see. Your issue then is that there is not a purpose-built lexer for Liquid fragments in HTML documents and you're trying to work around that by using indicators to do custom styling over top of the built-in HTML lexer....

Ya, you're trying to do something it wasn't designed for. :)

If you want that level of control over your styling then you need to write a [custom lexer](https://github.com/jacobslusser/ScintillaNET/wiki/Custom-Syntax-Highlighting).

**Comment by MscrmTools** [comment]
Ok, I understand. My question was just to know if it was possible to add a new `IndicatorStyle` as described. That will help me to achieve my goals and could be useful for others too

**Comment by jacobslusser** [comment]
In that case, the answer is that ScintillaNET is a wrapper around the Scintilla native component. Our project only makes that native Scintilla component easily callable from .NET, but doesn't provide any features of our own. To add new indicator styles would be a request for the native Scintilla team.

**Comment by MscrmTools** [comment]
ok, that makes sense!
Thank you very much!
