### ISSUE TITLE
Does not work for Windows Store Apps in Windows 10 Creators Update

### ISSUE THREAD

**Issue by PawelTroka** [jacobslusser/ScintillaNET#327]
Basically it looks like call to LoadLibrary is failing. See issue https://github.com/PawelTroka/Computator.NET/issues/73.

**Comment by jacobslusser** [comment]
Hmm... obviously something has changed with the Windows 10 Creators Update. Not sure what to do to fix it though. Maybe compile on a Windows 10 Creators Update machine with the latest SDK? If you are able to get any more information please let me know.

**Comment by PawelTroka** [comment]
@jacobslusser Yes I am trying to get more information on this. First I need to update my OS, thought.

**Comment by PawelTroka** [comment]
I just upgraded OS on one of my computers and I haven't been able to reproduce this issue. Everything seems to work fine. Don't know where those crash reports that I am getting in Windows Store Developer Dashboard are coming from.

**Comment by PawelTroka** [comment]
One question @jacobslusser about SciLexer.dll
How is it compiled? Is it statically linked against Visual C++ Redistributables?

**Comment by PawelTroka** [comment]
I have created StackOverflow question for this problem but so far I only got downvoted :(
http://stackoverflow.com/questions/43564611/loadlibraryw-is-failing-in-my-desktop-bridge-converted-application-on-windows-10

**Comment by jacobslusser** [comment]
I am currently building SciLexer.dll using the VS2015 command prompt (x86 or x64) and then running `nmake -f scintilla.mak` from the `win32` directory of the Scintilla source code. Not sure off the top of my head if any of the C++ redistributable is getting statically linked (would guess not, but need to check to be sure).

**Comment by PawelTroka** [comment]
According to dependency walker SciLexer.dll in x64 version has only few dependencies:
![image](https://cloud.githubusercontent.com/assets/11928766/25378480/7d0d3524-29aa-11e7-833c-863fa5ed2ce9.png)
I guess all of those should be present on any modern Windows system out of the box
