### ISSUE TITLE
Extending a built-in Lexer to add addition patterns - Question

### ISSUE THREAD

**Issue by LordChariot** [jacobslusser/ScintillaNET#332]
I'm using ScintillaNET with the Lexer.Html. This is doing 99% of what I want, but there is one additional thing I would like some advice on.

I need to have an additional style that matches the pattern `$(AnyText Goes here)` or in other words, 
start pattern=`$(` 
end pattern=`)`

I know that SciLexer natively has that pattern defined in:
`# define SCLEX_MAKEFILE 11`
and
`#define SCE_MAKE_IDENTIFIER 3`
And I can access that in ScintillaNET by manually setting the values, but I can't seem to merge the 2 styles.  (Is that even possible to mix them?)

I have also looked at the Custom Syntax Highlighting Wiki page, but can't see a way to do this without duplicating the entire HTML/JavaScript Style set.

What is the best way to retain all the Styling of Lexer.Html and simply add single custom highlight?

**Comment by Ahmad45123** [comment]
You could use a lexer AND custom highlighting using `StartStyling` and `SetStyling`

**Comment by Ahmad45123** [comment]
See this: https://github.com/Ahmad45123/ExtremeStudio/blob/master/ExtremeStudio/DockPanel%20Forms/MainForm%20Docks/EditorDock/EditorDock.vb#L653-L759

Its in VB.NET but similar to C#.

**Comment by LordChariot** [comment]
Excellent! I wasn't sure if the native style would overwrite anything you manually set. I'll pick this apart and see what I can come up with.

**Comment by LordChariot** [comment]
Thanks @Ahmad45123

I guarantee I probably did this the wrong way, but it works.
I'm using Lexer.Html and it has a number of styles that will never match due to the source of the content. I just hijacked Style.Html.Asp with my own colors and used the code below.
Since I couldn't figure out where or when to DoColor(), I just perform it on the entire .Text for every UpdateUI. It seems so wrong but it works.

Unless someone can suggest a more efficient way, I'll keep it as is.

```c#
    private void scintilla1_UpdateUI(object sender, UpdateUIEventArgs e)
    {
      DoColor(0, scintilla1.Text, @"\$\(.*?\)", true);
    }
    private void DoColor(int startPos, string code, string rgx, bool isMultiLine = false)
    {
        foreach (Match mtch in Regex.Matches(code, rgx, (isMultiLine) ? RegexOptions.Multiline : RegexOptions.None))
        {
          int targetStartStyle = scintilla1.GetStyleAt(mtch.Index + startPos);
          int targetEndStyle = scintilla1.GetStyleAt(mtch.Index + startPos + mtch.Length - 1);
          scintilla1.StartStyling(mtch.Index + startPos);
          scintilla1.SetStyling(mtch.Length, Style.Html.Asp);
        }
    }
```

**Comment by Ahmad45123** [comment]
The updateui event is called every time the onscreen text changes, you are processing whole file every time something changes.. Put a huge file there and LAG.. So you would want to process only visible text. _(Why colorize stuff he can't see anyways ?)_

You also don't really need a `DoColor` function, I only use it cause I have lots, you only have one.

Optimized Code: 
```c#
private void scintilla1_UpdateUI(object sender, UpdateUIEventArgs e)
{
	var startPos = Editor.Lines[Editor.FirstVisibleLine].Position;
    var endPos = Editor.Lines[Editor.FirstVisibleLine + Editor.LinesOnScreen].EndPosition;
	var code = Editor.GetTextRange(startPos, endPos - startPos);
	foreach (Match mtch in Regex.Matches(code, @"\$\(.*?\)", RegexOptions.Multiline))
	{
	  int targetStartStyle = scintilla1.GetStyleAt(mtch.Index + startPos);
	  int targetEndStyle = scintilla1.GetStyleAt(mtch.Index + startPos + mtch.Length - 1);
	  scintilla1.StartStyling(mtch.Index + startPos);
	  scintilla1.SetStyling(mtch.Length, Style.Html.Asp);
	}
}
```

Insert a huge file and you should see a huge difference.

**Comment by Ahmad45123** [comment]
And btw, You can have custom styles.. You could do: 
`scintilla.Styles[3000].ForeColor = Color.FromArgb(163, 21, 21); // Red`
You can have any number in place of the 3000 and use it.

**Comment by LordChariot** [comment]
Oh, wow. That was a lot easier than I thought. That works perfectly and is exactly what I need. One of these days I'll actually learn how to program. 😄

**Comment by Ahmad45123** [comment]
Great :)

Also, i just noticed you don't even use this: 
```
int targetStartStyle = scintilla1.GetStyleAt(mtch.Index + startPos);
	  int targetEndStyle = scintilla1.GetStyleAt(mtch.Index + startPos + mtch.Length - 1);
```

I am on phone right now, so i can't get the code exactly for you, but look at my project there was something i had to make sure the thing you are styling is not already styled. It was below those 2 lines.
You want to add that to prevent styling something in a comment for example.
