### ISSUE TITLE
Question : How to avoid content removing through Ctrl+Z

### ISSUE THREAD

**Issue by MscrmTools** [jacobslusser/ScintillaNET#333]
Hi,
I noticed that when I show the code editor with some content, if the user performs a Ctrl+Z, code editor becomes empty.

So, is there a way to avoid this behavior or to remove the initial text display from undoable actions?

Thanks

**Comment by jacobslusser** [comment]
The `Scintilla.EmptyUndoBuffer` method is probably what you're looking for.

**Comment by MscrmTools** [comment]
Great! That was it !
