### ISSUE TITLE
Adding items to the right click Context menu

### ISSUE THREAD

**Issue by andy194** [jacobslusser/ScintillaNET#334]
Hi,

Is there a way to add items to the context menu yet?  I've tried getting the menu after initialisation but it's always null, yet appears with all the edit options intact when right clicking.

Thanks.

**Comment by andy194** [comment]
Apologies, found it.  For those looking, http://swensencode.blogspot.co.uk/2013/03/extending-scintilla-with-modifiable.html

This gets you almost there but need updating to work with the new version of ScintillaNET, otherwise it's fine.

**Comment by FilipRychnavsky** [comment]
Hello andy194,
the code in the mentioned link uses ScintillaNET Dll in version 2.0. What kind of updates should be done to work with the current version? Undo, Redo are not accessible.
I have used slightly different Scintilla methods for delegates (Undo, Redo).
[my ScintillaNET.Demo](https://github.com/FilipRychnavsky/ScintillaNET.Demo/blob/ContextMenuItem/ScintillaNET.Demo/StandardScintilla.cs)
Thanks
> This gets you almost there but need updating to work with the new version of ScintillaNET, otherwise it's fine.

**Comment by andy194** [comment]
Hi,

You need to drive a class from scintilla and then from the constructor call a private method...

`private void initContextMenu()
        {
            var cm = this.ContextMenu = new ContextMenu();

            this.miUndo = new MenuItem("Undo", (s, ea) => this.Undo());
            cm.MenuItems.Add(this.miUndo);

            this.miRedo = new MenuItem("Redo", (s, ea) => this.Redo());
            cm.MenuItems.Add(this.miRedo);

            cm.MenuItems.Add(new MenuItem("-"));

            this.miCut = new MenuItem("Cut", (s, ea) => this.Cut());
            cm.MenuItems.Add(miCut);

            this.miCopy = new MenuItem("Copy", (s, ea) => this.Copy());
            cm.MenuItems.Add(miCopy);

            cm.MenuItems.Add(new MenuItem("Paste", (s, ea) => this.Paste()));

            this.miDelete = new MenuItem("Delete", (s, ea) => this.ReplaceSelection(""));
            cm.MenuItems.Add(miDelete);

            cm.MenuItems.Add(new MenuItem("-"));

            this.miSelectAll = new MenuItem("Select All", (s, ea) => this.SelectAll());
            cm.MenuItems.Add(miSelectAll);
        }
`

This will then give you access to the Undo and Redo.

Andy.
