### ISSUE TITLE
Question: Is there any method for getting selected lines?

### ISSUE THREAD

**Issue by imnishil** [jacobslusser/ScintillaNET#335]
I want to use the LineCollection class to implement comment/uncomment.
Here's the code:
 private void commentToolStripMenuItem_Click(object sender, EventArgs e)
{
            textarea.BeginUndoAction();
            int eol;
            LineCollection l = textarea.Lines; // I want only selected lines here
            foreach (var line in l)
            {
                eol = line.Position;
                textarea.InsertText(eol, "#");
            }
            textarea.EndUndoAction();
                
}

**Comment by jacobslusser** [comment]
The `Scintilla.SelectionStart` and `Scintilla.SelectionEnd` properties will give you the start and end positions of the *main* selection. However, if you enable rectangular selections and/or multiple selections you'll need to dive into the `Scintilla.Selections` property to get information about that.
