### ISSUE TITLE
How do I integrate Scintilla with a WPF application?

### ISSUE THREAD

**Issue by imnishil** [jacobslusser/ScintillaNET#339]

**Comment by Stumpii** [comment]
You can drop a WindowsFormsHost control to the WPF form and set a ScintillaNet control as the child, as below (XAML). You can find step by step instructions by googling winforms control in WPF.

```
        <WindowsFormsHost>
            <ScintillaNET:Scintilla x:Name="MyScintilla"/>
        </WindowsFormsHost>
```

ScintillaNet 2 had a branch for WPF that was a WPF control that provided all the properties and methods required without the host getting the way, All my new projects are WPF, so it may be worth the effort of recreating it.

Would be interested in Jacobs two cents.

**Comment by jacobslusser** [comment]
@Stumpii, my world doesn't intersect with WPF at all these days so I don't have any plans to add direct WPF-specific support myself -- beyond what you get with the `WindowsFormsHost`. 

However, I know that leaves a lot to be desired, so a community project that is a superset of ScintillaNET or a companion to it which provides a WPF wrapper for exposing dependency properties, etc. would probably be a good idea. Something outside of the main repo.

**Comment by RNTRND** [comment]
Thanks for your help @Stumpii ! 
Can you help me in binding the Text property of Scintilla to my local string TextContent.
I am getting an error:
'Binding' can only be set on a DependencyProperty of a DependencyObject.

**Comment by imnishil** [comment]
Thanks for your help @Stumpii !
Can you help me in binding the Text property of Scintilla to my local string TextContent.
I am getting an error:
'Binding' can only be set on a DependencyProperty of a DependencyObject.

**Comment by Stumpii** [comment]
@imnishil , that appears to be the rub. It's not a WPF control, so it does not support all the WPF features and as it is not in a Winform form, it can't access those features either! There needs to be a wrapper that holds all the code to make it work seamlessly.

A web search for 'winformshost databinding' reveals a few topic, but I imagine that it is too much work to bother with to bind just one property,

**Comment by imnishil** [comment]
Thanks for your help @Stumpii and @jacobslusser !

**Comment by Stumpii** [comment]
I am working a WPF wrapper with demo at the moment which is going well. Should have something to show in a few days. There may be a couple of tweaks needed to ScintillaNet to all the WPF version access to all the behind the scene classes.

**Comment by imnishil** [comment]
Ohh that's great, it will be quite useful for the people who want to use WPF instead of Windows Forms!

**Comment by Stumpii** [comment]
So here is the WPF wrapper project: [ScintillaNET.WPF](https://github.com/Stumpii/ScintillaNET.WPF). Hopefully it will be of use to someone.

**Comment by jacobslusser** [comment]
Cool. I'll add a link to your project from the main project ReadMe.

**Comment by imnishil** [comment]
Thank you for your help @Stumpii !
