### ISSUE TITLE
Event timing reports old incorrect values for WrapCount

### ISSUE THREAD

**Issue by dspwhite** [jacobslusser/ScintillaNET#34]
I have a Scintillia control with lots of text in it. When I add a `ClientSizeChanged` event, and then maximize the window, when I then check the WrapCount value for all Lines in the document, Scintilla looks at what the old WrapCount values were. It seems as if they aren't updated in time.

Is it a subtle bug with Scintilla? I mean, I expect these kind of issues with events from time to time as the order in which things happen is important. Is there any hack around this?

To try and remedy the problem, I tried all the events out to see if I could find one that happened AFTER the WrapCount values were properly updated. I didn't find any, except possibly the StyleNeeded event. Well, first off, I'm sure the StyleNeeded event wasn't meant for this, and in my case, the event will be repeated needlessly. In any case, the correct WrapCount values are not reported first time around, so any solution along these lines will be a kludge regardless (perhaps allowing it to be called say a quarter of a second after it being first called, but not later than this - I know; sounds kludgy to say the least).

I have simplified the bug to a small sample project if you would like me to post the link to the VS project. Or maybe I could post the full designer code + Form1.cs code directly here.

**Comment by jacobslusser** [comment]
Quoting from the Scintilla documentation:

> Wrapping is not performed immediately there is a change but is delayed until the display is redrawn. This delay improves performance by allowing a set of changes to be performed and then wrapped and displayed once. Because of this, some operations may not occur as expected. If a file is read and the scroll position moved to a particular line in the text, such as occurs when a container tries to restore a previous editing session, then the scroll position will have been determined before wrapping so an unexpected range of text will be displayed. To scroll to the position correctly, delay the scroll until the wrapping has been performed by waiting for an initial SCN_PAINTED notification.

I added support for the `Painted` event in commit dbc381711fe87f66c7bbfc04f59cb96f7d149b79 if you want to use it. Be aware that the `Painted` event fires *often*. Very often. So you'll need to include some logic at the top of your `Painted` handler to determine whether it was raised for the reasons you're interested in.... otherwise your application logic will likely be run way more frequently than is necessary and cause you performance problems.

**Comment by dspwhite** [comment]
Works a treat - thank you for the prompt response!
