### ISSUE TITLE
Synchronize scrolling between 2 text controls

### ISSUE THREAD

**Issue by autovaton** [jacobslusser/ScintillaNET#343]
I am trying to synchronize scrolling between 2 ScintillaNET controls, but I can't find anything in the API that seems like it will work.  I am using the UpdateUI event to find out if the control has been scrolled (horizontally or vertically), but I can't find out how to tell how much it has been scrolled or how to scroll the other window the same amount.  Please advise.  Thank you.

**Comment by jacobslusser** [comment]
I seem to recall some similar questions in our forum, so you might double-check that this hasn't already been answered. To point you in the right direction, horizontal scrolling is by pixel and is get/set via the `XOffset` property. Vertical scrolling is by line and is thus get/set via the `FirstVisibleLine` property.

**Comment by autovaton** [comment]
I did check the forums (that's how I found UpdateUI), but I did not notice
anything that mentioned the other pieces.

This should get me started. I'll write back if I hit a wall.

Thank you.

Dave

**Comment by maulwuff** [comment]
maybe something like this:
```csharp
        int oldPos = 0;
        int newPos = 0;
        private void scintilla_UpdateUI(object sender, UpdateUIEventArgs e)
        {
            if (e.Change.HasFlag(UpdateChange.VScroll))
            {
                oldPos = newPos;
                newPos = _scintilla.FirstVisibleLine ;
                Debug.WriteLine($"scroll: {oldPos} {newPos} ");
            }
        }

```

and to make a certain line visible in the other control:

```csharp
        /// <summary>
        /// scroll the line into view
        /// </summary>
        /// <param name="lineIndex"></param>
        public void MakeLineVisible(int lineIndex)
        {
            if (_scintilla.Lines[lineIndex].Visible || _scintilla.Lines[lineIndex].FoldParent < 0)
            {//line is visible or has no parant fold node. translate into visible index because of folding.
                _scintilla.FirstVisibleLine = _scintilla.Lines[lineIndex].DisplayIndex;
            }
            else
            {//line not visible, try to show the parent of this line
                MakeLineVisible(_scintilla.Lines[lineIndex].FoldParent);
            }
        }
```
