### ISSUE TITLE
What happened to the Configuration class

### ISSUE THREAD

**Issue by jeanpf** [jacobslusser/ScintillaNET#344]
Is there a way to specify the styles and keywords from an XML file in the version 3 as it was in version 2?

**Comment by Stumpii** [comment]
Not that I am aware of. I had the same issue when writing a custom lexer for v3 when I upgraded from v2. Are you writing a custom lexer as well?

When writing my lexer, I ended up with some utility functions that let me read the SciTE .properties files which are pretty standard across Sci based editors and seemed a better option than recreating the XML again. I can share the routines if you like. They are pretty simple.

**Comment by jeanpf** [comment]
Hello Stumpii, I will be glad!

Just to explain my situation: I was trying to avoid to create a custom lexer. Here is my scenario: today we open some files in Notepad++ (that uses Scintilla on its core) and we created a custom style called "userDefineLang.xml" which Notepad++ reads and configurate Scintilla from it using SCI_SET* methods. But, now, we need to open those files in a C# application and, of course, we still want the colouring to be applied.

**Comment by jacobslusser** [comment]
Closing as answered.
