### ISSUE TITLE
Minimum initialization to style a document 

### ISSUE THREAD

**Issue by go2stars** [jacobslusser/ScintillaNET#345]
What is the minimum initialization to style a document with Lexer.Vb, i mean if i create document like this

Dim cDoc As ScintillaNET.Scintilla = New ScintillaNET.Scintilla
cDoc.Text = IO.File.ReadAllText(vb_file)

then what is properties/methods should i set/call to styling VB source code file including coloring and folding

**Comment by jacobslusser** [comment]
The wiki is your friend.

There's a VB syntax highlight sample -- written in VB -- here: [https://github.com/jacobslusser/ScintillaNET/wiki/User-Submitted-Recipes](https://github.com/jacobslusser/ScintillaNET/wiki/User-Submitted-Recipes)

**Comment by go2stars** [comment]
Thank you very much for all your great work.
