### ISSUE TITLE
Clamping over the number of keywords

### ISSUE THREAD

**Issue by jeanpf** [jacobslusser/ScintillaNET#347]
Hello, 

I just found out that the maximum number of keywords allowed is 8. Is there any reason for that? I am working in a project where I need it to be 16. So, is it possible to either let me change this max value or
let me disable the clamping?

Thanks

**Comment by jacobslusser** [comment]
Can you be more specific about what lexer you are using and what you are attempting to do?

**Comment by jeanpf** [comment]
I am using one lexer from Notepad++, for that I call the SetModulePath to point to their SciLexer.dll.
The lexer I am trying to use is the LexUser.cxx that has 15 keywords. And using their same logic to read a xml, that defines the styles and other properties, I read those keywords and some properties from it. 

At this point, I configure Scintilla calling the SetProperty and SetKeywords method. However, the SetKeywords only allows me to enter 8 keywords because it clamps to the NativeMethods.KEYWORDSET_MAX and, thus, I don't have the excpected behaviour I need.

**Comment by jacobslusser** [comment]
Got it. Thanks for the additional info.

So ya, don't know why your custom lexer is going outside of the generally accepted maximum, but I guess its free to do that if it wants to. What you would need to do is go around the ScintillaNET API and talk directly to Scintilla using `DirectMessage`. See:
[https://github.com/jacobslusser/ScintillaNET/wiki/Direct-Messages](https://github.com/jacobslusser/ScintillaNET/wiki/Direct-Messages)

By doing that you can basically do the same thing that is happening in the `SetKeywords` method, but without the clamping:
[https://github.com/jacobslusser/ScintillaNET/blob/v3.6.3/src/ScintillaNET/Scintilla.cs#L2303-L2310](https://github.com/jacobslusser/ScintillaNET/blob/v3.6.3/src/ScintillaNET/Scintilla.cs#L2303-L2310)

**Comment by jeanpf** [comment]
Thanks Jacob. That will work!
