### ISSUE TITLE
Problem with SetModulePath and Margins

### ISSUE THREAD

**Issue by jeanpf** [jacobslusser/ScintillaNET#348]
Hello, 

in my project I need to call the SetModulePath to point to another SciLexer.dll. However, when I do this, I don't get the Margins numbers working correctly. Actually, I don't see any number there. If I comment the line where I set the module path, the Margins works fine.

I did the same margin style as it is on the Demo project.

**Comment by jacobslusser** [comment]
It is difficult/impossible for me to provide support when you chose to use your own version of SciLexer.dll. At that point you have gone off the reservation and are on your own.
