### ISSUE TITLE
How to set caret to a specific line number ?

### ISSUE THREAD

**Issue by geoffw123** [jacobslusser/ScintillaNET#351]
Hi

I managed to get the old version on Scintilla.net working fairly easily, but I cant load that project anymore into VS2017 :(.

Therefore it looks like I am forced to upgrade to the new library. I have got stuck on something simple.
I have read the the docs but I can figure out how I can set the caret to a specific line number ?

There is a method  LineFromPosition(), so I thought the obvious way to do it is use a method
PositionFromLine() to figure out what position in the text I need to set the caret to. However I was surprised to discover that method doesn't exist, so I am currently stumped ?

Any help would be much appreciated.

Thanks Geoff

**Comment by Stumpii** [comment]
What I like about v3 is that is almost a direct equivalent to Scintilla, so the [Scintilla documentation](http://www.scintilla.org/ScintillaDoc.html) is invaluable help. A quick look through there shows the following function:

SCI_GOTOPOS(int caret)
This removes any selection, sets the caret at caret and scrolls the view to make the caret visible, if necessary. It is equivalent to SCI_SETSEL(caret, caret). The anchor position is set the same as the current position.

ScintillaNET has the same method:

Scintialla1.GotoPosition(123);

**Comment by geoffw123** [comment]
hello Stumpii

Thanks for the very speedy reply.  Yes I had noticed the method  Scintialla1.GotoPosition(123);
but with my understanding (admittedly not very good) and a quick experiment that doesnt set the caret to line number 123,  I think it sets it to character position 123 into the text file.

Can you confirm if its line number or character position ? I need to set it to line 123

Thanks Geoff

**Comment by Stumpii** [comment]
Another quick look at the scintilla documentation reveals:

SCI_POSITIONFROMLINE(int line) → position
This returns the document position that corresponds with the start of the line. If line is negative, the position of the line holding the start of the selection is returned. If line is greater than the lines in the document, the return value is -1. If line is equal to the number of lines in the document (i.e. 1 line past the last line), the return value is the end of the document.

ScintillaNET uses a collection of lines to expose information about lines, so:

int x = Scintilla1.Lines(123).Position;

is probably what you want.

**Comment by xv** [comment]
This is what I use. Notice the -1 there. This is because Scintilla includes the 0 in counting, so without the -1 if would go to line 124

```c#
var lineNum = 123;
scintilla.Lines[lineNum -1].Goto();
```

**Comment by geoffw123** [comment]
Hi Both

Thanks very much for the assistance,  that was exactly what I was looking for.
``scintilla.Lines[lineNumber - 1].Goto();`  worked.
I had assumed lines was a simply array so would have struggled to figure that out.

To be honest I am not liking V3 compared to the old version, its so much more work to do what I want.
I need to figure out how to add autocompletion, intellisense, find/replace. where I got most of that "free" of effort in V2.
Thanks Stumpii for contributing the find file dialog example, that should be useful to me !!

Regards Geoff
