### ISSUE TITLE
How to speed up custom ReplaceAll method?

### ISSUE THREAD

**Issue by go2stars** [jacobslusser/ScintillaNET#352]
The following code take about **5 MINUTES** to replace 30,000 occurrences.

```
Me.Scintilla.TargetStart = 0
Me.Scintilla.TargetEnd = Me.Scintilla.TextLength
Me.Scintilla.SearchFlags = SearchFlags.None
Do While Me.Scintilla.SearchInTarget(strText) <> -1
    Me.Scintilla.ReplaceTarget(strReplace)
    Me.Scintilla.TargetStart = Me.Scintilla.TargetEnd
    Me.Scintilla.TargetEnd = Me.Scintilla.TextLength
Loop

```
While the following code takes only **20 milliseconds** to replace the same 30,000 occurrences.
```
Me.Scintilla.Text = Me.Scintilla.Text.Replace(strText, strReplace)
```
I set SearchFlags to None, so this huge process time is not caused by Regex or so.

Did i used the correct way using built-in **ReplaceTarget** method?

**Comment by go2stars** [comment]
Anyone please!

**Comment by jacobslusser** [comment]
Off the top of my head, some things that might improve your performance are:
1. Your search is re-searching already replaced areas. Instead of starting each search at the beginning of the document, keep a reference to the last place searching stopped and then resume at that place.
2. Try searching/replacing from the end of the document to the start. You can do that by making the `TargetStart` greater than the `TargetEnd`. By searching and replacing from end to start there **might** be less shifting of the text data and result in increase performance.
3. Finally, this might not provide much lift, but you can use the `SetTargetRange` method to set start and end in a single call.

**Comment by go2stars** [comment]
Thank you for replying

> Instead of starting each search at the beginning of the document, keep a reference to the last place searching stopped and then resume at that place.

This is exactly what above code do, see **Me.Scintilla.TargetStart = Me.Scintilla.TargetEnd** inside the loop.

Anyway until i found a solution I had changed the code to use **Text.Replace** method if SearchFlags is None

```
If Me.Scintilla.SearchFlags = SearchFlags.None Then
    Me.Scintilla.Text = Me.Scintilla.Text.Replace(strText, strReplace)
Else
    Me.Scintilla.TargetStart = 0
    Me.Scintilla.TargetEnd = Me.Scintilla.TextLength
    Do While Me.Scintilla.SearchInTarget(strText) <> -1
        Me.Scintilla.ReplaceTarget(strReplace)
        Me.Scintilla.TargetStart = Me.Scintilla.TargetEnd
        Me.Scintilla.TargetEnd = Me.Scintilla.TextLength
    Loop
End If
```

**Comment by jacobslusser** [comment]
Sorry, I should have looked at your code closer. My brain is elsewhere.

**Comment by aolszowka** [comment]
The underlying implementation is probably what's slowing you down with the sheer number of replacements, I don't think they intended that to be called in such a tight loop.

If you look at the implementation of the underlying library (https://sourceforge.net/p/scintilla/code/ci/default/tree/src/Editor.cxx#l5499) there is a lot of work that is redone every time you make a call to "ReplaceTarget".

 Sci::Position Editor::ReplaceTarget(bool replacePatterns, const char *text, Sci::Position length) {
	UndoGroup ug(pdoc);
	if (length == -1)
		length = istrlen(text);
	if (replacePatterns) {
		text = pdoc->SubstituteByPosition(text, &length);
		if (!text) {
			return 0;
		}
	}
	if (targetStart != targetEnd)
		pdoc->DeleteChars(targetStart, targetEnd - targetStart);
	targetEnd = targetStart;
	const Sci::Position lengthInserted = pdoc->InsertString(targetStart, text, length);
	targetEnd = targetStart + lengthInserted;
	return length;
}


For every Replace Target:
- The target string is casted using reinterpret_cast; this can be costly in and of itself (See the *CharPtrFromSPtr(sptr_t lParam) call)
- The length of the replacement string is calculated (See int istrlen(const char *s))
- The replacement characters are deleted
- The string in inserted (in Document.cxx which looks to be an expensive call in and of itself)

It'd be nice if the underlying library provided for a "ReplaceAll" that was more heavily optimized like Text.Replace() is (which I assume is calling the C# String.Replace() implementation; which doesn't do any of this mubo-jumbo).

Your best bet is to post up stream and hope they implement a lighter-weight replace all (this project is just simply a wrapper around that library). Bonus points for including your test case (sanitized of course).

**Comment by jacobslusser** [comment]
Closing as answered.
