### ISSUE TITLE
Update to use Scintilla 4.0

### ISSUE THREAD

**Issue by wmjordan** [jacobslusser/ScintillaNET#354]
They are releasing a new version about two months ago.
Is it possible to follow with the new API and wrap a new ScintillaNET?

**Comment by jacobslusser** [comment]
Not yet. Version 4.0 of Scintilla is a major change and by its own admission, the API is still in flux. When things calm down we can revisit the idea.

**Comment by jacobslusser** [comment]
Closing for now.
