### ISSUE TITLE
ScintillaNET 3.6.3.0 Basic Autocompletion

### ISSUE THREAD

**Issue by snak31** [jacobslusser/ScintillaNET#355]
Hello I contact you because I have a worry with the self completion of ScintillaNET.
The problem is that he can not get to the next word. I have the "WordStartPosition" function that always goes back 0. I took the same code as the example (https://github.com/jacobslusser/ScintillaNET/wiki/Basic-Autocompletion)
Thanks for your help :)

**Comment by jenokizm** [comment]
I use it https://github.com/Ahmad45123/AutoCompleteMenu-ScintillaNET
