### ISSUE TITLE
Button and/or Image

### ISSUE THREAD

**Issue by Aghlara** [jacobslusser/ScintillaNET#357]
Hi everyone,

Is there any way we can add a combination text, image and button in the editor. Texts are just text but for button and images, when users click we do need to do something.
I get we can add a text with slyle that appears as a hyper link and handle mouse down events for that. But wondering about image or button etc.

Regards,
Arash

**Comment by jacobslusser** [comment]
No.

A longshot option you might try is to add a child Button control to Scintilla (or just place one over top of it) and watch an event like `UpdateUI` to constantly recalculate the position of the button based on the current scroll values, etc. But like I said, that would be trying to use Scintilla in a way it was never intended so it would be a longshot.
