### ISSUE TITLE
Cannot seem to find a way to customize the highlighting of a <script> inside HTML

### ISSUE THREAD

**Issue by HitCoder9768** [jacobslusser/ScintillaNET#358]
I'm making syntax highlighting for HTML but I can't find a HTML style that changes the syntax highlighting of a script. I've done as follows

`scintilla.Styles[Style.Html.Script].ForeColor = Color.LightSteelBlue;
scintilla.Styles[Style.Html.Script].BackColor = Color.FromArgb(30, 30, 30);`

but this seems to affect nothing at all.
I have also tried modifying the CPP syntax highlighting, thinking that it maybe switches to that when a script is initiated.

Is there currently a way to syntax highlight scripts in HTML? If so, what am I doing wrong?

EDIT: this is a screenshot of the result: https://puu.sh/y2EHp/60755503ee.png

**Comment by jacobslusser** [comment]
The `GetStyleAt` method will tell you which style is at a given character position. Try using it within some of your script text to determine which style you should be setting.

**Comment by HitCoder9768** [comment]
Thanks;; the script regions of the HTML happened to be using the IDs 40, 41 and 46 (though I'm highlighting all three of these the same and can't remember which is which part), and I believe I changed the <!DOCTYPE html> part highlighting, which used the IDs 21 and 26.
Thanks for your help!
