### ISSUE TITLE
Drag text to change position

### ISSUE THREAD

**Issue by xonyen** [jacobslusser/ScintillaNET#36]
Hi Jacob,
Is there a simple way to support text dragging?

**Comment by jacobslusser** [comment]
Native Scintilla supports dragging text within the control, however, this ability was disabled with the implementation of standard Windows Forms Drag & Drop support in issue #6.

**Comment by gena03** [comment]
I'm still a novice. That is written Drag & Drop ...

`Imports System.Runtime.InteropServices`
`Public Class Form1`

	Const SCI_GETSELECTIONS = 2570
	Const SCI_GETSELECTIONSTART = 2143
	Const SCI_GETSELECTIONEND = 2145
	Const SCI_SELECTIONISRECTANGLE = 2372
	Const SCI_GETFIRSTVISIBLELINE = 2152
	Const SCI_LINESONSCREEN = 2370
	Const SCI_GETLINESELENDPOSITION = 2425
	Const SCI_GETLINESELSTARTPOSITION = 2424
	Const SCI_FINDCOLUMN = 2456
	Const SCI_TEXTHEIGHT = 2279

	Private flag As Boolean = False
	Private flag_DragEnter As Boolean = False
	Private flag_ALT As Boolean = False
	Private flag_Move As Boolean = False
	Private cursor_Width As Integer = 1
	Private cursor_Height As Integer = 20
	Private caret As Integer = 0
	Private pos_Start As Integer = 0
	Private pos_End As Integer = 0
	Private clipboard As String = ""
	Private column_Start As Integer = 0
	Private column_End As Integer = 0
	Private line_vis As Integer = 0
	Private line_sel As Integer = 0
	Private sign_sel As Integer = 0
	Private IntPtr_line As IntPtr = Marshal.AllocHGlobal(4)
	Private IntPtr_column As IntPtr = Marshal.AllocHGlobal(4)

	Private Sub Form1_Load(sender As System.Object, e As System.EventArgs) Handles MyBase.Load
		Scintilla1.AllowDrop = True
		With Scintilla1.Styles(ScintillaNET.Style.Default) : .Font = "Lucida Console" : .Size = 12 : End With
	End Sub

	'The event - the beginning of a drag operation
	Private Sub Scintilla1_DragEnter(ByVal sender As System.Object, ByVal e As System.Windows.Forms.DragEventArgs) Handles Scintilla1.DragEnter
		cursor_Width = Scintilla1.CaretWidth
		cursor_Height = Scintilla1.DirectMessage(SCI_TEXTHEIGHT, IntPtr.Zero, IntPtr.Zero) - 1
		flag_DragEnter = True
		Scintilla1.CaretWidth = 0
		pos_Start = Scintilla1.DirectMessage(SCI_GETSELECTIONSTART, IntPtr.Zero, IntPtr.Zero)
		pos_End = Scintilla1.DirectMessage(SCI_GETSELECTIONEND, IntPtr.Zero, IntPtr.Zero)
		If Scintilla1.DirectMessage(SCI_SELECTIONISRECTANGLE, IntPtr.Zero, IntPtr.Zero) Then
			column_Start = Scintilla1.GetColumn(pos_Start)
			column_End = Scintilla1.GetColumn(pos_End)
			flag_ALT = True	'the text has been selected frame (Alt - key)
		Else
			flag_ALT = False 'normal text selection
		End If
		line_vis = Scintilla1.DirectMessage(SCI_LINESONSCREEN, IntPtr.Zero, IntPtr.Zero) - 1
	End Sub

	'Event - during all dragging
	Private Sub Scintilla1_DragOver(ByVal sender As System.Object, ByVal e As System.Windows.Forms.DragEventArgs) Handles Scintilla1.DragOver
		Dim new_pos = Scintilla1.CharPositionFromPoint(Scintilla1.PointToClient(New Point(e.X, e.Y)).X, Scintilla1.PointToClient(New Point(e.X, e.Y)).Y)
		If Not new_pos = caret Then
			Scintilla1.Refresh() 'delete the previous position of the new cursor
			Dim x = Scintilla1.PointXFromPosition(new_pos)
			Dim y = Scintilla1.PointYFromPosition(new_pos)
			Dim g As Graphics = Scintilla1.CreateGraphics()
			Dim pen1 As New System.Drawing.Pen(Color.Red, cursor_Width + 1)	'the color and the thickness of the new cursor
			g.DrawLine(pen1, x, y, x, y + cursor_Height) 'draw new cursor
		End If
		caret = new_pos
		Dim pos_None = False
		If (caret > pos_Start AndAlso caret < pos_End) Then
			If flag_ALT Then
				Dim curr = Scintilla1.GetColumn(caret)
				If (curr > column_Start AndAlso curr < column_End) Then
					pos_None = True
				End If
			Else
				pos_None = True
			End If
		End If
		flag_Move = False
		If pos_None Then ' "dead" zone
			e.Effect = DragDropEffects.None
			Scintilla1.Refresh()
		ElseIf ((e.KeyState And 8) = 8 And (e.AllowedEffect And DragDropEffects.Copy) = DragDropEffects.Copy) Then
			e.Effect = DragDropEffects.Copy	' Did you press the Ctrl - up.
		ElseIf ((e.AllowedEffect And DragDropEffects.Move) = DragDropEffects.Move) Then
			e.Effect = DragDropEffects.Move	'Default - Move.
			flag_Move = True
		Else
			e.Effect = DragDropEffects.None
		End If
		'If the target is outside the visible window:
		Dim line_Up As Integer = Scintilla1.DirectMessage(SCI_GETFIRSTVISIBLELINE, IntPtr.Zero, IntPtr.Zero)
		Dim line_Down = line_Up + line_vis
		Dim line_cur = Scintilla1.LineFromPosition(caret)
		If line_cur = line_Up Then
			Scintilla1.LineScroll(-1, 0)
		ElseIf line_cur = line_Down Then
			Scintilla1.LineScroll(1, 0)
		End If
	End Sub

	'The event - with zaverschenii drag operation (not performed if DragDropEffects.None)
	Private Sub Scintilla1_DragDrop(ByVal sender As System.Object, ByVal e As System.Windows.Forms.DragEventArgs) Handles Scintilla1.DragDrop
		flag = True
		Scintilla1.BeginUndoAction()
		clipboard = My.Computer.Clipboard.GetText()
		Scintilla1.Copy()
		If flag_Move Then
			If flag_ALT Then
				'if you select the rectangle (Alt - key):
				IntPtr_line = Scintilla1.LineFromPosition(pos_Start)
				sign_sel = Scintilla1.DirectMessage(SCI_GETLINESELENDPOSITION, IntPtr_line, IntPtr.Zero) - Scintilla1.DirectMessage(SCI_GETLINESELSTARTPOSITION, IntPtr_line, IntPtr.Zero)
				line_sel = Scintilla1.DirectMessage(SCI_GETSELECTIONS, IntPtr.Zero, IntPtr.Zero) - 1
				Dim line_caret = Scintilla1.LineFromPosition(caret)
				IntPtr_line = line_caret
				If Scintilla1.GetColumn(caret) > column_End And (line_caret >= Scintilla1.LineFromPosition(pos_Start) AndAlso line_caret <= Scintilla1.LineFromPosition(pos_End)) Then
					caret -= sign_sel
				End If
				IntPtr_column = Scintilla1.GetColumn(caret)
			ElseIf (caret > pos_Start OrElse caret >= pos_End) Then
				caret = caret - (pos_End - pos_Start)
			End If
		End If
	End Sub

	Private Sub Scintilla1_MouseMove(ByVal sender As System.Object, ByVal e As System.Windows.Forms.MouseEventArgs) Handles Scintilla1.MouseMove
		If flag_DragEnter Then
			Scintilla1.CaretWidth = cursor_Width
			Scintilla1.Refresh()
			flag_DragEnter = False
		End If
		If flag Then
			If flag_ALT Then
				If flag_Move Then
					caret = Scintilla1.DirectMessage(SCI_FINDCOLUMN, IntPtr_line, IntPtr_column)
				End If
				Scintilla1.SetSel(caret, caret)
				Scintilla1.Paste()
				' Select the inserted text:
				IntPtr_column = Scintilla1.GetColumn(caret + sign_sel)
				IntPtr_line = Scintilla1.LineFromPosition(caret) + line_sel
				Scintilla1.RectangularSelectionCaret = Scintilla1.DirectMessage(SCI_FINDCOLUMN, IntPtr_line, IntPtr_column)
				Scintilla1.RectangularSelectionAnchor = caret
			Else
				Scintilla1.SetSel(caret, caret)
				Scintilla1.Paste()
				'Select the inserted text:
				Scintilla1.SetSel(caret, caret + (pos_End - pos_Start))
			End If
			My.Computer.Clipboard.SetText(clipboard)
			Scintilla1.EndUndoAction()
			flag = False
		End If
	End Sub

	Private Sub Scintilla1_MouseDoubleClick(ByVal sender As System.Object, ByVal e As System.Windows.Forms.MouseEventArgs) Handles Scintilla1.MouseDoubleClick
		Scintilla1.Cursor = Cursors.Default
		Cursor.Position = New Point(Cursor.Position.X + 4, Cursor.Position.Y) 'ignore the third-click (select an entire row). So far, so ...
	End Sub
`End Class`
