### ISSUE TITLE
SQL Lexer does not account for bracketed identifiers

### ISSUE THREAD

**Issue by Metritutus** [jacobslusser/ScintillaNET#362]
When using the SQL Lexer, if I type some text and surround it with square brackets, I would expect the Lexer to style the contents differently to how it would otherwise, like for when single or double quotes are used for strings.

Currently, with 'select' and 'from' as keywords, and keywords styled to have a foreground colour of blue, the following example would show the `select` in the square brackets highlighted in blue, as well as the `select` and `from` outside of the square brackets:
`SELECT * FROM [dbo].[select]`

An example of the desired syntax-highlighting behaviour can be seen in Microsoft's SQL Server Management Studio.

Is this a bug or a missing feature?  If it's unlikely to be fixed/implemented, is there anything I can do to implement the functionality in my project myself (ie a custom Lexer based on the existing SQL Lexer, etc)?

Further reading:
https://technet.microsoft.com/en-us/library/ms176027.aspx

**Comment by jacobslusser** [comment]
The SQL lexer is provided by the native Scintilla component. Any enhancements would need to be made there.
