### ISSUE TITLE
Keys combination is seen as text on VB

### ISSUE THREAD

**Issue by ITmasc** [jacobslusser/ScintillaNET#364]
When I press CTRL+S (for example) scintilla writes some weird characters on it.. any workaround for this?
I have overrided the keyDown function with particular operations, but it writes on the editor too, that's weird.

**Comment by xv** [comment]
It's a native Scintilla behavior. The "weird characters" and suppressed when you assign a keybinding, whether it's to your form (such as menu shortcuts) or Scintilla itself.  See #175.
