### ISSUE TITLE
An event for pasting?

### ISSUE THREAD

**Issue by toehead2001** [jacobslusser/ScintillaNET#368]
I would like to execute some code after text has been pasted.  Is there a way to detect a paste operation?

**Comment by jacobslusser** [comment]
Have you looked into the `BeforeInsert` event? [https://github.com/jacobslusser/ScintillaNET/wiki/Intercepting-Inserted-Text](https://github.com/jacobslusser/ScintillaNET/wiki/Intercepting-Inserted-Text)

**Comment by toehead2001** [comment]
Yeah, but how would I restrict the action to only execute when a paste has occurred?

**Comment by jacobslusser** [comment]
You're right, this wouldn't tell you specifically the change is coming from a paste operation. The only other thing I can think of is to intercept the WM_PASTE or similar message. See: [https://msdn.microsoft.com/en-us/library/windows/desktop/ms649028(v=vs.85).aspx](https://msdn.microsoft.com/en-us/library/windows/desktop/ms649028(v=vs.85).aspx)

**Comment by jacobslusser** [comment]
Closing for now as question answered.
