### ISSUE TITLE
Unable to use as winForms control

### ISSUE THREAD

**Issue by Gizego** [jacobslusser/ScintillaNET#369]
Hello. I just downloaded this api to make an IDE for my programming language but i am doing it this way:
menu.Show(richTextBox1, false);
because the control is not appearing in my toolbox. Also how do I add images(i am using nugget)? Thanks

**Comment by Stumpii** [comment]
You can't show images in the control.

You can check out the demo and look at the source code on how to use the control: https://github.com/robinrodricks/ScintillaNET.Demo
