### ISSUE TITLE
Not raise the CharAdded event after insert a '\t'?

### ISSUE THREAD

**Issue by xonyen** [jacobslusser/ScintillaNET#37]
Hi Jacob
It seems that it's not to raise the CharAdded event after insert a '\t'. Is this a bug or a feature?

**Comment by jacobslusser** [comment]
This is a "feature". The native Scintilla documentation states that the `CharAdded` event:
> ... is sent when the user types an ordinary text character (as opposed to a command character) that is entered into the text.

**Comment by xonyen** [comment]
Maybe I should use the Insert event. I'll have a try about the insert event. Thanks Jacob.
