### ISSUE TITLE
Is there a way to customize the comment literals?

### ISSUE THREAD

**Issue by Visual-Vincent** [jacobslusser/ScintillaNET#371]
I'm working on a customizable script editor, in which I need to be able to modify some fundamentals of a lexer. Currently all languages made for my application are based on the C++ lexer.

Is there a way to customize what literals to use for comments, or would that require me to create a completely new lexer?

For instance, C++'s comment literals are `//`, `/*`, `*/` and `///` (documentation comments). Is it possible to change them to something else, like for example: `#`, `#{`, `}#` and `##`?

Thanks!

----

If I have to create my own lexer I also have a follow up question:

I've read the [Custom Syntax Highlighting](https://github.com/jacobslusser/ScintillaNET/wiki/Custom-Syntax-Highlighting) article on the wiki. When is the `StyleNeeded` event actually raised (i.e. when does the document need to be restyled) and what does `startPos` and `endPos` represent?

Is it:

- When you've written a whole word and added a whitespace/punctuation character? (making `startPos` and `endPos` the bounds of that word)
- For every new character of a word?
- For every new character at any time?
- (other?)

**Comment by xv** [comment]
As far as I know, Scintilla's lexers are not extensible or modifiable. That leaves you with the choice of writing your own lexer, which is a topic I have very little knowledge on. Perhaps someone else can offer better help.

**Comment by Visual-Vincent** [comment]
@xv Thanks for your reply! Sorry for replying so late... After further looking into this it seems, as you say, that writing a custom lexer is the best, so that's what I'm going to (at least try to) do.

**Comment by Visual-Vincent** [comment]
Creating a custom lexer was the solution, thanks!
