### ISSUE TITLE
Is it possible Re-define SetKeywords(); at the runtime?

### ISSUE THREAD

**Issue by alimsahy** [jacobslusser/ScintillaNET#374]
Hi,

I am currently working on small C++ editor and i want to re-define SetKeywords() function when i add new preprocessor at the runtime. So, i want to highlight added preprocessor's where i use it. Is it possible?

**Comment by Ahmad45123** [comment]
Let me know what you did ^_^

**Comment by alimsahy** [comment]
1) Control: I'am checking inserted text. User will press enter, program will re-parse script.
![1](https://user-images.githubusercontent.com/5039536/35285423-07cfc87e-0066-11e8-93a1-2a6a4d3e17c3.PNG)

2) Parsing: Parser will control every lines of script. If line starts with #define, i will add #define name to list. Parser function also passing parameter to SetLexer (Step 3) function with define list.
![2](https://user-images.githubusercontent.com/5039536/35285495-32f66850-0066-11e8-9288-c8f96fbbbe9d.PNG)

3) Lexer & Keywords: As you can see, i will redeclare SetWords(1)  with pros parameter which is coming from parser class.
![3](https://user-images.githubusercontent.com/5039536/35285680-b37beb6c-0066-11e8-9ab6-774f586f40de.PNG)

Result: Defined preprocessors will highlighted where they used. It perferct right? :D
![4](https://user-images.githubusercontent.com/5039536/35285850-0fe758f0-0067-11e8-9396-b9460f490d5a.PNG)
