### ISSUE TITLE
how to change the background color of selected text?

### ISSUE THREAD

**Issue by sczybt** [jacobslusser/ScintillaNET#375]
i am creating a xml editor use ScintillaNet。this is the style code which is changed from the demo:
`TextArea.StyleResetDefault();
			TextArea.Styles[Style.Default].Font = "Consolas";
			TextArea.Styles[Style.Default].Size = 12;
			TextArea.Styles[Style.Default].BackColor = Color.White;
            TextArea.Styles[Style.Default].ForeColor = Color.Black;
            
            TextArea.StyleClearAll();

            TextArea.Styles[Style.Xml.Default].ForeColor = Color.Black;
            TextArea.Styles[Style.Xml.Tag].ForeColor = Color.Blue;            
            TextArea.Styles[Style.Xml.Attribute].ForeColor = Color.Red;
            TextArea.Styles[Style.Xml.Number].ForeColor = Color.Pink;
            TextArea.Styles[Style.Xml.SingleString].ForeColor = Color.FromArgb(128,0,255);
            TextArea.Styles[Style.Xml.DoubleString].ForeColor = Color.FromArgb(128, 0, 255);
            TextArea.Styles[Style.Xml.Comment].ForeColor = Color.Green;
            TextArea.Styles[Style.Xml.XmlStart].ForeColor = Color.Black;
            TextArea.Styles[Style.Xml.XmlEnd].ForeColor = Color.Black;
            
            TextArea.Lexer = Lexer.Xml;
            TextArea.CaretLineBackColor = Color.Yellow;
            TextArea.CaretLineVisible = true;`

but when i select text in the editor, it looks like bad, so i wan to know how to change the selected text background color, thank you.

**Comment by xv** [comment]
Use:
```c#
TextArea.SetSelectionForeColor(...);
TextArea.SetSelectionBackColor(...);
```

**Comment by jacobslusser** [comment]
Closing as answered.
