### ISSUE TITLE
How can I change DoubleClick Selection Mode (lastest dll version) ??

### ISSUE THREAD

**Issue by venerealulcer** [jacobslusser/ScintillaNET#376]
![image](https://user-images.githubusercontent.com/15730936/36015995-f3130592-0dab-11e8-89d8-1b26e2e11b31.png)

just like above image, left-double click the 'transfer' , Scintilla will only select 'transfer';

but, what i need look like this (Select whole word 'mipi_transfer'):

![image](https://user-images.githubusercontent.com/15730936/36016061-4900bef4-0dac-11e8-9fbc-35db552677fb.png)

the letter '_' influences Selection Mode!!!

what can i do ? thks.

**Comment by jacobslusser** [comment]
Actually, what I think might help you is the `Scintilla.WordChars` property. That's what tells Scintilla what to consider a "word boundary" Add underscore to that list and it will consider it a word character as well and thus your whole "mipi_transfers" variable name.

**Comment by venerealulcer** [comment]
thks, that works
