### ISSUE TITLE
ShowWhitespace have a minimum (or better yet constant) arrow width for tab character

### ISSUE THREAD

**Issue by taylour** [jacobslusser/ScintillaNET#377]
![scintillanet](https://user-images.githubusercontent.com/4664989/36712263-fa0823ac-1b55-11e8-901f-6be4b7c146a0.png)

When I want to view whitespace, the tab character seems to sometimes display the arrow character at a very small width (sometimes so small that it is indistinguishable from a dot). Ideally I would like the arrow width to be a constant size if it is possible. If it isn't possible to have the arrow width a constant size, then there should be a way to at least make it have a minimum width. Please see screenshot where I compare the same text in ScintillaNet and Notepad++. With Notepad++, the arrows for the tabs are different sizes, but there is at least a minimum width. With ScintillaNet, the arrows are also different widths but the minimum width is incredibly small (and gets smaller than this with other example text). I have looked at the various properties available but didn't see a way to do this.

`TabWidth = 4;`
`WhitespaceSize = 4;`
`TabDrawMode = TabDrawMode.LongArrow;`
`SetWhitespaceForeColor(true, Color.DarkOrange);`

Thanks for your help and the great control!

**Comment by xv** [comment]
The whitespace chars are font-dependent. In other words, it is the font you are using that is causing the arrows not to render as you wish. This also applies to Notepad++/native Scintilla.

Change the font to Consolas or Courier New and I am certain the result will be different.

**Comment by taylour** [comment]
thanks for your help. Courier New has the arrows looking much nicer than Calibri, which I was using before.
