### ISSUE TITLE
Separator Line

### ISSUE THREAD

**Issue by Aghlara** [jacobslusser/ScintillaNET#378]
Hi, 
I have a quick question that I could not find any the answer anywhere. I have a DSL and for each block of definition I want to add a Separator line. Something like below:

![image](https://user-images.githubusercontent.com/5187409/37554668-39707cd6-2a30-11e8-8009-cf01283d7f0a.png)

This is an image from Notepad++ but I want to add the separator line based on the DSL logic. When a block is finished, add that line.

**Comment by Stumpii** [comment]
Maybe SC_MARK_UNDERLINE

http://www.scintilla.org/ScintillaDoc.html

**Comment by Aghlara** [comment]
Thanks, how can I do it in ScintillaNET? Any sample code in ScintillaNET?

**Comment by Aghlara** [comment]
OK, I figured it out. Thanks for pointing to add Underline Marker.

Here is what worked for me if anyone else has the question:
      
```
public void AddUnderline(int line)
{
    if (line == -1)
        return;

    if (_markerUnderline == null)
    {
        _markerUnderline = Markers[7];
        _markerUnderline.Symbol = MarkerSymbol.Underline;
        _markerUnderline.SetBackColor(Color.Gray);
        _markerUnderline.SetForeColor(Color.Gray);
    }

    Lines[line].MarkerAdd(_markerUnderline.Index);
}
```
