### ISSUE TITLE
Access Violation Exception

### ISSUE THREAD

**Issue by Aghlara** [jacobslusser/ScintillaNET#379]
We do I get this exception randomly from Scintilla?

![image](https://user-images.githubusercontent.com/5187409/37561996-2365bc54-2ab1-11e8-9310-2ede29d07e54.png)

**Comment by Aghlara** [comment]
I'll try to see if I can produce it relaibalely. Thanks.

**Comment by jacobslusser** [comment]
Closing for now, but can reopen if you get details.
