### ISSUE TITLE
Background Marker and Custom Style

### ISSUE THREAD

**Issue by Aghlara** [jacobslusser/ScintillaNET#380]
What is the order of execution for:
- StyleNeeded
- Applying Markers

When I apply maker for Background, it overwrites the Style of the text. I would have thought background goes to the back of the Style not top of it. 

Am I missing something here?

**Comment by Aghlara** [comment]
How can I apply background Marker and then have the Styling of the text on top?

**Comment by Stumpii** [comment]
Certainly makes sense for the marker to be applied on top of the style. Just imagine a C# editor with the selected line highlighted. Would not be possible if the marker is ignored. Sounds like you need multiple background markers of different colours? Or use a different marker. Screen shot of use would be useful.

**Comment by Aghlara** [comment]
Thanks for the response.

![image](https://user-images.githubusercontent.com/5187409/37580632-f06c1922-2b98-11e8-838b-bc8d9679bcf5.png)

We have multiple of these sections. And would like to change the background color of the sections based on status of the section i.e. new, deleted, modified,...

**Comment by jacobslusser** [comment]
I believe your original statement is correct... that markers render on top of styles. The original Scintilla documentation may provide more information, but if I recall, the Visual Studio breakpoint is a good example. Visual Studio highlights the whole row in red AND changes any foreground styling to plain white. This is the approach that I believe Scintilla tries to mimic.

**Comment by Aghlara** [comment]
So how do I achieve this behaviour like the image above? Any solution?

**Comment by jacobslusser** [comment]
Closing this for now but can reopen if you still need to discuss.
