### ISSUE TITLE
MarginRightClick never gets fired

### ISSUE THREAD

**Issue by ajan1966** [jacobslusser/ScintillaNET#381]
Hi, I am trying to use MarginRightClick Event. But whatever I do, the Event doesn't fire.
I have tried to set UsePopup to false, also to PopUpMode.Text, but i can't get MarginRightClick to Work.
What have I missed?
Thanks in advance.

**Comment by jacobslusser** [comment]
Is your margin flagged as ‘Sensitive’ to mouse clicks?

**Comment by ajan1966** [comment]
Yes it is, I have checked double. For testing purpose I used the ScintillaNet.Demo Application. I have checked that the margins are set to sensitive - they are. Doing a RightClick in the margin opens the expected default popup-menu.
I then added

```
           TextArea.UsePopup(PopupMode.Text);
           TextArea.MarginRightClick += TextArea_MarginRightClick;
```
at the end of Mainform.Load and also added
```
        private void TextArea_MarginRightClick(object sender, MarginClickEventArgs e)
        {
            MessageBox.Show("Test");
        }
```
But the MessageBox never shows up and in debug mode the method never gets called.

**Comment by xv** [comment]
I was digging into this and found this change in v3.7.1 [changelog](http://www.scintilla.org/ScintillaHistory.html) (we're at v3.6.3).

![changelog](https://i.imgur.com/EKPTfiy.png)

**Comment by xv** [comment]
I was digging into this and found this change in v3.7.1 [changelog](http://www.scintilla.org/ScintillaHistory.html) of native Scintilla (we're at v3.6.3).

![changelog](https://i.imgur.com/EKPTfiy.png)

Perhaps that explains why `MarginRightClick` event isn't firing.

**Comment by jacobslusser** [comment]
Did you try changing the `Scintilla.UsePopup` properties to verify?
