### ISSUE TITLE
Vertical scrollbar always shown

### ISSUE THREAD

**Issue by graduenz** [jacobslusser/ScintillaNET#382]
I would like to know if there is a possibility to have an always shown vertical scrollbar on the Scintilla control, and if it is, how?

I tried to do it on my own, but I've failed. After cloning the repository and trying to discover how the current scroll controls works, I gave up, sorry!

Thank you for any hint!

**Comment by xv** [comment]
I am not 100% certain, but I don't think Scintilla has the ability to keep the vertical scrollbar visible when it's not needed. If I'm not wrong, you'd have to hack the native version of the component to change this behaviour.

**Comment by jacobslusser** [comment]
I believe this is correct. You can control whether the vertical scroll is displayed when necessary but not whether it is displayed all the time. I seem to remember looking into hacking this and it was a nightmare.

**Comment by Stumpii** [comment]
You could hide the scrollbar in ScintillaNet and then add a separate scrollbar control next to the ScintillaNet control and link the using events. I did something similar when I started writing a custom scrollbar that could show indicators on it like the one in VS.

https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/hscrollbar-and-vscrollbar-controls-overview-windows-forms
