### ISSUE TITLE
ClearCmdKey & AssignCmdKey Not Working

### ISSUE THREAD

**Issue by UCFKnights83** [jacobslusser/ScintillaNET#383]
v3.6.3

I am trying to override the default list of command keys so as to prevent the inserting of ASCII characters on commands I am handling programmatically. There seems to be an issue though where the ClearCmdKey is not removing the Scintilla command and AssignCmdKey will not override the Scintilla command. The below code should add/override Scintilla commands of Null so that my code is all that runs when the keys are pressed. What am I doing wrong?

```
private List<Keys> _SupportedKeys = new List<Keys> { Keys.F3 };
private List<Keys> _SupportedShiftKeys = new List<Keys> { Keys.F3 };
private List<Keys> _SupportedControlKeys = new List<Keys> { Keys.F, Keys.G, Keys.I, Keys.O, Keys.R };

public QueryEditor()
{
    InitializeComponent();
    this.ClearScintillaCommandKeys();
}

private void ClearScintillaCommandKeys()
{
    _SupportedKeys.ForEach(SK => 
    {
	this.SQueryEditor.AssignCmdKey(SK, ScintillaNET.Command.Null);
    });

    _SupportedShiftKeys.ForEach(SSK => 
    {
	this.SQueryEditor.AssignCmdKey(Keys.Shift | SSK, ScintillaNET.Command.Null);
    });

    _SupportedControlKeys.ForEach(SCK =>
    {
	this.SQueryEditor.AssignCmdKey(Keys.Control | SCK, ScintillaNET.Command.Null);
    });
}
```

**Comment by Stumpii** [comment]
I did similar in my find replace dialog:

https://github.com/Stumpii/ScintillaNET-FindReplaceDialog

Here is some sample code that maybe useful:

https://github.com/Stumpii/ScintillaNET-FindReplaceDialog/wiki/Usage-Code-Example

**Comment by UCFKnights83** [comment]
Thank you Stumpii but your code examples do not address the issue I stated. No where in your code example do you add/override the commands using the ClearCmdKey or AssignCmdKey methods. My KeyDown event already marks Handled = true and SuppressKeyPress = true. However, these commands do nothing to prevent the insert of the ASCII character when Ctrl + O is pressed which is why I am trying to use ClearCmdKey and AssignCmdKey

```
public void SQueryEditor_KeyDown(Object _Sender, KeyEventArgs _Args)
{
    if (_Args.Control && _SupportedControlKeys.IndexOf(_Args.KeyCode) != -1)
    {
	switch (_Args.KeyCode)
	{
	    case Keys.O:
		_Args.Handled = true;
		_Args.SuppressKeyPress = true;
		break;
	}
    }
}
```

**Comment by jacobslusser** [comment]
This question has been asked and answered several times in our issues list...

**Comment by UCFKnights83** [comment]
I did a search for this issue and found nothing in the issue list. If this has been asked and answered several times could you please provide the issues for me to review? I searched using:

ClearCmdKey in:title,body
AssignCmdKey in:title,body

**Comment by jacobslusser** [comment]
[https://github.com/jacobslusser/ScintillaNET/issues?utf8=%E2%9C%93&q=Ctrl](https://github.com/jacobslusser/ScintillaNET/issues?utf8=%E2%9C%93&q=Ctrl)

**Comment by UCFKnights83** [comment]
Thank you for the listings but none of them addressed the ClearCmdKey & AssignCmdKey not working as expected. I will try out the override of the ProcessCmdKey as a work around but it shouldn't be needed if I am clearing a key binding or trying to set one to one of my own making.

**Comment by UCFKnights83** [comment]
I attempted to use the ProcessCmdKey override but it would not allow my parent object to detect a specific key combination since the return of true essentially made it seen as already handled. I need to have the key combination able to flow through to the parent which is why I am trying to use the ClearCmdKey or AssignCmdKey to remove the key combination from Scintilla's default list. I would rather have Scintilla not have any default keys and to set my own.

**Comment by jacobslusser** [comment]
Closing as answered.
