### ISSUE TITLE
Conversion code VB.NET

### ISSUE THREAD

**Issue by cristo1985** [jacobslusser/ScintillaNET#384]
Hi,
vs2017 says to me there are some errors about Form.Designer.vb. I think it depends by conversion from old scintilla (v. 2.2.0.0) to latest downloaded with nuget. 

        '
        'MainTextBox  <-- scintilla old
        '
        Me.MainTextBox.ConfigurationManager.Language = "cpp" -- NOT WORK
        Me.MainTextBox.Dock = System.Windows.Forms.DockStyle.Fill -- OK
        Me.MainTextBox.IsBraceMatching = True  -- NOT WORK
        Me.MainTextBox.Location = New System.Drawing.Point(174, 25)  -- OK
        Me.MainTextBox.Margins.Margin0.Width = 20  -- NOT WORK 
        Me.MainTextBox.Name = "MainTextBox" -- OK
        Me.MainTextBox.Scrolling.HorizontalWidth = 1000  -- NOT WORK 
        Me.MainTextBox.Size = New System.Drawing.Size(379, 457) -- OK
        Me.MainTextBox.Styles.BraceBad.FontName = "Verdana" -- NOT WORK
        Me.MainTextBox.Styles.BraceLight.FontName = "Verdana" -- NOT WORK
        Me.MainTextBox.Styles.ControlChar.FontName = "Verdana" -- NOT WORK
        Me.MainTextBox.Styles.Default.FontName = "Verdana" -- NOT WORK
        Me.MainTextBox.Styles.IndentGuide.FontName = "Verdana" -- NOT WORK
        Me.MainTextBox.Styles.LastPredefined.FontName = "Verdana" -- NOT WORK
        Me.MainTextBox.Styles.LineNumber.FontName = "Verdana" -- NOT WORK
        Me.MainTextBox.Styles.Max.FontName = "Verdana" -- NOT WORK
        Me.MainTextBox.TabIndex = 7   -- OK

Thanks for any helps....
Cris

**Comment by cristo1985** [comment]
I tried changing the line:
` Me.MainTextBox.Margins.Margin0.Width = 20  -- NOT WORK `
into:

 `Me.EditorCodice.Margins(0).Width = 20 `

and it works but it's equivalent from old scintilla?

Thanks again

**Comment by xv** [comment]
`MainTextBox.ConfigurationManager.Language = "cpp"` => `MainTextBox.Lexer = Lexer.Cpp`
`MainTextBox.Margins.Margin0.Width = 20` => `MainTextBox.Margins(0).Width = 20`
`MainTextBox.Scrolling.HorizontalWidth = 1000` => `MainTextBox.ScrollWidth = 1000`
`MainTextBox.Styles.</>.FontName` => `MainTextBox.Styles(Style.</>).Font`

Some stuff from older Scintilla no longer exist in the new version. You may need to make core changes to the older code.

**Comment by cristo1985** [comment]
Thanks!!!
