### ISSUE TITLE
How to keeping the Caret active while the control does not have focus?

### ISSUE THREAD

**Issue by Aghlara** [jacobslusser/ScintillaNET#387]
I have two panels side by side, one has the editor and other one a treeview. When I focus on the treeview I still need to have the Caret visible on the editor. How can I do that? I saw `SCI_SETFOCUS` and seems to be doing the job but not sure how to use it.

**Comment by Aghlara** [comment]
any one?

**Comment by Stumpii** [comment]
There is a native command:

SCI_SETCARETLINEVISIBLEALWAYS(bool alwaysVisible)
SCI_GETCARETLINEVISIBLEALWAYS → bool
Choose to make the caret line always visible even when the window is not in focus. Default behaviour SCI_SETCARETLINEVISIBLEALWAYS(false) the caret line is only visible when the window is in focus.

So you could try:

          public void SetCaretLineInvisibleAlways(bool enabled)
        {
          var val = (enabled ? new IntPtr(1) : IntPtr.Zero);
            DirectMessage(NativeMethods.SCI_SETCARETLINEVISIBLEALWAYS, val);
}

**Comment by Aghlara** [comment]
Thanks, why my DirectMessage has parameters?

![image](https://user-images.githubusercontent.com/5187409/38124512-d06c4fa0-342d-11e8-9ffe-b34ea083438a.png)

Probably I am at old version?

**Comment by Aghlara** [comment]
I tested your suggestion @Stumpii , it keeps the line visible, meaning my line background remains. But Caret disappears. How can I have the Caret also blinking and visible?

**Comment by Stumpii** [comment]
You are correct about the line, my mistake.

It looks like SCI_SETFOCUS is a bit of a hack and I could not get to work correctly. This would be a feature request to the Scintilla group, or a you would have to try setting a marker on loss of focus, or an owner drawn line on top of the control.

If you work something out, let us know. We could add as feature in ScintillaNet.

**Comment by Stumpii** [comment]
Example add an indicator on loss of focus and removes it when you have focus again. The indicator is not great, but it is something.

`        private void scintilla1_Leave(object sender, EventArgs e)
        {
            // Indicators 0-7 could be in use by a lexer
            // so we'll use indicator 8 to highlight words.
            const int NUM = 8;

            // Remove all uses of our indicator
            scintilla1.IndicatorCurrent = NUM;
            scintilla1.IndicatorClearRange(0, scintilla1.TextLength);

            // Update indicator appearance
            scintilla1.Indicators[NUM].Style = IndicatorStyle.Point;
            scintilla1.Indicators[NUM].Under = true;
            scintilla1.Indicators[NUM].ForeColor = Color.Black;
            //scintilla1.Indicators[NUM].OutlineAlpha = 50;
            //scintilla1.Indicators[NUM].Alpha = 30;

            // Search the document
            // Mark the search results with the current indicator
            scintilla1.IndicatorFillRange(scintilla1.CurrentPosition, 1);
        }

        private void scintilla1_Enter(object sender, EventArgs e)
        {
            // Indicators 0-7 could be in use by a lexer
            // so we'll use indicator 8 to highlight words.
            const int NUM = 8;

            // Remove all uses of our indicator
            scintilla1.IndicatorCurrent = NUM;
            scintilla1.IndicatorClearRange(0, scintilla1.TextLength);
        }`

**Comment by Aghlara** [comment]
There will be many complications, e.g. when a text is appended at the current position, Caret shadow/image/point etc. should be updated as well, meaning that indicator should simulate the Caret behavior.

**Comment by Aghlara** [comment]
Thanks, Will keep you updated if we added this functionality.
