### ISSUE TITLE
XSD File

### ISSUE THREAD

**Issue by Naicos** [jacobslusser/ScintillaNET#388]
Is there a way to include a XSD File to Scintilla?

**Comment by jacobslusser** [comment]
You mean an XSD syntax highlighter? That would be the same as the XML highlighter, right?

**Comment by Naicos** [comment]
I mean something like in Visual Studio in the XML Editor where you have an autocompletition and Tag completition with the XSD File. for example you type < and get all usable Tags for autocompletition and if you choose one for example Form you get <Form></Form>

**Comment by Stumpii** [comment]
Refer to this: [Basic-Autocompletion](https://github.com/jacobslusser/ScintillaNET/wiki/Basic-Autocompletion)

For XSD, you would have to create your own list for the autocomplete:

scintilla.AutoCShow(lenEntered, "abstract as base break case catch checked continue default delegate do else event explicit extern false finally fixed for foreach goto if implicit in interface internal is lock namespace new null object operator out override params private protected public readonly ref return sealed sizeof stackalloc switch this throw true try typeof unchecked unsafe using virtual while");

would become:

**Comment by Naicos** [comment]
Lexer.Xml is active. yeah already saw this kind of autocompletition but its complete static.
and Im not talking about writing XSD Files with Scintilla Im talking about using an existing XSD
file for Scintilla to write XML just like the XML Editor in VS. so if i Type <Form and when i add the > it atomatically adds </Form> and if i press space inside the Tag an autocomplete window appears with the propertys which can be used inside this Tag for exapmle id or required and when i use required="" and the cursor is inside the " " a window comes with true and false as options.

**Comment by jacobslusser** [comment]
Custom lexer is your answer.

I'm closing this answered.
