### ISSUE TITLE
"NativeMethods" is inaccesible due to its protection level

### ISSUE THREAD

**Issue by StrikerMan780** [jacobslusser/ScintillaNET#390]
I'm trying to update another project to use the latest version of ScintillaNet, but I get this error:
```
1>D:\Modding\GitHub\GZDoom-Builder-Bugfix\Source\Core\Controls\Scripting\ScriptEditorControl.cs(152,29,152,42): error CS0122: 'NativeMethods' is inaccessible due to its protection level
```
Here's the code:
```
			// Script editor properties
			//TODO: use ScintillaNET properties instead when they become available
			scriptedit.DirectMessage(NativeMethods.SCI_SETBACKSPACEUNINDENTS, new IntPtr(1));
			scriptedit.DirectMessage(NativeMethods.SCI_SETMOUSEDOWNCAPTURES, new IntPtr(1));
			scriptedit.DirectMessage(NativeMethods.SCI_SETTABINDENTS, new IntPtr(1));
```

**Comment by Stumpii** [comment]
Note also that SCI_SETMOUSEDOWNCAPTURES is commented as disabled in the ScintillaNET code because it probably won't work. What are you trying to achieve with this one?

**Comment by StrikerMan780** [comment]
I don't know. This isn't exactly my project, I'm just trying to get it compiling with the latest libs in 64-bit. This project is a level and script editor for a game I'm making a mod for, and I'm hitting the 32-bit memory limit, thus my need to do this.

Anyhow. I notice DirectMessage now has 3 parameters, rather than two. Any adjustments I should make to those calls?

**Comment by Stumpii** [comment]
My guess from the link I sent is IntPtr.Zero for unused.args.

**Comment by StrikerMan780** [comment]
Not sure what you mean. There's no mention of unused.args in that page. I guess what I want to know is if it's the 2nd or 3rd parameter of DirectMessage that should be 1.

**Comment by Stumpii** [comment]
Page Down does not need any additional arguments, so the two unused arguments are null:

`const int SCI_PAGEDOWN = 2322;
scintilla.DirectMessage(SCI_PAGEDOWN, IntPtr.Zero, IntPtr.Zero);`

**Comment by StrikerMan780** [comment]
Do SETTABINDENTS, or SETBACKSPACEUNINDENTS need additional parameters? I can't find any documentation.

**Comment by xv** [comment]
https://www.scintilla.org/ScintillaDoc.html#SCI_SETTABINDENTS
https://www.scintilla.org/ScintillaDoc.html#SCI_SETBACKSPACEUNINDENTS

`SCI_SETTABINDENTS` and `SCI_SETBACKSPACEUNINDENTS ` both take only one `bool` parameter. So, as @Stumpii said, use `IntPtr.Zero` for the other parameter.

```c#
const int SCI_SETTABINDENTS = 2260;
const int SCI_SETBACKSPACEUNINDENTS = 2262;

void SetTabIndents(bool tabIndents)
{
    scintilla.DirectMessage(SCI_SETTABINDENTS, tabIndents ? new IntPtr(1) : IntPtr.Zero, IntPtr.Zero);
}

void SetBackspaceUnIndents(bool bsUnIndents)
{
    scintilla.DirectMessage(SCI_SETBACKSPACEUNINDENTS, bsUnIndents ? new IntPtr(1) : IntPtr.Zero, IntPtr.Zero);
}
```

**Comment by StrikerMan780** [comment]
Ah, I see. Thanks.

**Comment by jacobslusser** [comment]
Closing as answered.
