### ISSUE TITLE
MarkerDelete

### ISSUE THREAD

**Issue by Aghlara** [jacobslusser/ScintillaNET#391]
I have a situation that `MarkerDelete` does not seem to remove the marker from line:

![image](https://user-images.githubusercontent.com/5187409/38231814-99d42c42-3757-11e8-8b77-9145d8638bc7.png)

As you see the above, the `MarkerDelete` is reached, but still marker is on the screen and visible.

![image](https://user-images.githubusercontent.com/5187409/38232063-c4b3be0e-3758-11e8-81ef-9d23f797de87.png)

I am calling it inside `UpdateUI` event. Am I doing something wrong?

**Comment by xv** [comment]
Is this how you implemented `LineHasMarker()` function?

```c#
bool LineHasMarker(int markerMask, int line)
{
    var lineMarker = sci.Lines[line].MarkerGet();
    return (lineMarker & markerMask) > 0;
}
```

Note that you need to use a marker **mask** value, not a marker number to check if the line has a marker. So, if your marker number is 3, then the marker mask should be `1 << 3`.

```c#
bool found = NaturalLanguage.Editor.LineHasMarker(1 << MarkerNumber, line);
if (found)
    NaturalLanguage.Editor.Lines[line].MarkerDelete(MarkerNumber);
```

**Comment by Stumpii** [comment]
Also refer to this wiki page on markers:

[https://github.com/jacobslusser/ScintillaNET/wiki/Markers-and-Bookmarking-Lines](url)

**Comment by Aghlara** [comment]
As explained in the original post and it is obvious the yellow highlighted passed the check point, the issue is after calling the MarkerDelete, the MarkerGet does not return 0.

**Comment by xv** [comment]
I am really not sure then. I tested your code inside `UpdateUI` event and it works fine.

**Comment by xv** [comment]
I am really unsure what's the issue then. But `UpdateUI` event isn't the issue here according to my tests.

**Comment by Stumpii** [comment]
It would be useful to see the function `LineHasMarker()` and code that defines and populates MarkerNumber. I have tested the code on the wiki link and the same from @xv and it works fine.
