### ISSUE TITLE
Switching from rectangular to multiple selections

### ISSUE THREAD

**Issue by zhaDeth** [jacobslusser/ScintillaNET#397]
I want to make ALT+backspace / ALT + delete do backspace/delete but only deleting white spaces (space or tab) in order to make it easy to make align in columns, or make columns 

ex:
![2018-04-17_15-31-02](https://user-images.githubusercontent.com/18398968/38892423-2a16dfea-4255-11e8-92b8-8920e59aa52c.png) 
to
![2018-04-17_15-31-22](https://user-images.githubusercontent.com/18398968/38892440-34c1cd92-4255-11e8-992e-fe431fcae9a9.png)
-----
or:
![2018-04-17_15-32-10](https://user-images.githubusercontent.com/18398968/38892465-46206d6e-4255-11e8-9663-7b761e7f65a7.png)
to
![2018-04-17_15-32-34](https://user-images.githubusercontent.com/18398968/38892472-4b2a0fa4-4255-11e8-8c0f-34fe27efe0d8.png)
-----

So, in a keydown event, I check ALT+backspace/delete, and for each selection, delete the character if its a space using DeleteRange

The carret of each line seems to be updated correctly,
![2018-04-17_15-43-11](https://user-images.githubusercontent.com/18398968/38892827-56076574-4256-11e8-85d0-79479ca99825.png)
but then when typing, the selection goes back into a rectangle
![2018-04-17_15-44-17](https://user-images.githubusercontent.com/18398968/38892843-625ad522-4256-11e8-912e-508245677f3b.png)

**Comment by zhaDeth** [comment]
Ok, I found a work-around:
after the rectangular selection changed, save the data of each selection
clear selections
add saved selections

This seems to make scintilla "forget" that the selections come from a rectangular selection and prevents this odd behaviour

**Comment by jacobslusser** [comment]
Whatever this is, it is within the native Scintilla component and there is nothing we can do about it in our ScintillaNET wrapper.
