### ISSUE TITLE
Question about events

### ISSUE THREAD

**Issue by lightfinder** [jacobslusser/ScintillaNET#4]
What events are identical to DocumentChange and ModifiedChanged of previous versions?

Is there a plan to implement IncrementalSearcher for newer version?

**Comment by jacobslusser** [comment]
DocumentChange in v2.x ScintillaNET was essentially the native SCN_MODIFIED notification and included everything from text changes to style changes to fold changes and more. To make those events more discoverable in v3.x I've broken them out into:

- Insert
- Delete
- BeforeInsert
- BeforeDelete
- InsertCheck (which v2.x never had)
- and TextChanged (of course).

I haven't yet implemented the aforementioned style change, fold change, etc.. events that the old DocumentChange event supported but would be happy to prioritize them if you need.

The replacement for the ModifiedChanged event in v3.x is a combination of the SavePointLeft and SavePointReached events.

I don't have plans to implement the IncrementalSearcher. My feeling was that the 2.x version of ScintillaNET tried to be more than just a control--by offering search, font, and print dialogs, etc.... IMO this is application logic and doesn't belong in the core ScintillaNET project.

However, that being said I've considered creating a separate GitHub repo for "ScintillaNET extensions" which might have this type of functionality. Feel free to start one if you'd like.

**Comment by hfoffani** [comment]
Are there any event that's fired on text selection?

**Comment by jacobslusser** [comment]
The `UpdateUI` event should be what you're looking for. The `UpdateUIEventArgs` supplied has a property called `Change` which is a bit flag indicating why the update occurred. If you were interested in only selection changes you could use it like this:

```cs
if ((e.Change & UpdateChange.Selection) > 0)
{
    // Selection changed....
}
```

**Comment by hfoffani** [comment]
Cool. I like the new API, definitely much better!

I'm doing a "select all" via programming:

    scintilla.AddSelection(scintilla.TextLength, 0);

which does select but doesn't fire the UpdateUI event.

**Comment by jacobslusser** [comment]
You are correct. I've observed this as well. This is one of those things that only the Scintilla overlords can explain. For the most part it seems that selections set via the user are reliable, but ones created programmatically only raise the `UpdateUI` event sporadically.

I will open an issue with the native Scintilla team to investigate more.

Until then I've taken to calling my `UpdateUI` event handler directly when I make a programmatic change to the selection. If you are worried about calling the `UpdateUI` event twice because you've called it manually and native Scintilla might also raise the event, you could try storing off the last caret and anchor positions into some variables which you check against in the event handler to determine if the selection has really changed. i.e. 

```cs
int lastCurrentPosition = -1;
int lastAnchorPosition = -1;

private void scintilla_UpdateUI(object sender, UpdateUIEventArgs e)
{
    var currentPosition = scintilla.CurrentPosition;
    var anchorPosition = scintilla.AnchorPosition;

    if (currentPosition != lastCurrentPosition || anchorPosition != lastAnchorPosition)
    {
        lastCurrentPosition = currentPosition;
        lastAnchorPosition = anchorPosition;

        // Selection changed...
    }
}

private void DoWork()
{
    scintilla.SetSelection(scintilla.TextLength, 0);
    scintilla_UpdateUI(scintilla, new UpdateUIEventArgs(UpdateChange.Selection));
}
```

**Comment by hfoffani** [comment]
That's all I need, thanks!

**Comment by jacobslusser** [comment]
Just to follow-up a bit on this... I opened a ticket for the native Scintilla team which you can track here: [https://sourceforge.net/p/scintilla/bugs/1723/](https://sourceforge.net/p/scintilla/bugs/1723/).

In the meantime, I added support for the `SelectAll` and `SetSel` methods. Both of these could be used to "select all" if that is your only goal; the first does not scroll the caret into view, the second does. I've verified that making a selection using either of these methods WILL raise the `UpdateUI` event.

**Comment by jacobslusser** [comment]
The native Scintilla team responded to my ticket with pretty much the same explanation I gave. In short, the UpdateUI event is only guaranteed to be raised for user changes, not programmatic ones. The intention being that an event is required to know about a user change. A programmatic change, however, is deterministic and thus doesn't need an event.
