### ISSUE TITLE
Possible bug with CharAdded event due to extended ASCII charset

### ISSUE THREAD

**Issue by xv** [jacobslusser/ScintillaNET#400]
I just realised I have an issue with `CharAdded` event when calling `AutoIndentLines()`. It is somehow caused by non-US-ASCII characters. Here's the code used for auto indentation:

```c#
public static void AutoIndentLines(CharAddedEventArgs e)
{
    if (e.Char != '\n')
        return;

    var currentPosition = sci.CurrentPosition;
    var currentLine     = sci.LineFromPosition(currentPosition);
    var previousIndent  = sci.Lines[currentLine - 1].Indentation;

    sci.Lines[currentLine].Indentation = previousIndent;

    var newCaretPosition = sci.PositionFromLine(currentLine) + previousIndent;
    sci.GotoPosition(newCaretPosition);
}

private void Sci_CharAdded(object sender, CharAddedEventArgs e)
{
    AutoIndentLines(e);
}
```

## What's happening?
As you can see in the demonstration below, in the first code block, auto indentation behaves correctly, as the caret remains behind the curly braces and in the correct position when auto indenting `// lines`. 

However, do you see that non-English alphabet letter `ä` in the comment after the first block? The indentation itself will work fine, but this where `sci.GotoPosition()` messes up. Any newline entry after that letter causes `sci.GotoPosition(newCaretPosition)` to add up 1 extra position to the right.

I don't think my method is wrong. I wrote it in multiple different ways and the result is still the same. I have also tested it on native/C++ Scintilla and the behaviour seems correct.

### EDIT - 14th May 018
* It appears that it is not only alphabetic characters that are causing incorrect caret position. Characters such as `9✕10¹⁵` carry the same effect. Thus, it looks like any character that is not in the lower/standard ASCII set, aka ``!"#$%&'()*+'`./0123456789:<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\^_{|}~``, will result in incorrect caret offset.

![bug_gif](https://i.imgur.com/cJmADPk.gif)

## To replicate...
You can replicate the issue using the code above with this dummy code below:
```c#
// change the world!

private void foo() {
    if (something) {
        // lines
        // lines
    }   
}

// ändere die Welt!

private void roo() {
    if (something) {
        // lines
        // lines
    }
}
```

## Notes
1. It is not this letter in specific that is causing the abnormal behaviour. It can be any foreign letter, such as `ش`, `д`, `š`, etc, or character that is not in the standard ASCII table.
2. The method `scintilla.GotoPosition()` may not necessarily be the culprit. I have tried setting the caret position with `scintilla.SetSel()` and the new caret position still gains one extra position to the right.

**Comment by jacobslusser** [comment]
Interesting. I'll try to replicate when I get time.

**Comment by xv** [comment]
Replacing `sci.PositionFromLine(currentLine)` with `sci.Lines[currentLine].Position` seems to fix the issue from what I can observe.

I am closing this issue for now.
