### ISSUE TITLE
Selection gets lost when trying to set cursor position at the beginning of the selection.

### ISSUE THREAD

**Issue by acharbonneau98** [jacobslusser/ScintillaNET#403]
Hi,

I`m trying to programmatically define a selection within my text and then set the cursor position to the beginning of the said selection.  Like this:

editor.SelectionStart = 2;
editor.SelectionEnd = 4;
editor.GotoPosition(2);

However, what append is that the selection gets removed when I set the cursor position.

Is there something I am doing wrong?

Thanks
Antoine

**Comment by jacobslusser** [comment]
Yes, set end to 2 and start to 4. End position will be where cursor is so you don’t have to move it.

**Comment by jacobslusser** [comment]
Closing as answered.
