### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by pgonzal** [jacobslusser/ScintillaNET#406]
Hey @jacobslusser, I noticed there hasn't been much activity for ScintillaNET lately.  There is an open PR from March, and it looks like the last merged PR was in September of 2017.

Are you the sole maintainer of this GitHub project?  Is this project still being actively maintained?

(Thanks very much for creating ScintillaNET BTW.  It's awesome!)

**Comment by Stumpii** [comment]
It is still maintained. As this is a wrapper around the Scintilla control, it generally only changes when a bug is fixed, or a new Scintilla control is released. Feature enhancements are usually found as extra projects in the related projects section of the home page, or in the wiki under user submitted recipes.

**Comment by jacobslusser** [comment]
What he said. :)

Admittedly I don't have as much time for it these days as I used to so if there are any features people want, the best way is to branch and send a pull request. I'll try and do better about at least expediting those.
