### ISSUE TITLE
ScintillaNET fails to load

### ISSUE THREAD

**Issue by PenguinF** [jacobslusser/ScintillaNET#407]
When an application with a reference to ScintillaNET is first run as administrator, it saves a copy of SciLexer.dll in C:\Users\...\AppData\Local\Temp\ScintillaNET with administrator rights. Then, when this same application is run normally, it fails to load ScintillaNET with the following error message:

Could not load the Scintilla module at the path "C:\Users\...\AppData\Local\Temp\ScintillaNET\3.6.3\x86\SciLexer.dll".

I'm not expecting this issue to be fixed, but it might help with analysis if other people experience the same kind of error message and can't figure out where it came from.

**Comment by jacobslusser** [comment]
A good reminder for anyone else. Thanks.

Please remember that you can always configure ScintillaNET to use an external SciLexer.dll which you can set permissions on yourself.

[https://github.com/jacobslusser/ScintillaNET/wiki/Using-a-Custom-SciLexer.dll](https://github.com/jacobslusser/ScintillaNET/wiki/Using-a-Custom-SciLexer.dll)

**Comment by issctg1** [comment]
I am hitting this issue. What is the fix? What account does Scintilla run under? I am on a work pc and do not (and cannot) have admin rights.

**Comment by Fiahblade** [comment]
I believe this can also be caused because a certain `Visual C++ Redistributable` package is not installed.
