### ISSUE TITLE
Can we use it for autocomplete functionality ?

### ISSUE THREAD

**Issue by VarunNagal** [jacobslusser/ScintillaNET#408]
Lets say I have multiple string arrays. These act as a source for autocomplete based on certain conditions.

e.g. If I enter . then 'A,B,C,D,E' should come in popup. Then if I type { then 'X,Y,Z' pops up.

e.g. result strings
.A{XYZ} 
.ADC {Z}{R}
etc

**Comment by Stumpii** [comment]
Did you look at this (have not personally used it): [Custom-Autocompletion](https://github.com/jacobslusser/ScintillaNET/wiki/Custom-Autocompletion)

**Comment by jacobslusser** [comment]
Closing as answered.
