### ISSUE TITLE
Backspace causes position to move to 0

### ISSUE THREAD

**Issue by mathewgrabau** [jacobslusser/ScintillaNET#409]
I am using the editor in a WPF WindowsFormsHost element with the JSON lexer. If I am typing, pressing the backspace key results in the location being moved back to position 0. It does not seem to fire the TextChanged event when this happens.

I did implement a two-way binding for the control.

**Comment by jacobslusser** [comment]
I've never experienced this before and it sounds like an issue localized to your specific application. I'm closing this for now but if you feel it is a library issue we can reopen it.

**Comment by colinxia** [comment]
when use databidng, I also encountered this situation.

	ceDoScript.DataBindings.Add("Text", model, "DoScript",false, DataSourceUpdateMode.OnPropertyChanged);

If modified like below, there is no problem, but I don't know why.

	ceDoScript.DataBindings.Add("Text", model, "DoScript",true, DataSourceUpdateMode.OnPropertyChanged);
