### ISSUE TITLE
DLL Initialization fail when Scintilla component is open in multiple studios

### ISSUE THREAD

**Issue by theryan722** [jacobslusser/ScintillaNET#41]
I believe this has to do with ScintillaNET trying to extract the Scilexer DLL's to a temp folder. If I have a project in Visual Studio with a ScintillaNET component on it, I can not then open another project in another instance of Visual Studio with the ScintillaNET component, if you try to view the form, it states the DLL has failed to initialize. 

The trouble I am having is recreating this issue, it doesn't happen all of the time. 

This is obviously a rare case as I don't imagine many people working on 2 projects at the same time with the component.

**Comment by jacobslusser** [comment]
I think I've seen the error you're describing, but in my haste to get things done I've dismissed it.

If it becomes a problem let me know and we can investigate, but otherwise I'm going to consider it a low priority.

**Comment by theryan722** [comment]
It's definitely low priority for now, but once this project becomes more developed, should become a thought.

**Comment by jacobslusser** [comment]
I did a little more research on this and the exception implies that the native Scintilla DllMain function failed (threw an exception). In other words, if there is an issue here, the error message suggests it's with Scintilla, not ScintillaNET. I also don't think it has to do with there being two instances of Visual Studio. I've seen it when using only one.

I'm going to close this for now, but if it becomes a problem I'll reopen the issue.
