### ISSUE TITLE
How to handle serveral document objects?

### ISSUE THREAD

**Issue by agmorpheus** [jacobslusser/ScintillaNET#410]
Hi,
i have a problem.  I have read [this ](https://github.com/jacobslusser/ScintillaNET/wiki/Documents)about documents but i dont get it to manage several tabs with one scintilla control.

I have a list with document objects.
As soon when i call the SwitchScintillaDocment function I get a memory exception.

```
private List<Document> _documents = new List<Document>() { new Document(), new Document(), new Document() };
private void SwitchScintillaDocument(Document nextDocument)
        {
            var prevDocument = scintilla.Document;
            scintilla.AddRefDocument(prevDocument);

            // Replace the current document and make Scintilla the owner
            scintilla.Document = nextDocument;
            scintilla.ReleaseDocument(nextDocument); // Exception here
        }
private void htmlToolStripMenuItem_Click(object sender, EventArgs e)
        {
            SwitchScintillaDocument(_documents[1]);
        }
```
It looks like, the reference count of nextDocument is 1 after assigning it to the document property. Why? Shouldn't it be 2?
I can remove this line `scintilla.ReleaseDocument(nextDocument);`  but i think then the first document object ref count will increase each time I switch to it.
May be you can help me with this?! Thanks

**Comment by jacobslusser** [comment]
Not sure I could explain anything any clearer than it already is in the wiki documentation... 

For now I'm closing this issue, but if you feel there is more that can be done let me know and we can reopen it.
