### ISSUE TITLE
Feature request : support for #region / #endregion

### ISSUE THREAD

**Issue by lafrank** [jacobslusser/ScintillaNET#411]
It would be great to have support for #region ˛#endregion like Visusal Studio code editor does for C# code.

Thank you.

**Comment by jacobslusser** [comment]
That would require a custom lexer and folding implementation. Please refer to these guides to get started:

[https://github.com/jacobslusser/ScintillaNET/wiki/Custom-Syntax-Highlighting](https://github.com/jacobslusser/ScintillaNET/wiki/Custom-Syntax-Highlighting)
[https://github.com/jacobslusser/ScintillaNET/wiki/Automatic-Code-Folding](https://github.com/jacobslusser/ScintillaNET/wiki/Automatic-Code-Folding)
