### ISSUE TITLE
Is ScintillaNET the same as Notepad++, in theory, but with C#.NET instead of C++ (non .NET)?

### ISSUE THREAD

**Issue by meatballcoder** [jacobslusser/ScintillaNET#413]
Hello, I'm trying to understand Scintilla and how it works with Notepad++, and I stumbled onto your project.  After reading it looks like Notepad++ is a C++ consumer of the Scintilla engine, if that is the proper term, and ScintillaNET is a C# .NET runtime consumer.

Is that correct?  It's not that C++ is some how more integrated with NPP than ScintillaNET.  Rather, it is only a choice of language(s) bindings?

Thanks.

**Comment by Stumpii** [comment]
Scintilla is a text editor control, so the text portion only, no buttons, menus, tabs, just a box for text. That control is used in Notepad++, NP++ being the tabbed interface, menus, buttons, etc. to provide features and interface with Scintilla. ScintillaNET is a control itself, basically a wrapper around Scintilla that make it easier to use ScintillaNET in a .Net program. If you wanted to write your own NP++ in .Net, you would use the ScintillaNET control much like NP++ uses the Scintilla control.
