### ISSUE TITLE
Deleting something after inserting

### ISSUE THREAD

**Issue by wasmachien75** [jacobslusser/ScintillaNET#415]
Hello,

I want to delete a portion of the Scintilla text after a certain character was inserted.
For example, when I have the character `a`, and right after character `b` is inserted, the first character should be removed (so only `b` would remain) - note that this should only be done when the first character is `a`.

I have added following method to the Insert event handler:
```
private void OnInsert(object sender, ModificationEventArgs e)
        {
            if(e.Text == "b")
            {
                if(GetCharAt(e.Position - 1) == 'a')
                {
                    DeleteRange(e.Position - 1, 1);
                }
            }
        }
```

But it seems the DeleteRange method call doesn't do anything.
What am I missing?
Thanks.

**Comment by wasmachien75** [comment]
Managed to fix this by using the CharAdded event instead.
Although it might still be interesting to find out why the first way didn't work.

**Comment by jacobslusser** [comment]
You cannot call methods like `DeleteRange` from within the `InsertCheck` event handler. That's not supported. The only text you are able to change during that event is the text that is being inserted and only by using the `InsertCheckEventArgs.Text` property. See:

[https://github.com/jacobslusser/ScintillaNET/wiki/Intercepting-Inserted-Text](https://github.com/jacobslusser/ScintillaNET/wiki/Intercepting-Inserted-Text)
