### ISSUE TITLE
Code Folding (BUG)

### ISSUE THREAD

**Issue by cRUSHER-HLG** [jacobslusser/ScintillaNET#417]
Hello Guys,

How or where can i change the code folding. The problem is that the white line are also displayed inside a method when i intend them. Normaly only namespace/methods/regions need them. How can i remove the white lines inside methods?
(1)
![unbenannt2e2e](https://user-images.githubusercontent.com/35463368/46586791-b8843a00-ca83-11e8-8e11-cd76fe4e33bd.JPG)

(2) The next thing is how can i make this whit ScintillaNet, to highlight brackets:
![klammerhighlight](https://user-images.githubusercontent.com/35463368/46588189-1fabe980-ca98-11e8-9029-007241dbc779.JPG)

(3) How can i change the current code folding from:
![eingeklappt](https://user-images.githubusercontent.com/35463368/46588198-35211380-ca98-11e8-82ea-8b8290b54017.JPG)
To:
![eingeklapptvs](https://user-images.githubusercontent.com/35463368/46588200-394d3100-ca98-11e8-93fb-50786adaade4.JPG)
Better said how can i change it, that the { is not anymore in a single line and will displayed like visual studio with ...?

(4) The BUG:
![wdwdwd](https://user-images.githubusercontent.com/35463368/46588351-18d2a600-ca9b-11e8-89bf-e1559bfef4f3.JPG)
I use scintilla for c# but when i folded with TextArea.Lexer = Lexer.Cpp is shows like in point (3). When i still use C# as files and change it to TextArea.Lexer = Lexer.VbScript; the brackets seems to works? 

Can someone make a tutorial how to make own lexer/custom folding.

**Comment by jacobslusser** [comment]
[https://github.com/jacobslusser/ScintillaNET/wiki/Automatic-Code-Folding](https://github.com/jacobslusser/ScintillaNET/wiki/Automatic-Code-Folding)
[https://github.com/jacobslusser/ScintillaNET/wiki/Brace-Matching](https://github.com/jacobslusser/ScintillaNET/wiki/Brace-Matching)
