### ISSUE TITLE
Question: Any viable alternative to SCN_AUTOCSELECTIONCHANGE?

### ISSUE THREAD

**Issue by billybooth** [jacobslusser/ScintillaNET#419]
As I assume you’re aware, Scintilla 4.0.x added support for the [SCN_AUTOCSELECTIONCHANGE](https://www.scintilla.org/ScintillaDox.html#SCN_AUTOCSELECTIONCHANGE) notification, which is basically the only event we’re missing to implement true, generic Intellisense with the built-in AutoComplete box and a separate formatted tooltip.  I have done some initial work (Win32 only) getting the window rect and selected item offset in the AutoComplete box to display properly aligned tooltips, but I can’t detect when the selected item changes due to user interaction via arrow keys, and I can’t override `WndProc` to catch [LBN_SELCHANGE](
https://docs.microsoft.com/en-us/windows/desktop/controls/lbn-selchange), since the ScintillaNET wrapper control doesn’t actually process the messages.  Do you have any thoughts about whether we’ve got any reasonable options prior to ScintillaNET being updated to wrap the 4.x release and API?

Sorry if this feels like a duplicate of #354.  Feel free to close this if it is (or if it’s not), but I’m curious whether anyone has ideas about a workaround in the meantime.  Thanks for your work on this wrapper.  My experience so far, albeit limited, has been an absolute dream.

**Comment by billybooth** [comment]
Hmm, based on the lack of support (in Scintilla, not ScintillaNET) for filtering down the autocomplete list as the user types.  I think this is a case where I'll need to implement the AutoComplete functionality from scratch in addition to the tooltips.  I'll go ahead and close this one, although add a plus one from me regarding the updating the wrapper to Scintilla 4.0.

**Comment by Ahmad45123** [comment]
@billybooth You could use a third party autocomplete library if you don't want to do it all from scratch.
https://github.com/Ahmad45123/AutoCompleteMenu-ScintillaNET
This is a scintillanet wrapper I made for a nice one I found on codeproject.
It's also available via NuGET 👍

**Comment by billybooth** [comment]
Thanks @Ahmad45123.

LGPL is off the table for me, since I’d need to integrate it.  I’ve done some initial work, and it’s been going better than I was anticipating.  I'll be writing it against a vendored listbox and formatted tooltip implementation, but if I ever get that far, I'll see what I can do about posting an MIT-licensed implementation against subclassed .NET ListBox and ToolTip.
