### ISSUE TITLE
Working with multiple selections at one time 

### ISSUE THREAD

**Issue by tobeypeters** [jacobslusser/ScintillaNET#436]
How do you select multiple ranges of text and do operations on each selection?  For example, I got:

```
public static Scintilla SelectedTextToUpper(this Scintilla value)
        {
            foreach(var sel in value.Selections)
            {
                int start = sel.Start;
                int end = sel.End;

                Debug.Print($"{sel.ToString()}");

                value.ReplaceSelection(value.GetTextRange(start, end - start).ToUpper());

                value.SetSelection(start, end);
            }

            //int start = value.SelectionStart;
            //int end = value.SelectionEnd;

            //value.ReplaceSelection(value.GetTextRange(start, end - start).ToUpper());

            //value.SetSelection(start, end);

            return value;
        }
```
**Before I execute this particular extension I have:**

![capture1](https://user-images.githubusercontent.com/35942395/53290488-6f066400-3772-11e9-8324-0bf2e0e047c4.PNG)

**After I execute this particular extension I get:**

![capture2](https://user-images.githubusercontent.com/35942395/53290492-85acbb00-3772-11e9-9fb2-287baa082867.PNG)

I assume I'm missing something obvious.  I know, this control isn't supposed to conform to true .NET fashion.  But, if you can't really do anything with something.  Just make those things Private.

**Comment by justinbittner11** [comment]
I'm not entirely sure what you're trying to do here, If you can give more insight. Are you trying to make all 3 of the boxes the same when you change one? If so, I would use the text changed event for each, and have it set the other 2 to the same text. So if textBox1 is changed, set textBox2 = textBox1.Text; textBox3 = textBox1.Text;. But I'm not entirely sure if I understood the problem, or the goal.

**Comment by tobeypeters** [comment]
No, um, in Scintilla you can turn on "multiple selection" mode by doing MultipleSelection = true; So, in the control, I'm selecting multiple or separate lines of texts which I want to "work" on.  In the example I posted, I was trying to implement a Comment line option.  I got a partially working version here:

public struct SelectionItem
    {
        public int start;
        public int end;
        public string text;
    }

    static class ScintillaExtensions
    {
        public static List<SelectionItem> SelectedItemList(this Scintilla value)
        {
            List<SelectionItem> SelectedItemBuffer = new List<SelectionItem>();

            for (int i = 0; i < value.Selections.Count; i++)
            {
                SelectedItemBuffer.Add(new SelectionItem()
                {
                    start = value.Selections[i].Start,
                    end = value.Selections[i].End,
                    text = value.GetTextRange(value.Selections[i].Start, value.Selections[i].End - value.Selections[i].Start).ToUpper()
                });
            }

            return SelectedItemBuffer;
        }

        public static Scintilla Comment(this Scintilla value, bool inRemoveMarkers = false)
        {
            List<int> lineIndexes;

            Line LookupLine;

            string LineText = "";

            string GetLineText(int inIndex) => value.GetTextRange(value.Lines[inIndex].Position,
                                              (value.Lines[inIndex].EndPosition - value.Lines[inIndex].Position));

            string StripCommentMarkers(string inStripIt)
            {
                inStripIt = inStripIt.Replace("//", ""); inStripIt = inStripIt.Replace("/*", ""); inStripIt = inStripIt.Replace("*/", "");

                return inStripIt;
            }

            List<SelectionItem> CommentThem = value.SelectedItemList();

            for (int i = (CommentThem.Count - 1); i > -1; i--)
            {
                int lineIndexTemp = -1, lineIndex = -1;

                lineIndexes = new List<int>();

                for (int j = 0; j < CommentThem[i].text.Length; j++)
                {
                    lineIndexTemp = value.LineFromPosition((CommentThem[i].start + j));

                    if (lineIndex != lineIndexTemp)
                    {
                        lineIndex = lineIndexTemp;
                        lineIndexes.Add(lineIndexTemp);
                    }
                }

                if (lineIndexes.Count == 1)
                {
                    if (!inRemoveMarkers)
                    {
                        string Line = Regex.Replace(value.GetTextRange(value.Lines[lineIndexes[0]].Position,
                            (value.Lines[lineIndexes[0]].EndPosition - value.Lines[lineIndexes[0]].Position)),
                            "[^0-9a-zA-Z]+", "");
                        string Comment = Regex.Replace(CommentThem[i].text, "[^0-9a-zA-Z]+", "");

                        if (Comment.Length < Line.Length)
                        {
                            value.InsertText(CommentThem[i].start, "/*"); value.InsertText((CommentThem[i].end + 2), "*/");
                            lineIndexes.Clear();
                        }
                    }

                    if (inRemoveMarkers)
                    {
                        LineText = GetLineText(lineIndexes[0]);

                        if (CommentThem[i].text.Length < LineText.Length)
                        {
                            LineText = StripCommentMarkers(LineText);
                            {
                                LookupLine = value.Lines[lineIndexes[0]];

                                value.SetSel(LookupLine.Position, LookupLine.EndPosition);
                                value.ReplaceSelection(LineText);

                                lineIndexes.Clear();
                            }
                        }
                    }
                }

                for (int k = 0; k < lineIndexes.Count; k++)
                {
                    if (!inRemoveMarkers) { value.InsertText(value.Lines[lineIndexes[k]].Position, "//"); }

                    if (inRemoveMarkers)
                    {
                        LineText = GetLineText(lineIndexes[k]);

                        LineText = StripCommentMarkers(LineText);
                        {
                            LookupLine = value.Lines[lineIndexes[k]];

                            value.SetSel(LookupLine.Position, LookupLine.EndPosition);
                            value.ReplaceSelection(LineText);
                        }
                    }
                }

                for (int k = 0; k < lineIndexes.Count; k++)
                {
                    LookupLine = value.Lines[lineIndexes[k]];

                    //value.AddSelection(LookupLine.Position, LookupLine.EndPosition);
                }
            }

            return value;
        }
    }

It's not perfect.
________________________________
