### ISSUE TITLE
Set color for all keyword types in cpp lexer

### ISSUE THREAD

**Issue by MaticBabnik** [jacobslusser/ScintillaNET#437]
How to set colors for keywords 2, 3, 4, 5... The cpp lexer only has .Word and .Word2

**Comment by xv** [comment]
The lexer doesn't support that many keyword sets. Aside from `Style.Cpp.Word` and `Style.Cpp.Word2`, you could use `Style.Cpp.GlobalClass` as an extra set. Use index 3 for this set.

```c#
Sci.Lexer = Lexer.Cpp;
Sci.Styles[Style.Cpp.Word].ForeColor = Color.Blue;
Sci.Styles[Style.Cpp.Word2].ForeColor = Color.Red;
Sci.Styles[Style.Cpp.GlobalClass].ForeColor = Color.HotPink;

Sci.SetKeywords(0, "ks1");
Sci.SetKeywords(1, "ks2");
Sci.SetKeywords(3, "ks3");
```

**Comment by MaticBabnik** [comment]
Thanks! I think 3 different sets will be enough.
