### ISSUE TITLE
Select one row on margin

### ISSUE THREAD

**Issue by ntnam171** [jacobslusser/ScintillaNET#446]
Hi. Please help me.
When i move the mouse on margin, left click to select one row, continue right click to open context menu, the menu Cut and Copy is disable. It is normal when i select more than two rows.

![image](https://user-images.githubusercontent.com/49466800/55851350-6c28cc80-5b82-11e9-89ec-930a32a57a9e.png)

**Comment by tobeypeters** [comment]
How do you keep it from unselecting the text?  When I try it, I can select one or more lines and it unselects it.  I assume you're right-clicking in the margin?  Cause, if I select entire lines by clicking in the margin and I right-click in the text area it works properly.

**In text area:**
![Capture](https://user-images.githubusercontent.com/35942395/55883134-c40c0700-5b73-11e9-9c9a-40182ac53d72.PNG)

**Outside text area:**
![Capture2](https://user-images.githubusercontent.com/35942395/55883168-d423e680-5b73-11e9-89a9-11df94852d8e.PNG)

I mean, I guess, that is weird.  I may look at it some later.

**Update:**
https://sourceforge.net/p/scintilla/feature-requests/1080/
Looks like this issue has been talked about & I think they decided that's how they wanted it to work.  I'm assuming, that's what they said.  But, I bet it does treat margins the same as the text area.

You might be able to build your own menu and use that?  CanPaste, CanUndo, all the stuff is there to make one.

If you're a Pimp ... You could capture the right click and manually send another right click to the ScintillaNET control, with the coordinates of the selected area.  Tell it you right clicked on the selected text and not in the margin.

**Comment by xv** [comment]
> **Update:**
> https://sourceforge.net/p/scintilla/feature-requests/1080/
> Looks like this issue has been talked about & I think they decided that's how they wanted it to work. 

https://sourceforge.net/p/scintilla/bugs/1580/ as well.

**Comment by ntnam171** [comment]
Yes, Thanks you.
It's not like WordPad, but it's like Word.
