### ISSUE TITLE
How do I incorporate new Scintilla files?

### ISSUE THREAD

**Issue by tobeypeters** [jacobslusser/ScintillaNET#450]
I've updated and recompiled the Scintilla source code.  How do I incorporate the new Scintilla.dll and SciLexer.dll files?

**Comment by xv** [comment]
Did you try [/wiki/Using-a-Custom-SciLexer.dll](https://github.com/jacobslusser/ScintillaNET/wiki/Using-a-Custom-SciLexer.dll)?

**Comment by tobeypeters** [comment]
I saw my mistake and see the SetModulePath().  

But, I really would like to know, how to "upgrade" ScintillaNet.  Then, I don't have to ship an extra .dll and I don't have to dynamically create Scintilla controls.

I'm not seeing any DLLImport commands to load Scintilla.dll.  So, I'm at a loss right now.

I plan on forking ScintillaNet and Scintilla itself and upload the source changes.  I've got other things planned, for them.
