### ISSUE TITLE
MSSQL Lexer

### ISSUE THREAD

**Issue by leojazz** [jacobslusser/ScintillaNET#453]
Hi,

I noticed that global mssql variables such as @@version aren't styled with the general SQL lexer.

I noticed ScintillaNET has a declaration for an MSSQL Lexer
public const int SCLEX_MSSQL = 55;
but it isn't implemented.

Would the MSSQL lexer solve this problem of styling global variables ?
If yes, would I be able to implement the MSSQL lexer myself ?

Thanks in advance

**Comment by VPKSoft** [comment]
Have you tried just to set the lexer index using an integer. I was able to create a NSIS lexer that way:
```cs
scintilla.Lexer = (Lexer)SCLEX_MSSQL;
```
I also did use custom indices for the style colors:
```cs
scintilla.Styles[SOME_CONSTANT].ForeColor = color1;
scintilla.Styles[SOME_CONSTANT].BackColor = color2;
```

**Comment by leojazz** [comment]
Thanks
