### ISSUE TITLE
How can I modify the Pasca lexer to have more then a keyword set ? 

### ISSUE THREAD

**Issue by METOUIA7** [jacobslusser/ScintillaNET#456]
Is there any solution to get word more like, Word2, Word3 and so on.

**Comment by xv** [comment]
It's not possible to augment built-in lexers. From the [Custom Syntax Highlighting](https://github.com/jacobslusser/ScintillaNET/wiki/Custom-Syntax-Highlighting) page:

> it's not generally possible to augment an existing, built-in lexer with your own custom styling logic. They are not designed to support that.

However, it's actually possible to do it with a bit of work and basic C++ knowledge. You'd need to:
1. Download the native [Scintilla 3.7.2](https://sourceforge.net/projects/scintilla/files/scintilla/3.7.2/) (this is the version our latest-released wrapper uses) so you can modify the [Pascal lexer](https://sourceforge.net/p/scintilla/code/ci/default/tree/lexers/LexPascal.cxx).
2. Start extending the lexer:
   1. Open `scintilla\include\Scintilla.iface` and jump to `SCE_PAS_ASM`. Add your new constant(s) below it. For example: `val SCE_PAS_WORD2=15`.
   2. Run the Python script `scintilla\scripts\LexGen.py`. If the script runs successfully, you should see your new definition(s) in `scintilla\include\SciLexer.h`.
   3. Now open `scintilla\lexers\LexPascal.cxx` and add your own extended lexing.
3. Compile Scintilla for both x64 and x86.
4. Archive the compiled x64 and x86 SciLexer.dll with a .gz extension and place them in `ScintillaNET\x64` and `ScintillaNET\x86` accordingly. Alternatively, check the [Using a Custom SciLexer.dll](https://github.com/jacobslusser/ScintillaNET/wiki/Using-a-Custom-SciLexer.dll) wiki page.
5. Delete the folder in `%localappdata%\Temp\ScintillaNET`.
6. Compile ScintillaNET and see if it outputs any errors.
7. Open `ScintillaNET\NativeMethods.cs` and jump to where `SCE_PAS_ASM` is located. Add your new style constant(s) below it. For example: `public const int SCE_PAS_WORD2 = 15;`.
8. Open `ScintillaNET\Style.cs` and jump to `public static class Pascal`. Add your "human-readable" style constant(s) to the class. For example: `public const int Word2 = NativeMethods.SCE_PAS_WORD2;`.
9. Recompile ScintillaNET.

That's pretty much it. You can work with your new styles like any other old one. It's a long and tedious process, but that's the only way I think think of to extend an existing lexer.

Disclaimer: I did not test what I just wrote. I can't confirm that everything will go buttery smooth, but it should give you an idea of how it's done.

**Comment by forever2020** [comment]
Hi https://github.com/xv
How Compile Scintilla for both x64 and x86

**Comment by forever2020** [comment]
> It's not possible to augment built-in lexers. From the [Custom Syntax Highlighting](https://github.com/jacobslusser/ScintillaNET/wiki/Custom-Syntax-Highlighting) page:
> 
> > it's not generally possible to augment an existing, built-in lexer with your own custom styling logic. They are not designed to support that.
> 
> However, it's actually possible to do it with a bit of work and basic C++ knowledge. You'd need to:
> 
> 1. Download the native [Scintilla 3.7.2](https://sourceforge.net/projects/scintilla/files/scintilla/3.7.2/) (this is the version our latest-released wrapper uses) so you can modify the [Pascal lexer](https://sourceforge.net/p/scintilla/code/ci/default/tree/lexers/LexPascal.cxx).
> 2. Start extending the lexer:
>    
>    1. Open `scintilla\include\Scintilla.iface` and jump to `SCE_PAS_ASM`. Add your new constant(s) below it. For example: `val SCE_PAS_WORD2=15`.
>    2. Run the Python script `scintilla\scripts\LexGen.py`. If the script runs successfully, you should see your new definition(s) in `scintilla\include\SciLexer.h`.
>    3. Now open `scintilla\lexers\LexPascal.cxx` and add your own extended lexing.
> 3. Compile Scintilla for both x64 and x86.
> 4. Archive the compiled x64 and x86 SciLexer.dll with a .gz extension and place them in `ScintillaNET\x64` and `ScintillaNET\x86` accordingly. Alternatively, check the [Using a Custom SciLexer.dll](https://github.com/jacobslusser/ScintillaNET/wiki/Using-a-Custom-SciLexer.dll) wiki page.
> 5. Delete the folder in `%localappdata%\Temp\ScintillaNET`.
> 6. Compile ScintillaNET and see if it outputs any errors.
> 7. Open `ScintillaNET\NativeMethods.cs` and jump to where `SCE_PAS_ASM` is located. Add your new style constant(s) below it. For example: `public const int SCE_PAS_WORD2 = 15;`.
> 8. Open `ScintillaNET\Style.cs` and jump to `public static class Pascal`. Add your "human-readable" style constant(s) to the class. For example: `public const int Word2 = NativeMethods.SCE_PAS_WORD2;`.
> 9. Recompile ScintillaNET.
> 
> That's pretty much it. You can work with your new styles like any other old one. It's a long and tedious process, but that's the only way I think think of to extend an existing lexer.
> 
> Disclaimer: I did not test what I just wrote. I can't confirm that everything will go buttery smooth, but it should give you an idea of how it's done.

Hi
How Compile Scintilla for both x64 and x86
