### ISSUE TITLE
ScintillaReader.cs problem

### ISSUE THREAD

**Issue by forever2020** [jacobslusser/ScintillaNET#476]
i have a problem when compiling the project in file ScintillaReader.cs in these line
        private int BufferRemaining => _data != null ? _data.Length - _dataIndex : 0;
        private int UnbufferedRemaining => _lastData - _nextData;
        private int TotalRemaining => BufferRemaining + UnbufferedRemaining;
the error is after lambda expression

**Comment by xv** [comment]
These lambdas are expression body definitions. They’re part of C# 6.0 syntax, which requires VS 2015 and up.

If you’re already on VS 2015 or newer then check the C# version your Scintilla project is using and increment it if below 6.0.

Alternatively, you can just convert them to regular properties:
```c#
private int BufferRemaining
{
    get { return _data != null ? _data.Length - _dataIndex : 0; }
}

private int UnbufferedRemaining
{
    get { return _lastData - _nextData; }
}

private int TotalRemaining
{
    get { return BufferRemaining + UnbufferedRemaining; }
}
```

**Comment by forever2020** [comment]
Thanks a lot for help
