### ISSUE TITLE
I have Problem with line number.

### ISSUE THREAD

**Issue by ghost** [jacobslusser/ScintillaNET#477]
I want to make lua text program. but I can't make line numbers... I want it to start at 1st line ([image](https://c0rona.is-a.fail/BNt1GA.png)) but, scintilla starting at 0. 
Problem Image: https://c0rona.is-a.fail/03Y08W.png
how to make it.

**Comment by xv** [comment]
Hard to know what's going on without seeing related code. The Lua lexer has a built-in folding mechanism. Is that what you are using?

[/wiki/Automatic-Code-Folding](https://github.com/jacobslusser/ScintillaNET/wiki/Automatic-Code-Folding)
