### ISSUE TITLE
Scintillanet scrollbar

### ISSUE THREAD

**Issue by forever2020** [jacobslusser/ScintillaNET#478]
Hi,
how customise color of horizontal and vertical scrollbar

**Comment by xv** [comment]
You cannot. Scintilla uses the default system scrollbars, so their style is determined directly by the operating system.

The only way to style them is to modify the code of C++ Scintilla to implement a custom scrollbar, then you could probably compile the modified library to use it in ScintillaNET.

You can check out [BowPad](https://github.com/stefankueng/BowPad); they implemented custom scrollers.

Related: #463

**Comment by forever2020** [comment]
thank's for reponse

**Comment by viebrix** [comment]
@forever2020 
see my answer in: https://github.com/jacobslusser/ScintillaNET/issues/463#issuecomment-669987672
