### ISSUE TITLE
Where do I put the license in my app? C#

### ISSUE THREAD

**Issue by Shreddedcoconut** [jacobslusser/ScintillaNET#479]
I don't know where to put the license for Scintilla in my app. It's a commercial app, which I will be selling, but I'm not sure where to put the license.

Should I put it in a text file embedded in the app, or display it to the user if they click a certain button?

Thanks :)

**Comment by xv** [comment]
Licensing is a legal matter and it's best you consult a lawyer when it comes to these things, especially that you are intending to sell your software.

What I can suggest is add a copy of ScintillaNET's LICENSE file to your software's distribution folder and acknowledge ScintillaNET's copyright in your executable's "About" dialog.

**Comment by xv** [comment]
Licensing is a legal matter and it's best you consult a lawyer when it comes to these things, especially that you are intending to sell your software.

What I can suggest is add a copy of ScintillaNET's LICENSE file to your software's distribution folder and acknowledge ScintillaNET's copyright in your executable's "About" dialog. You can acknowledge it by adding a line such as `ScintillaNET (C) Jacob Slusser, MIT` with a hyperlink to this repository.

**Comment by Shreddedcoconut** [comment]
Oh, thanks! Just what I needed :)
