### ISSUE TITLE
Memory leak when adding content in Scintilla.Text

### ISSUE THREAD

**Issue by larouchefrancois** [jacobslusser/ScintillaNET#490]
Hi,

I'm using CefSharp component with this great library to load the source code of a webpage inside ScintillaNet and realized that the memory keeps going up when I load the source inside Scintilla.Text. It is more obvious when I load huge pages like a youtube page (3.7mb) consecutively. I see the memory going up and staying up. And to prove my point I load a small 6k page and it stays the same when it supposes to go down.

Perhaps I need to free it somehow before assigning new content to Scintilla.Text but didn't find how.

I'm using version 3.6.3.

Thanks

**Comment by VPKSoft** [comment]
How about `scintilla.EmptyUndoBuffer();` ?

**Comment by larouchefrancois** [comment]
It's exactly that!!! I saw it but told myself, it's for undo or redo history I don't need that since I never edited it.  But in fact yes, as far the scintilla is concerned, it's first empty and putting text it's still in cache. Worst thing in my case is that I was constantly updating the content with those dynamic content webpages. Especially youtube!

Thanks a lot! :+1:
