### ISSUE TITLE
Multiline comment CPP style ...

### ISSUE THREAD

**Issue by leonunezcl** [jacobslusser/ScintillaNET#50]
Hi,
Testing the .net component i found the multiline comment for a CPP language style it's not working.

/*
    Multiline comment ....
*/

Form load c# sample.

scintilla.Lexer = Lexer.Cpp;
scintilla.Styles[Style.Cpp.CommentLine].ForeColor = Color.FromArgb(0x00, 0x7F, 0x00);
scintilla.Styles[Style.Cpp.CommentLine].Italic = true;

scintilla.Styles[Style.Cpp.CommentDoc].ForeColor = Color.FromArgb(0x00, 0x7F, 0x00);
scintilla.Styles[Style.Cpp.CommentDoc].Italic = true;

scintilla.Styles[Style.Cpp.CommentDocKeyword].ForeColor = Color.FromArgb(0x00, 0x7F, 0x00);
scintilla.Styles[Style.Cpp.CommentDocKeyword].Italic = true;

scintilla.Styles[Style.Cpp.CommentDocKeywordError].ForeColor = Color.FromArgb(0x00, 0x7F, 0x00);
scintilla.Styles[Style.Cpp.CommentDocKeywordError].Italic = true;

scintilla.Styles[Style.Cpp.CommentLineDoc].ForeColor = Color.FromArgb(0x00, 0x7F, 0x00);
scintilla.Styles[Style.Cpp.CommentLineDoc].Italic = true;

scintilla.Styles[Style.Cpp.Preprocessor].ForeColor = Color.FromArgb(0x00, 0x7F, 0x00);
scintilla.Styles[Style.Cpp.Preprocessor].Italic = true;

scintilla.Styles[Style.Cpp.PreprocessorComment].ForeColor = Color.FromArgb(0x00, 0x7F, 0x00);
scintilla.Styles[Style.Cpp.PreprocessorComment].Italic = true;

scintilla.Styles[Style.Cpp.PreprocessorCommentDoc].ForeColor = Color.FromArgb(0x00, 0x7F, 0x00);
scintilla.Styles[Style.Cpp.PreprocessorCommentDoc].Italic = true;

**Comment by theryan722** [comment]
You have not set the style:

```c#
Scintilla1.Styles(Style.Cpp.Comment).ForeColor = COLORHERE;
```

**Comment by leonunezcl** [comment]
It's works!

Thanks!

:)
