### ISSUE TITLE
Question: What event to use to detect mouse move?

### ISSUE THREAD

**Issue by egkareem** [jacobslusser/ScintillaNET#505]
In the demo project, I am trying to capture mouse move to display current line number and column number. What event can I use? None of the events below fire:

```
private void TextPanel_MouseMove(object sender, MouseEventArgs e)
        {

        }

        private void MainForm_MouseMove(object sender, MouseEventArgs e)
        {
			
        }

        private void TextPanel_MouseDown(object sender, MouseEventArgs e)
        {

        }
```

Thanks.

**Comment by Deepchand-Calmove** [comment]
private void Scintilla1_MouseMove(object sender, MouseEventArgs e)
{
}

Where Scintilla1 is textbox kind of control from ScintillaNET. Hope it helps you.

**Comment by egkareem** [comment]
Thank you. Many events are not firing in the demo...I will study it more. For now consider this answered. Thanks much.
