### ISSUE TITLE
Scintilla footer with cursor position and other file properties like NotePad++

### ISSUE THREAD

**Issue by abc983ft** [jacobslusser/ScintillaNET#509]
Is there any built in property to Scintilla that we can enable to get a similar footer to NotePad++ with the cursor position and other useful info?

If there is no such built in method, are there any demo apps that show how to do this in ScintillaNET?

![image](https://user-images.githubusercontent.com/4664989/112908091-e11da580-90bc-11eb-856d-09e74576b955.png)

**Comment by VPKSoft** [comment]
The Scintilla control itself doesn't provide a [StatusStrip](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.statusstrip?f1url=?appId=Dev16IDEF1&l=EN-US&k=k(System.Windows.Forms.StatusStrip);k(Designer_Microsoft.WinForms.DesignTools.Designers.DocumentProxyDesigner);k(VisualSelection)&rd=true&view=net-5.0). 
Starting from this [here](https://github.com/VPKSoft/ScintillaTabbedTextControl/blob/e402a77ff258e34cfa1af9e64c4db8f9e7f23da9/ScintillaTabbedTextControl/ScintillaTabbedTextControl.cs#L2114) are calculations for the required locations, etc... for the Scintilla control.
To detect the encoding I have used the [UTF Unknown](https://github.com/CharsetDetector/UTF-unknown) class library.
For the new ["line delimiter", i.e. `\n\r`, Wikipedia](https://en.wikipedia.org/wiki/Newline).

**Comment by abc983ft** [comment]
thank you very much!
