### ISSUE TITLE
Change background colour of LineNumber column

### ISSUE THREAD

**Issue by Dinoosawruss** [jacobslusser/ScintillaNET#513]
Hi,

I am trying to change the background colour of the LineNumber column in the below Scintilla but have so far been unsuccessful
![image](https://user-images.githubusercontent.com/22278485/122986549-7f0ccd80-d397-11eb-98cc-4c18624cd97e.png)

Any assistance would be appreciated

**Comment by VPKSoft** [comment]
This doesn't seem to be possible if I read the [Scintilla.org](https://www.scintilla.org/ScintillaDoc.html#Margins) instructions correctly; the margin changes into a symbol margin:
```cs
scintilla.Margins[0].Type = MarginType.Color;
scintilla.Margins[0].BackColor = Color.OrangeRed;
```
![image](https://user-images.githubusercontent.com/40712699/122992299-a1f6ac00-d3ae-11eb-86ae-15266df33464.png)

But I'm not sure with such a short test 🙄

**Comment by VPKSoft** [comment]
Seemingly I was wrong:
This works:
```cs
scintilla.Styles[Style.LineNumber].BackColor = Color.OrangeRed;
scintilla.Styles[Style.LineNumber].ForeColor = Color.BlueViolet;
```

![image](https://user-images.githubusercontent.com/40712699/122994803-7aeda980-d3b1-11eb-86d8-63a88228577a.png)

**Comment by Dinoosawruss** [comment]
@VPKSoft hmm I tried what you did and it didn't work? I'll test it again and see

EDIT: Somehow it appears to now work, thanks for the help
