### ISSUE TITLE
How can I remove the background color of the focused line?

### ISSUE THREAD

**Issue by cgm-wmaisenhelder** [jacobslusser/ScintillaNET#528]
I'm using ScintillaNET 5.3.1.3 in .NET Framework 4.5.2 WinForms.  I just dropped the Scintilla control on a new form, and when I run my application, the focused line is black, and I can't read the text on that line unless I select it.  I would like to either simply outline the current line or remove the current line highlighting/focusing altogether.

Please advise.

![image](https://user-images.githubusercontent.com/16723592/199596939-b40e30a6-8e8b-44c2-ae60-890c5e904428.png)

**Comment by VPKSoft** [comment]
Hi,
Set the `scintilla1.CaretLineBackColor = Color.White;`.

**Comment by cgm-wmaisenhelder** [comment]
Awesome! Thank you very much.  I was looking at that, but I (incorrectly) assumed that was referring to the _color_ of the carat, not the background.

Thanks again.
