### ISSUE TITLE
SnippetsList equivalent?

### ISSUE THREAD

**Issue by theryan722** [jacobslusser/ScintillaNET#54]
Are there plans to add the SnippetsList in?

**Comment by jacobslusser** [comment]
Not likely. The usual answer applies--I don't believe there is a universal way to do this where everybody is happy. That should be handled in an application-specific way.

**Comment by theryan722** [comment]
No problem, I'll create a custom one then. Is there a way to get the (x,y)
coordinates of the caret in the editor?

On Thu, Jul 2, 2015 at 4:28 PM, jacobslusser <notifications@github.com>
wrote:

> Not likely. The usual answer applies--I don't believe there is a universal
> way to do this where everybody is happy. That should be handled in an
> application-specific way.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jacobslusser/ScintillaNET/issues/54#issuecomment-118157901>
> .
>



-- 
Ryan O'Day
------------------------------------
Business Email: bionetworkscorp@gmail.com
Business Website: www.bionetworkscorp.net

**Comment by jacobslusser** [comment]
`CharPositionFromPoint`, `CharPositionFromPointClose`, `PointXFromPosition`, and `PointYFromPosition`. 

That should be what you need if you wanted to display a custom popup, buy my recollection is that the last version of ScintillaNET simply used user completion / auto completion lists to display a list of snippets.

**Comment by theryan722** [comment]
Thank you once again.
