### ISSUE TITLE
Custom Keybinding Commands?

### ISSUE THREAD

**Issue by theryan722** [jacobslusser/ScintillaNET#55]
Is it possible to use a method as a command? Or do I have to modify ScintillaNET to add them in?

For example I want to create a key binding for my method to display my snippet list. Is this possible?

Sorry for my storm of questions and whatnot.

**Comment by JohnyMac** [comment]
I don't get what you mean.
But if you want to create a key binding for a certain functionality that is related to your program like saving the file.

You goto the KeyDown event in the control and check if the `e.Key == Keys.WHATEVERKEY` do whatever you want.

**Comment by theryan722** [comment]
I am aware of that solution, however ScintillaNET provides its own key binding. What I want to know is if I can do this through ScintillaNET. But thank you for answering, always greatly appreciated :)

**Comment by jacobslusser** [comment]
There is no facility within ScintillaNET to keybind to a method. It can only bind to one of the `Command` enumeration values. To get the keybinding you want you'll have to intercept the keys in Windows Forms before ScintillaNET processes them as @JohnyMac suggested.

**Comment by theryan722** [comment]
Darn, oh well. Thank you both of you.

On Thu, Jul 2, 2015 at 8:14 PM, jacobslusser <notifications@github.com>
wrote:

> There is no facility within ScintillaNET to keybind to a method. It can
> only bind to one of the Command enumeration values. To get the keybinding
> you want you'll have to intercept the keys in Windows Forms before
> ScintillaNET processes them as @JohnyMac <https://github.com/JohnyMac>
> suggested.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jacobslusser/ScintillaNET/issues/55#issuecomment-118199220>
> .
>



-- 
Ryan O'Day
------------------------------------
Business Email: bionetworkscorp@gmail.com
Business Website: www.bionetworkscorp.net
