### ISSUE TITLE
Is it possible for Auto indentation to mark lines as foldpoints?

### ISSUE THREAD

**Issue by theryan722** [jacobslusser/ScintillaNET#56]
I am using auto indentation, and would like to be able to determine if a line is a fold point or not. I remember reading somewhere about setting a property to do this. Is this possible?

**Comment by theryan722** [comment]
I really wish we could set labels so not everything is posted as an issue.

**Comment by JohnyMac** [comment]
IDK if its implemented in ScintillaNET or not but in native scintilla, I think you will use this: `SCI_GETFOLDEXPANDED`

**Comment by jacobslusser** [comment]
The `SCI_GETFOLDEXPANDED` constants translates to the `Line.Expanded` property in ScintillaNET. That will tell you whether the line is marked as expanded or collapsed, however, to determine if a line is a fold point you should test for the `FoldLevelFlags.Header` flag. i.e.

```cs
if((scintilla.Lines[0].FoldLevelFlags & FoldLevelFlags.Header) > 0)
{
    // ...
}
```

**Comment by theryan722** [comment]
Sorry, but the code isn't working for me.

**Comment by jacobslusser** [comment]
Can you be more specific? It's difficult for me to provide assistance with such little information to go on....

When I run the following code, the output matches 1 for 1 with my fold points:
```cs
foreach (var line in scintilla.Lines)
{
    var message = "Lines[{0}] - fold level: {1}, is fold point: {2}";
    Debug.WriteLine(message, line.Index, line.FoldLevel, ((line.FoldLevelFlags & FoldLevelFlags.Header) > 0));
}
```

**Comment by theryan722** [comment]
Okay sorry about that. You example fixed my issue, however I am having trouble folding/expanding a line.

Here is what I have: 

```c#
public object LineIsFoldPoint(bool linenum)
{
	return ((Scintilla1.Lines(linenum).FoldLevelFlags & FoldLevelFlags.Header) > 0);
}

public void FoldAll()
{
	foreach (Line ln in Scintilla1.Lines) {
		if (LineIsFoldPoint(ln.Index)) {
			ln.FoldLine(FoldAction.Contract);
		}
	}
}
```

The **Fold()** method does nothing for me, the same if I try **FoldAction.Toggle** or **FoldAction.Expand**

**Comment by jacobslusser** [comment]
`Scintilla.FoldAll(FoldAction.Toggle)` does exactly as advertised for me....

Are you implementing custom folding or using one provided by a lexer? If you are implementing your own, the chances are your error is in your implementation. Custom folding can be difficult. Studying the Scintilla lexer source code can be helpful here as can be helper methods which dump your current `FoldLevel` and `FoldLevelFlags` as the sample I have above does.

**Comment by theryan722** [comment]
I'm using the automatic folding provided by the lexer, weird.

**Comment by theryan722** [comment]
WHAT, how did I not see this?! Thank you!
