### ISSUE TITLE
Thoughts on large file management?

### ISSUE THREAD

**Issue by theryan722** [jacobslusser/ScintillaNET#59]
I am aware that Scintilla can only deal with files up to 2 GB. However the ScintillaNET control starts to really lag before even before 100,000 lines (with each line being 32 characters long). Is there a way to combat this? I know that the FastColoredTextBox control handles large files pretty well (handles over 100,000 lines without lagging) and can handle even larger files through lazy loading of the file.

Does Scintilla have something similar, or is there a way to do something similar?

**Comment by JohnyMac** [comment]
What..

I am pretty sure it's either your program that do too much logic on the background or you have a very old computer, as I did some tests like a month ago with a 90k lines file between ScintillaNET and various other editors and scintilla was the fastest at loading the files and at colorizing them.. 

It was ScintillaNet 2.6 and not this one though, dunno if it matters.

**Comment by theryan722** [comment]
I didn't think I was performing that many background actions :( Just tested on a fresh project. Entered in 130,000 lines of code. Super fast. Darn.

**Comment by theryan722** [comment]
Still better than Visual Studio's file management haha, just tried opening the 130,000 line file, Visual Studio crashed.

**Comment by theryan722** [comment]
Upon further testing, the raw ScintillaNET control flawlessly handles millions of lines, extremely impressive.
