### ISSUE TITLE
PASCAL highlighting

### ISSUE THREAD

**Issue by METOUIA7** [jacobslusser/ScintillaNET#61]
CAN YOU HELP ME 
HOW TO CONFIGURE PASCAL highlighting

**Comment by theryan722** [comment]
ScintillaNET does not have the style configuration setup for Pascal yet. The creator of this project has stated that he has been adding them on an on-need basis. So your language will likely be added very soon, I might even implement it for you.

You can also check out [this wiki page on syntax highlighting](https://github.com/jacobslusser/ScintillaNET/wiki/Automatic-Syntax-Highlighting)

**Comment by METOUIA7** [comment]
Thank you for response
I can implement syntax highlighting for PASCAL or no ??????

**Comment by theryan722** [comment]
On second thought, and rereading the Scintilla documentation, Pascal uses the same style configuration as C++. All the wrapper needs is the **lexer** to be implemented. I will do so now for you and create a merge request. (Jacob, please correct me if I am wrong about the styling part).

**Comment by theryan722** [comment]
After reviewing the documentation, the styling configuration for Pascal is the same as the configuration for C++. So all you have to do is set the lexer to Pascal, but use the C++ style configuration. Like so:

```c#
// Configuring the default style with properties
// we have common to every lexer style saves time.
scintilla.StyleResetDefault();
scintilla.Styles[Style.Default].Font = "Consolas";
scintilla.Styles[Style.Default].Size = 10;
scintilla.StyleClearAll();

// Configure the lexer styles
scintilla.Styles[Style.Cpp.Default].ForeColor = Color.Silver;
scintilla.Styles[Style.Cpp.Comment].ForeColor = Color.FromArgb(0, 128, 0); // Green
scintilla.Styles[Style.Cpp.CommentLine].ForeColor = Color.FromArgb(0, 128, 0); // Green
scintilla.Styles[Style.Cpp.CommentLineDoc].ForeColor = Color.FromArgb(128, 128, 128); // Gray
scintilla.Styles[Style.Cpp.Number].ForeColor = Color.Olive;
scintilla.Styles[Style.Cpp.Word].ForeColor = Color.Blue;
scintilla.Styles[Style.Cpp.Word2].ForeColor = Color.Blue;
scintilla.Styles[Style.Cpp.String].ForeColor = Color.FromArgb(163, 21, 21); // Red
scintilla.Styles[Style.Cpp.Character].ForeColor = Color.FromArgb(163, 21, 21); // Red
scintilla.Styles[Style.Cpp.Verbatim].ForeColor = Color.FromArgb(163, 21, 21); // Red
scintilla.Styles[Style.Cpp.StringEol].BackColor = Color.Pink;
scintilla.Styles[Style.Cpp.Operator].ForeColor = Color.Purple;
scintilla.Styles[Style.Cpp.Preprocessor].ForeColor = Color.Maroon;
scintilla.Lexer = Lexer.Pascal;

// Set the keywords
scintilla.SetKeywords(0, "KEYWORDS HERE");
scintilla.SetKeywords(1, "KEYWORDS HERE");
```

I believe this should work, but I haven't tested it.

**Comment by METOUIA7** [comment]
THANKS ALOT FOR YOUR HELP

**Comment by jacobslusser** [comment]
Support for the dedicated Pascal lexer was added in ScintillaNET v3.5.0. See also issue #65 for more details.
