### ISSUE TITLE
How to add custom highlighting for a certain regex statement.

### ISSUE THREAD

**Issue by JohnyMac** [jacobslusser/ScintillaNET#62]
I want to highlight any text that match this regex: `(?:\/\*\*[\s\S])(?:\*\*.*[\s\S])+(?:\*\/)` with a green italic font.

How can this be done ?, Thanks in advanced :)

**Comment by theryan722** [comment]
[This wiki page should help you](https://github.com/jacobslusser/ScintillaNET/wiki/Custom-Syntax-Highlighting)

**Comment by JohnyMac** [comment]
It did help me, Thanks a lot.
