### ISSUE TITLE
pascal treatment 

### ISSUE THREAD

**Issue by METOUIA7** [jacobslusser/ScintillaNET#65]
the comment in pascal is between { .... } and the treatment several instruction is between begin ... end
how to change { }  in lexer cpp  to begin end  and say { } is for the comment

this is my code
Scintilla.StyleResetDefault();
Scintilla.Styles(Style.Default).Font = "Times new roman";
Scintilla.Styles(Style.Default).Size = 11;
Scintilla.StyleClearAll();

Scintilla.Lexer = Lexer.Cpp;

Scintilla.SetProperty("fold", "1");

Scintilla.Margins(2).Type = MarginType.Symbol;
Scintilla.Margins(2).Mask = Marker.MaskFolders;
Scintilla.Margins(2).Sensitive = true;
Scintilla.Margins(2).Width = 20;

for (int i = Marker.FolderEnd; i <= Marker.FolderOpen; i++) {
	Scintilla.Markers(i).SetForeColor(SystemColors.ControlLightLight);
	Scintilla.Markers(i).SetBackColor(SystemColors.ControlDark);
}

Scintilla.Markers(Marker.Folder).Symbol = MarkerSymbol.CirclePlus;
Scintilla.Markers(Marker.Folder).SetBackColor(SystemColors.ControlText);
Scintilla.Markers(Marker.FolderOpen).Symbol = MarkerSymbol.CircleMinus;
Scintilla.Markers(Marker.FolderEnd).Symbol = MarkerSymbol.CirclePlusConnected;
Scintilla.Markers(Marker.FolderEnd).SetBackColor(SystemColors.ControlText);
Scintilla.Markers(Marker.FolderMidTail).Symbol = MarkerSymbol.TCorner;
Scintilla.Markers(Marker.FolderOpenMid).Symbol = MarkerSymbol.CircleMinusConnected;
Scintilla.Markers(Marker.FolderSub).Symbol = MarkerSymbol.VLine;
Scintilla.Markers(Marker.FolderTail).Symbol = MarkerSymbol.LCorner;

Scintilla.AutomaticFold = (AutomaticFold.Show | AutomaticFold.Click | AutomaticFold.Change);

Scintilla.Styles(Style.Cpp.Default).ForeColor = Color.FromArgb(0x80, 0x80, 0x80);
Scintilla.Styles(Style.Cpp.CommentLine).ForeColor = Color.FromArgb(0x0, 0x7f, 0x0);
Scintilla.Styles(Style.Cpp.CommentLine).Italic = true;
Scintilla.Styles(Style.Cpp.Number).ForeColor = Color.FromArgb(0x0, 0x7f, 0x7f);
Scintilla.Styles(Style.Cpp.String).ForeColor = Color.FromArgb(0x7f, 0x0, 0x7f);
Scintilla.Styles(Style.Cpp.Character).ForeColor = Color.FromArgb(0x7f, 0x0, 0x7f);
Scintilla.Styles(Style.Cpp.Word).ForeColor = Color.FromArgb(0x0, 0x0, 0x7f);
Scintilla.Styles(Style.Cpp.Word).Bold = true;
Scintilla.Styles(Style.Cpp.Operator).Bold = true;

Scintilla.Styles(Style.Cpp.StringEol).ForeColor = Color.FromArgb(0x0, 0x0, 0x0);
Scintilla.Styles(Style.Cpp.StringEol).BackColor = Color.FromArgb(0xe0, 0xc0, 0xe0);
Scintilla.Styles(Style.Cpp.StringEol).FillLine = true;
Scintilla.Styles(Style.Cpp.Word2).ForeColor = Color.FromArgb(0x40, 0x70, 0x90);

Scintilla.ViewWhitespace = WhitespaceMode.VisibleAlways;

dynamic pascal1 = "absolute abstract and array as asm assembler automated begin case";
dynamic pascal2 = "cdecl class const constructor delayed deprecated destructor dispid dispinterface";
dynamic pascal3 = "div do downto dynamic else end except experimental export exports external far";
dynamic pascal4 = "file final finalization finally for forward function goto helper if";
dynamic pascal5 = "implementation in inherited initialization inline interface is label library";
dynamic pascal6 = "message mod near nil not object of on operator or out overload override packed";
dynamic pascal7 = "pascal platform private procedure program property protected public published";
dynamic pascal8 = "raise record reference register reintroduce repeat resourcestring safecall";
dynamic pascal9 = "sealed set shl shr static stdcall strict string then threadvar to try type unit";
dynamic pascal10 = "unsafe until uses var varargs virtual while winapi with xor add default implements index name nodefault read readonly remove stored write writeln read readln writeonly";
Scintilla.SetKeywords(0, pascal1 + " " + pascal2 + " " + pascal3 + " " + pascal4 + " " + pascal5 + " " + pascal6 + " " + pascal7 + " " + pascal8 + " " + pascal9 + " " + pascal10);

**Comment by jacobslusser** [comment]
Sorry, I believe there was some confusion about suggesting you use the C++ lexer. You should actually be using the dedicated Pascal lexer. Switch all your references from `Style.Cpp` to `Style.Pascal` and `Lexer.Cpp` to `Lexer.Pascal` and you should be good.

The pascal constants were added in ScintillaNET v3.5.0.

**Comment by theryan722** [comment]
I apologize, I the scintilla documentation listed **ColourizePascal()** under each style constant so I assumed it was the same without digging any further.

**Comment by METOUIA7** [comment]
thanks jacobslusser for help it works well
