### ISSUE TITLE
Indicators is not documented.

### ISSUE THREAD

**Issue by JohnyMac** [jacobslusser/ScintillaNET#66]
I took a quick a look at the wiki searching for the way to add indicators, But I couldn't find anything.

I want to use indicators to highlight errors in the code.

**Comment by theryan722** [comment]
[This wiki page demonstrates using indicators](https://github.com/jacobslusser/ScintillaNET/wiki/Find-and-Highlight-Words)

**Comment by JohnyMac** [comment]
Thanks mate.
