### ISSUE TITLE
print and search in scintilla

### ISSUE THREAD

**Issue by METOUIA7** [jacobslusser/ScintillaNET#68]
what s command to use for printing scintilla document and to search a word in it
in the old virsion i use name of scintilla.Printing.Print()
and for search Scintilla.FindReplace
and thank you

**Comment by METOUIA7** [comment]
This is the code that i used in my project
Scintilla1.SetProperty("tab.timmy.whinge.level", "1");
Scintilla1.SetProperty("fold", "1");


Scintilla1.Margins(2).Type = MarginType.Symbol;
Scintilla1.Margins(2).Mask = Marker.MaskFolders;
Scintilla1.Margins(2).Sensitive = true;
Scintilla1.Margins(2).Width = 20;

for (int i = Marker.FolderEnd; i <= Marker.FolderOpen; i++) {
	Scintilla1.Markers(i).SetForeColor(SystemColors.ControlLightLight);
	Scintilla1.Markers(i).SetBackColor(Color.Black);
}

Scintilla1.Markers(Marker.Folder).Symbol = MarkerSymbol.BoxPlus;
Scintilla1.Markers(Marker.Folder).SetBackColor(SystemColors.ControlText);
Scintilla1.Markers(Marker.FolderOpen).Symbol = MarkerSymbol.BoxMinus;
Scintilla1.Markers(Marker.FolderEnd).Symbol = MarkerSymbol.BoxPlusConnected;
Scintilla1.Markers(Marker.FolderEnd).SetBackColor(SystemColors.ControlText);
Scintilla1.Markers(Marker.FolderMidTail).Symbol = MarkerSymbol.TCorner;
Scintilla1.Markers(Marker.FolderOpenMid).Symbol = MarkerSymbol.BoxMinusConnected;
Scintilla1.Markers(Marker.FolderSub).Symbol = MarkerSymbol.VLine;
Scintilla1.Markers(Marker.FolderTail).Symbol = MarkerSymbol.LCorner;

Scintilla1.AutomaticFold = (AutomaticFold.Show | AutomaticFold.Click | AutomaticFold.Change);

**Comment by jacobslusser** [comment]
> what s command to use for printing scintilla document and to search a word in it
in the old virsion i use name of scintilla.Printing.Print()

I haven't implemented printing yet in the new version.

> and for search Scintilla.FindReplace

For searching you should use the `SearchFlags`, `TargetStart`, `TargetEnd`, `SearchInTarget` APIs. You can find examples in the project Issues and Wiki.

**Comment by METOUIA7** [comment]
THANKS ALOT FOR HELP

**Comment by JohnyMac** [comment]
Why do you have your CAPS on in all your issues.. Please stop it.
