### ISSUE TITLE
[Question] How to detect when the mouse hovers over an indicator.

### ISSUE THREAD

**Issue by JohnyMac** [jacobslusser/ScintillaNET#69]
Just as the title says.

I want to show a call-tip when the user hovers over an indicator.

**Comment by jacobslusser** [comment]
A combination of `DwellStart` event and the `Indicator.Start` and `Indicator.End` methods. Only problem is the `Indicator.Start` and `Indicator.End` methods have not been implemented yet. If you want to take a stab at implementing them or want to drop down to native calls, go ahead. [http://www.scintilla.org/ScintillaDoc.html#SCI_INDICATORSTART](http://www.scintilla.org/ScintillaDoc.html#SCI_INDICATORSTART).

I'll add it to my to-do list.

**Comment by JohnyMac** [comment]
I took a look but I couldn't understand how to use it.

First parameter will be the indicator's ID and the second paramater will be the position of what exactly ?

And what will it return ?

**Comment by jacobslusser** [comment]
In commit de2efd6608bcbf382f79efd1372b6736294bcf6c I added support for the indicator stuff you need. The commit also includes some new documentation (work in progress) which should give you a jumpstart on how to use the new methods.

[docs/sections](https://github.com/jacobslusser/ScintillaNET/tree/master/docs/sections)
