### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by trdwll** [jacobslusser/ScintillaNET#7]
Will the search/find form be implemented by default again?
Making custom lexer highlights via xml?

*BUG*
When displaying line numbers and you have alot in the editor, it messes up the numbers and doesn't display them fully. (Lines 1-100 show then 1000+ shows 000 etc)

**Comment by jacobslusser** [comment]
**Will the search/find form be implemented by default again?** See issue #4. My personal feeling is that these dialogs are application-specific and not well suited for inclusion in the ScintillaNET core library. However, my suggestion was that if there was sufficient demand a separate ScintillaNET.Extensions library might be created (or community driven).
**Making custom lexer highlights via xml?** See issue #5. I don't currently have plans to define lexer settings via XML, but I'm not particularly opposed to a simple "load style definitions from XML" method.

From the description of your bug it sounds like your line numbers margin width is not automatically adjusting and when the number of characters is > 3, it is getting cut off. If that is the case you can find instructions in the project README.md for automatically adjusting the margin width in the section "[Displaying Line Numbers](https://github.com/jacobslusser/ScintillaNET#line-numbers)".

**Comment by trdwll** [comment]
Thanks for the response. I just recently found this newer version if ScintillaNET, and it's looking promising. Keep up the great work! :D
