### ISSUE TITLE
Scintilla icons

### ISSUE THREAD

**Issue by METOUIA7** [jacobslusser/ScintillaNET#71]
How can i use  the scintilla icon in this virsion
http://www.scintilla.org/Icons.html
if it's possible can you write an example
and thanks

**Comment by jacobslusser** [comment]
You didn't specify how you wanted to use the icons. In an autocompletion list? In a marker? These icons don't come packaged with Scintilla(NET) and they are also in an old XPM format that would require conversion before you could use them in ScintillaNET.

For a general explanation of how to use images with an autocompletion list, see Issue #72.

**Comment by METOUIA7** [comment]
i like to insert an icon like this image 
![impr](https://cloud.githubusercontent.com/assets/13167974/8638798/1ec3d3b8-28be-11e5-81b1-e3734eb32de8.png)

**Comment by jacobslusser** [comment]
The wiki article [Bookmark Lines](https://github.com/jacobslusser/ScintillaNET/wiki/Bookmark-Lines) has a brief explanation of how to display markers in a margin. However, to use an image instead of a symbol, you would do something like this:

```cs
marker.Symbol = MarkerSymbol.RgbaImage;
marker.DefineRgbaImage(new Bitmap(@"custom_image.png"));
```

**Comment by METOUIA7** [comment]
thanks alote for help
