### ISSUE TITLE
Using icon in AutoComplete list

### ISSUE THREAD

**Issue by Aghlara** [jacobslusser/ScintillaNET#72]
Hi,

In the new implementation (v3) I cannot find how to add Icon/Image in the autocomplete list. 
When I look at usages of SCI_REGISTERIMAGE seems to be unused as well.

So the question is how to add icon on the list that is displayed with scintilla.AutoCShow method?

Many thanks,
Arash

**Comment by jacobslusser** [comment]
The SCI_REGISTERIMAGE message uses an old XPM format and was superseded by SCI_REGISTERRGBAIMAGE. The ScintillaNET implementation of that is `Scintilla.RegisterRgbaImage`.

To use an image in an autocomplete list, you would first call `RegisterRgbaImage` to associate an image with an integer index. Then, to display that image you would suffix an autocomplete word with `"?n"`, where `n` is the integer index. For example:

```cs
// Register the images. This only needs to be done once.
scintilla.RegisterRgbaImage(0, new Bitmap(@"my_first_image.png"));
scintilla.RegisterRgbaImage(1, new Bitmap(@"my_second_image.png"));
```

```cs
// Refer back to the registered image index using "?n"
scintilla.AutoCShow(lenEntered, "abstract?0 as base?1 break etc");
```

For a primer on how to use autocompletion in general, you might also enjoy the [Basic Autocompletion](https://github.com/jacobslusser/ScintillaNET/wiki/Basic-Autocompletion) wiki article.

**Comment by FlexRule** [comment]
Thanks a lot, that helped.

**Comment by Aghlara** [comment]
Thanks a lot that helped.
