### ISSUE TITLE
Custom Marker

### ISSUE THREAD

**Issue by Aghlara** [jacobslusser/ScintillaNET#73]
Hi Jacob,

Thanks for the control. 

How is that possible to add a custom image on a margin?

Regards,
Arash

**Comment by theryan722** [comment]
[See Issue #71](https://github.com/jacobslusser/ScintillaNET/issues/71)

**Comment by Aghlara** [comment]
Thanks for the help. This works, however I see difference in version 2 to 3. In v2 image was displayed in a better quality. Is there any reason that the image looked better in v2 than v3?

**Comment by jacobslusser** [comment]
Can you provide an example?

**Comment by Aghlara** [comment]
Here is v2:
![v2](https://cloud.githubusercontent.com/assets/5187409/8733971/28e38f16-2c4a-11e5-8413-90ca00350081.png)

Here is v3:
![v3](https://cloud.githubusercontent.com/assets/5187409/8733953/10e2907e-2c4a-11e5-886e-58ea6a1308b2.png)

v2 is the correct image look/quality.

**Comment by jacobslusser** [comment]
I believe the "quality" issue you were seeing was because of a bug in the image conversion logic. Please get commit 23e5ee68d62f553094798c264192bafd2fdc462e and try again.

**Comment by Aghlara** [comment]
Thanks Jacob. 

That solved the issue, you were right, there was an issue in that convertor logic.
I got the latest from main branch and updated it, I noticed a strange behaviour (miss-behaviour) with markets. So I decided to use the 3.5.0 and patched it with your fix for icon convertor and the problem went away and the icon now is all good.

Many thanks,
