### ISSUE TITLE
about  Lexer.Container 

### ISSUE THREAD

**Issue by wkevinst** [jacobslusser/ScintillaNET#77]
in Lexer.Container 
AutomaticFold  can't work ?

thanks

   scintilla.SetProperty("fold", "1");
   scintilla.SetProperty("fold.compact", "1");

            
            scintilla.Margins[2].Width = 16;
            scintilla.Margins[2].Sensitive = true;
            scintilla.Margins[2].Type = MarginType.Symbol;
            scintilla.Margins[2].Mask = Marker.MaskFolders;

            for (int i = Marker.FolderEnd; i <= Marker.FolderOpen; i++)
            {
                scintilla.Markers[i].SetForeColor(SystemColors.ControlLightLight);
                scintilla.Markers[i].SetBackColor(SystemColors.ControlDark);
            }

            scintilla.Markers[Marker.Folder].Symbol = MarkerSymbol.BoxPlus;
            scintilla.Markers[Marker.Folder].SetBackColor(SystemColors.ControlText);
            scintilla.Markers[Marker.FolderOpen].Symbol = MarkerSymbol.BoxMinus;
            scintilla.Markers[Marker.FolderEnd].Symbol = MarkerSymbol.BoxPlusConnected;
            scintilla.Markers[Marker.FolderEnd].SetBackColor(SystemColors.ControlText);
            scintilla.Markers[Marker.FolderMidTail].Symbol = MarkerSymbol.TCorner;
            scintilla.Markers[Marker.FolderOpenMid].Symbol = MarkerSymbol.BoxMinusConnected;
            scintilla.Markers[Marker.FolderSub].Symbol = MarkerSymbol.VLine;
            scintilla.Markers[Marker.FolderTail].Symbol = MarkerSymbol.LCorner;

            scintilla.AutomaticFold = (AutomaticFold.Show | AutomaticFold.Click | AutomaticFold.Change);

**Comment by jacobslusser** [comment]
Fold points are not provided automatically. `AutomaticFold` refers to how you want Scintilla to automatically handle the clicking, expanding, and collapsing of fold points, not the *creation* of fold points.

The creation of fold points is usually handled by the lexer. If you are using `Lexer.Container` then you must create the fold points yourself.
