### ISSUE TITLE
Folding

### ISSUE THREAD

**Issue by Aghlara** [jacobslusser/ScintillaNET#81]
Hi,

I am in process of migrating to v3 from v2.

When I used the config in wiki to show the folds I get this:
![image](https://cloud.githubusercontent.com/assets/5187409/8708592/47e37374-2b80-11e5-8a17-2e578e8d40c4.png)

The plus does not appear for click.

**Comment by Aghlara** [comment]
This is what I used:

            editor.Margins[2].Type = MarginType.Symbol;
            editor.Margins[2].Mask = Marker.MaskFolders;
            editor.Margins[2].Sensitive = true;
            editor.Margins[2].Width = 20;
            editor.MarginClick += editor_MarginClick;
            for (int i = 25; i <= 31; i++)
            {
                editor.Markers[i].SetForeColor(SystemColors.ControlLightLight);
                editor.Markers[i].SetBackColor(SystemColors.ControlDark);
            }

            // Configure folding markers with respective symbols
            editor.Markers[Marker.Folder].Symbol = MarkerSymbol.BoxPlus;
            editor.Markers[Marker.FolderOpen].Symbol = MarkerSymbol.BoxMinus;
            editor.Markers[Marker.FolderEnd].Symbol = MarkerSymbol.BoxPlusConnected;
            editor.Markers[Marker.FolderMidTail].Symbol = MarkerSymbol.TCorner;
            editor.Markers[Marker.FolderOpenMid].Symbol = MarkerSymbol.BoxMinusConnected;
            editor.Markers[Marker.FolderSub].Symbol = MarkerSymbol.VLine;
            editor.Markers[Marker.FolderTail].Symbol = MarkerSymbol.LCorner;
            editor.AutomaticFold = (AutomaticFold.Show | AutomaticFold.Click | AutomaticFold.Change);

**Comment by Aghlara** [comment]
Fixed! it is related to Lines.IsFoldPoint which in new version is FoldLevelFlags.

**Comment by DaRumpel** [comment]
Strangely, I got the opposite problem: Only +/- is showing, but not the markers for your lines 5-9. 
![sc1](https://cloud.githubusercontent.com/assets/13260880/8835295/dfa91090-30b9-11e5-99ae-b92939857334.jpg)
My code:

            this.editor.SetProperty("fold", "1");       

            // Configure a margin to display folding symbols
            this.editor.Margins[2].Type = MarginType.Symbol;
            this.editor.Margins[2].Mask = Marker.MaskFolders;
            this.editor.Margins[2].Sensitive = true;
            this.editor.Margins[2].Width = 20;

            // Set colors for all folding markers
            for (int i = 25; i <= 31; i++)
            {
                this.editor.Markers[i].SetForeColor(SystemColors.ControlLightLight);
                this.editor.Markers[i].SetBackColor(SystemColors.ControlDark);
            }

            // Configure folding markers with respective symbols
            this.editor.Markers[Marker.Folder].Symbol = MarkerSymbol.BoxPlus;
            this.editor.Markers[Marker.FolderOpen].Symbol = MarkerSymbol.BoxMinus;
            this.editor.Markers[Marker.FolderEnd].Symbol = MarkerSymbol.BoxPlusConnected;
            this.editor.Markers[Marker.FolderMidTail].Symbol = MarkerSymbol.TCorner;
            this.editor.Markers[Marker.FolderOpenMid].Symbol = MarkerSymbol.BoxMinusConnected;
            this.editor.Markers[Marker.FolderSub].Symbol = MarkerSymbol.VLine;
            this.editor.Markers[Marker.FolderTail].Symbol = MarkerSymbol.LCorner;

            // Enable automatic folding
            this.editor.AutomaticFold = (AutomaticFold.Show | AutomaticFold.Click | AutomaticFold.Change);
            this.editor.SetFoldFlags(FoldFlags.LineAfterContracted | FoldFlags.LineBeforeContracted);

And in the custom lexer (block start is "c {", block end is "c }"):

            // Level storage
            int currentLevel = 0;

            // Go through all lines
            for (int i = 0; i < this._lines.Length; i++)
            {
                string line = this._scintilla.Lines[this._lines[i]].Text.TrimEnd();

                if (line.Length > 2 && line.Substring(0, 3).ToLower() == "c {")
                {
                    // Folder start
                    this.SetLevel(this._lines[i], currentLevel);
                    this._scintilla.Lines[this._lines[i]].FoldLevelFlags = FoldLevelFlags.Header;
                    currentLevel++;
                }
                else if (line.Length > 2 && line.Substring(0, 3).ToLower() == "c }")
                {
                    // Folder end
                    this.SetLevel(this._lines[i], currentLevel);
                    currentLevel--;

                    if (currentLevel < 0)
                        currentLevel = 0;
                }
                else
                {
                    // Ordinary line
                    if (line.Length == 0)
                        this._scintilla.Lines[this._lines[i]].FoldLevelFlags = FoldLevelFlags.White;

                    this.SetLevel(this._lines[i], currentLevel);
                }
            }

and

        private void SetLevel(int line, int level)
        {
            this._scintilla.Lines[line].FoldLevel = level;
        }

What am I doing wrong?
