### ISSUE TITLE
Selection

### ISSUE THREAD

**Issue by Aghlara** [jacobslusser/ScintillaNET#82]
Hi,
What are the equivalent of 

*Selection.Start
*Selection.Length

in v3 code base?

Regards,

**Comment by Aghlara** [comment]
Selections.First() does it.

**Comment by jacobslusser** [comment]
As you've discovered, v3 supports multiple selections. When there is only a single selection doing `Selections.First()` as you did should be what you want. For safety you might also check the `Selections.IsEmpty` and/or `Selections.Count` property before doing that. When there are multiple selections you can use the `Scintilla.MainSelection` property to identify which selection in the collection is the "main" selection. i.e.

```cs
Selection sel = null;
if (!scintilla.Selections.IsEmpty)
    sel = scintilla.Selections[scintilla.MainSelection];
```

That being said, I think there is still a lot of people who are not using multiple selections and will want to use simple properties to get the selection start and selection end. So In commit 94ccd92ad53567be91b160fb7d20d97235834b80 I've added support for `SelectionStart` and `SelectionEnd` properties. Be sure to read the remarks for each to make sure you understand their usage.
