### ISSUE TITLE
Encoding error when first loading file

### ISSUE THREAD

**Issue by jacobslusser** [jacobslusser/ScintillaNET#87]
https://github.com/HTD/ScintillaNET/tree/master/Test

Here's the sample. It has to be cloned as whole project because of encoded test files.

After starting program - select any menu option - this would load one of the test files.
The correct text is "Zażółć gęślą jaźń.". But you will get something else - corrupt text.
Select any menu option again - you should see correct text. With any encoding option.
Uncomment line 20 in Test.cs ("scintilla1.Document = Document.Empty;")
Run program and select any option
Now text should be displayed correctly for each test from the first time.

**Comment by jacobslusser** [comment]
Upon closer examination, calling `scintilla.Document = Document.Empty` isn't really a fix. A side product of that call (and another bug) is that it is resetting the encoding used internally by Scintilla from UTF8 to the default. That gives the appearance that it is working but it actually isn't.

So in addition to determining what the underlying issue is, I believe I also have a fix to do when changing the document to make sure the encoding does not change.

**Comment by HTD** [comment]
Looks like I found a real workaround for this: Scintilla.cs, added line 3489:

    DirectMessage(NativeMethods.SCI_SETCODEPAGE, new IntPtr(NativeMethods.SC_CP_UTF8));

in `Document` setter. Works as charm. Is it OK? Look at my test again, now it works, and I added some Russian text to my UTF-8 sample to illustrate correct UTF-8 behavior.
