### ISSUE TITLE
[Request]Selection Events

### ISSUE THREAD

**Issue by theryan722** [jacobslusser/ScintillaNET#92]
Would it be possible to implement any of the following events:

SelectionChanged (the selected text has changed, like in v2)
SelectionStarted (a selection has begun, i.e. the user is dragging the mouse etc.)
SelectionEnded (the user has made the selection)

**Comment by jacobslusser** [comment]
The `UpdateUI` event should be sufficient for what you want (and is what the v2 `SelectionChanged` event is based on). To determine if the update was the result of a selection change:

```cs
if((e.Change & UpdateChange.Selection) > 0) ...
```

**Comment by theryan722** [comment]
Thanks!
