### ISSUE TITLE
Crash when control is moved

### ISSUE THREAD

**Issue by theryan722** [jacobslusser/ScintillaNET#93]
I use a dockpanel suite with the ScintillaNET control in it. Everything was fine until one of the recent versions, where now if you drag the form that the control is on an exception is thrown. I don't know which version of ScintillaNET caused it because I only just noticed it. The following error is displayed:

    An unhandled exception of type 'System.AccessViolationException' occurred in ScintillaNET.dll
    Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

for the method:

```c#
private static IntPtr DirectMessage(IntPtr sciPtr, int msg, IntPtr wParam, IntPtr lParam)
        {
            // Like Win32 SendMessage but directly to Scintilla
            var result = directFunction(sciPtr, msg, wParam, lParam);
            return result;
        }
```

EDIT: now for some reason even if I try using an older version it happens. Is there a fix for this? It is absolutely necessary that I be able to drag it around in my application. Thanks.

**Comment by Aghlara** [comment]
I had the similar issue reported as well #85

**Comment by HTD** [comment]
When should I call `SetDestroyHandleBehavior(true)`? I tried to call it in overriding class constructor, but it crashes. Then I overrode `OnHandleCreated` method and called it there:

        protected override void OnHandleCreated(EventArgs e)
        {
            base.OnHandleCreated(e);
            SetDestroyHandleBehavior(true);
            
        }

But it doesn't work as expected. When the panel is undocked Scintilla settings are reset, all of them, like the low level Scintilla was recreated with default settings.
