### ISSUE TITLE
Loading a file as `Document` makes `StartStyling()` and `SetStyling()` break after text is inserted or deleted by user

### ISSUE THREAD

**Issue by HTD** [jacobslusser/ScintillaNET#94]
https://github.com/HTD/TraxCodeEditor/tree/master/Test1

The test (Test1 project) uses signed `ScintillaNET` 3.5.0 from Nuget package. 
It sets up 2 identical `Scintilla` instances, configures exactly one highlighting style, loads a short text into both instances but using different methods. The text using ASCII encoding to reject any encoding issues.

Left instance's text is loaded by assigning its `Text` property. Right instance's text is loaded using `Scintilla.ILoader` instance.

Both editors are set up to highlight the word "FOX" on each UI update.

Then I simulate of adding and deleting some characters from both editors. I delete all I insert, so the text in both editors should not be changed, and so their highlighting shouldn't change.

Expected behavior: identical text and highlighting on both sides.
Observed behavior: highlighting of the last line in the right editor is moved incorrectly.

![issue94](https://cloud.githubusercontent.com/assets/263558/8894598/9d99dc38-33bc-11e5-8512-e0163f6744f6.png)

**Comment by jacobslusser** [comment]
I believe this is an issue with the native Scintilla component. I've opened a ticket for that team to take a look:

[https://sourceforge.net/p/scintilla/bugs/1745/](https://sourceforge.net/p/scintilla/bugs/1745/)

To summarize, the delete notification doesn't appear to be working correctly when the text being deleted was added via the `Scintilla.ILoader`. You can verify this by watching the `Scintilla.Delete` event. The result is that the byte-to-char translation layer in ScintillaNET is getting out of sync.

**Comment by HTD** [comment]
So I've read the guy's answer. I added `UndoCollection = true` after loading document and now it works. I'm not sure, but it's probably not a bug, OR... Maybe ScinntillaNET should ensure `UndoCollection` is true in `Document` setter?

This seems like the right thing to do (in `Document` setter):
    
    var ptr = value.Value;
    DirectMessage(NativeMethods.SCI_SETDOCPOINTER, IntPtr.Zero, ptr);
    DirectMessage(NativeMethods.SCI_SETCODEPAGE, new IntPtr(NativeMethods.SC_CP_UTF8)); // see issue #87
    DirectMessage(NativeMethods.SCI_SETUNDOCOLLECTION, new IntPtr(1));
