### ISSUE TITLE
Can't install on 2008

### ISSUE THREAD

**Issue by ableeker** [jacobslusser/ScintillaNET#95]
Adding the DLL to VB 2008 results in an error message claiming it's not a .NET module. It looks like this is because 2008 is a 32-bit program that can't use 64-bit modules. Is it possible to create a 32-bit version that will run in 2008? Or do I have to upgrade to a later version? And if I use a later version and the 64-bit module, does the application that uses the module need to be 64-bits as well?

**Comment by jacobslusser** [comment]
ScintillaNET is built in AnyCPU mode which means it will run on 64 or 32-bit operating systems. I'm not sure why you would have an issue, but then again, I'm not sure what you mean by VB 2008. Is it possible you're trying to use ScintillaNET on an old version of the .NET framework? The standard ScintillaNET build targets .NET v4.0.

If you want to do a build that is specifically for 32-bit or a different version of the framework, you can do that by downloading the source and changing the project settings.

**Comment by ableeker** [comment]
Thanks for the clarification. Then I don't get it, because if I try to add the DLL as a toolbox component, I get the message saying it's not a .NET module. I had to do that for 2.6 according to the installation instructions, and that worked.

**Comment by ableeker** [comment]
By VB 2008 I mean that the program is written in Visual Basic, and that's part of Visual Studio 2008.

**Comment by jacobslusser** [comment]
To my knowledge Visual Studio 2008 does not have support for .NET 4.0. My guess is that the reason this is not recognized as a .NET module is because your project only supports .NET 2.0.
