### ISSUE TITLE
problem in MarkerAdd

### ISSUE THREAD

**Issue by METOUIA7** [jacobslusser/ScintillaNET#96]
Hi, i use this code for add a marker
Scintilla1.Lines(X).MarkerAdd(22)
but i get the arrow however i changed  MarkerAdd(22) by other number

![sans titre](https://cloud.githubusercontent.com/assets/13167974/8973239/996cf5aa-365a-11e5-8ef0-14cb97fcc128.png)

**Comment by jacobslusser** [comment]
I'm not sure I understand your question (if there is one). The wiki has a brief example showing how to use Markers. Perhaps you'll find that helpful.

[https://github.com/jacobslusser/ScintillaNET/wiki/Bookmark-Lines](https://github.com/jacobslusser/ScintillaNET/wiki/Bookmark-Lines)

**Comment by METOUIA7** [comment]
thanks alot for help
