### ISSUE TITLE
Can I create a pull request for the docking fix?

### ISSUE THREAD

**Issue by theryan722** [jacobslusser/ScintillaNET#97]
Or is that something you are leaving up to the user. Thanks.

**Comment by jacobslusser** [comment]
Remind me again, what is the "docking fix"?

**Comment by theryan722** [comment]
From Issue #85  the fix that was implemented in v2.x

**Comment by jacobslusser** [comment]
Oh, THAT "docking fix". :)

Thanks for the offer, but I'm probably going to incorporate the v2 fix as a configuration option developers can opt into and also explore some of the other options.

Just busy with my day job. :)

**Comment by theryan722** [comment]
No problem, guess I won't be vanilla until the option comes out haha
