### ISSUE TITLE
.FindReplace.ShowFind() and FindReplace.ShowReplace()

### ISSUE THREAD

**Issue by mroshaw** [jacobslusser/ScintillaNET#98]
Hi! Absolutely love version 3 of the ScintillaNET control - thank you for your continued efforts with this amazing control!

I've just about migrated my code that renders XML from using the 2.6 control to the new 3.5 control. All pretty straight forward and syntax and folding are now working well.

I used the rather extravagant .FindReplace.ShowFind() and .ShowReplace() methods in 2.6. Is there anything equivalent in 3.5?

Many thanks!

**Comment by jacobslusser** [comment]
Thanks. Glad you like it. :)

See issues #79, #7, and #4 (among others) for background on why there is no Find/Replace dialog in v3.

**Comment by mroshaw** [comment]
Superb, thank you! Time to write my own, methinks! :+1:
