### ISSUE TITLE
Higher DPI support is poor?

### ISSUE THREAD

**Issue by huhu2207** [jacobslusser/ScintillaNET#99]
Hi,

Firstly thanks for your great jobs on this library project!

I just downloaded and compiled the latest source code and imported to VS2015, but it seems the text box is a bit blurry on my Retina Macbook Pro. I addded dpiAware code (see: https://msdn.microsoft.com/en-us/library/windows/desktop/dn469266(v=vs.85).aspx) to app.manifest on both the Scintilla library and my app, but it still has the same result, so, what should I do? 

Regards,
Jackson Ming Hu

**Comment by jacobslusser** [comment]
Quite honestly I haven't ever tested ScintillaNET in a high DPI setting or put any thought into it. Based on my understanding, a control has to be specifically DPI aware and I'm assuming Scintilla is not. So Windows will apply scaling to the control and that may result in some blurriness. You might be able to play around with the `Zoom` as described in the [wiki](https://github.com/jacobslusser/ScintillaNET/wiki/Zooming) to compensate but I'm honestly unsure. We would need some more research into this.

**Comment by huhu2207** [comment]
Hi,

I tried to use ZoomIn and ZoomOut but it's more blurry than before.
Sorry about that...BTW do you have any other suggestion to solve this problem?

Regards,
Jackson.

**Comment by huhu2207** [comment]
Okay it seems solved
Add these code below to my app's program.cs, not the library:
(See: http://stackoverflow.com/questions/13228185/winforms-high-dpi-blurry-fonts)

`    [STAThread]`
`    static void Main() {`
`        if (Environment.OSVersion.Version.Major >= 6) SetProcessDPIAware();`
`        Application.EnableVisualStyles();`
`        Application.SetCompatibleTextRenderingDefault(false);`
`        Application.Run(new Form1());             // Edit as needed`
`    }`

`    [System.Runtime.InteropServices.DllImport("user32.dll")]`
`    private static extern bool SetProcessDPIAware();`

**Comment by aolszowka** [comment]
If you read the rest of that StackOverflow Post you'll see it does not work with Windows 8/8.1 (and I assume 10) it is recommended that you use the .manifest; baring that make sure that in Windows 8+ you use SetProcessDpiAwareness (https://msdn.microsoft.com/en-us/library/windows/desktop/dn302122%28v=vs.85%29.aspx) which unfortunately is not present in earlier versions of Windows (yay for ifdefs!).

The Manifest is the same between all versions and is taken care of for you.

**Comment by huhu2207** [comment]
RE: Aoszowka:

I tested on Windows 10 RTM build 10240, I don't know why but the SetProcessDPIAware() function does work! But so far for some reason I didn't use this library any more, I changed to FCTB library.
